### ISSUE TITLE
config.yaml setting no longer works - possibly due to passthrough update? 

### ISSUE THREAD

**Issue by samuelmanzer** [jupyterhub/zero-to-jupyterhub-k8s#1023]
Using this `pullPolicy` setting used to work to get pods to always pull the latest image version: 

```
singleuser:
   image:
     name: [my image]
     tag: latest
     pullPolicy: Always
```

However, it is now ignored, based on inspection of the spawned pods. Back when I submitted [this issue](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/892) the `pullPolicy` value was passed through like this:

```
singleuser.image-pull-policy: {{ .Values.singleuser.image.pullPolicy | quote }}
```

But I think [this PR](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/f20f3e16a222b2e6b2bc7de78760e08c76f1593b) may have changed how things are passed through. This is what now seems to work:

```
singleuser:
  imagePullPolicy: Always
```
Will do a PR for the docs when I have time - there may be other settings with this issue.

**Comment by manycoding** [comment]
@consideRatio I tried several ways and nothing worked for me so far.

I have an image tag `latest` which I update periodically. To avoid unnecessary jhub deploys I set

```
singleuser:
  image:
    name: images.s.com/jupyterhub-app/arche-notebook
    tag: latest
    pullPolicy: "Always"
```

But continuous-image-puller hasn't pulled anything new after the first updated when I set latest.

I also tried:
```
singleuser:
  image:
    name: images.s.com/jupyterhub-app/arche-notebook
    tag: latest
  imagePullPolicy: Always
```
