### ISSUE TITLE
400: Bad Request - OAuth state missing from cookies (Google auth)

### ISSUE THREAD

**Issue by anton-khodak** [jupyterhub/zero-to-jupyterhub-k8s#1028]
Hi,

I want to use Google authentication with JupyterHub. The problem is that cookie "oauthenticator"  that get set up by JupyterHub disappears once Google redirects from oauth page back to Jupyter. Thus I see 
```
403 : Forbidden 
You are not signed in to your jupyter.cellgeni.sanger.ac.uk account.
```
and on refresh
```
400 : Bad Request
OAuth state missing from cookies
```
I noticed that among other cookies "oauthenticator" one is the only one set with `HttpOnly: true`. This is the only reason I can think of to be invalidated since the expiration date for the cookie is one day ahead.

This is the cookie state after the server sets up cookies : 
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/10351924/48722104-2db66380-ec1b-11e8-937c-37b91d667665.png">
Once Google authenticated a user and returns them back to JupyterHub, the `oauthenticator` cookie just disappears. Other cookies stay.

I looked into https://github.com/jupyterhub/jupyterhub/issues/2044 and https://github.com/jupyterhub/jupyterhub/issues/1519, didn't help to understand how to fix this problem.

Hope someone can give a clue how to handle it.

## Contents of `config.yaml`
```
proxy:
  secretToken: <token>

auth:
  type: google
  google:
    clientId: "<client-id>"
    clientSecret: "<secret>"
    callbackUrl: "https://jupyter.cellgeni.sanger.ac.uk/hub/oauth_callback"
    hostedDomain: "jupyter.cellgeni.sanger.ac.uk"
    loginService: "JupyterHub at Wellcome Trust Sanger Institute"

cull:
  timeout: 129600

singleuser:
  defaultUrl: "/lab"
  storage:
    capacity: 30Gi
  memory:
    limit: 20G
    guarantee: 16G
  cpu:
    limit: 4
    guarantee: 2
  image:
    name: quay.io/cellgeni/cellgeni-jupyter
    tag: v0.2.8
  lifecycleHooks:
    postStart:
      exec:
        command: ["bash", "/poststart.sh"]

```
