### ISSUE TITLE
Posibility for pod utilizing more than one core?

### ISSUE THREAD

**Issue by tregin** [jupyterhub/zero-to-jupyterhub-k8s#1034]
Hello 

I would like to ask a question whether is possible to allocate more that one CPU core in the configuration.
In the [Customizing User Resources](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-resources.html) you are mentioning you can specify:

```yaml
singleuser:
  cpu:
    limit: .5
    guarantee: .5
```

Could the limit be increased to let's say 4 so the pod can use 4 cores or is the limit 1?

**Comment by consideRatio** [comment]
@tregin yepp! You can specify more than 1.

I have specified something like this for example, allowing my users to peak up to 6 cores of CPU usage, and always be ensured 5% of a CPU core.
```yaml
singleuser:
  cpu:
    limit: .05
    guarantee: 6
```
