### ISSUE TITLE
Our PriorityClass resources are Helm hooks, but shouldn't be any more

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1035]
I made the PriorityClass resources Helm hooks to ensure they are installed before any pod would reference them, but that may not be needed any more as Helm may have added logic to always prioritize the creation of these anyhow by now. I don't know though.

If that is the case, we should stop installing them as Helm hooks, since this causes some trouble. For example, if you would disable `scheduling.podPriority.enabled` then there would be resources remaining...

We should also consider using the `.Capabilities` function to evaluate if K8s 1.11 or higher is installed, since that is required for `scheduling.podPriority.enabled` and fail in a nicer manner instead.

**Comment by consideRatio** [comment]
When start depending on Helm 2.12, we could stop using hooks, perhaps.

> **consideRatio [7:01 PM]**
>PriorityClass objects must be created before a deployment references it, and i assume it makes sense to always create these first if a bunch of k8s resources is to be created.
>
>Is there logic to do this in Helm, or do i need to abandon the managed resources by installing them as helm hooks?
>
>Example:
I have a chart. The single deployment in it has a pod-spec with `priorityClassName: my-custom-priority`. I also have a PriorityClass resource defined in the chart with the name `my-custom-priority`. Can I trust that this is created before the deployment?

> **bacongobbler [2:11 AM]**
yes, the current plan is to wait for 2.12. We discussed it in the dev call a few weeks back IIRC.
> @consideRatio https://github.com/helm/helm/blob/master/pkg/tiller/kind_sorter.go (edited)

**Comment by consideRatio** [comment]
Here is one of our priorityclass resources, as you can see from the annotations, its a Helm hook resource, which means they are created before other and not managed by helm after creation. We only needed them to be that before, but no longer, but making them real resources now will cause a conflict because there will suddenly be a resources named like this already that Helm doesn't want to delete.

```yaml
{{- if .Values.scheduling.podPriority.enabled }}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-default-priority
  labels:
    {{- $_ := merge (dict "componentLabel" "default-priority") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
  annotations:
    # PriorityClasses was created as a Helm hook for legacy reasons, now we need
    # to introduce a breaking change to make them stop being Helm hooks though,
    # by asking users to manually delete them before trying to run `helm
    # upgrade`.
    #
    # ref: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1035
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-100"
value: {{ .Values.scheduling.podPriority.defaultPriority }}
globalDefault: {{ .Values.scheduling.podPriority.globalDefault }}
description: "A default priority higher than user placeholders priority."
{{- end }}
```
