### ISSUE TITLE
How to use firstuseauthenticator as authentication module?

### ISSUE THREAD

**Issue by dalonlobo** [jupyterhub/zero-to-jupyterhub-k8s#1042]
Hello Team,

I have a working setup of jupyterhub on kubernetes. How can I configure [firstuseauthenticator ](https://github.com/jupyterhub/firstuseauthenticator.git) as the authentication module in the helm chart? 

Your help is much appreciated.

**Comment by BertR** [comment]
```yaml
auth:
    type: "custom"
    custom:
        className: "firstuseauthenticator.FirstUseAuthenticator"
```
