### ISSUE TITLE
Subdomains and wildcard hosts

### ISSUE THREAD

**Issue by beneath-hq** [jupyterhub/zero-to-jupyterhub-k8s#1058]
Hi

First of all, I appreciate the work you're doing making JupyterHub easy to deploy on Kubernetes.

I wish to enable user subdomains for my JupyterHub installation as described here [https://jupyterhub.readthedocs.io/en/0.7.2/websecurity.html#subdomains](https://jupyterhub.readthedocs.io/en/0.7.2/websecurity.html#subdomains).

1. Do you have any documentation for how to set that up in my `config.yaml`? I have not been able to find it.

2. To start out, I tried to setup wildcard hosts and TLS. This is my `config.yaml`:

```
ingress:
  enabled: true
  hosts:
  - jupyter.xxx.com
  - "*.jupyter.xxx.com"
  tls:
  - secretName: xxx-tls
    hosts:
    - jupyter.xxx.com
    - "*.jupyter.xxx.com"
```

However, when running `helm upgrade ... -values config.yaml`, I get the following error:

```
Error: UPGRADE FAILED: YAML parse error on jupyterhub/templates/ingress.yaml: error converting YAML to JSON: yaml: line 23: did not find expected alphabetic or numeric character
```

It seems to be related to the wildcard character because when I remove it, everything works fine.

What are your thoughts?

Much appreciated
Benjamin
