### ISSUE TITLE
Bug with the pass-through for profile lists

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#1097]
I was getting a multi-profile jupyterhub set up in order to write some docs for #1085 and I think I ran into a bug with the profile list pass through.

I'm using the latest version of the helm chart (`--version 0.8-17d72b0`). If I use this configuration:

```

hub:
  extraConfig: |
    c.KubeSpawner.profile_list = [
      {
        "display_name": "Minimal environment",
        "description": "Super minimal",
        "defualt": True,
      },
      {
        "display_name": "Datascience environment",
        "description": "If you want the additional bells and whistles: Python, R, and Julia.",
        "kubespawner_override": {'image': "jupyter/datascience-notebook:2343e33dec46"}
      }]
```

then it works fine and I get a list of profiles. However, if I use this config:

```yaml
singleuser:
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
```

Then I get the following error:

```
Error: UPGRADE FAILED: render error in "jupyterhub/templates/image-puller/daemonset.yaml": template: jupyterhub/templates/image-puller/daemonset.yaml:9:4: executing "jupyterhub/templates/image-puller/daemonset.yaml" at <include "jupyterhub....>: error calling include: template: jupyterhub/templates/image-puller/_daemonset-helper.yaml:64:25: executing "jupyterhub.imagePuller.daemonset" at <$container.kubespawn...>: can't evaluate field image in type interface {}
```

It seems like something isn't being interpolated properly? Anyone have ideas?
