### ISSUE TITLE
Configure existing volume for User's pod

### ISSUE THREAD

**Issue by tregin** [jupyterhub/zero-to-jupyterhub-k8s#1109]
Hello

Although this is not a real issue I wanted to ask whether there is a possibility to configure a volume/storage that would be available/mounted automatically to all Jupyter hub pods  so everyone would have access the resources stored there?
Would it be even possible to have this volume mounted as an additional volume to the existing one which is created automatically just for the user?

Any suggestion on how to this could be solved are welcome! :)
Thank you very much

```

**Comment by manics** [comment]
You'll have to create a shared PersistentVolume and PersistentVolumeClaim as @consideRatio said. Then you can mount it into your singleuser servers like this:
```
singleuser:
  storage:
    extraVolumes:
    - name: jupyterhub-sharedscratch-rw
      persistentVolumeClaim:
        claimName: jupyterhub-sharedscratch-nfs-volume
    extraVolumeMounts:
    - name: jupyterhub-sharedscratch-rw
      mountPath: /home/jovyan/shared
```
