### ISSUE TITLE
Error: failed to download "0.7.0" 

### ISSUE THREAD

**Issue by danielchalef** [jupyterhub/zero-to-jupyterhub-k8s#1111]
I'm unable to install v0.7.0 of the `jupyterhub/jupyterhub` helm chart.

```
RELEASE=jhub NAMESPACE=jhub helm upgrade --install $RELEASE jupyterhub/jupyterhub   --namespace $NAMESPACE    --version 0.7.0   --values config.yaml
Error: failed to download "0.7.0" (hint: running `helm repo update` may help)
```
The jupyterhub helm repo has been added and I'm able to see the `jupyterhub/jupyterhub` chart when searching for jupyterhub. Curiously, the chart version is 0.8-ff69a77.

```
$ helm search jupyterhub
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
jupyterhub/jupyterhub   0.8-ff69a77     0.9.4           Multi-user Jupyter installation
jupyterhub/binderhub    0.2.0-f80738c                   A helm chart to install Binder
```

## Contents of `config.yaml`
```
proxy:
  secretToken: XXXXXXX

auth:
  admin:
    users:
      - XXXXXXXX

singleuser:
  storage:
    dynamic:
      storageClass: aws-efs
  defaultUrl: "/lab"
  image:
    # Get the latest image tag at:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
    name: jupyter/all-spark-notebook
    tag: 87210526f381

hub:
  extraConfig: |-
     c.Spawner.cmd = ['jupyter-labhub']
```
