### ISSUE TITLE
Admin users when using AD authentication

### ISSUE THREAD

**Issue by tregin** [jupyterhub/zero-to-jupyterhub-k8s#1116]
Hello

I'm trying to a set and admin user who could control others.

I'm able to set this up using the whitelist configuration (see below example):

Contents of `config.yaml`
```
auth:
  whitelist:
    users:
      - user1
      - user2
      - user3
  admin:
    users:
      - user1
```
However when using the AD authentication the button for "Admin" does not show up. (example below)

Contents of `config.yaml`
```
auth:
  type: ldap
  ldap:
    admin:
      access: true
      users:
        - user1
    server:
       address: xxx.xxx.xxx.xxx
       port: x
       ssl: false
    dn:
       lookup: true
       search:
 config goes on...
```

Does anyone has experience in setting this up? Is it even possible?
