### ISSUE TITLE
Using the orgWhitelist key

### ISSUE THREAD

**Issue by arokem** [jupyterhub/zero-to-jupyterhub-k8s#1118]
Hi everyone -- I am trying to set up an instance of pangeo, and also update the cloud setup guide there (https://github.com/pangeo-data/pangeo/pull/402). I found a discrepancy between the existing description there and the description of setting GitHub organization white-list here: https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#giving-access-to-organizations-on-github, which is the key-word is `org_whitelist` there vs. `orgWhitelist` here. Does this matter? 

Further, when I set this, it doesn't seem to have the intended effect. It seems that any GitHub user can log into my JHub (not only members of the white-listed org). Any ideas why that might be happening?

Here is the entire `secret_config.yaml` file (with necessary obfuscation): 

```
jupyterhub:
  proxy:
    secretToken: "XXX"

  # comment this out if not using github authentication
  auth:
    type: github
    github:
      clientId: "XXX"
      clientSecret: "XXX"
      callbackUrl: "http://XXX/hub/oauth_callback"
      orgWhitelist:
        - "my_org"
    scopes:
      - "read:user"
    admin:
      access: true
      users:
        - arokem 
```

**Comment by manics** [comment]
The docs were updated recently: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1107
I'm still got `org_whitelist` in my config but that's for an old version of z2jh `v0.7-d617e0a`, I haven't tested the latest z2jh with Github auth yet.

**Comment by arokem** [comment]
Also, there used to be a way to white-list individual GitHub users, but it seems like that option is no longer documented. How do I do that?

**Comment by amanda-tan** [comment]
```
auth:
  type: github
  github:
    clientId: “CLIENT_ID”
    clientSecret: “CLIENT_SECRET”
    callbackUrl: “https://example.org/hub/oauth_callback”
  admin:
    access: true
    users:
      - user1
  whitelist:
    users:
      - user2

```
