### ISSUE TITLE
Where (and if) to put documentation for the following

### ISSUE THREAD

**Issue by hnykda** [jupyterhub/zero-to-jupyterhub-k8s#1125]
Hello,

the last week, I used this awesome stack in my team and it works great. Nevertheless, there were some non-trivial findings/steps I had to do and I am unsure if it's worth mentioning in the docs or no (because the docs are good in how they are concise). I can't take all the credit, my colleagues helped me, but that's irrelevant for the contribution.

1. `GCE Ingress`. First of all, #1004  must be used. Additionally, I wasn't able to make ingress work if I didn't added the default backend, so this:
```
{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
...
spec:
  backend:
    serviceName: proxy-public
    servicePort: 80
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: {{ $.Values.hub.baseUrl }}{{ $.Values.ingress.pathSuffix }}
            backend:
              serviceName: proxy-public
              servicePort: 80
    {{- end }}
...
```
and in config then:

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: juphub-static-ip
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "false"
  hosts:
  - ...hostname...
  pathSuffix: "*"
  tls:
  - hosts:
    - ...hostname...
    secretName: jupyterhub-tls
proxy:
  https:
    enabled: true
    type: offload
  service:
    type: NodePort
```
2. profile list is so awesome feature that it would deserve some more examples, the below is mine. A sad thing is that [kubespawner](https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py) documentation is broken ([nothing shows up in the readthedocs](https://github.com/jupyterhub/kubespawner/issues/291)) and one must dive into the code to find corresponding settings.
 
```
singleuser:
  image:
    name: ...image...
    tag: ...tag...
  profileList:
  # there is some DRY violations below
  - display_name: data tools  [Version 0.1.1]
    description: 'Some our stuff'
    default: true
  - display_name: data tools  [Version latest]
    description: 'Some our stuff'
    kubespawner_override:
      # image pull policy for latest tag is automatically always: 
      # https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L376
      image: ...image:latest...
  - display_name: Minimal environment
    description: 'To avoid too much bells and whistles: Python.'
    kubespawner_override:
      image: jupyter/minimal-notebook:2343e33dec46
  - display_name: Datascience environment
    description: 'If you want the additional bells and whistles: Python, R, and Julia.'
    kubespawner_override:
      image: jupyter/datascience-notebook:2343e33dec46
  - &dataToolsProfile
    display_name: data tools (High Mem node) [Version 0.1.1]
    description: 'Same as data tools but on a 52G node'
    kubespawner_override: &highMemNode
      image: ...image:tag...
      node_selector:
        app: jupyterhub
      tolerations:
        - key: "resilent"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
  - <<: *dataToolsProfile
    display_name: data tools (High Mem node)  [Version latest]
    kubespawner_override:
      <<: *highMemNode
      # image pull policy for latest tag is automatically always: 
      # https://github.com/jupyterhub/kubespawner/blob/master/kubespawner/spawner.py#L376
      image: ...image:latest...
```
3. github auth works and it's mentioned in the docs, but I would really recommend mentioning that you wil need `read:org` in case you wanna whitelist organization (otherwise just 404 is returned):
```
auth:
  type: github
  admin:
    users:
    - someAdminname
  github:
    callbackUrl: https://jupyter.example.com/hub/oauth_callback
    orgWhitelist:
    - YourOrgName
  scopes:
  - read:org
  - read:user
...secrets...
```

All the above was on the latest version `0.8-a78b3d6`.

**Comment by consideRatio** [comment]
Thank you for this excellent feedback! :D

**Comment by hnykda** [comment]
Oh, I thank you! This is an awesome project. I am still amazed how smooth it was. 

Anyway, should I contribute to the docs directly or will you somehow curate this? If the latter, you can probably close this "issue".

**Comment by consideRatio** [comment]
Oh you are very welcome to make a PR to improve the documentation! It is hard to keep up without such help, it is very appreciated!

I'm not grasping point 1 very well yet and I know there are plenty of different use cases, so I'm not sure where the docs should reside. The other points though should be pretty straightforward!

BTW: Note that schema.yaml file renders to the configuration reference found on z2jh.jupyter.org

@hnykda :heart: :star2:

**Comment by hnykda** [comment]
OK, will do. 

The first bullet point is just configuring jupyterhub with SSL/HTTPS through GCE Ingress. So offloading public-proxy (making it "not public" by the way) and resolving HTTPS on the ingress level, how it should be done.

**Comment by hnykda** [comment]
OK, I did my best. I didn't add new pages, rather tried to put it on existing places.

**Comment by TiemenSch** [comment]
Not sure if this belongs here (seems fitting, but please let me know otherwise):

I can't seem to find a fitting example where a private registry is used for the singleuser image.
I'm currently experimenting with the config variables after setting a docker-registry secret, but especially if the private image is the only singleuser image, the Helm upgrade fails in an unpretty way. (e.g. you need to do a ton of cleanup/start fresh)

**Comment by hnykda** [comment]
We are using it and it works fine. What out of https://zero-to-jupyterhub.readthedocs.io/en/latest/reference.html#hub-imagepullsecret-registry doesn't work for you?

**Comment by TiemenSch** [comment]
Ah, I was trying to create the secret using 
```bash
kubectl create secret docker-registry singleuser-image-credentials \
  --docker-server=registry.gitlab.com/myorg/myrepo \
  --docker-username=<username> \
  --docker-password=<password> \
```
and then reference it using:
```yaml
singleuser:
  profileList:
  - display_name: 'myname'
    description: 'mydescription'
    image: registry.gitlab.com/myorg/myrepo/myimage:latest
  imagePullSecret:
    registry: registry.gitlab.com/myorg/myrepo
    name: singleuser-image-credentials
```

Or does referencing the secret involve additional params in the ``hub`` config as well? 
The reference docs are not fully clear to me on that point.
