### ISSUE TITLE
Add tolerations to everything!

### ISSUE THREAD

**Issue by AXington** [jupyterhub/zero-to-jupyterhub-k8s#1130]
Our organization uses taints on literally all our nodes to separate our node pools. It would be rather nice to have tolerations and affinities added to all of these resources so that we don't have to maintain a fork or this repo in order to deploy to the right node pools. 

Further problems are caused when your node pools have multiple availability zones on EKS and using PVCs. PVCs by default can be in any AZ the cluster has nodes provisioned in, however the volume has to be deployed to the same AZ as the node it's being mounted to, and therefore there are issues when trying to use the default sqlite pvc database for the hub.

**Comment by guohenghaha** [comment]
same problem

**Comment by zzh8829** [comment]
My solution to EKS EBS PVC problem is create a separate single AZ autoscaling group dedicated to jupyter. It works great for user pods, but since we currently can't set dedicated tolerance on "hub", hub pods has to share "dedicated" node with other pods.

**Comment by stevenstetzler** [comment]
I ran in to this issue as well, where I wanted to have tolerations for every schedulable object in the chart. I tweaked the Chart to allow for this. I haven't had time to run extensive tests, but I've been able to deploy a JupyterHub and everything works as expected. I've forked the repo and made a new branch with my changes, here is the commit: 456b78a25a237e7cf83bd2241d75f45a09f272c4 I think it would be a helpful addition to the Helm chart. Should I open a PR for this?

**Comment by betatim** [comment]
sounds like a good idea/PR to make. One thing that @consideRatio commented on in another PR is that things should be wrapped in if statements so that they only get added to (say) an objects template when they are set to "not their empty value". Another thing to double check is if kubespawner adds the right tolerations to the pods it starts. Potentially with a short bit of documentation for how to make it all work together.

**Comment by consideRatio** [comment]
This is probably still relevant, and we should support this.

**Comment by AXington** [comment]
we're not even using jupyterhub anymore, but a better solution that we've been using for cross az storage using EBS is to use rook+ceph with EBS backed OSDs. 

But yeah, would open a PR for this myself but getting my employer's legal team to approve of contributions to FOSS projects is... so far not allowed.

**Comment by mausch** [comment]
I'm using EFS for cross-az storage... Really easy to set up, however tolerations might still be necessary for other things (or if you don't want to use EFS)!

**Comment by stevenstetzler** [comment]
I've opened a PR to merge the small change I made to add tolerations to the Helm chart.

Echoing others, I ended up using a different solution using the `nodeSelector` in the Helm chart. The notebook servers and volumes can be made zone-aware using built-in support from Kubernetes (https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies). Here is the configuration in the Helm chart
```
jupyterhub:
  singleuser:
    nodeSelector: 
      failure-domain.beta.kubernetes.io/zone: "us-west-2a"
    storage:
      dynamic:
        storageClass: "gp2-us-west-2a"
```
which uses a custom zone-aware storage class created as follows:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-us-west-2a
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - us-west-2a
```
