### ISSUE TITLE
Profiles not working ??

### ISSUE THREAD

**Issue by stelford** [jupyterhub/zero-to-jupyterhub-k8s#1134]
Howdy Everyone,
So, I maybe crazy, but, I jst can't seem to get the profiles to show anyplace. It always defaults to the minimal image notebook. I have tried restarting everything under k8s, deleting my pod/jupyter-user as well as checking in the admin for any bells/whistles to flip on. It's very weird. Any pointers gratefully received.

## Contents of `config.yaml`
```
proxy:
  secretToken: "xxx"
auth:
  admin:
    users:
      - adminuser1
singleuser:
  image:
    pullPolicy: Always
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/all-spark-notebook:2343e33dec46
```

```root@node1:/home/stef/jupyterhub# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean"}

root@node1:/home/stef/jupyterhub# kubectl get all --namespace jhub

NAME                         READY   STATUS    RESTARTS   AGE
pod/hub-6c9fdbc4b4-jrhmh     1/1     Running   0          12m
pod/jupyter-adminuser1       1/1     Running   0          55m
pod/jupyter-stef             1/1     Running   0          65m
pod/proxy-6f68b877c8-rmk5d   1/1     Running   0          4h17m

NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/hub            ClusterIP   10.233.20.179   <none>        8081/TCP       4h17m
service/proxy-api      ClusterIP   10.233.33.110   <none>        8001/TCP       4h17m
service/proxy-public   NodePort    10.233.57.35    <none>        80:32410/TCP   4h17m

NAME                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hub     1         1         1            1           4h17m
deployment.apps/proxy   1         1         1            1           4h17m

NAME                               DESIRED   CURRENT   READY   AGE
replicaset.apps/hub-6c9fdbc4b4     1         1         1       12m
replicaset.apps/proxy-6f68b877c8   1         1         1       4h17m```
