### ISSUE TITLE
Chris testing upgrade from v0.7 to latest helm chart

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#1140]
In #1054 @consideRatio gave a little list of steps to try the upgrade path from v0.7 to v0.8. I'm gonna give this a shot now and will use this issue to report!
I'm following these steps:

1. A deployment is installed with 0.7.0
2. The deployment is upgraded to 0-8.a2143a2 (currently latest release)
3. The deployment is ugpraded with a config.yaml that specifies the usage of the continuous prePuller, userScheduler and podPriority and userPlaceholders like this:

```yaml
prePuller:
  continuous:
    enabled: true

scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 4
```
