### ISSUE TITLE
Improve EKS documentation

### ISSUE THREAD

**Issue by manycoding** [jupyterhub/zero-to-jupyterhub-k8s#1150]
I managed to succesfully follow https://z2jh.jupyter.org/en/latest/amazon/step-zero-aws-eks.html and https://z2jh.jupyter.org/en/latest/setup-helm.html only up to `helm init` step.

I am not sure how to improve the docs yet, so for the time being I just list here what I found so far.
I have done everything from under an assumed role.

1. `arn` in my config blocked my access, so I commented this out while following **step 6. Configure kubeconfig** 

2. `helm init` failed. While going deeper, I found that nodes are not ready:
>reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

I haven't found the solution yet. I used configMap setup from here https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html instead of **9. Create a AWS authentication ConfigMap** since this description doesn't make sense to me (pull up from where?).

>To find the ARN of the instance role, you can pull up any node created in ...

## Contents of `config.yaml`
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: scrubbed
    server: https://scrubbed.yl4.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:scrubbed:cluster/QA-Z2JHKubernetesCluster
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:scrubbed:cluster/QA-Z2JHKubernetesCluster
    user: arn:aws:eks:us-west-2:scrubbed:cluster/QA-Z2JHKubernetesCluster
  name: arn:aws:eks:us-west-2:scrubbed:cluster/QA-Z2JHKubernetesCluster
current-context: arn:aws:eks:us-west-2:scrubbed:cluster/QA-Z2JHKubernetesCluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:scrubbed:cluster/QA-Z2JHKubernetesCluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - QA-Z2JHKubernetesCluster
      # - -r
      # - arn:aws:iam::scrubbed:role/jupyterhub
     #  - arn:aws:iam::scrubbed:role/Full-access-to-QA-resources
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: amazon-qa-inf
```
