### ISSUE TITLE
Active Directory LDAP Authentication

### ISSUE THREAD

**Issue by narion** [jupyterhub/zero-to-jupyterhub-k8s#1166]
To resolve an issue with the active directory allowedGroups configuration item the line spacing in the documentation is incorrect. 

Documentation shows allowedGroups inline with the dn: setting however this does not then actually manage the checking of user groups. I had to indent the allowedGroups item to match the items listed within user: (a further 4 spaces in the yml/yaml)

Being specific in the code displayed guide page is `https://z2jh.jupyter.org/en/latest/authentication.html:- 

```yaml
auth:  
  type: ldap  
  ldap:  
    server:  
      address: ad.EXAMPLE.org  
    dn:  
      lookup: true  
      search:  
        filter: '({login_attr}={login})'  
        user: 'ldap_search_user_technical_account'  
        password: 'secret'  
      templates:  
        - 'uid={username},ou=people,dc=wikimedia,dc=org'  
        - 'uid={username},ou=developers,dc=wikimedia,dc=org'  
      user:  
        searchBase: 'ou=people,dc=wikimedia,dc=org'  
        escape: False  
        attribute: 'sAMAccountName'  
        dnAttribute: 'cn'  
    allowedGroups:
      - 'cn=researcher,ou=groups,dc=wikimedia,dc=org'  
      - 'cn=operations,ou=groups,dc=wikimedia,dc=org'
```	  
To get the allowedGroups working I had to format as follows:- 
```yaml
auth:  
  type: ldap  
  ldap:  
    server:  
      address: ad.EXAMPLE.org  
    dn:  
      lookup: true  
      search:  
        filter: '({login_attr}={login})'  
        user: 'ldap_search_user_technical_account'  
        password: 'secret'  
      templates:  
        - 'uid={username},ou=people,dc=wikimedia,dc=org'  
        - 'uid={username},ou=developers,dc=wikimedia,dc=org'  
      user:  
        searchBase: 'ou=people,dc=wikimedia,dc=org'  
        escape: False  
        attribute: 'sAMAccountName'  
        dnAttribute: 'cn'  
        allowedGroups:
          - 'cn=researcher,ou=groups,dc=wikimedia,dc=org'  
          - 'cn=operations,ou=groups,dc=wikimedia,dc=org'
```

**Comment by hqwl159** [comment]
yeal! I hava the same issue.  
I don't know what's  the mean of  config "ldap.dn.search.user". It's don't work either  'ldap.dn.search.user = ldap_search_user_technical_account' or   'ldap.dn.search.user = ${my ldap admin user}'

This is my config:
`auth:
  admin:
    access: true
    users:
      - xxxxx
  type: ldap
  ldap:
    server:
      address: 10.1.21.30
      port: 10389
    dn:
      lookup: true
      search:
        filter: '({login_attr}={login})'
        user: '*****'
        password: '******'
      templates:
        - 'uid={username},ou=people,dc=hduldap,dc=com'
        - 'uid={username},ou=developers,dc=hduldap,dc=com'
      user:
        searchBase: 'ou=people,dc=hduldap,dc=com'
        escape: False
        attribute: 'sAMAccountName'
        dnAttribute: 'cn'
    allowedGroups:
      - 'cn=researcher,ou=groups,dc=hduldap,dc=com'
      - 'cn=operations,ou=groups,dc=hduldap,dc=com'
  state:
    enabled: true
   cryptoKey: "cabaf09e100a9483c737e1af998fff927373ee929815e126f28ee9ff6f320897"
`

**Comment by narion** [comment]
> Yeal! I hava the same issue.
> I don't know what's the mean of config "ldap.dn.search.user". It's don't work either 'ldap.dn.search.user = ldap_search_user_technical_account' or 'ldap.dn.search.user = ${my ldap admin user}'
> 
> my juputerhub/k8s version is 0.9.0
> 
> This is my config:
> 
> ```
> auth:
>   admin:
>     access: true
>     users:
>       - xxxxx
>   type: ldap
>   ldap:
>     server:
>       address: 10.1.21.30
>       port: 10389
>     dn:
>       lookup: true
>       search:
>         filter: '({login_attr}={login})'
>         user: '*****'
>         password: '******'
>       templates:
>         - 'uid={username},ou=people,dc=hduldap,dc=com'
>         - 'uid={username},ou=developers,dc=hduldap,dc=com'
>       user:
>         searchBase: 'ou=people,dc=hduldap,dc=com'
>         escape: False
>         attribute: 'sAMAccountName'
>         dnAttribute: 'cn'
>     allowedGroups:
>       - 'cn=researcher,ou=groups,dc=hduldap,dc=com'
>       - 'cn=operations,ou=groups,dc=hduldap,dc=com'
>   state:
>     enabled: true
>    cryptoKey: "cabaf09e100a9483c737e1af998fff927373ee929815e126f28ee9ff6f320897"
> ```

 user:
         searchBase: 'ou=people,dc=hduldap,dc=com'
         escape: False
         attribute: 'sAMAccountName'
         dnAttribute: 'cn'
         allowedGroups:
           - 'cn=researcher,ou=groups,dc=hduldap,dc=com'
           - 'cn=operations,ou=groups,dc=hduldap,dc=com'

:)

**Comment by hqwl159** [comment]
> > Yeal! I hava the same issue.
> > I don't know what's the mean of config "ldap.dn.search.user". It's don't work either 'ldap.dn.search.user = ldap_search_user_technical_account' or 'ldap.dn.search.user = ${my ldap admin user}'
> > my juputerhub/k8s version is 0.9.0
> > This is my config:
> > ```
> > auth:
> >   admin:
> >     access: true
> >     users:
> >       - xxxxx
> >   type: ldap
> >   ldap:
> >     server:
> >       address: 10.1.21.30
> >       port: 10389
> >     dn:
> >       lookup: true
> >       search:
> >         filter: '({login_attr}={login})'
> >         user: '*****'
> >         password: '******'
> >       templates:
> >         - 'uid={username},ou=people,dc=hduldap,dc=com'
> >         - 'uid={username},ou=developers,dc=hduldap,dc=com'
> >       user:
> >         searchBase: 'ou=people,dc=hduldap,dc=com'
> >         escape: False
> >         attribute: 'sAMAccountName'
> >         dnAttribute: 'cn'
> >     allowedGroups:
> >       - 'cn=researcher,ou=groups,dc=hduldap,dc=com'
> >       - 'cn=operations,ou=groups,dc=hduldap,dc=com'
> >   state:
> >     enabled: true
> >    cryptoKey: "cabaf09e100a9483c737e1af998fff927373ee929815e126f28ee9ff6f320897"
> > ```
> 
> The indentation on the allowedGroups needs to be within user, the documentation really needs updating as I'd completely forgotten I'd ever posted this...

Thank you for your reply!!! I alter the config:
```
auth:
  admin:
    access: true
    users:
      - hqwl159
  type: ldap
  ldap:
    server:
      address: 10.1.21.30
      port: 10389
    dn:
      lookup: true
      search:
        filter: '({login_attr}={login})'
        user: 'ldap_search_user_technical_account'
        password: 'secret'
      templates:
        - 'uid={username},ou=people,dc=hduldap,dc=com'
        - 'uid={username},ou=developers,dc=hduldap,dc=com'
      user:
        searchBase: 'ou=people,dc=hduldap,dc=com'
        escape: False
        attribute: 'sAMAccountName'
        dnAttribute: 'cn'
        allowedGroups:
          - 'cn=researcher,ou=groups,dc=hduldap,dc=com'
          - 'cn=operations,ou=groups,dc=hduldap,dc=com'
```

But it don't work with “500 : Internal Server Error”.
It can work with auth by github.
Do you have right configuration file about auth of  juputerhub  with ldap?Could  you shared your configuration file with me ？
