### ISSUE TITLE
Sidecar container for notebook pod?

### ISSUE THREAD

**Issue by daldridge-cs** [jupyterhub/zero-to-jupyterhub-k8s#1170]
I'm attempting to add a docker-in-docker sidecar container to the singleuser notebook pods.  In my k8s cluster in a separate namespace, I can create the following pod, which has a correctly functioning sidecar (taken from [here](https://applatix.com/case-docker-docker-kubernetes-part-2/)):
```
apiVersion: v1 
kind: Pod 
metadata: 
    name: dind 
spec: 
    containers: 
      - name: docker-cmds 
        image: docker:1.12.6 
        command: ['docker', 'run', '-p', '80:80', 'httpd:latest'] 
        resources: 
            requests: 
                cpu: 10m 
                memory: 256Mi 
        env: 
          - name: DOCKER_HOST 
            value: tcp://localhost:2375 
      - name: dind-daemon 
        image: docker:1.12.6-dind 
        resources: 
            requests: 
                cpu: 20m 
                memory: 512Mi 
        securityContext: 
            privileged: true 
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker 
    volumes: 
      - name: docker-graph-storage 
        emptyDir: {}
```
I can exec into the pod and I've verified d-in-d is working fine.

Now I'd like to add the same `dind-daemon` to the notebook pod.  I've tried the following in my helm chart config.yaml:
```
...
hub:
  image:
    name: c12e/cortex-jupyterhub
    tag: 1.0.14-g2134beb-develop
  imagePullSecret:
    enabled: true
    username: <redacted>
    password: <redacted>
  allowNamedServers: true
  extraConfig: |
    c.KubeSpawner.extra_pod_config = {
        "containers": [{
            "name": "dind-daemon",
            "image": "docker:1.12.6-dind",
            "securityContext": { "privileged": True },
            "volumeMounts": [{ "name": "docker-graph-storgage", "mountPath": "/var/lib/docker" }]
        }],
        "volumes": [{ "name": "docker-graph-storage", "emptyDir": {} }]
    }
...
```
With this configuration, I get the following error in the hub logs (stacktrace omitted for brevity):
```
    kubernetes.client.rest.ApiException: (422)
    Reason: error
    HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Thu, 28 Feb 2019 20:13:24 GMT', 'Content-Length': '449'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Pod \"jupyter-tenant1-2ddaldridge-2d1\" is invalid: spec.containers[0].volumeMounts[0].name: Not found: \"docker-graph-storgage\"","reason":"Invalid","details":{"name":"jupyter-tenant1-2ddaldridge-2d1","kind":"Pod","causes":[{"reason":"FieldValueNotFound","message":"Not found: \"docker-graph-storgage\"","field":"spec.containers[0].volumeMounts[0].name"}]},"code":422}
```
Looks like the `docker-graph-storage` volume doesn't exist...

What am I doing wrong?  Should this approach be possible?
