### ISSUE TITLE
Globus auth error: Missing client_id parameter

### ISSUE THREAD

**Issue by rabernat** [jupyterhub/zero-to-jupyterhub-k8s#1173]
Over in https://github.com/pangeo-data/pangeo-cloud-federation/issues/101, I am trying to set up globus auth with a pangeo jupyterhub.

First I saw #1171, and then I updated my chart to depend on `jupyterhub-0.9-e120fda`. With this, I was able to begin the authentication process with Globus. But I am now getting a new error, from Globus itself, after I get redirected there.

```
Unable to Fulfill Your Request
Error processing OAuth2 request
Sorry, but we encountered a problem while servicing your request.

Missing client_id parameter.
Occurred at time:
2019-03-02T05:49:36.154561+00:00
Error ID:
a8045c6211e249f1891c5f97059632d1
Error code:
OAUTH_AUTH_REQUEST_FAILURE
If this problem persists, please contact support and copy-paste the information above to help us resolve the problem.
```

In my encrypted secret config, I have

```yaml
jupyterhub:
  proxy:
    secretToken: XXX
  auth:
    type: globus
    github:
      clientId: "XXX"
      clientSecret: "XXX"
      callbackUrl: "https://staging.pangeo.io/hub/oauth_callback"
      identityProvider: "ORCID"
```

I also tried with  `client_id` instead of `clientId`, but it made no difference.

Given all his recent work on auth, I expect that @consideRatio has some idea what is going on here.

## Contents of `config.yaml`

This is a rather complex hubploy deployment. Most of the config is here: https://github.com/pangeo-data/pangeo-cloud-federation/tree/staging/deployments/ocean/config.

**Comment by consideRatio** [comment]
@rabernat thanks for providing the config! Replace `github` with `globus` below and I think you may be good to go!

```yaml
jupyterhub:
  proxy:
    secretToken: XXX
  auth:
    type: globus
    github:
      clientId: "XXX"
      clientSecret: "XXX"
      callbackUrl: "https://staging.pangeo.io/hub/oauth_callback"
      identityProvider: "ORCID"
```

Related code:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/e120fdae9d945e78e79a291f90b0bb5e703c4091/images/hub/jupyterhub_config.py#L295-L302
