### ISSUE TITLE
Per-user Resource Allocation

### ISSUE THREAD

**Issue by szelenka** [jupyterhub/zero-to-jupyterhub-k8s#1178]
These pages seems to suggest you're able to adjust resource allocation on a per-user basis:

> Since JupyterHub can serve many different types of users, JupyterHub managers and administrators must be able to flexibly allocate user resources, like memory or compute. For example, the Hub may be serving power users with large resource requirements as well as beginning users with more basic resource needs. The ability to customize the Hub’s resources to satisfy both user groups improves the user experience for all Hub users.
ref: https://zero-to-jupyterhub.readthedocs.io/en/latest/user-resources.html

> Specify traitlets that take callables as values, allowing dynamic per-user configuration.
ref: https://zero-to-jupyterhub.readthedocs.io/en/latest/advanced.htm

The code seems to be sending using [KubeSpawner](https://github.com/jupyterhub/kubespawner) as the spawner class, however I'm not seeing any configuration parameters in the [jupyterhub_config.py](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/jupyterhub_config.py) which would suggest we can do a per-user allocation of RAM/CPU.

Does this project allow for mapping a set of users to different resources than the defaults configured in the **config.yaml** when creating the Helm charts? If so, were can I find an example of how to do this?

**Comment by consideRatio** [comment]
@szelenka hi =D

KubeSpawner will create a "pod" (kubernetes concept) for each user with the configured resources, which will be the same for each user. Unless... You were to run code to adjust it based on the user just before the user's pod is about to be created (spawn).

```yaml
# in your config.yaml...
hub:
  extraConfig:
    myExtraConfig: |
      async def my_pre_spawn_hook(spawner):
          auth_state = await spawner.user.get_auth_state()
          user_details = auth_state['oauth_user']
          username = user_details['preferred_username']
          if (username == "szelenka"):
              c.spawner.<any KubeSpawner (or Spawner) setting> = <any value>

      c.KubeSpawner.pre_spawn_hook = my_pre_spawn_hook
```

I think something like this may work out for you.

Personally, I'm using information passed by my authenticator to the user_details to decide if my user are supposed to be granted access to GPU Nodes, company internal network access, and other things. Very neat!

**Comment by szelenka** [comment]
I'm still having trouble with this, I'm using the LDAPAuthenticator, and I want to dynamically provision the **profileList** based on the LDAP group the authenticated user is a member of. This way, certain users are offered the option to select greater resources, while other users will only have the default options available to them.

From the JupyterHub source, it seems this should be possible with the [post_auth_hook](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L225), but I'm encountering these types of errors:

> [W 2019-03-11 18:21:09.692 JupyterHub configurable:168] Config option `post_auth_hook` not recognized by `LDAPAuthenticator`.

Would this be a JupyterHub or LDAPAuthenticator problem?

**Comment by consideRatio** [comment]
AH! @szelenka I have recently run into this challenge as well. To customize the profile list, you must currently with jupyterhub 0.9.4 do something like the following:

```yaml
hub:
  extraConfig:
    spawner: |
      # Override the options_form presented for users if they have gpu_access.
      # See: https://github.com/jupyterhub/jupyterhub/issues/2390 for related details
      async def custom_options_form(self):
          auth_state = await self.user.get_auth_state()
          user_details = auth_state['oauth_user']
          username = user_details['preferred_username']

          # Use logic here to decide how to configure your profile_list

          ## FIXME: Before #2415 is part of a JH release, must provide a default option
          ## to be presented.
          ## SEE: https://github.com/jupyterhub/jupyterhub/pull/2415

          self.profile_list = [
              {
                  'default': True,
                  'display_name': 'Shared, 8 CPU cores',
                  'description': 'Your code will run on a shared machine. This machine will already be running and you should be up and running in 30 seconds or less.',
              },
          ]

          # Let KubeSpawner inspect profile_list and decide what to return
          return self._options_form_default()

      c.KubeSpawner.options_form = custom_options_form
```
