### ISSUE TITLE
auth.custom.config should reside in hub-secret rather than hub-config

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1184]
This is my current setup to authenticate with my OIDC provider. But, anything I put within the auth.custom.config is not going into the hub-secret  but instead hub-config, and we are not setting the auth.custom.clientSecret field automatically as we do for the non-custom ones, so I either need to put it outside the config and named `clientSecret` to make it go into the hub-secret instead of hub-config, or I need to manually set it from the jupyterhub_config.py after letting it pass through the hub-secret.

This is a typical reason for me to want to merge the hub-config and hub-secret into one hub-secret, as discussed in #1167.

> ABOUT: I'm using Okta, but KeyCloak can act as a OIDC provider as well. But this config does not couple the logout button of JH back to logout of Okta.

```yaml
jupyterhub:
  hub:
    extraEnv:
      # See: https://<REDACTED.okta.com/oauth2/<REDACTED-AUTH-SERVER-ID>/.well-known/openid-configuration
      JUPYTERHUB_CRYPT_KEY: <REDACTED>
      JUPYTERHUB_API_TOKEN: <REDACTED>
      OAUTH2_AUTHORIZE_URL: https://<REDACTED>.okta.com/oauth2/<REDACTED-AUTH-SERVER-ID>/v1/authorize
      OAUTH2_USERDATA_URL:  https://<REDACTED>.okta.com/oauth2/<REDACTED-AUTH-SERVER-ID>/v1/userinfo
      OAUTH2_TOKEN_URL:     https://<REDACTED>.okta.com/oauth2/<REDACTED-AUTH-SERVER-ID>/v1/token
      OAUTH_CALLBACK_URL:   https://jupyter.example.com/hub/oauth_callback
    extraConfig:
      auth: |
        from z2jh import get_config
        c.GenericOAuthenticator.client_secret = get_config('auth.custom.clientSecret')

  auth:
    type: custom
    custom:
      className: oauthenticator.generic.GenericOAuthenticator
      clientSecret: <REDACTED>
      config:
        client_id:     <REDACTED>
        login_service: Okta
        username_key:  preferred_username
```

/cc: @ablekh
