### ISSUE TITLE
Cannot use named servers feature

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#1186]
Just upgraded our pilot cluster to the latest dev. version of the Helm chart (to test named servers feature), however I don't see relevant UI appearing as expected. The redacted `config.yaml` follows. Thank you!

```
hub:
  cookieSecret: <SECRET>
  extraConfig: |
    c.KubeSpawner.singleuser_image_pull_secrets = "sbdh-acr-secret"
    c.JupyterHub.allow_named_servers = True

proxy:
  secretToken: <SECRET>
  type: ClusterIP
  https:
    enabled: true
    type: letsencrypt
    letsencrypt:
      contactEmail: <EMAIL>
    hosts:
      - <FQDN>

prePuller:
  continuous:
    enabled: true

imagePullSecrets:
  - name: sbdh-acr-secret-contrib

rbac:
  enabled: true

auth:
  admin:
    users:
      - ablekh
  type: github
  github:
    clientId: <CLIENT_ID>
    clientSecret: <CLIENT_SECRET>
    callbackUrl: "https://<FQDN>/hub/oauth_callback"

singleuser:
  profileList:
    - display_name: "Minimal Jupyter environment"
      description: "Provides access to Python kernel only."
      default: true
    - display_name: "Data science environment"
      description: "Provides access to Python, R and Julia kernels."
      kubespawner_override:
        image: jupyter/datascience-notebook:6fb3eca57bd3
    - display_name: "Custom SBDH data science environment - SBDH-DS-O"
      description: "Provides access to Python, R, Julia and Octave kernels."
      kubespawner_override:
        image: <PRIVATE_CONTAINER_REPO>/datascience-octave-notebook:v3
```
