### ISSUE TITLE
Configuring SSL with load balancer in helm chart config does not work

### ISSUE THREAD

**Issue by wierzba3** [jupyterhub/zero-to-jupyterhub-k8s#1194]
**Describe the bug**
Configuring SSL in jupyterhub helm chart does not work, per [Off-loading SSL to a Load Balancer](https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#off-loading-ssl-to-a-load-balancer)
When I install the chart on my cluster, the ELB has only one listener: HTTP (port 80) .

My helm chart config looks like so:
```
proxy:
  secretToken: "<redacted>"
  https:
    enabled: true
    type: offload
  service:
    annotations:
      # Certificate ARN
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<redacted>"
      # The protocol to use on the backend, we use TCP since we're using websockets
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      # Which ports should use SSL
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '1800'
```

I was able to manually update the k8s service to add SSL to load balancer:
```
kubectl apply -f proxy-public.yaml
```

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1800"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <redacted>
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  creationTimestamp: null
  labels:
    app: jupyterhub
    chart: jupyterhub-0.7.0
    component: proxy-public
    heritage: Tiller
    release: jhub
  name: proxy-public
  selfLink: /api/v1/namespaces/jhub/services/proxy-public
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    component: proxy
    release: jhub
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

However, this is not ideal. This seems to be flaky. It works sometimes, and other times it somehow corrupts the k8s nodes, requiring me to completely rebuild the cluster. This is an issue I am actively debugging, so I don't have much info on this. However, the main issue here is that load balancer SSL doesn't work via helm chart config.

**Expected behavior**
I expect a SSL listener to be configured
