### ISSUE TITLE
LDAP Authentication failing

### ISSUE THREAD

**Issue by ramkrishnan8994** [jupyterhub/zero-to-jupyterhub-k8s#1204]
I'm running version 0.7 of Jupyter Hub. (--version=0.7 in helm install )
This is my config.yaml

```
hub:
  # output of first execution of 'openssl rand -hex 32'
  cookieSecret: "<token1>"
  extraConfig: |
    c.KubeSpawner.singleuser_extra_pod_config = {
        'hostNetwork': True,
        'hostPID': True
    }
    c.KubeSpawner.image_pull_secrets = '<creds>'
proxy:
  # output of second execution of 'openssl rand -hex 32'
  secretToken: "<token2>"
singleuser:
  image:
    # Get the latest image tag at:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
    name: jupyter/all-spark-notebook
    tag: latest
  image-pull-secret-name:  '<creds>'
auth:
  type: ldap
  ldap:
    server:
      address: ldap-server
      port: 389
    dn:
      templates:
        - 'uid={username},ou=people,dc=company,dc=org'
```
This is one of the entry types in my ldap server : 

```
dn: uid=doe,ou=people,dc=company,dc=org
objectclass:top
objectclass:person
objectclass:organizationalPerson
objectclass:inetOrgPerson
cn: doe
sn: doe
uid: doe
userPassword: <pass>
```

Jupyter is able to connect to the ldap server, but im getting the following error in the ldap server : 
`**ERROR authn.AbstractAuthenticator (SimpleAuthenticator.java:lookupUserPassword(290)) - ERR_6 Authentication error : Attempt to lookup non-existant entry: uid=doe,ou=people,dc=company,dc=org**`

The entry exists in my users.ldif and still the error occurs.
I have redacted some info. Basically the issue is that LDAP Authentication fails and the logs say that the entry does not exist, but the entry exists.
Is there any issue with my config.yaml
