### ISSUE TITLE
Is it possible to use annotations for PVCs when using dynamic storage for users?

### ISSUE THREAD

**Issue by cbjuan** [jupyterhub/zero-to-jupyterhub-k8s#1241]
I'm using a kind of dynamic PVCs which need some annotations for the creation. As far as I see in the Z2JH `schema.yaml`, the only annotations supported for dynamic PVCs are declared for `hub.db`'s `sqlite-pvc` storage. In this case, I would like to do the same but under the `singleuser.storage.dynamic` section.

## Contents of `config.yaml`
The contents of the YAML I'm using to create the PVC manually are something similar to this:

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-user-1
  namespace: jhub
  annotations:
    ibm.io/auto-create-bucket: "true"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: "bucket-user-1"
    ibm.io/secret-name: storage-secrets-jhub
    volume.beta.kubernetes.io/storage-class: ibmc-s3fs-flex-perf-regional
    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-s3fs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi 
  storageClassName: ibmc-s3fs-flex-perf-regional
```

The `values.yaml` I expect to use to set up JupyterHub can be something similar to:

```yaml
singleuser:
  storage:
    homeMountPath: /home/jovyan
    capacity: 1Gi
    dynamic:
      storageClass: ibmc-s3fs-flex-perf-regional
      annotations:
          annotation-1: "value"
          annotation-2: "value"
          annotation-3: "value"
```

If there is another workaround to use these annotations, it would be great.
Finally, if it's not possible currently and anyone guides me, I'm open to submit a PR and work to provide support for these annotations.

Thanks
