### ISSUE TITLE
How to define api tokens in config.yaml

### ISSUE THREAD

**Issue by jonathanballs** [jupyterhub/zero-to-jupyterhub-k8s#1250]
Hi,

Having read through the documentation about authentication and tokens, I am a bit confused as to how I can define a hard coded api_token in my `config.yaml` file. I think that I need to edit hub.services.proxy.apiTokens or something but I have not been able to successfully create a token.

I have found [examples](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8f6c2a20e409494562a4d6a003031185ee04372f/minikube-config.yaml#L22) however these haven't worked for me. Perhaps I am configuring them incorrectly?

Some pointers would be appreciated!

Jonathan

**Comment by jonathanballs** [comment]
This is my current configuration:
```yaml
proxy:
  secretToken: "30fb1f57ba1ea9977be102cabdcc4b4fbb7a3ae1c52d2673861c9ab4b8934b7a"

singleuser:
  image:
    name: nanowire/datascience-notebook
    tag: 0.0.2

hub:
  image:
    name: nanowire/jupyterhub-nanowireauthenticator
    tag: 0.1
  services:
    nanowireserviceaccount:
      admin: True
      apiTokens:
        - { '4844c8ac5612700667248831d8e811e190efbe47a000f879d4d238fcad498514': 'nanowireserviceaccount' }

auth:
  type: custom
  admin:
    access: true
    users:
      - nanowireserviceaccount
  custom:
    className: "nanowireauthenticator.NanowireAuthenticator"
```

We are using a custom authenticator however I don't think that should affect api tokens as I have been able to create working tokens through the web interface.
