### ISSUE TITLE
[Question] Resource Quota for the entire Jhub namespace

### ISSUE THREAD

**Issue by emirot** [jupyterhub/zero-to-jupyterhub-k8s#1251]
Hi there,

I would like to set resource quota at the namespace level as well as individual pods.
Is this possible ?

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: jhub
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 4Gi
    limits.cpu: "5"
    limits.memory: 20Gi
```

Trying to do something like that using helm, it just hangs an `--debug` and don't say anything.
