### ISSUE TITLE
Volume mount timeout if there are too many files

### ISSUE THREAD

**Issue by 24hours** [jupyterhub/zero-to-jupyterhub-k8s#1252]
I uploaded a bunch of file into my jupyter notebook ( ~300k images ), when i restart my server, the notebook creation always failed with  `Unable to mount volumes for pod "pod": timeout expired waiting for volumes to attach or mount for pod "pod". list of unmounted volumes=[volume]. list of unattached volumes=[volume]`

Eventually server creation timeout and deleted the pod. I tried to mount the volume separately using different deployment and it managed to mount without issue. I finally track down the offending config down to 
```
securityContext:
    fsGroup: 100
    runAsUser: 1000
```
which according to https://github.com/Azure/acs-engine/issues/2989#issuecomment-414933515 is running `chmod` on all file taking up all the time. However, I'm using rancher/longhorn storage class to manage volumes. 

My current work around is increasing `start_timeout: 2400`, while the notebook can be created successfully, it take around ~10 min to spawn a new notebook with high file count. 

Here is my config.yml

```
ingress:
  enabled: true
  hosts:
    - jhub.example.com

singleuser:
  defaultUrl: "/lab"
  storage:
    capacity: 40Gi
  profileList:
    - display_name: "Pytorch / Tensorflow Notebook"
      description: "GPU-Accelerated, 24 CPU cores & 256GB RAM, 2 NVIDIA GPU
      kubespawner_override:
        start_timeout: 2400
        image: registry.example.com/pytorch-notebook-gpu:0.3
        extra_resource_limits:
          nvidia.com/gpu: "2"
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule

hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
```
