### ISSUE TITLE
Setting environment variables that depend on other environment variables using extraEnv

### ISSUE THREAD

**Issue by stevenstetzler** [jupyterhub/zero-to-jupyterhub-k8s#1255]
Hi. I am trying to set an environment variable like so:
```
jupyterhub:
  singleuser:
    extraEnv:
      SPARK_PUBLIC_DNS: my.url.com${JUPYTERHUB_SERVICE_PREFIX}proxy/4040/jobs/
```
The issue is that this will get parsed to the literal string "my.url.com${JUPYTERHUB_SERVICE_PREFIX}proxy/4040/jobs/" instead of evaluating the environment variable. 

A further issue is that since both SPARK_PUBLIC_DNS and JUPYTERHUB_SERVICE_PREFIX are set only on container creation, there doesn't seem to be a way to set an environment variable that requires e.g. JUPYTERHUB_SERVICE_PREFIX before the container is started. I have worked around this by altering my single-user container's Entrypoint script to set SPARK_PUBLIC_DNS, but this feels like an inelegant solution given the option to set extra environment variables directly in the `config.yaml`. Is there any other way I could go about doing this?

I could also imagine that a situation where I pass a list of environment variables that all depend on one another to `extraEnv`, none that depend on environment variables that are only set on container creation. For example,
```
jupyterhub:
  singleuser:
    extraEnv:
      - A: "env_1"
      - B: "env_2_${A}"
      - C: "env_3_${B}_${A}"
```
or something like that. Here, environment variables B and C won't be set correctly, but it would be reasonable to imagine that they would be since A precedes both B and C and B precedes C in definition. Is this functionality possible?
