### ISSUE TITLE
Smooth JupyterHub template customization

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1266]
I've tried figuring out a good pattern to configure the z2jh's charts templates and considered many options, perhaps we can document a decent option like below?

# Not good options
- If we would mount a persistent disk with the templates we would need to have an init container to make the jupyterhub user be able to access it.
- If we would use a script to copy content from a git repo or so, we would copy perhaps a bit much and need to provide credentials to do so if the git repo was private, as well as write such script etc to be started.
- If we would override the Docker image, we would need to manage building and keeping up to date with new builds etc of Docker images, not fun and slow.

# One limited but decent option
We configure JupyterHub to look for templates from k8s ConfigMap resources that we mount on the hub pod. If we change this ConfigMap, it will be reflected in the pod without restart, and JupyterHub will within a minute actually use the latest template.

Woops now that I've written this much, I realize that we won't be able to provide images if we want to, only text. Doh. UPDATE: we can provide images as well, but they must fit within ConfigMap's after base64 encoding, which limits the image size to about ~2MB at most I think.

### Chart configuration
```yaml
hub:
  extraConfig:
    templates: |
      ## Configure JupyterHub to look for the templates we inject with a ConfigMap
      c.JupyterHub.template_paths.insert(0, "/etc/jupyterhub/templates")
  extraVolumes:
    ## Make the hub pod be able to access a ConfigMap volume
    - name: hub-templates
      configMap:
        name: hub-templates
  extraVolumeMounts:
    ## Make the hub pod hub container mount that ConfigMap volume
    - mountPath: /etc/jupyterhub/templates
      name: hub-templates
```

### Manually added k8s ConfigMap

Create a `configmap.yaml` file with the following content and `kubectl apply -n <your-jhub-namespace> configmap.yaml`.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-templates
data:
  # NOTE: helm will render content inside {{` here `}} as a
  # string no matter what curly braces etc. it will find there.
  # So if this yaml is first to be rendered by helm before parsed
  # as a k8s resource, you can wrap the entire section below with
  # that. Like below for example:
  # {{`
  # page.html |
  #   my template content with lots of curly braces that could conflict with
  #   helm rendering...
  # `}}
  spawn.html: |
    {% extends "page.html" %}
    {% if announcement_spawn %}
      {% set announcement = announcement_spawn %}
    {% endif %}

    {% block main %}

    <div class="container">
      {% block heading %}
      <div class="row text-center">
        <h1>Server Options</h1>
      </div>
      {% endblock %}
      <div class="row col-sm-offset-2 col-sm-8">
        {% if for_user and user.name != for_user.name -%}
          <p>Spawning server for {{ for_user.name }}</p>
        {% endif -%}
        {% if error_message -%}
          <p class="spawn-error-msg text-danger">
            Error: {{error_message}}
          </p>
        {% endif %}
        <form enctype="multipart/form-data" id="spawn_form" action="{{url}}" method="post" role="form">
          {{spawner_options_form | safe}}
          <br>
          <input type="submit" value="Start server" class="btn btn-jupyter form-control">
        </form>
      </div>
    </div>

    {% endblock %}
```

# Related
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1267
- https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1691

**Comment by michzimny** [comment]
Hi, we have had the same problem. Eventually, we build an image with the custom template dir based on the official hub image. This has disadvantages as described above.

Are there any news or idea regarding this issue?

**Comment by consideRatio** [comment]
> Are there any news or idea regarding this issue?

Yes, two!

### 1 - Less issues building a derivative hub image
It should now be a lot more sustainable to override the hub image, as the JupyterHub configuration file is attached to it from a configmap and not built into the image itself. This makes you able to keep up with everything in the configuration file automatically, and only need to rebuild your derivative images when the image packages are updated.

### 2 - It is possible to use images (<1 MB) after all
I managed to provide images as well, it is a bit messy to document the exact details of the setup to reproduce this, but the key elements are.

1. You cannot use an image that makes your ConfigMap bigger than 1MB i think, because k8s etcd server only allow them to be at most 1 MB each.

2. You create a meta helm chart - a Helm chart that depends on z2jh, to which you can add a your-own-configmap.yaml template to it. Then, you let that configmap glob files available in a folder called `files` next to the `templates` folder of your meta helm chart.

   ```yaml
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: hub-templates
   data:
     {{- (.Files.Glob "files/etc/jupyterhub/templates/*").AsConfig | nindent 2 }}
   ---
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: hub-external
   binaryData:
     {{- $root := . }}
     {{- range $path, $bytes := .Files.Glob "files/static/external/*" }}
     {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
     {{- end }}
   ```

3. You mount the configmap's and the globbed files as extraVolumes and extraVolumesMount.

   ```yaml
   jupyterhub:
     hub:
       extraVolumes:
         - name: hub-templates
           configMap:
             name: hub-templates
         - name: hub-external
           configMap:
             name: hub-external
       extraVolumeMounts:
         - mountPath: /etc/jupyterhub/templates
           name: hub-templates
         - mountPath: /usr/local/share/jupyterhub/static/external
           name: hub-external
   ```

4. You create templates like `spawn.html` in `files/etc/jupyterhub/templates` where `files` is next to your meta charts `templates` folder. Within such template, you can reference images like this:

   ```html
   <img src="/hub/static/external/myimg.svg" height="80px" />
   ```

----

Hope this helps, good luck @michzimny!
