### ISSUE TITLE
Extract files from Dockerfile to ConfigMaps?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1267]
In #1266 I suggest the use of configmap's to customize jupyterhub jinja templates for its looks. Perhaps this is something we want to do for our `jupyterhub_config.py` file etc. as well that is currently residing in our Dockerfile.

**Comment by minrk** [comment]
We've been experimenting with mounting etc/jupyter as a volume [in mybinder.org-deploy](https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/templates/user-configmap.yaml#L22) and it's been really nice. I think we should try to explore a similar approach to allowing arbitrary config and files in e.g. /etc/jupyterhub from values.yaml, and others using the helm files api.

**Comment by consideRatio** [comment]
Ah! mounting /etc/jupyter as a volume from a ConfigMap! Nice!

**Comment by consideRatio** [comment]
Min your comment inspired me to inject templates and images into the hub pod, as well as configuration files into the singleuser pods.

These are the files I inject, through four ConfigMaps.

![image](https://user-images.githubusercontent.com/3837114/57691428-7851ef00-7644-11e9-8117-9a5b327e53f5.png)

> **WARNING:** I decided to override the images folder of the hub, residing in `/usr/local/share/jupyterhub/static/` with the one I provide. So while doing that I also decided to copy the files I found in this folder to the folder I inject.

### My ConfigMap

> **NOTE:** This configmap was provided in a meta-chart that has a `requirements.yaml` file with a dependency on the Z2JH Helm chart. This is why I'm able to use Helm templating.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-templates
data:
  {{- (.Files.Glob "files/etc/jupyterhub/templates/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-images
# NOTE: Because '.AsConfig' and '.AsSecret' only work on string files, we rely on 'binaryData'
# to perform a base64 decoding before mount, and we base64 our image files first.
binaryData:
  {{- $root := . }}
  {{- range $path, $bytes := .Files.Glob "files/static/images/*" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-bash-bashrc
data:
  {{- (.Files.Glob "files/etc/bash.bashrc").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-jupyter-notebook-config
data:
  {{- (.Files.Glob "files/etc/jupyter/*").AsConfig | nindent 2 }}
```

### My provided Helm template values

> **NOTE:** These was provided to a meta-chart that has a `requirements.yaml` file with a dependency on the Z2JH Helm chart. This is why I'm nesting my configuration under `jupyterhub`.

```yaml
# extract from my provided helm template values in config.yaml
jupyterhub:
  hub:
    extraConfig:
      templates: |
        c.JupyterHub.template_paths.insert(0, "/etc/jupyterhub/templates")
    extraVolumes:
      - name: hub-templates
        configMap:
          name: hub-templates
      - name: hub-images
        configMap:
          name: hub-images
    extraVolumeMounts:
      - mountPath: /etc/jupyterhub/templates
        name: hub-templates
      - mountPath: /usr/local/share/jupyterhub/static/images
        name: hub-images

  singleuser:
    storage:
      extraVolumes:
        - name: user-bash-bashrc
          configMap:
            name: user-bash-bashrc
        - name: user-jupyter-notebook-config
          configMap:
            name: user-jupyter-notebook-config
      extraVolumeMounts:
        # NOTE: using 'subPath' we can mount a single file, and by specifying a filename in the mountPath
        # we will mount this single file into a file instead of a directory.
        # See: https://stackoverflow.com/questions/44325048/kubernetes-configmap-only-one-file
        - mountPath: /etc/bash.bashrc
          subPath: bash.bashrc
          name: user-bash-bashrc
        - mountPath: /etc/jupyter/jupyter_notebook_config.py
          subPath: jupyter_notebook_config.py
          name: user-jupyter-notebook-config
```
