### ISSUE TITLE
User-scheduler doesn't work with rancher/local-path-provisioner

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#1300]
I've just been trying Z2JH on a single node [K3s](https://github.com/rancher/k3s) cluster with [rancher/local-path-provisioner](https://github.com/rancher/local-path-provisioner) for dynamic local volumes. See https://github.com/manics/k3s-test for my `Vagrantfile`.

`hub-db-dir` is created automatically as expected, but user pods fail to start (version `0.9-9c580a1`)

```
$ kubectl describe pod jupyter-c2144b5b-2dbd79-2d4017-2d8c7d-2d5c65e58b0711
...
    Mounts:
      /home/jovyan from volume-c2144b5b-2dbd79-2d4017-2d8c7d-2d5c65e58b0711 (rw)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  volume-c2144b5b-2dbd79-2d4017-2d8c7d-2d5c65e58b0711:
    Type:        PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:   claim-c2144b5b-2dbd79-2d4017-2d8c7d-2d5c65e58b0711
    ReadOnly:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     hub.jupyter.org/dedicated=user:NoSchedule
                 hub.jupyter.org_dedicated=user:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  18s (x2 over 21s)  jh-user-scheduler  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.
```
```
$ kubectl describe pvc claim-c2144b5b-2dbd79-2d4017-2d8c7d-2d5c65e58b0711
Name:          claim-c2144b5b-2dbd79-2d4017-2d8c7d-2d5c65e58b0711
Namespace:     default
StorageClass:  local-path
Status:        Pending
Volume:        
Labels:        app=jupyterhub
               chart=jupyterhub-0.9-9c580a1
               component=singleuser-storage
               heritage=jupyterhub
               release=jh
Annotations:   hub.jupyter.org/username: c2144b5b-bd79-4017-8c7d-5c65e58b0711
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason                Age                   From                         Message
  ----       ------                ----                  ----                         -------
  Normal     WaitForFirstConsumer  13s (x13 over 2m53s)  persistentvolume-controller  waiting for first consumer to be created before binding
Mounted By:  jupyter-c2144b5b-2dbd79-2d4017-2d8c7d-2d5c65e58b0711
```
Setting `scheduling.userScheduler.enabled: false` allows the pod to start.

```yaml
debug:
  enabled: true

auth:
  type: tmp

proxy:
  secretToken: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
  service:
    type: ClusterIP

# Doesn't work with local-provisioner
# scheduling:
#   userScheduler:
#     enabled: false

singleuser:
  storage:
    capacity: 100Mi

ingress:
  enabled: true
  hosts:
  - 192.168.99.100.xip.io
  tls:
  - hosts:
    - 192.168.99.100.xip.io
```
Perhaps there's an interaction between the node affinities set by the storage provisioner (since a pod must be scheduled on the same node that the local PVC is created on) and those set by the user-scheduler? [Local Persistent Volumes are GA in Kubernetes 1.14](https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/) so it'd be worth testing whether this problem is specific to the Rancher Local Path Provisioner, or if it's a problem for all local provisioners in which case a mention in the docs would be helpful.

**Comment by consideRatio** [comment]
Hmmmm, from mobile quickly: try to override the hardcoded old image used by the user scheduler pod, try a newer scheduler binary.

**Comment by cjimti** [comment]
```
    singleuser.storage.dynamic.storageClass: local-path
    hub.db.pvc.storageClassName: local-path
```

Same issue for me. Running jupyterhub-**0.8.1** charts on k3s (using rancher/local-path-provisioner) would create a pv and the Pod could start. However, Gitlab auth is broken in 0.8.x and so I tried jupyterhub-**0.9-b609a67** which fixed the broken gitlab auth but Pods fail to start waiting for the pv. 

Going back to jupyterhub-**0.7.0** both work fine, Gilab auth and Pods get volumes.

**Comment by cgiraldo** [comment]
I hit the same problem deploying version: 0.9.0-alpha.1.084.5ca8a6f on a k3s.
Inspecting the user-schedule-xxxx pod log:

> error binding volumes: persistentvolumeclaims "claim-test" is forbidden: User "system:serviceaccount:ns:user-scheduler" cannot update resource "persistentvolumeclaims" in API group "" in the namespace "ns"

I fix it by creating a new roleBinding to let user-scheduler update the volume claim:

```
{{- if .Values.scheduling.userScheduler.enabled -}}
{{- if .Values.rbac.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-user-scheduler-complementary2
  labels:
    {{- $_ := merge (dict "componentSuffix" "-complementary") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
rules:
  # Workaround for missing permission
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-user-scheduler-complementary2
  labels:
    {{- $_ := merge (dict "componentSuffix" "-complementary") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: user-scheduler
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-user-scheduler-complementary2
  apiGroup: rbac.authorization.k8s.io

{{- end }}
{{- end }}
```
