### ISSUE TITLE
Ability to configure our Ingress resource with a default backend

### ISSUE THREAD

**Issue by nfds89** [jupyterhub/zero-to-jupyterhub-k8s#1314]
Hello everyone,

I just started to deploy Jupyterhub and trying to set up some features.
At the moment I'm struggling configuring the ingress route. I don't want to specify an explicit host for jupyterhub, being accessible by IP, so far.
I already have an Ingress Controller in my k8s cluster, and I'm using the paths to route my applications. So I want to configure an ingress route for my pre-existing Nginx ingress controller.

I have the configuration on ingress as follows:

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  pathSuffix: '(.*)'
```

And when upgrading jupyterhub I get the following error:

```
UPGRADE FAILED
Error: failed to create resource: Ingress.extensions "jupyterhub" is invalid: spec: Invalid value: [] extensions.IngressRule(nil): either `backend` or `rules` must be specified
Error: UPGRADE FAILED: failed to create resource: Ingress.extensions "jupyterhub" is invalid: spec: Invalid value: []extensions.IngressRule(nil): either `backend` or `rules` must be specified
```

I understand that it's because I didn't assign any value to 'hosts' and 
Is there any way around this?

**Comment by manics** [comment]
Kubernetes ingress doesn't support wildcard hosts: https://github.com/kubernetes/kubernetes/issues/41881
Nor does it support bare IPs as it uses virtualhosts. If you don't want to setup a host you can get around this by using something like xip.io to return a domain-name for your IP, e.g. `10.0.0.1.xip.io` → `10.0.0.1`

**Comment by nfds89** [comment]
> Kubernetes ingress doesn't support wildcard hosts: [kubernetes/kubernetes#41881](https://github.com/kubernetes/kubernetes/issues/41881)
> Nor does it support bare IPs as it uses virtualhosts. If you don't want to setup a host you can get around this by using something like xip.io to return a domain-name for your IP, e.g. `10.0.0.1.xip.io` → `10.0.0.1`

Thanks for your reply @manics !

I tried the workaround you suggested, and even though i can upgrade without errors, a cannot longer access to jupyterhub on my browser just using the IP.

**Comment by consideRatio** [comment]
I think we can do something here to help you @nfds89, let me elaborate.

## apiVersion
This Helm chart can render a configurable Ingress resource, but its `apiVersion` will either be `extensions/v1beta1` or `networking.k8s.io/v1beta1`.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/220f952553c140363f2c8488d640e2d95571bb21/jupyterhub/templates/ingress.yaml#L2-L6

Your error indicates you got the old Ingress API, `extensions/v1beta1`.

```
Invalid value: []extensions.IngressRule(nil): either `backend` or `rules` must be specified
```

## backend / defaultBackend

The [extensions/v1beta1 Ingress](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressspec-v1beta1-extensions) has `backend` part of its specification, which also [networking.k8s.io/v1beta1 Ingress](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressspec-v1beta1-networking-k8s-io) has, but [the networking.k8s.io/v1 Ingress](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressspec-v1-networking-k8s-io) has a `defaultBackend` part of its specification instead.

The `networking.k8s.io/v1` version is added with k8s 1.19, we should add a clause for that... but anyhow the point is that our Helm template for the Ingress resource does not allow you to render a `backend` specification, and if you provide something in hosts you end up with `rules` entries which may not allow for wildcard hosts it as @manics described in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1314#issuecomment-503987801.

If you only could specify a `backend` / `defaultBackend` configuration, you would be good I think, so, let's try to address that. That is what would close this issue.

**Comment by EnziinSystem** [comment]
You missing hosts, not hosts in "tls".

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/issuer: letsencrypt-prod
  hosts:
    - domain.com
  tls:
    - hosts:
        - domain.com
      secretName: jupyterhub-tls
```
