### ISSUE TITLE
Documentation for kubespawner override in profile list

### ISSUE THREAD

**Issue by sampathkethineedi** [jupyterhub/zero-to-jupyterhub-k8s#1323]
I'm trying to pull different branches of repo using gitpuller based on the profile selected. 

My **singleuser** snippet from config.yaml - 

```
singleuser:
  profileList:
    - display_name: <name>
      description: <description>
      kubespawner_override:
        cpu_limit: .5
        lifecycle_hooks:
          postStart:
            exec:
              command: ["gitpuller",<url>, <branch>,<folder>]
    - display_name: <name>
      description: <description>
      kubespawner_override:
        cpu_limit: 1
        cpu_guarantee: .2
        storage:
          capacity: 2Gi
        lifecycle_hooks:
          postStart:
            exec:
              command: ["gitpuller",<url>, <different branch>,<folder>]

  storage:
    capacity: 1Gi
  image:
    name: <docker>/<image>
    tag: <tag>

```

What is the proper way to add lifecyclehooks to kubespawner_override? Thanks!

_Originally posted by @sampathkethineedi in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/906#issuecomment-508408018_
