### ISSUE TITLE
gitlab authentication, cannot resolve hostname, 500 internal error

### ISSUE THREAD

**Issue by ahmedanis03** [jupyterhub/zero-to-jupyterhub-k8s#1328]
Hello,

after trying to log in with gitlab auth, the hub redirect me to 500 page, and logs showing an error: tornado process cannot resolve hostname

temp-solution: inject the hostname manually after pod creation in /etc/hosts then everything works fine!

<details><summary>Config.yaml</summary>
<p>

```
proxy:
  secretToken: token

singleuser:
  serviceAccountName: spark
  storage:
    type: none
    extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: nfs-claim
    extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/shared
  profileList:
    - display_name: "spark-conda"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      serviceAccountName: spark
      kubespawner_override:
        image:image

hub:
    db:
      type: sqlite-memorys
    uid: 0
    fsGid: 0
    extraConfig:
      myConfig.py: |
        c.KubeSpawner.uid = 0
        c.JupyterHub.allow_named_servers=True
    extraEnv:
      # for using local instance
      GITLAB_HOST: "http://myhostname:30051/gitlab"

# Will do it manually in my ingress def
#ingress:
#  enabled: true
#  hosts:
#    - myhostname
#  pathSuffix: 'jhub'


auth:
  type: gitlab
  gitlab:
    clientId: "gitlab-id"
    clientSecret: "gitlab-secret"
    # this should be put in gitlab application oauth provider
    callbackUrl: "http://myhostname:30051/hub/oauth_callback"
  admin:
    access: true
    users:
      - root

```
</p>
</details>

<details><summary>ingress.yaml</summary>
<p>

```
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ing
  annotations:
    nginx.ingress.kubernetes.io/class: "nginx"
 #   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: myhostname
      http:
       paths:
       - backend:
          serviceName: gitlab-service
          servicePort: 80
         path: /gitlab
       - backend:
          serviceName: proxy-public
          servicePort: 80
         path: /

```

</p>
</details>
