### ISSUE TITLE
EKS - How to access AWS S3 from JupyterHub terminal

### ISSUE THREAD

**Issue by asimb123** [jupyterhub/zero-to-jupyterhub-k8s#1330]
Hi,
I have successfully installed Jupyterhub on EKS with auto scaling. One of the need is to able to interact with S3 to download and upload file from terminal or python.

Worker node's Instance profile role has all necessary permission to interact with s3. I confirm that by SSH in to worker node. However, when I tried to access s3 from user's Jupyter service terminal, I get error like

`Unable to locate credentials. You can configure credentials by running "aws configure".`

I also tried to install Kube2iam however was not successful.

Could somebody please help or guide me to achieve this?

Thanks,
Asim

**Comment by stevenstetzler** [comment]
For interfacing with AWS services like S3, you usually need to have credentials (access key and secret access key for an IAM user) stored in files in the `~/.aws` folder or stored in [environment variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html). When you run `aws configure` it will ask you to specify a region / access keys and it will create two files in `~/.aws`: `~/.aws/config` which might look like
```
[default]
region = us-west-2
``` 
and `~/.aws/credential` which might look like
```
[default]
aws_access_key_id = <<YOUR_IAM_ACCESS_KEY>>
aws_secret_access_key = <<YOUR_IAM_SECRET_KEY>>
```
To have these available in the Jupyter service terminal, these files will need to be embedded in the single user notebook image that the JupyterHub is spawning (`jupyterhub.singleuser.image`), mounted from a [ConfigMap](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) that exists in your k8s cluster to `~/.aws` (`jupyterhub.singleuser.storage.extraVolumes`), or loaded as environment variables at spawn time (`jupyterhub.singleuser.extraEnv`). Accessing S3 should come down to just ensuring in some way that those files / environment variables exist in the single user container when spawned.

A good first step is to open a Jupyter terminal, export the required environment variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_DEFAULT_REGION`, and see if you can access S3 then.

**Comment by asimb123** [comment]
Thank you @stevenstetzler for your valuable input!
Setting Access key and Secret key works. Any idea how we can leverage IAM role instead of IAM user?

Thanks,
AB

**Comment by stevenstetzler** [comment]
I am not sure if you can escape using an IAM user. For example, we want users using the Jupyter notebooks to have read only access to S3 buckets. To do this, we created an IAM user in our organization to represent a "notebook user" that has **just** the *AmazonS3ReadOnlyAccess* policy. I think you have to assign permissions on a per-account basis and then have the user assume that account's position. I'm not sure of another way to do this.

Also I mentioned mounting a ConfigMap as an option in my original reply, but mounting a [Secret](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/) might be a better way to do this.

**Comment by radu-stefanache** [comment]
@asimb123 I'm currently using kube2iam, the only downside is the fact that this is a global solution (the assumed role) and not a per user one because that would require some more development on the JupyterHub side.
Also, presumingly you've installed this using helm, did you enable CloudMetadata ? https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/ec48133c863973e4640c2b12680a21a27b33d85f/jupyterhub/values.yaml#L168

**Comment by asimb123** [comment]
Thank you very much @radu-stefanache! I was able to use Kube2iam with CA and Pod.

However, I am still not able to set annotation correctly for pod so Kube2iam can assume role correctly.

Below is my `config.yml` and I am putting annotation under proxy. I am not sure if this is right place for it.

```
proxy:
  secretToken: "xxxxx"
  https:
    enabled: true
    type: offload
  service:
    type: LoadBalancer
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
    annotations: 
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: xxxx     
      iam.amazonaws.com/role: arn:aws:iam::xxxxxx:role/k8s-jupyter-pod-role
```

Could you please guide which is right place in `config.yml` to Kube2iam role annotation.

Thanks,
Asim

**Comment by radu-stefanache** [comment]
The role should be passed to the singleuser, not the proxy.

**Comment by asimb123** [comment]
Hi,

I tried different options under singleuser like extra_annotation, extraAnnotation, annotation etc but nothing worked.

Finally, I tried below and I could see annotation in pod

```
hub:
  extraConfig:
    myConfig: |
          c.KubeSpawner.extra_annotations = {"iam.amazonaws.com/role":"k8s-jupyter-pod-role"}
```

But, still from Jupyter Terminal when I am trying to access s3, it is still using Node role instead of using pod role which I specified in annotation. I tried to run different pod to test Kube2iam and it worked as expected.

I am not sure what is the issue. One different between jupyter pod and test pod that Jupyter Pod has taint and toleration. Could this be an issue?

To get this working, I can attach required policies to Node role itself.

Thanks,
Asim
