### ISSUE TITLE
Google OAuth and Whitelisting

### ISSUE THREAD

**Issue by celine168** [jupyterhub/zero-to-jupyterhub-k8s#1345]
Hello! I cannot whitelist specific email addresses while using Google OAuth at the same time. The [documentation](https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#adding-a-whitelist) makes it sound possible, but any user from the same organization could log in, regardless if the whitelist lists them or not.

Part of our `config.yaml` file looks like this:
```
auth:
  type: google
  google:
    clientId: "<client id>"
    clientSecret: "<client secret>"
    callbackUrl: "<domain/hub/oauth_callback>"
    hostedDomain: "<domain>"
    loginService: "<organization>"
  whitelist:
    users:
      - <username>@email.edu

hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
```
I also tried to remove the `@email.edu` part of each user, but that doesn't seem to work either.
Extra info: our cluster is set up so that nginx forwards public IP addresses to the LoadBalancers' `EXTERNAL-IP`'s. Not sure if that would make a difference.
