### ISSUE TITLE
Ingress with backend config + readiness probe

### ISSUE THREAD

**Issue by lboudard** [jupyterhub/zero-to-jupyterhub-k8s#1353]
Hi,

We've started using jupyterhub on our kubernetes cluster (and so far it's great!).
I've experienced limitation on current ingress options.
We use google cloud armor to centralize security policies
https://cloud.google.com/kubernetes-engine/docs/how-to/cloud-armor-backendconfig

We typically need to expose the proxy->hub service and be able to access it through our vpn.
It would be great to add the options to be able to have an ingress defined for which we would be able to configure those policies.
The ingress current config in jhub8's repo doesn't work for us, though I've created one asides that satisfies our needs:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: star-***
    beta.cloud.google.com/backend-config: '{"ports": {"80": "jupyterhub-backend-config"}}'
  name: jupyterhub-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: proxy-public
          servicePort: 80
```
That references this backend configuration:
```
apiVersion: v1
items:
- apiVersion: cloud.google.com/v1beta1
  kind: BackendConfig
  metadata:
    generation: 1
    name: jupyterhub-backend-config
    namespace: jhub
  spec:
    securityPolicy:
      name: security-policy-allowing-vpn
kind: List
```
 And I've also needed to customize the proxy deployment as ingress needs to healtcheck for a readiness/liveness probes on public-proxy service:
```
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /hub/login
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
```

It would be great to have those options added into jhub k8s repo.

Thanks!
