### ISSUE TITLE
hub.deploymentStrategy.type: "Recreate" or "RollingUpdate"

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1365]
@clkao you resolved an issue we got before in #763!

I'm using an external DB and could go for the RollingUpdate [deploymentStrategy](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#deploymentstrategy-v1-apps) of the hub. But I'm a bit confused about a comment. Perhaps you could help me out by some insight about this?

```yaml
  deploymentStrategy:
    # sqlite-pvc backed hub requires Recreate strategy to work
    type: Recreate
    # This is required for upgrading to work
    rollingUpdate: null
```

1. The note say "for upgrading to work". You are referring to helm chart upgrades here, or is it database upgrades, or either?
2. Why did we need to set that to null? I'd assume those are options only in use during a rollingupdate, and now that I want to use a `type: RollingUpdate` strategy. I suspect I will need to specify the default explicitly to override the default `null` value. Should we delete setting that section?

__My attempted answer to 2:__
It seems from the Helm documentation, that setting a value to null is a way to signal we want to delete a previous value, to do an "unset" operation so to say. From my current understanding, that means it would accomplish nothing as the values in `values.yaml` of the helm chart are the default values already.

I think it makes sense to delete setting that value.
