### ISSUE TITLE
Allow customising the proxy image choices via the Helm chart

### ISSUE THREAD

**Issue by mz2** [jupyterhub/zero-to-jupyterhub-k8s#1383]
The JupyterHub Helm chart at the moment allows for the hub and singleuser notebook server image to be configured. There is no (at least documented?) facility for doing the same for the proxy images. I mean these kinds of properties are missing for the images involved in the proxy service:

```
  image:
    name: ...
    tag: ...
  imagePullSecret:
    username: ...
    password: ...
    registry: ...
    enabled: ...
```
