### ISSUE TITLE
Optionally pull the profileList images

### ISSUE THREAD

**Issue by scottyhq** [jupyterhub/zero-to-jupyterhub-k8s#1393]
**Problem:** Long start-up times (10min+)  for hubs that have many large images in profileList. This might be behind some issues we are seeing with pods failing to schedule due to timeouts and network assignment issues on AWS (for example https://github.com/pangeo-data/pangeo-cloud-federation/issues/356)

**Description:**
We are configuring hubs that have many large docker images that users can choose from via profileList:
https://github.com/pangeo-data/pangeo-cloud-federation/blob/b628f0901c4f2b116eadfe3e0d39b7d06a1ae23f/deployments/nasa/config/common.yaml#L61-L80 

It looks like the continuous-image-puller pulls all of these images when a new 'user' node comes online, *regardless of which image the user selected to run* (some cropped output from `kubectl describe`)
```
  Normal  Scheduled  6m30s  default-scheduler                       Successfully assigned nasa-staging/continuous-image-puller-qjm95 to ip-192-168-61-89.ec2.internal
  Normal  Pulling    6m28s  kubelet, ip-192-168-61-89.ec2.internal  pulling image "783380859522.dkr.ecr.us-east-1.amazonaws.com/pangeo-nasa:e76d5bf"
  Normal  Pulled     5m31s  kubelet, ip-192-168-61-89.ec2.internal  Successfully pulled image "783380859522.dkr.ecr.us-east-1.amazonaws.com/pangeo-nasa:e76d5bf"
  Normal  Created    5m8s   kubelet, ip-192-168-61-89.ec2.internal  Created container
  Normal  Started    5m8s   kubelet, ip-192-168-61-89.ec2.internal  Started container
  Normal  Pulling    5m7s   kubelet, ip-192-168-61-89.ec2.internal  pulling image "scottyhq/geohackweek2019:latest"
  Normal  Pulled     4m26s  kubelet, ip-192-168-61-89.ec2.internal  Successfully pulled image "scottyhq/geohackweek2019:latest"
  Normal  Created    4m11s  kubelet, ip-192-168-61-89.ec2.internal  Created container
  Normal  Started    4m10s  kubelet, ip-192-168-61-89.ec2.internal  Started container
```

I see a setting for `prePuller extraImages` in the [docs](https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html?highlight=image%20puller). Would it be straightforward to add `omitImages` - for example only prepull the default image?

pinging @consideRatio and @jhamman

**Comment by consideRatio** [comment]
Hmmmm...

Hmmmm, well to start it is possible to disable, and you can also have placeholders to allow for time to scale up ahead of time, other than that, hmmmm...

A hack to accomplish this atm is to add only those you want to pull using values in the helm chart, and those you dont by using extraConfig to add them to KubeSpawners profilelist.

How are you currently configuring the progile list? through helm values?

**Comment by consideRatio** [comment]
Just to verify also, yepp a node pulling images for pods will do it in sequence, so yes, it can certainly cause slow startups having needing to wait for the continuous pre puller pulling all kinds of images.

**Comment by scottyhq** [comment]
Thanks for the suggestion @consideRatio . 

> How are you currently configuring the progile list? through helm values?

see link in the top comment.

I'm wondering if it would be of interest to follow up with a PR that allows setting something like `defaultOnly: true`. If so, could you point to where changes would need to happen?

```
   jupyterhub:
     prePuller:
       continuous:
         enabled: true
         defaultOnly: true
```

**Comment by consideRatio** [comment]
@scottyhq the prepulling, in both the continuous and the hook pre-puller is done by pods in a daemonset who has additional init-containers.

I think it could be a good idea to have a defaultOnly option. Perhaps `prePuller.pullDefaultImageOnly` or similar would make sense.

**Comment by consideRatio** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/9c15a42b1227f3b54826f273f1689e4dc8c8e12e/jupyterhub/templates/image-puller/_daemonset-helper.yaml#L55-L109

**Comment by Chrisjw42** [comment]
Hi guys, and thanks for your work on this project. 

I believe a feature such as this could solve an issue I'm having. The pre-puller fails to complete it's initial boot when a separate image is defined as part of one of the profiles. 

Multiple profiles have worked well, it's only when an image is defined that the error occurs. In the below example, the helm install runs fine, except when the final profile is added. 

Not sure if this is useful info for you, but thanks anyway! 

```
  profileList:
    - display_name: "Small: 1 CPUs, 6Gb RAM"
      description: |
        Default configuration for normal workflows.
      default: True
      kubespawner_override:
        cpu_limit: 1
        cpu_guarantee: 1
        mem_limit: "6G"
        mem_guarantee: "512M"
    - display_name: "Medium: 2 CPUs, 12Gb RAM"
      description: |
        Slightly larger configuration 
      kubespawner_override:
        cpu_limit: 2
        cpu_guarantee: 1
        mem_limit: "12G"
        mem_guaranttee: "2G"
        extra_resource_limits: {}
    - display_name: "Large: 4 CPUs, 24Gb RAM"
      description: |
        Large configuration for memory-intensive work.
      kubespawner_override:
        cpu_limit: 4
        cpu_guarantee: 2
        mem_limit: "14G"
        mem_guarantee: "8G"
        extra_resource_limits: {}
    - display_name: "Massive: 7 CPUs, 46Gb RAM"
      description: |
        Massive configuration for memory-intensive work.
      kubespawner_override:
        cpu_limit: 7
        cpu_guarantee: 5
        mem_limit: "46G"
        mem_guarantee: "35G"
        extra_resource_limits: {}
    - display_name: "Dev"
      description: |
        Dev
      kubespawner_override:
        image: XYZ:XYZ
        cpu_limit: 1
        cpu_guarantee: 1
        mem_limit: "6G"
        mem_guarantee: "512M"
```
