### ISSUE TITLE
PR Discussion - mounting jupyterhub_config.py

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1395]
# Mounting jupyterhub_config.py into the hub container
We have a configuration file that is built into the image. This makes for a more complicated and slower local development, CI builds, and provides no real benefit over writing it to a ConfigMap that we mount as far as I can tell.

## Relevant understanding
- ConfigMap and Secrets are limited to 1 MB in file size as that is what ETCD which is used by k8s is limited to. Our current configmap and secret for the hub is currently less than 30 kB together, and the jupyterhub_config.py is 18 kB, so we have a large margin here.

## PR work to be done (#1407)
- [x] Create or reuse a helm template .yaml file for a k8s ConfigMap resource, that reads the content of the jupyterhub_config.py and puts it into the `data.jupyterhub_config.py` key's value.
- [x] Mount it on the hub pod.
  - Don't override the full folder where you mount it by mounting the full ConfigMap and all its key's under `data` to a folder. Instead mount the specific key directly to `/etc/jupyterhub/jupyterhub_config.py`. To accomplish this, use subPath to select a specific key to mount and set the mountPath to a filename instead of a directory.
    ```yaml
              volumeMounts:
                - mountPath: /etc/jupyterhub/jupyterhub_config.py
                  name: <config-volume-name-here>
                  subPath: jupyterhub_config.py
    ```
  - [x] Make sure to verify this works and the file can be read as it should, or if we need to also mount it as a specific user or similar.
- [x] Repeat the idea for z2jh.py and cull_idle_servers.py
