### ISSUE TITLE
Blocking access to cloudmetadata endpoint requires "unsecure" PodSecurityPolicy

### ISSUE THREAD

**Issue by deichten** [jupyterhub/zero-to-jupyterhub-k8s#1408]
Fix of issue [#407 Block access to cloud metadata endpoint by default](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/407) unfortunately introduced the requirement to grant `NET_ADMIN` capability and `privileged: true` to the user Pod to successfully start up as the `initContainer` manipulates `iptables`. 

A better approach would be to use Egress rules in a `NetworkPolicy` as usually cluster admins that use PSPs also have NetPols in place.

So for example if JupyterHub is running in `Namespace` jhub a possible Network Policy could look like this:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-cloudmetadata
  namespace: jhub
spec:
  podSelector:
    matchLabels:
      app: jupyterhub
      component: singleuser-server
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32
```

Couldn't check yet but will do asap.
