### ISSUE TITLE
PVC stays pending indefinitely

### ISSUE THREAD

**Issue by GergelyKalmar** [jupyterhub/zero-to-jupyterhub-k8s#1413]
In a single-zone JupyterHub cluster user PVCs seem to be hanging indefinitely:

```
$ kubectl describe pod jupyter-(username)
...
Events:
...
Warning  FailedScheduling  57s (x4 over 60s)  jupyter-user-scheduler
0/2 nodes are available: 2 node(s) didn't find available persistent volumes to bind.

$ kubectl describe pvc claim-(username)
...
Events:
...
Normal  WaitForFirstConsumer  19s (x83 over 20m)  persistentvolume-controller
waiting for first consumer to be created before binding
```

Can anyone provide some guidance what the issue might be?

**Comment by GergelyKalmar** [comment]
A little context: the deployment is new, the cluster has been set up on AWS EKS with autoscaling enabled. It worked on an earlier cluster (without the autoscaling policy). The hub-db volume works fine, it is only the user volumes that seem to hang.

**Comment by GergelyKalmar** [comment]
Okay, for those who stumble upon the same issue... First, if you're deploying to AWS EKS and want to enable single-zone autoscaling you need to restrict your node group to a single zone:

```
...
nodeGroups:
  - name: worker-1-14
    instanceType: t2.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    privateNetworking: true
    volumeType: gp2
    volumeSize: 8
    volumeEncrypted: true
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        cloudWatch: true
    availabilityZones: [eu-west-1a]
...
```

Then you need to add a new storage class as follows (assume this is `storage.yml`):

```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zone-eu-west-1a
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
volumeBindingMode: Immediate
allowedTopologies:
  - matchLabelExpressions:
    - key: failure-domain.beta.kubernetes.io/zone
      values: [eu-west-1a]
```

After which you do `kubectl apply -f storage.yml`. It is important that you set `volumeBindingMode` to `Immediate`, it doesn't seem to work with `WaitForFirstConsumer` (which is the binding mode for the default AWS EBS storage class). Also, you need to restrict creation to the right zone using `allowedTopologies`.

Finally, you need to configure JupyterHub to use the new storage class:

```
singleuser:
  storage:
    capacity: 32Gi
    dynamic:
      storageClass: zone-eu-west-1a
```

This way persistent user volumes will get created in the right zone and they won't hang waiting for the first consumer, moreover, even scaling will work just fine.

I'm not sure anymore if this was triggered by experimenting with single-zone autoscaling, I have a suspicion this may be related to the Kubernetes cluster update to 1.14 instead.

**Comment by faizanbashir** [comment]
I was facing the same problem the whole day, solved it finally for multi-az scaling using the following steps:
1. Deleted the default StorageClass ```gp2```, which was present by default in the cluster after creation.
2. Created a new StorageClass with almost the same config:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  type: gp2
  fsType: ext4
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```
3. Applied the patch to make it the default StorageClass:
```
kubectl patch storageclass gp2 -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```
4. Created PVC and it is working for me.

Spread across 3 Availability Zones:
```yaml
  - name: act1
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 4
    ebsOptimized: true
    volumeSize: 32
    volumeType: gp2
    availabilityZones: ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
        cloudWatch: true
        ebs: true
    ...
```

Kubectl Version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b8860f", GitCommit:"b8860f6c40640897e52c143f1b9f011a503d6e46", GitTreeState:"clean", BuildDate:"2019-11-25T00:55:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
