### ISSUE TITLE
Incompatible versions

### ISSUE THREAD

**Issue by HelenCousins** [jupyterhub/zero-to-jupyterhub-k8s#1415]
I followed these instructions carefully (https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html)

I get this error when I go to the resulting address:
 Redirect loop detected. Notebook has jupyterhub version 0.9.2, but the Hub expects 0.9.4. Try installing jupyterhub==0.9.4 in the user environment if you continue to have problems. 

I have tried a few versions of the Helm chart, they all have similar errors for me.  I am confused as to where I went wrong.

**Comment by manics** [comment]
Can you share your full config (with private info redacted) and the chart versions you tried?

**Comment by HelenCousins** [comment]
cat config.yaml 
proxy:
  secretToken: A SECRET NUMBER

(that's the entire contents)

I did
helm upgrade --install $RELEASE jupyterhub/jupyterhub   --namespace $NAMESPACE    --version=0.8.2   --values config.yaml

and

 helm upgrade --install $RELEASE jupyterhub/jupyterhub   --namespace $NAMESPACE    --version=0.8.0   --values config.yaml

With a 
helm delete --purge $RELEASE
 in between.

 helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}

**Comment by manics** [comment]
Thanks! What values of `$RELEASE` did you use?

**Comment by manics** [comment]
In 0.8.2 the versions of JupyterHub (0.9.6) is defined in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0.8.2/chartpress.yaml#L9-L20
But it looks like the singleuser sample Dockerfile doesn't use this variable: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0.8.2/images/singleuser-sample/Dockerfile#L1
The corresponding base-notebook is https://github.com/jupyter/docker-stacks/blob/8ccdfc1da8d5048874bbc202aefbf16136aaba60/base-notebook/Dockerfile#L91 which uses would've used whatever the latest in the `0.9.*` series was so there's a potential mismatch, will need investigating.

**Comment by HelenCousins** [comment]
echo $RELEASE
jhub

**Comment by consideRatio** [comment]
I think our singleser demo image has got out of sync with our hub image, they may have too different JupyterHub versions.

**Comment by jtlz2** [comment]
I still have this problem too. How can I fix it? It's a showstopper right now. I can provide any info required. Otherwise jhub saves the day!

**Comment by jtlz2** [comment]
@manics @consideRatio Do you know of a workaround? In my case it is 0.9.2 / 0.9.6 - every since yesterday my installation is borked - nothing I have found has overcome this problem :\

**Comment by manics** [comment]
@jtlz2 which singleuser docker image are you using? The singleuser demo image might be out of sync but that doesn't contain anything useful for a production image.

**Comment by jtlz2** [comment]
@manics Thanks! The problem goes away when I (presumably correctly) portforward into the proxy pod rather than the hub. I am not sure why there is a difference though. But at least this is resolved... I wonder if I am the only one to have made this silly mistake? Thanks again

**Comment by Aisuko** [comment]
I hit the same issue, Is there has any solution to fix this? I used the helm chart of `jupyter` was 0.8.2(https://jupyterhub.github.io/helm-chart/)

```
[D 2019-11-25 08:40:36.357 SingleUserNotebookApp application:177] Searching ['/home/jovyan', '/home/jovyan/.jupyter', '/opt/conda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2019-11-25 08:40:36.359 SingleUserNotebookApp application:555] Looking for jupyter_config in /etc/jupyter
[D 2019-11-25 08:40:36.359 SingleUserNotebookApp application:555] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2019-11-25 08:40:36.359 SingleUserNotebookApp application:555] Looking for jupyter_config in /opt/conda/etc/jupyter
[D 2019-11-25 08:40:36.359 SingleUserNotebookApp application:555] Looking for jupyter_config in /home/jovyan/.jupyter
[D 2019-11-25 08:40:36.360 SingleUserNotebookApp application:555] Looking for jupyter_config in /home/jovyan
[D 2019-11-25 08:40:36.362 SingleUserNotebookApp application:555] Looking for jupyter_notebook_config in /etc/jupyter
[D 2019-11-25 08:40:36.362 SingleUserNotebookApp application:577] Loaded config file: /etc/jupyter/jupyter_notebook_config.py
[D 2019-11-25 08:40:36.363 SingleUserNotebookApp application:555] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 2019-11-25 08:40:36.363 SingleUserNotebookApp application:555] Looking for jupyter_notebook_config in /opt/conda/etc/jupyter
[D 2019-11-25 08:40:36.364 SingleUserNotebookApp application:577] Loaded config file: /opt/conda/etc/jupyter/jupyter_notebook_config.json
[D 2019-11-25 08:40:36.364 SingleUserNotebookApp application:555] Looking for jupyter_notebook_config in /home/jovyan/.jupyter
[D 2019-11-25 08:40:36.364 SingleUserNotebookApp application:555] Looking for jupyter_notebook_config in /home/jovyan
[W 2019-11-25 08:40:36.370 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[D 2019-11-25 08:40:36.725 SingleUserNotebookApp config_manager:98] Paths used for configuration of jupyter_notebook_config:
    	/etc/jupyter/jupyter_notebook_config.json
[D 2019-11-25 08:40:36.726 SingleUserNotebookApp config_manager:98] Paths used for configuration of jupyter_notebook_config:
    	/usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2019-11-25 08:40:36.728 SingleUserNotebookApp config_manager:98] Paths used for configuration of jupyter_notebook_config:
    	/opt/conda/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
    	/opt/conda/etc/jupyter/jupyter_notebook_config.d/nbgitpuller.json
    	/opt/conda/etc/jupyter/jupyter_notebook_config.json
[D 2019-11-25 08:40:36.729 SingleUserNotebookApp config_manager:98] Paths used for configuration of jupyter_notebook_config:
    	/home/jovyan/.jupyter/jupyter_notebook_config.json
[I 2019-11-25 08:40:36.786 SingleUserNotebookApp extension:59] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2019-11-25 08:40:36.786 SingleUserNotebookApp extension:60] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2019-11-25 08:40:36.796 SingleUserNotebookApp singleuser:405] Starting jupyterhub-singleuser server version 0.9.2
[D 2019-11-25 08:40:36.803 SingleUserNotebookApp _version:50] jupyterhub version 0.9.6 != jupyterhub-singleuser version 0.9.2.
[C 2019-11-25 08:40:36.803 SingleUserNotebookApp notebookapp:1680] Running as root is not recommended. Use --allow-root to bypass.
[D 2019-11-25 08:40:36.803 SingleUserNotebookApp application:647] Exiting application: jupyter-notebook
```

```
singleuser:
  extraTolerations: []
  nodeSelector: {}
  extraNodeAffinity:
    required: []
    preferred: []
  extraPodAffinity:
    required: []
    preferred: []
  extraPodAntiAffinity:
    required: []
    preferred: []
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: '0.8.2'
  cloudMetadata:
    enabled: false
    ip: 169.254.169.254
  networkPolicy:
    enabled: false
    egress:
    # Required egress is handled by other rules so it's safe to modify this
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 169.254.169.254/32
  events: true
  extraAnnotations: {}
  extraLabels:
    hub.jupyter.org/network-access-hub: 'true'
  extraEnv: {}
  lifecycleHooks:
  initContainers: []
  extraContainers: []
  uid: 0
  fsGid: 0
  serviceAccountName:
  storage:
    type: dynamic
    extraLabels: {}
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: '{username}'
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass: cephfs
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: '0.8.2'
    pullPolicy: IfNotPresent
  imagePullSecret:
    enabled: false
    registry:
    username:
    email:
    password:
  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 1G
  extraResource:
    limits: {}
    guarantees: {}
  cmd: jupyterhub-singleuser
  defaultUrl:
```
