### ISSUE TITLE
Jupyterhub Autoscaling AWS

### ISSUE THREAD

**Issue by mgotham900** [jupyterhub/zero-to-jupyterhub-k8s#1421]
Hello Everyone, 
We have successfully deployed the Jupyter Hub on Kubernetes Cluster by following your guide and also have setup the Cluster Autoscaler which takes care of node autoscaling. But upon the below user scheduler configuration to enable auto scaling, getting the error below (pulled out from logs)
**Logs:**
0/4 nodes are available: 4 node(s) didn't match node selector.

**Config.yaml**
```yaml
scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 1
  userPods:
    nodeAffinity:
      matchNodePurpose: require
```

Any help is highly appreciated, thanks in advance.
