### ISSUE TITLE
from http to https: could not resolve

### ISSUE THREAD

**Issue by yertaitanai** [jupyterhub/zero-to-jupyterhub-k8s#1437]
Hi, 

I am having a problem securing jhub using letsencrypt. I am using GCP and domain is [ds131.fresnostate.edu](http://ds131.fresnostate.edu). Following is the ```config.yaml```:

```
proxy:
    secretToken:"*****"

proxy:
  https:
    hosts:
      - ds131.fresnostate.edu
    letsencrypt:
      contactEmail: ytanai@csufresno.edu
```

And error message shows like this:
```
Error: render error in "jupyterhub/templates/proxy/deployment.yaml": template: jupyterhub/templates/proxy/deployment.yaml:26:32: executing "jupyterhub/templates/proxy/deployment.yaml" at <include (print $.Template.BasePath "/hub/secret.yaml") .>: error calling include: template: jupyterhub/templates/hub/secret.yaml:9:19: executing "jupyterhub/templates/hub/secret.yaml" at <required "Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!" .Values.proxy.secretToken>: error calling required: Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!
Error: UPGRADE FAILED: render error in "jupyterhub/templates/proxy/deployment.yaml": template: jupyterhub/templates/proxy/deployment.yaml:26:32: executing "jupyterhub/templates/proxy/deployment.yaml" at <include (print $.Template.BasePath "/hub/secret.yaml") .>: error calling include: template: jupyterhub/templates/hub/secret.yaml:9:19: executing "jupyterhub/templates/hub/secret.yaml" at <required "Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!" .Values.proxy.secretToken>: error calling required: Proxy token must be a 32 byte random string generated with `openssl rand -hex 32`!
```

Any help would be appreciated and sorry for my illiteracy.

**Comment by gareth-j** [comment]
To use LetsEncrypt you should have a `config.yaml` such as
.
```yaml
proxy:
  secretToken: "<your-string-here>"
  https:
    hosts:
      - ds131.fresnostate.edu
    letsencrypt:
      contactEmail: ytanai@csufresno.edu
```

where <your-string-here> is the output of the `openssl rand -hex 32` command.
