### ISSUE TITLE
Assigning storageClass in config.yaml

### ISSUE THREAD

**Issue by fzhan** [jupyterhub/zero-to-jupyterhub-k8s#1452]
I've tried to setup the storageClass in config.yaml 

```yaml
# cat config.yaml 
singleuser:
  storage:
    dynamic:
      storageClass: cephfs
  defaultUrl: "/jupyterlabhub"
hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']
proxy:
  secretToken: "..."
```

But it doesn't affect the deployment, where I wanted to use cephfs, and the deployment is continued to use Filesystem and create its own namespace.
