### ISSUE TITLE
Authenticator.logut_url - Ignored by tornado?

### ISSUE THREAD

**Issue by cslovell** [jupyterhub/zero-to-jupyterhub-k8s#1475]
The intention is to make it so that when you logout, you get redirected to a particular page, in this case: https://auth.oursite.com/welcome, while the jupyter environment is set up on 'jupyter.oursite.com'.

This doesn't work--it would be great to know the proper way to accomplish this. 

```
hub: 
  extraEnv: 
    GITLAB_URL: https://gitlab.oursite.com
  extraConfig: 
    jupyterlab: |
      c.Spawner.cmd ['jupyter-labhub']
      c.ConfigurableHTTPProxy.command = ['configurable-http-proxy', '--redirect-port', '80']
      c.Authenticator.logout_url = ['https://auth.oursite.com/welcome']
  
auth: 
  type: gitlab
    clientID: [secret client ID]
    clientSecret: [secret client secret]
    callbackUrl: "callbackUrl"
  admin: 
    users: 
     - user1
     - user2
```
