### ISSUE TITLE
Deploying on a cluster with strict PodSecurityPolicies

### ISSUE THREAD

**Issue by ltupin** [jupyterhub/zero-to-jupyterhub-k8s#1491]
Hello there,

First of all I want to thank you a lot for all the work on this helm charts, its really changing the game and avoid hand-craft we did before to customize my jhub server !!!

### Situation
My cluster is secured with PodSecurityPolicies
```
Name:  privileged

Settings:
  Allow Privileged:                       true
  Allow Privilege Escalation:             0xc000304728
  Default Add Capabilities:               <none>
  Required Drop Capabilities:             <none>
  Allowed Capabilities:                   *
  Allowed Volume Types:                   *
  Allow Host Network:                     true
  Allow Host Ports:                       0-65535
  Allow Host PID:                         true
  Allow Host IPC:                         true
  Read Only Root Filesystem:              false
  SELinux Context Strategy: RunAsAny
    User:                                 <none>
    Role:                                 <none>
    Type:                                 <none>
    Level:                                <none>
  Run As User Strategy: RunAsAny
    Ranges:                               <none>
  FSGroup Strategy: RunAsAny
    Ranges:                               <none>
  Supplemental Groups Strategy: RunAsAny
    Ranges:                               <none>


Name:  restricted

Settings:
  Allow Privileged:                        false
  Allow Privilege Escalation:              0xc0008d0139
  Default Add Capabilities:                <none>
  Required Drop Capabilities:              ALL
  Allowed Capabilities:                    <none>
  Allowed Volume Types:                    configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
  Allow Host Network:                      false
  Allow Host Ports:                        <none>
  Allow Host PID:                          false
  Allow Host IPC:                          false
  Read Only Root Filesystem:               false
  SELinux Context Strategy: RunAsAny
    User:                                  <none>
    Role:                                  <none>
    Type:                                  <none>
    Level:                                 <none>
  Run As User Strategy: MustRunAsNonRoot
    Ranges:                                <none>
  FSGroup Strategy: MustRunAs
    Ranges:                                1-65535
  Supplemental Groups Strategy: MustRunAs
    Ranges:                                1-65535
```

### Issue
As you can see containers cannot run as root and must run with a UID. This is best practices to deploy k8s like this accordly with documentation and bad issues like [CVE-2019-11245](https://nvd.nist.gov/vuln/detail/CVE-2019-11245).

When I tried to deploy Jhub with helm charts I get for job `hook-image-awaiter`:
```
Error: container has runAsNonRoot and image will run as root 
```

And for `hook-image-puller`:
```
Error: container has runAsNonRoot and image has non-numeric user (jovyan), cannot verify user is non-root 
```

### How to reproduce

With minikube:

```
K8SADDONS=~/.minikube/files/etc/kubernetes/addons/
K8SPSP=https://gist.githubusercontent.com/ltupin/0c9205777b2bba167e763275b38b25aa/raw/b2238e901ff22a4ae526df81817ce28bc17b641d/psp.yaml

mkdir -p $K8SADDONS
cd $K8SADDONS && { curl -LO $K8SPSP ; cd -; }

minikube start \
  --kubernetes-version=v1.12.0 \
  --cpus 4 \
  --memory 4092 \
  --extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy \
  --alsologtostderr -v=1

# helm3 command is a link to helm version 3 command (as I still have helm 2 on my laptop)
helm3 repo add jupyterhub https://jupyterhub.github.io/helm-chart/
helm3 repo update

RELEASE=jhub-app
NAMESPACE=svc-jhub
kubectl create ns $NAMESPACE &&\
helm3 upgrade --install $RELEASE jupyterhub/jupyterhub \
  --namespace $NAMESPACE  \
  --version=0.8.2 \
  --values hub.yaml
```
And with CLI or `minikube dashboard` you can see.

### What I tried
I am building new containers modifying Dockerfiles I found [here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/master/images). But I think it is not the best way to do.

### Important detail
I can't use the privileged PSP, it is reserved for kube services (the cluster is also protected by [OPA](https://www.openpolicyagent.org)).

**Comment by consideRatio** [comment]
Id be happy to see updates of the chart to reduce root-iness with this in mind.

Steps to take:
1. Identify where we have rootiness causing problems and if they can be disabled etc.
2. Reduce the need for root wherever we can.
3. Document about PSPs and what can be done to manage a restrictive PSP

Workarounds for now to avoid some of them, is to disable prepulling with the hook puller and to not use the network ip tools container, it can be disabled by not blocking cloud metadata something as found in values.yaml.

(on the subway, cant find link now)

**Comment by manics** [comment]
If network policies are enabled by default the network tools container may not be needed any more.
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1271

See also https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1408

**Comment by consideRatio** [comment]
@manics well hmmm, If they are enabled so this helm chart creates a networkpolicy resources AND there is a controller to enforce them installed, such as calico. But, that isn't part of a fresh k8s cluster setup with kubeadm.

**Comment by ltupin** [comment]
So far here what I did.

I ve put:
```
securityContext:
  runAsUser: 1000
```
for all container images (as it was not helmized, I quickly did it by hand on my cluster) and now JHub is running :-D : Maybe we should add this as an option for the charts what do you think ?

But, when I want to spawn a notebook I get a : 
```
Spawn failed: (403) Reason: error HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Wed, 27 Nov 2019 22:15:02 GMT', 'Content-Length': '587'}) HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"jupyter-ltupin\" is forbidden: unable to validate against any pod security policy: [spec.initContainers[0].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden spec.initContainers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.initContainers[0].securityContext.capabilities.add: Invalid value: \"NET_ADMIN\": capability may not be added]","reason":"Forbidden","details":{"name":"jupyter-test","kind":"pods"},"code":403} 
```
Where I can set this `runAsUser: 1000` `securityContext` for the spawned notebooks ?

I'll continue troubleshooting tmw and to test my "solution" on my "real" cluster.

**Comment by consideRatio** [comment]
Look into disabling cloud metadata, there is a init container that does some adminny things. Look in the charts default values.yaml and look for cloudmetadata or something like that. Switch that enabled flag to get rid of the init container!

**Comment by ltupin** [comment]
It works ! Many thanks !

Now lets work on user management :-) with a token authentication I want to make a local env associated to the logged in user /home/loggeduser/ but thats another story.

What do we do with this : 
```
securityContext:
  runAsUser: 1000
```

Adding as an option in the templates ?

**Comment by consideRatio** [comment]
Perhaps this works? I recall we recently got ourselves a passthrough general purpose configuration way in the helm chart. If not, this is meant to be supported.

```yaml
config:
  KubeSpawner:
    run_as_uid: 1000
```

;)

**Comment by ltupin** [comment]
I was talking about all containers running at root or with a non-numeric
user ? This parameter is only for the spawner no ?

Le jeu. 28 nov. 2019 à 01:01, Erik Sundell <notifications@github.com> a
écrit :

**Comment by consideRatio** [comment]
No, I realized that limitation in kubespawner recently. If you want to help, it would be helpful to write that this is of relevance to you in an issue for the kubespawner repository. fsGroup on the pod spec supports this, but kubespawner only sets integers because of historical reasons for JupyterHub spawners in general.

**Comment by consideRatio** [comment]
It is only for the users being spawned yepp. I think you presume I understand more than I do about your issues currently and what you specifically aim to accomplish, in a technically specific manner.

I know that a PSP can specify something totally unreasonable for this helm chart to comply with, so a question to you is, what specific aspect of a PSP would you like to see this helm chart being able to comply with?

Is it relating to these sections? If you help clarify what is required to comply with these, and why they are plausible to have, I think it would be helpful in order for me to better understand your situation and what makes sense to do within this helm chart to comply for that.

```yaml
  # from your PSP named "restricted"
  runAsUser:
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
```

```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
```

**Comment by ltupin** [comment]
@consideRatio the helm must only be compliant with (thats what I find as now):
- MustRunAsNonRoot
- MustRunAs id 1 to 65535

Putting the securityContext bellow for **each container** solve the point because all of them are trying to RunAsRoot and/or with a username (jovyan) instead of an id.
```
securityContext:
  runAsUser: 1000
```

So my idea is to add a boolean statement in charts such as:
`MustRunAsNonRoot: true` ( securityContext will be applied in this condition)

**Comment by manics** [comment]
@ltupin which of the current containers don't comply with the policy? It's good practice to run as non-root, and I think everything in this repo already runs as non-root unless they require privileged access, i.e. network tools and pre-pullers.

**Comment by consideRatio** [comment]
Questions:
1. What is the benefit of saying they must run as id in the range 1-65535? Is this viable to comply with?
2. Does a username like jovyan not always map to a UID also? Can our use of for example jovyan as a username be compliant with a UID range of 1-65535?
3. Is the UID range of 1-65535 the same as "run as non root", how are they different?

**Comment by ltupin** [comment]
@manics at least I found those images are running as root:
- docker run -ti jupyterhub/k8s-network-tools:0.8.2
- quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.15.0
And all jupyterhub images are running as jovyan (hub and notebooks)

@consideRatio 
1. 2. 3. First of all, in my context, I'm not the kubernetes manager, it is owned by another team so I cannot change anything and I already know that they will never change thoses policies for security reasons (to avoid any escalation). I need to adapt applications to their policies. I think this situation can be the same in all companies who are strict with security. Sincerely, that's the first time I encounter this problem with an application (means all others runs asnonroot).
1. As far as I understand, kubernetes check if the user is root regarding is id. Root is always id 0.
2. Previous answer, k8s PSPs is not able to check on username, just on ids
3. As 0 is root, all others are not

**Comment by manics** [comment]
you can safely disable the two root containers:
- `k8s-network-tools`: As @consideRatio said earlier you can disable cloud metadata to avoid running this. Since it manipulates network config it has to run as root.
- `nginx-ingress-controller`: This will only be used if you've enabled the built-in https lets-encrypt certificates in z2jh. This is provided so people with minimal experience are able to configure https. Given you've got dedicated sysadmins and a locked down cluster you'll probably be using other mechanisms for https (e.g. a cluster ingress) so you can disable the built-in https ingress.

If this doesn't take care of your requirements with respect to running as root it would be helpful if you could give us more explanation.

> 3. Previous answer, k8s PSPs is not able to check on username, just on ids

I don't understand what you need to do to fix this. I think all containers are running as UID `1000` by default. It might be possible for the hub to run as an arbitrary UID if write permissions on the required volumes are set. I'm pretty sure it's not possible to have a singleuser-server running as an arbitrary UID unless it also has a matching username.

**Comment by betatim** [comment]
In a lot of other helm charts you can define a `securityContext` for the chart which sets the UID that pods run as. I've discovered this as part of running helm charts on OpenShift where you have to set the UID explicitly.

You then put something like this in your `deployment.yaml`:
```yaml
    spec:
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
```

and something like this in the `values.yaml`:
```yaml
securityContext:
  enabled: true
  runAsUser: 1000
  fsGroup: 1000
```

I think trying to follow this structure would be good when we introduce this kind of feature.

The [`nginx-ingress` chart](https://github.com/helm/charts/tree/master/stable/nginx-ingress) uses `podSecuritycontext` to do this.

The container that executes `iptables` rules to block access to the metadata service would have to be replaced by something equivalent for disabling access. There is no way to do what it does without being root.

**Comment by betatim** [comment]
Another thing people do to deal with getting their container to run in an OpenShift cluster where the UID you will end up running as is unknown until you start the pod is to make directories and files owned by group `root`. Which I think means because the UID that OpenShift picks for you doesn't equate to a user that exists you are in the "root" group and hence can access stuff.

I need to find my notes on this to really remember how things work but https://blog.openshift.com/jupyter-on-openshift-part-6-running-as-an-assigned-user-id/ looks like a good introduction and it is related to JupyterHub ;)

**Comment by betatim** [comment]
This is a security context I use to deploy the keycloak chart from `helm/charts` on an OpenShift cluster:
```yaml
securityContext:
  runAsUser: 1002880001
  fsGroup: 1002880000
  runAsNonRoot: true
```
