### ISSUE TITLE
Unable to get JWT Authenticator working with Z2JH

### ISSUE THREAD

**Issue by stevegore** [jupyterhub/zero-to-jupyterhub-k8s#1506]
I'm not having much luck with using [JWT Authenticator](https://github.com/mogthesprog/jwtauthenticator) with Z2JH.

I have a custom Docker image to include the authenticator:

```
FROM jupyterhub/k8s-hub:0.8.2
RUN pip3 install jupyterhub-jwtauthenticator
```

Running it confirms it is available in the same environment that JupyterHub runs under:

```
-> docker run --rm -it qctrl/jupyterhub-k8s-hub python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jwtauthenticator.jwtauthenticator import JSONWebTokenAuthenticator
>>> a = JSONWebTokenAuthenticator()
```

Here's my `config.yml` (slightly redacted):

```
hub:
  image:
    name: qctrl/jupyterhub-k8s-hub
    tag: 0.8.2

singleuser:
  defaultUrl: "/lab"
  imagePullSecret:
    enabled: true
    registry: asia.gcr.io
    username: _json_key
    password: $GCLOUD_SERVICE_KEY

  image:
    name: <our image>
    tag: latest
    imagePullPolicy: Always    

  cpu:
    limit: 2
    guarantee: 1
  memory:
    limit: 4G
    guarantee: 2G
  storage:
    capacity: 100Mi

  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            rm -rf lost+found;
            cp -r /examples /home/jovyan;
            cp -r /README.ipynb /home/jovyan

prePuller:
  continuous:
    enabled: true

scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 2
  userPods:
    nodeAffinity:
      matchNodePurpose: require

cull:
  enabled: true
  timeout: 900
  every: 300

hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

auth:
  type: custom
  custom:
    className: jwtauthenticator.jwtauthenticator.JSONWebTokenLocalAuthenticator
    config:
      secret: '$SIGNING_KEY'
      username_claim_field: user_id
      header_name: 'Authorization'
  admin:
    users:
      - "steve" 
```

However, I still get the following error on start, which would seem to indicate the class cannot be imported:

```
[C 2019-12-02 05:28:18.719 JupyterHub application:90] Bad config encountered during initialization:
[C 2019-12-02 05:28:18.719 JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f346f7e50f0> instance must be a type, but 'jwtauthenticator.jwtauthenticator.JSONWebTokenLocalAuthenticator' could not be imported
```

This is preceded by what looks to be a help guide for the `jupyterhub` command: 
```Loading /etc/jupyterhub/config/values.yaml
Loading /etc/jupyterhub/secret/values.yaml
Loading extra config: jupyterlab
Start a multi-user Jupyter Notebook server

Spawns a configurable-http-proxy and multi-user Hub, which authenticates users
and spawns single-user Notebook servers on behalf of users.

Subcommands
-----------

Subcommands are launched as `jupyterhub cmd [args]`. For information on using
subcommand 'cmd', do: `jupyterhub cmd -h`.
etc.
etc.
```

I've tried many various combinations but cannot seem to get this to work. Any suggestions?

**Comment by stevegore** [comment]
It would appear that something is wrong with my YAML. It was still running the default hub image despite the below:

```
hub:
  image:
    name: qctrl/jupyterhub-k8s-hub
    tag: 0.8.2
```

Once I used  ` --set hub.image.name=qctrl/jupyterhub-k8s-hub  --set hub.image.tag=0.8.2` with my `helm upgrade` the issues seems to have resolved.
