### ISSUE TITLE
Upgrade from Beta2 to Beta3 fails

### ISSUE THREAD

**Issue by belfhi** [jupyterhub/zero-to-jupyterhub-k8s#1550]
I get a TOO_MANY_REDIRECTS error when upgrading from Beta2 to Beta3 that
uses the traefik proxy, so I'm guessing that might be cuasing the problems for me. 
We use Nginx Ingress controller into the k8s cluster, which worked fine. There is an alias set in out 
DNS to resolve eosc-pan-jhub.desy.de to one of the Cluster nodes.
Cert-manager is installed and used instead of the provided kube-lego which is deprecated for 
account creation. 
My config.yaml relevant infos are:

```
proxy:
  secretToken: <TOKEN>
  service:
    type: ClusterIP
  https:
    enabled: true
    type: letsencrypt
    letsencrypt:
      contactEmail: <MYEMAIL>
    hosts:
      - eosc-pan-jhub.desy.de
ingress:
  enabled: true
  hosts:
    - eosc-pan-jhub.desy.de 
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-body-size: 64m
    ingress.kubernetes.io/proxy-connect-timeout: "30"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  tls:
  - secretName: jupyterhub-tls
    hosts:
      - eosc-pan-jhub.desy.de
```
