### ISSUE TITLE
Setting resource requests only for some profiles

### ISSUE THREAD

**Issue by betatim** [jupyterhub/zero-to-jupyterhub-k8s#1557]
A configuration like shown below with two profiles where one profile has a guarantee bigger than the default limit doesn't work right now. When you try to launch your user's pod for the second profile the Pod spec that gets sent to kubernetes has the defaut mem limit in it, instead of the mem limit set in the second profile. [Full log](https://gist.github.com/betatim/79e3b26d61415813f364350f0ee84ed4)

```yaml
singleuser:
    cpu:
      guarantee: 0.5
      limit: 2
    memory:
      guarantee: 2G
      limit: 3G
    profileList:
      - display_name: "Launches fast (2CPUs, 2G)"
        description: "Just the basics"
        default: true
      - display_name: "Launches more slowly (4CPUs, 9G)"
        description: "More toys!"
        kubespawner_override:
          cpu_guarantee: 0.8
          cpu_limit: 4
          mem_guarantee: '9G'
          mem_limit': '9G'
```

I've not investigated if this is a bug in the helm chart or kubespawner.

The workaround is to define the resources in each profile instead of having a "default".
