### ISSUE TITLE
Doing a Kubernetes upgrade if JupyterHub is running will stall the Kubernetes upgrade

### ISSUE THREAD

**Issue by kmhughes** [jupyterhub/zero-to-jupyterhub-k8s#1575]
I have installed the JupyterHub chart 0.8.2.

I was doing an automatic upgrade of my Kubernetes cluster on GKE. Eventually the update stalled out. After some research I found that the node running the Jupyter Hub Hub pod was not updating. The Pod Disruption Budget for the Hub pod requires a minimum of 1 instance of the pod. This meant the single instance of the Hub could not be shut down because that would mean 0 instances of the Hub.

The deployment.yaml template for the Hub only allows for a single instance of the Hub (replicas: 1) and there is no way in the values.yaml file to specify the number of replicas desired.

```
jupyterhub/templates/hub/deployment.yaml:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: 1  <= NOTICE CANNOT BE CHANGED

```
This means if you enable a pod disruption budget, you cannot drain the node running the Hub pod unless you have a minimum value of 0 in your pod disruption budget.

Please make it so that the number of replicas of the Hub pod can be specified in a values.yaml file. You might also want to mention having a pod disruption budget enabled with only 1 replica will lead to this problem.

I have not checked if the other pods have similar issues.
