### ISSUE TITLE
singleuser pod stock in "Reconnecting" when using Ambassador to manage ingress

### ISSUE THREAD

**Issue by josibake** [jupyterhub/zero-to-jupyterhub-k8s#1596]
Hey all, I've been trying to deploy using helm (`0.9.0-beta.3`) and am running into the following issue: we use ambassador internally, so the goal is to turn off the loadbalancer and route everything through Ambassador.. so far so good. Here are the relevant parts of my config:

```yaml
jupyterhub:
  auth:
    google:
      callbackUrl: <redacted>
      clientId: <redacted>
      clientSecret: <redacted>
      hostedDomain:
      - <redacted>
      loginService: <redacted>
    type: google
  hub:
    extraConfig:
      jupyterConfig: |
        c.NotebookApp.token = ''

  proxy:
    secretToken: <secret_token>
    service:
      annotations:
        getambassador.io/config: |
          ---
          apiVersion: ambassador/v1
          kind: Mapping
          name: "jupyterhub_mapping"
          host: "<redacted>"
          prefix: /
          service: "http://proxy-public.jhub.svc.cluster.local:80"
          timeout_ms: 30000
          connect_timeout_ms: 10000
          retry_policy:
            retry_on: "gateway-error"
            num_retries: 2
            per_try_timeout: "10s"
      type: NodePort

  singleuser:
    defaultUrl: /lab
```

Everything starts up seemingly fine but then when I open a notebook, it gets stuck as "Reconnecting" and won't execute cells. Checking the logs in Ambassador, everything seems to be fine and I can't find anything off in the hub or single user pod. Does anything look wrong with what I have here and is using ambassador even possible the way I'm doing it? Thanks!

**Comment by manics** [comment]
I don't have any experience with Ambassador. Does your deployment work with a standard ingress/loadbalancer/nodeport?

If your notebook starts but doesn't execute it could be a problem with websockets? If you check your browser's dev-tools console you might see some errors.
https://www.getambassador.io/user-guide/websockets-ambassador/

**Comment by josibake** [comment]
Hey @manics , thanks for the reply! I was able to get something running using the regular loadbalancer but since we manage certificates and everything else through ambassador, that won't work for production. I'll investigate the websockets thing. 

Based on what I have in the config, is there any reason why it shouldn't work to just make the `public-proxy` a NodePort service and attach it to something external?

**Comment by josibake** [comment]
That was indeed the problem! Thanks for much for your help, @manics . For posterity, all I needed to do was the following:

```yaml
proxy:
    secretToken: <secret_token>
    service:
      annotations:
        getambassador.io/config: |
          ---
          apiVersion: ambassador/v1
          kind: Mapping
          name: "jupyterhub_mapping"
          host: "<redacted>"
          prefix: /
          service: "http://proxy-public.jhub.svc.cluster.local:80"
          use_websocket: true
          timeout_ms: 30000
          connect_timeout_ms: 10000
          retry_policy:
            retry_on: "gateway-error"
            num_retries: 2
            per_try_timeout: "10s"
      type: NodePort
```
