### ISSUE TITLE
Pending external IP

### ISSUE THREAD

**Issue by Joris29** [jupyterhub/zero-to-jupyterhub-k8s#1597]
Hi i'm trying to set up jupyterhub with an external ip.

But it keeps saying pending:
```
proxy-public   LoadBalancer   10.105.248.225   <pending>
```

Config:
```yaml
proxy:
  secretToken: ''
  service:
    loadBalancerIP: 172.168.0.15
```

What i want to achieve is to add the external ip's like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
spec:
  selector: 
    app: test
  type: LoadBalancer
  externalIPs:
    - 172.168.0.15
  ports:
    - port: 3333
      targetPort: 3333
```

Which results into:
```
test      LoadBalancer   10.111.242.223   172.168.0.15
```

**Comment by consideRatio** [comment]
@Joris29 this was new to me... Is it related to a new feature in some k8s version to only be able to specify the external ip like this, or is it a custom requirement of the controller reacts to LoadBalancer services and provides the actual service?

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller
spec:
  clusterIP: 10.68.34.103
  loadBalancerIP: 35.204.81.31
  ports:
  - name: http
    nodePort: 31752
    port: 80
    protocol: TCP
    targetPort: http
  - name: gitlab-shell
    nodePort: 30835
    port: 22
    protocol: TCP
    targetPort: gitlab-shell
  selector:
    app: nginx-ingress
    component: controller
    release: gitlab
  type: LoadBalancer
```
