### ISSUE TITLE
Authentication with openldap

### ISSUE THREAD

**Issue by sibcm** [jupyterhub/zero-to-jupyterhub-k8s#1600]
Can someone kindly share a sample config for auth using OpenLDAP?  My k8s was created  on a Bright cluster with a fully functional OpenLDAP.  I kept getting '500 Internal Error' while attempting to setup this LDAP to authenticate users following the admin manual.  Inspecting the logs from  the hub did not yield any useful information. 

Thank you for any hints in advance,

GR

**Comment by titansmc** [comment]
@sibcm 
```
auth:
  type: ldap
  whitelist:
    users:
      - prometheus
  admin:
    access: true
    users:
      - myuser
  dummy:
    password:
  ldap:
    server:
      address: ldapr.domain.org
    dn:
      lookup: true
      search:
        filter: '(&(objectClass=posixAccount)(uid={login}))'
      templates:
        - '{username}'
      user:
        searchBase: 'cn=Users,dc=domain,dc=org'
        attribute: 'uid'
        dnAttribute: 'entryDN'
    #user: {}
  state:
    enabled: false
    cryptoKey:

```
