### ISSUE TITLE
Poststart hook not executed

### ISSUE THREAD

**Issue by romanzac** [jupyterhub/zero-to-jupyterhub-k8s#1606]
Hi All,

**Describe the bug**

I have configured profile and related poststart hook. It is a simple copy from /tmp directory into user's home.

```yaml
singleuser:
  storage:
    dynamic:
      storageClass: gfs
  image:
    name: registry:8443/q/bio-jupyter-k8s
    tag: test
    pullPolicy: IfNotPresent
  #fsGid: 100
  profileList:
    - display_name: "Bio Environment"
      description: "Sample Jupyter notebook."
      default: true
      lifecycle_hooks:
        postStart:
          exec:
            command:
              - "sh"
              - "-c"
              - >
                cp -r -u /tmp/bio-python /home/jovyan;
```

**To Reproduce**
Login as LDAP user, select profile and start it.

**Expected behavior**
bio-python folder copied to /home/jovyan

**Compute Information**
- helm upgrade --install jhub jupyterhub/jupyterhub --version 0.9.0-beta.4  --values config.yaml
- Kubernetes 16.6
