### ISSUE TITLE
How do you expose Jupyterhub to the outside without using public-proxy

### ISSUE THREAD

**Issue by summerswallow** [jupyterhub/zero-to-jupyterhub-k8s#1625]
Here's the use case,

I have a Kubernetes cluster on AWS, built on an existing VPC with an existing load balancer. I'd like to simply be able to forward to hub using an existing load balancer without creating a new one.

What is the best way to do this? What node should be exposed?

Originally, I changed the hub service to a NodePort and thought that worked however, recently I see a lot of redirection issues /user->/hub/user -> /user and /service ->/hub/service -> 404. So either there is an issue with my network or this approach doesn't work.

Appreciate any suggestions for what to try next.

**Comment by consideRatio** [comment]
> I have a Kubernetes cluster on AWS, built on an existing VPC with an existing load balancer. I'd like to simply be able to forward to hub using an existing load balancer without creating a new one.

If you have a loadbalancer already, you should:
1. Make your-jupyterhub-domain.com point to it
2. Assuming your load balancer can reach your cluster local addresses, configure proxy-public like this:
   ```yaml
   proxy:
     service:
       type: ClusterIP
   ```
3. Make your loadblancer redirect traffic to http://proxy-public.<jupyterhub namespace>/

If you cannot assume your load balancer can reach your cluster local addresses, you need an entrypoint to the cluster somehow, and then perhaps you need to make the service have an externalIP hmmm...

**Comment by sortigoza** [comment]
> > I have a Kubernetes cluster on AWS, built on an existing VPC with an existing load balancer. I'd like to simply be able to forward to hub using an existing load balancer without creating a new one.
> 
> If you have a loadbalancer already, you should:
> 
> 1. Make your-jupyterhub-domain.com point to it
> 2. Assuming your load balancer can reach your cluster local addresses, configure proxy-public like this:
>    ```yaml
>    proxy:
>      service:
>        type: ClusterIP
>    ```
> 3. Make your loadblancer redirect traffic to http://proxy-public./
> 
> If you cannot assume your load balancer can reach your cluster local addresses, you need an entrypoint to the cluster somehow, and then perhaps you need to make the service have an externalIP hmmm...

There seems to be an issue when trying to use this value:

```
Error: UPGRADE FAILED: Service "proxy-public" is invalid: [spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP', spec.ports[1].nodePort: Forbidden: may not be used when `type` is 'ClusterIP']
```

I have tried setting `nodePorts.{http,https}` to nothing, "", and false, all of them result in the same issue.

All our kubernetes traffic goes trough the ingress-controller, we are trying to disable the proxy-public to avoid exposing it.

The template has some conditions around it but they are not having effect:

```
      {{- if .Values.proxy.service.nodePorts.https }}
      nodePort: {{ .Values.proxy.service.nodePorts.https }}
      {{- end }}
```

Chart version: 0.9.1
Helm Version: 2.14.3
Kubernetes Version: 1.15 (EKS)
Ingress controller: traefik (with https)

**Comment by consideRatio** [comment]
@sortigoza I believe your issue is a result of trouble with Helm to reconcile the old configuration with the new. It will probably require some `kubectl delete service proxy-public` and redo `helm upgrade` and, also, whenever you use `helm upgrade`, i strongly recommend `--cleanup-on-fail` to avoid other issues.

**Comment by cglacet** [comment]
For those who have ingress (nginx here) enabled, maybe you can use this: 

```yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyterhub-ingress
  namespace: jupyter
  labels:
    environment: jupyter
    app: jupyterhub
    tier: backend
    run: web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /hub/
            pathType: Prefix
            backend:  
              service:
                name: proxy-public
                port: 
                  number: 80
```

The service does some kind of url rewriting (it seems) so I feel like it has to be at `/hub` (at least my usual ingress URL rewriting didn't work here as it seems everything that goes to `/` is automatically redirected to `/hub`).

**Comment by bartgras** [comment]
Thanks @cglacet. 

My (AWS) cluster has ALB and jupyter subdomain pointing at it. 
In my case there was no issue with rewriting and following manifest works as well:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyter-ingress
  namespace: jupyter
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
spec:
  rules:
    - host: notebooks.example.com
      http:
        paths: 
          - path: /
            backend:
              serviceName: proxy-public
              servicePort: 80
```
