### ISSUE TITLE
cloudMetadata: improve on-prem confguration

### ISSUE THREAD

**Issue by aflag** [jupyterhub/zero-to-jupyterhub-k8s#1644]
### Proposed change

When deploying on prem, we obviously won't have a metadata server, like cloud providers do. Therefore, if we want to skip the network-tool setup, we need to add the following configuration:

```
singleuser:
  cloudMetadata:
    enabled: true
```

which is a bit misleading. I suggest something like

```
cloud:
  enabled: <true|false>
singleuser:
  cloudMetadata:
    enabled: <true|false>
```

So, if cloud is disabled, any cloud settings would be ignored.

### Alternative options

Alternatively, we could at least have a more descriptive name in the current variable. Something like:

```
singleuser:
  blockCloudMetadata: <true|false>
```

that way, if deploying on prem, people wouldn't be surprised to see

```
singleuser:
  blockCloudMetadata: false
```

### Who would use this feature?

Anyone deploying jupyterhub to a on-prem k8s cluster (and possibly some clouds without metadata servers?)

**Comment by manics** [comment]
I can see why it's confusing.

Adding a top level key `cloud` is still confusing because on-prem can still be described as "in the cloud", and may or may not include a metadata server.

I think the more descriptive name `blockCloudMetadata` makes sense. If we wanted to avoid a breaking change this requires a bit of additional logic to check if the old name is defined, which makes the chart more complex.

Let's see what everyone else thinks?

**Comment by consideRatio** [comment]
This was resolved by #1805.

```yaml
# new way to disable the initContainer using iptables to block that cloud metadata server
singleuser:
  cloudMetadata:
    blockWithIptables: false
```
