### ISSUE TITLE
nodeSelectorTerms not behaving as expected

### ISSUE THREAD

**Issue by rlantz-cfa** [jupyterhub/zero-to-jupyterhub-k8s#1646]
Possible that I'm misreading how the YAML is being parsed.  Apologies if so, but this same set up appears to work for other pod specs.

### Bug description
I'm attempting to specify `extraNodeAffinity` in the config.yaml.  Using the following `singleuser` spec throws an error when attempting to deploy/upgrade.
```
singleuser:
  cpu:
    limit: 2
    guarantee: 0.05
  memory:
    limit: 4G
    guarantee: 512M

  extraNodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: group-type
          operator: In
          values: 
            - single-user
```
#### Expected behaviour
I expect that a set of `nodeSelectorTerms` would be handled as a list.  I've tried quite a few combinations of list and literal within the `nodeSelectorTerms` to no avail.  It either fails on upgrade or when the user pod is created after the user selects a container. (500 error)

#### Actual behaviour
It appears to fail a validation, though the error is truncated...
```
Error: UPGRADE FAILED: DaemonSet in version "v1" cannot be handled as a DaemonSet: 
v1.DaemonSet.Spec: v1.DaemonSetSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Affinity:
 v1.Affinity.NodeAffinity: v1.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution: 
v1.NodeSelector.NodeSelectorTerms: []v1.NodeSelectorTerm: decode slice: 
expect [ or n, but found {, error found in #10 byte of ...|orTerms":{"nodeSelec|..., bigger context 
...|lingIgnoredDuringExecution":{"nodeSelectorTerms":{"nodeSelectorTerms":[{"matchExpressions":
[{"key":"|...
```

### Your personal set up

Running on EKS - K8S version 1.15 with two nodegroups.  One has a label: `group-type=single-user`.
 - OS:
Linux
 - Version:
 jupyterhub --version=0.8.2
 - Configuration:
