### ISSUE TITLE
PAM authentication

### ISSUE THREAD

**Issue by marty90** [jupyterhub/zero-to-jupyterhub-k8s#1655]
Is it possible to authenticate local users using the PAMAuthenticator?

I tried setting:
```
auth:
  type: custom
  custom:
    className: jupyterhub.auth.PAMAuthenticator
```

and mounting `/etc/pam.d`

but does not work.

**Comment by marty90** [comment]
Thank you. Just to inform, finally we managed to make local authentication working from within the Kubernetes Hub image.
We had to mount several volumes (our setup has LDAP + Kerberos) on both Hub and user images:

- /var/run/nslcd/socket
- /etc/nslcd.conf
- /etc/nsswitch.conf
- /etc/pam.d
- /etc/krb5.conf

**Comment by jasonliu747** [comment]
@marty90 I run a pod with root, and mount /var/run/nslcd/socket, /etc/nslcd.conf, /etc/nsswitch.conf and /etc/pam.d. After the pod is running, I get `No passwd entry for user xxx(ldap user)` when trying to use `su - xxx` command.

**Comment by fadam-csgroup** [comment]
Thanks  to @marty90 comment, I managed to have a working configuration using classical pam_unix.so module.

This is done by running the hub as root, and mounting the configuration files of the host. The corresponding part of the values file is bellow:
```yaml
hub:
  config:
    JupyterHub:
      authenticator_class: pam
  extraVolumes:
    - name: passwd
      hostPath:
        path: /etc/passwd
    - name: group
      hostPath:
        path: /etc/group
    - name: shadow
      hostPath:
        path: /etc/shadow
  extraVolumeMounts:
    - name: passwd
      mountPath: /etc/passwd
    - name: group
      mountPath: /etc/group
    - name: shadow
      mountPath: /etc/shadow
  containerSecurityContext:
    runAsGroup: 0
    runAsUser: 0
```

The remaining work is to:
- set the NB_USER and NB_UID singleuser environment variables, depending of the user.
This should be possible by adding some python code (see [here](https://discourse.jupyter.org/t/local-unix-users-in-jupyterhub-minikube-setting-up-authentication-volumes-nb-uid-nb-user/13937))
- ensure that the file permissions are correct in the singleuser container image.
