### ISSUE TITLE
Allow custom securityContext in hub

### ISSUE THREAD

**Issue by sdague** [jupyterhub/zero-to-jupyterhub-k8s#1677]
We'd like to be able to integrate py-spy into our JupyterHub hub environment to help debug some performance issues that have been seen.

In order to do that we need additional securityContext parameters per - https://github.com/benfred/py-spy#how-do-i-run-py-spy-in-kubernetes 

### Proposed change

A change such as adding support for extraSecurityContext below would allow this. Is this something that would be interesting to upstream (if so will make a patch for it).

```yaml
          securityContext:
            runAsUser: {{ .Values.hub.uid }}
            {{- if .Values.hub.extraSecurityContext }}
            {{- .Values.hub.extraSecurityContext | toYaml | trimSuffix "\n" | nindent 12 }}
            {{- end }}
            # Don't allow any process to execute as root inside the container
            allowPrivilegeEscalation: false
```

### Who would use this feature?

This would allow for adding py-spy into local builds, we'd use it for profiling the system when under load to help with debugging and tuning.
