### ISSUE TITLE
k8s question: dynamic storage provisioning for kubeadm setup cluster w. multiple nodes (storage not provisioned for PVC w. a local-storage storageclass)

### ISSUE THREAD

**Issue by Guanzhou-Ke** [jupyterhub/zero-to-jupyterhub-k8s#1709]
I am so sorry for posted this question here. I try to post this question on [SOF](https://stackoverflow.com/questions/62715904/kubernetes-why-jupyterhub-new-users-pvc-was-pending) before, but I do not get any answer. Here is my last try. Help me! Thanks!

My problem is **When a new user to login my jupyterhub on k8s, it could not auto create a PV for this new user, just a user's PVC and it was pending.**

My environment are:

```
System: Centos 7
k8s: 1.18.0
JupyterHub: 0.9.0
```

I using a local storage now, and it config such below:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

it was running well.

When I try to first install JupyterHub with below config:

```
proxy:
  secretToken: "2fdeb3679d666277bdb1c93102a08f5b894774ba796e60af7957cb5677f40706"
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
singleuser:
   storage:
    dynamic:
      storageClass: local-storage
    capacity: 2Gi
    # type: none # if I set type as none, it will be work.
  memory:
    limit: 32G
    guarantee: 2G
  cpu:
    limit: .3
    guarantee: .3   
```

I had been got failure to start JupyterHub, because the `hub-db-dir` was pending, then I attempted to create a new PV for it by my self, it is working well. My `hub-db-pv` file config such below: 

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-db-pv
  namespace: jhub
spec:
  capacity:
    storage: 600Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/jovyan
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
          - node2
``` 

```
NAME                  STATUS    VOLUME      CAPACITY   ACCESS MODES   STORAGECLASS    AGE
hub-db-dir            Bound     hub-db-pv   600Gi       RWO            local-storage   4h
``` 

After that, my jupyterhub start finally. But I so naive, because when I click the login button, I got a warning:

```
[Warning] 0/5 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 4 node(s) didn't find available persistent volumes to bind.
```

Then I check the status of pods of `jhub`,  I saw that the user's pod was pending,  and I check `kubectl get pvc --namespace jhub`

```
NAME                  STATUS    VOLUME      CAPACITY   ACCESS MODES   STORAGECLASS    AGE
claim-ss-2dke   Pending                                         local-storage   4h19m
claim-cc     Pending                                         local-storage   20s
hub-db-dir            Bound     hub-db-pv   600Gi      RWO            local-storage   4h46m
```

Definitely, my jupyterhub never to auto create a PV for new user. Why? And then, I attempted to create a new PV for the one user by myself again. The config file is similar to the `hub-db-pv`.  But I got a new warning after that action.

```
2020-07-04 08:52:10+00:00 [Warning] persistentvolumes "claim-pv" is forbidden: User "system:serviceaccount:jhub:user-scheduler" cannot update resource "persistentvolumes" in API group "" at the cluster scope
2020-07-04 08:52:10+00:00 [Warning] AssumePod failed: pod 5789ae10-278e-407c-ba44-b72c5504765a is in the cache, so can't be assumed
```

Finally I failed to start jupyterhub. 

**Note:** If I set the storage type as none in jupyterhub config file, it work very well, just cannot persistent to save data. That big trouble for me.

So, how action can I do to save my jupyterhub? Thanks!

**Comment by consideRatio** [comment]
Hi @Guanzhou-Ke, I'm dont know whats wrong, but I'm close to certain it relates to your k8s setup and its inability to provision PVs referencing actual storage for your PVCs.

So when looking how to solve this, search the internet based on your k8s setup. Your issue likely relates to your storage class configuration.

PS: the hub will be fine with 1GB of storage or so, no need for 600GB.

**Comment by Guanzhou-Ke** [comment]
> Hi @Guanzhou-Ke, I'm dont know whats wrong, but I'm close to certain it relates to your k8s setup and its inability to provision PVs referencing actual storage for your PVCs.
> 
> So when looking how to solve this, search the internet based on your k8s setup. Your issue likely relates to your storage class configuration.
> 
> PS: the hub will be fine with 1GB of storage or so, no need for 600GB.

There, I am so sorry about that, I have been tried to search this issue. But nothing to me.

**Comment by consideRatio** [comment]
@Guanzhou-Ke its okay! Perhaps someone at the jupyter forum under the z2jh category knows how to resolve the issue? Describe there what tools/services you've used to setup your k8s cluster especially.
- Did you use kubeadm or another tool to setup k8s?
- Om what machines are k8s running?
- Did you manually create the storageclass?

**Comment by Guanzhou-Ke** [comment]
@consideRatio 
- Yup, I used `kubeadm init` to install k8s. I according to the tutorial of k8s.
- Yes, I did, because that did not config a default storageclass for me when I done by `kubeamd init`. So, before that, I created a local storageclass `local-storage` and it provisioner was set as 'no-provisioner'. It can not auto assign a PV for jhub's pod PVC. Today, I try to config a external provisioner [sig-storage-local-static-provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner#managing-your-local-volumes), But I also failed.
So, I really puzzle for that, and I really want to use jupyterhub.
- The k8s were running at five machines, one master and four slave nodes, and they OS are CentOS 7.

Finally, thank you for your help, please tell me what I need to do? I want to fix the problem of local storageclass. It can not auto assign PV.

**Comment by Guanzhou-Ke** [comment]
@consideRatio When I try to manually create a PV for new user, I got below warning from k8s:
```
[Warning] persistentvolumes "hub-user-pv1" is forbidden: User "system:serviceaccount:jhub:user-scheduler" cannot update resource "persistentvolumes" in API group "" at the cluster scope
```
and then fail to start my jhub.

**Comment by consideRatio** [comment]
This is entirely a k8s issue, about the topic here: https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/

You need a volume plugin / storage provisioner installed. And you need a default storage class to reference that volume plugin / storage provisioner.

Info about storage classes are found here: https://kubernetes.io/docs/concepts/storage/storage-classes/

Reading specifically about the local storage provisioner shipping with k8s, it sais:

> Local volumes do not currently support dynamic provisioning

Considering local volumes are node local, it will only available on one of the various nodes even if you provision them manually.

This is the key issue you are facing. You will probably need to learn more than both of us currently know about this.

If you find a sensible way forward, a quick summary of pointers for future people googling their way to this issue would be useful. This is a common challenge.

**Comment by Guanzhou-Ke** [comment]
@consideRatio I also have a hunch that this is a big challenge. But I am a beginner for this area. I just can try my best.

**Comment by Guanzhou-Ke** [comment]
In short, I also posted this question on SOF, [QLink](https://stackoverflow.com/questions/62739026/kubernetes-what-is-the-best-practice-for-create-dynamic-local-volume-to-auto-as), I hope that it could help other people who also suffering this issue.

**Comment by consideRatio** [comment]
@Guanzhou-Ke a final pointer: I think what you maybe want is:

1. Allow pods to automatically make use of storage.
2. Allow pods making use of storage to be located on any of the nodes, no matter if they restart on another node.

I would consider the following solutions:
1. Having one single node with lots of storage that ran a NFS server, and then manually creating one PV and PVC for this storage, and let all pods use the PVC but mount their home directories based on their username.
   - I think this is what you would need: https://github.com/helm/charts/tree/master/stable/nfs-server-provisioner
2. Using Rook and CephFS, which is something I know very little about. I think that solution may allow you to make use of the storage of all the nodes instead of just one single nodes hard drive. See:
   - https://rook.io/docs/rook/v1.3/ceph-filesystem.html
   - https://github.com/rook/rook/blob/master/Documentation/ceph-filesystem.md#provision-storage

Both options require a lot of additional learning, NFS is an older option, Rook is a newer option with more bells and whistles.

**Comment by Guanzhou-Ke** [comment]
@consideRatio Thanks, I will try it.

**Comment by Guanzhou-Ke** [comment]
@consideRatio Hi, I had been fixed my problem following your advice. I built an external nfs-server on my local node. But now, I got a new question: When I first select my initial jupyter image, it running very well, and I could use `pip` to install any packages. However, when I logout my jupyter, I need to choice jupyter image again after logout a few moments latter. At the same time, I need to re-install my packages which had been installed at my first time. How do I fix it?

This is my config for jupyterhub:

```
singleuser:
  defaultUrl: "/lab"
  image:
    name: jupyter/minimal-notebook
    tag: 2343e33dec46
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "GPU Server"
      description: "Spawns a notebook server with access to a GPU"
      kubespawner_override:
        extra_resource_limits:
          nvidia.com/gpu: "1"
    - display_name: "Datascience environment"
       description: "If you want the additional bells and whistles: Python, R, and Julia."
       kubespawner_override:
       image: jupyter/datascience-notebook:2343e33dec46
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/all-spark-notebook:2343e33dec46
    - display_name: "Learning Data Science"
      description: "Datascience Environment with Sample Notebooks"
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
        lifecycle_hooks:
          postStart:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  gitpuller https://github.com/data-8/materials-fa17 master materials-fa;
```

**Comment by Guanzhou-Ke** [comment]
@consideRatio And I want to know, how should I config if I want to assemble multiple images such as datascient and gpu.

**Comment by Guanzhou-Ke** [comment]
@consideRatio Sorry, and I do not know how to include CUDA10.2 into jupyterhub. I found it could not use my local CUDA. I could see CUDA information in my local machine when if run `nvidia-smi`. But I could not see it in my notebook when I run `!nvidia-smi`. My docker has been installed `CUDA:10.2-base`, but how should I include it into jupyterhub with setting `hub` config?

**Comment by consideRatio** [comment]
@Guanzhou-Ke please post these questions on the discourse.jupyter.org forum or elsewhere as separare posts per question.

**Comment by Guanzhou-Ke** [comment]
@consideRatio Sorry, I try it. Thanks

**Comment by asubb** [comment]
I had exactly the same issue on my local k8s 3-node setup. I didn't setup for now any storage like Ceph, so I'm using the local-storage tight to the specific node.

So adding a new user consists of 2 steps for me, the order doesn't matter:

* Creating a user via Jupyter Hub (which causes creating a pod)
* Creating a Persistent volume with specific name (which create a persistent volume claim aka pvc)


The Persistent volume should be named specifically, otherwise it won't be claimed. Though there is a way to define the pattern in `config.yaml` via `singleuser.storage.dynamic.pvcNameTemplate` and `singleuser.storage.dynamic.volumeNameTemplate`, which have default values `claim-{username}{servername}` and `volume-{username}{servername}` respectively.

However I had an issue with Service Account mentioned here, I solved it by altering the `ClusterRole` in my install script:

```bash
cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: $RELEASE
    meta.helm.sh/release-namespace: $RELEASE
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-0.9.0
    component: user-scheduler-complementary
    heritage: Helm
    release: $RELEASE
  name: $RELEASE-user-scheduler-complementary
rules:
- apiGroups:
  - ""
  resourceNames:
  - user-scheduler
  resources:
  - configmaps
  verbs:
  - get
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolume
  - persistentvolumeclaims
  verbs:
  - "update"
- apiGroups: [""]
  resources:
  - persistentvolumes
  verbs:
  - list
  - get
  - update
  - watch
  - create
EOF
```

This is what was added additionally to the existing ClusterRole which was dumped from the cluster after installation via Helm.
```yaml
- apiGroups: [""]
  resources:
  - persistentvolumes
  verbs:
  - list
  - get
  - update
  - watch
  - create
```

Because of the last statement I'm considering that as a bug, at least for some environments.
