### ISSUE TITLE
Binderhub deploy 404 when connecting to jupyterhub

### ISSUE THREAD

**Issue by ctr26** [jupyterhub/zero-to-jupyterhub-k8s#1737]
At the step where one connects jupyterhub to binderhub I get a 404.

`kubectl --namespace=<namespace-from-above> get svc proxy-public`

This step doesn't work on my cluster as our ingress controller is slightly different (same for minikube). What I can do is port forward the public proxy to `127.0.0.1:8000` which when I visit it gives me the same screen as visiting `https://hub.mybinder.org/`, all expected behaviour. When I try to update the binderhub config to use this port address:

```
config:
  BinderHub:
    hub_url: http://127.0.0.1:8000/
    # hub_url: https://hub.mybinder.org/
    base_url: /binderhub
    use_registry: true
    image_prefix: bioimagearchive/binder-

ingress:
  enabled: true
  hosts:
    - ""
    - localhost
```

I get a 404 error, same happens if I drop in a link to the hub at mybinder. Exactly the same happens if I use the internal IP address. I assumed it was a secrets problem but I've generated keys for this several times now:

```
jupyterhub:
  hub:
    services:
      binder:
        apiToken: "<output of FIRST `openssl rand -hex 32` command>"
  proxy:
    secretToken: "<output of SECOND `openssl rand -hex 32` command>"
```

Any advice very welcome at this point and apologies if this belongs in the binderhub repo.

Best

Craig
