### ISSUE TITLE
singleuser ignoring nodeSelector rules configured in values.yaml

### ISSUE THREAD

**Issue by adr-arroyo** [jupyterhub/zero-to-jupyterhub-k8s#1744]
### Bug description
I am trying to spawn a different profile (configuration) for each node in my Kubernetes cluster. As I have one node set up with a NVIDIA Jetson, I have to use an ARM version of the docker image for the servers that are going to be spawned here, while on my other nodes I have an Intel/AMD machine so I can use the officials docker images.

In order to do this separation, I am trying to use the `nodeSelector` rules, as my nodes are labelled depending on the machine's architecture. I currently have this configuration: 

```
...
singleuser:
  defaultUrl: "/lab"
  image:
    name: easierai/jupyterhub-core
    tag: latest
  profileList:
    - display_name: "EASIER.AI environment"
      description: "Environment preconfigured to work with EASIER.AI platform."
      default: true
      kubespawner_override:
        nodeSelector:
          ARCH: "intel"
          LAYER: "cloud"
    - display_name: "Minimal Environment"
      kubespawner_override:
        image: jupyter/minimal-notebook
        nodeSelector:
          ARCH: "intel"
          LAYER: "cloud"
    - display_name: "one NVIDIA"
      kubespawner_override:
        image: step21/jupyter-minimal-notebook:arm64
        extra_resource_limits:
          nvidia.com/gpu: "1"
        nodeSelector:
          ARCH: "arm64"
          LAYER: "edge"
...
```

While on the `hub` and the `proxy` pods, the nodeSelector seems to work properly, It does not work inside the singleuser.profilelist. 

Is it possible what I am trying to achieve? Is it a misconfiguration?

#### Expected behaviour
The rules defined under `singleuser.profileList.profile.kubespawner_override.nodeSelector`  effectively spawn user's server in the node which labels match the nodeSelector rules.

#### Actual behaviour
NodeSelector rules under singleuser.profilelist are ignored and the user's servers are spawned in any node of the kubernetes cluster.

The produced yaml when a server is spawned is here 
[jupyter-adr-2darroyo.zip](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/5056986/jupyter-adr-2darroyo.zip). As you may see, the `nodeSelector` does not appear at all in the .yaml. 
Why is it? 

### How to reproduce
Use my configuration above.

### Your personal set up

 - OS:
Linux in Ubuntu and NVIDIA Jetson nano
 - Version:
 0.9.0
 - Configuration:
 Shown above.

**Comment by manics** [comment]
The properties that can be overriden are the config properties (with attribute `config=True`) defined in https://github.com/jupyterhub/kubespawner/blob/0.12.0/kubespawner/spawner.py#L116, or those inherited from the parent Spawner class.

Where did you find `nodeSelector`?

**Comment by adr-arroyo** [comment]
Hi @manics thanks for the answer

I guess I have missunderstood what the kubespawner_override does. Indeed I do not see in that file any `nodeSelector` fields.

What is the right terminology, then? Something like this?:

```
kubespawner_override:
        image: jupyter/minimal-notebook
        node_affinity_required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ARCH
            operator: In
            values:
            - "intel"
          - key: LAYER
            operator: In
            values:
            - "cloud"
```
