### ISSUE TITLE
Specify certificate through Secret resource Documentation Bug

### ISSUE THREAD

**Issue by salvis2** [jupyterhub/zero-to-jupyterhub-k8s#1750]
### Bug description

The Z2JH K8s section [Specify certificate through Secret resource](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/security.html#specify-certificate-through-secret-resource) shows an example configuration as follows:

```
proxy:
  https:
    hosts:
      - <your-domain-name>
    type: secret
      secret:
        name: example-tls
```

#### Expected behaviour

I thought a `helm upgrade` command with this configuration inside it would succeed.

#### Actual behaviour

The `helm upgrade` command results in the following error:

```
Error: failed to parse ./config.yaml: error converting YAML to JSON: yaml: line 100: mapping values are not allowed in this context
```

### How to reproduce

1. Putting that configuration in a [YAML validator](https://onlineyamltools.com/validate-yaml) tells me that that configuration is incorrect YAML.

or 

2. Putting that configuration in a `.yaml` file and then running 
```
helm upgrade jupyterhub jupyterhub/jupyterhub --values ./config.yaml --namespace jhub
```
should yield the error above.

### Your personal set up

 - OS: Linux, Ubuntu 18.04
 - Version: JupyterHub version v0.9.0-beta.3, kubectl client v1.17.4, kubectl server version v1.15.11-eks-065dce
 - Configuration: Listed above

### Solution

I think the configuration in the listed documentation section needs to be changed to:

```
proxy:
  https:
    hosts:
      - <your-domain-name>
    type: secret
    secret:
      name: example-tls
```

This configuration allows my `helm upgrade` command to succeed.
