### ISSUE TITLE
Documentation Request/Adjustment: Z2JH Security Section

### ISSUE THREAD

**Issue by LRSutton** [jupyterhub/zero-to-jupyterhub-k8s#1751]
### Proposed change

This is a **Documentation Request / Suggestion** for clearer communication to help newbies.

On the https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/security.html **Specify certificate through Secret resource** section, the following example configuration is given:

```
proxy:
  https:
    hosts:
      - <your-domain-name>
    type: secret
      secret:
        name: example-tls
```

Accepting the changes from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1750, then this block is fine as is.  

But! Newbies, like myself, who are so focused on getting this one thing to work, will probably do what I did... Which was create a whole new "proxy" stanza at the bottom of my config.yaml, thus overwriting the original `proxy.secretToken` entry. Causing a very confusing error complaining about my secretToken being wrong. ("How can it be wrong?  It's right there and I didn't change it??")

### Alternative options

```
proxy:
  secretToken: < redacted >
  https:
    hosts:
      - <your-domain-name>
    type: secret
      secret:
        name: example-tls
```

### Who would use this feature?

Anyone reading the documentation trying to set up a self-signed cert.

### (Optional): Suggest a solution

See above.
