### ISSUE TITLE
.singleuser.image.pullSecrets not applied to new notebook pod

### ISSUE THREAD

**Issue by iss0** [jupyterhub/zero-to-jupyterhub-k8s#1754]
### Bug description

I've set a pullSecret via .singleuser.image.pullSecrets in the values.yaml along with specifying a custom image from a private registry. I verified the config map "hub-config" after applying the chart and the pullSecret is in there. When a new notebook is spawned the pullSecret is not defined in spec and therefore the pod is crashing with ErrImagePull.

#### Expected behaviour

Pod spec has pullSecret defined and pulls image from private registry with no error.

#### Actual behaviour

Pod spec misses pullSecret and fails to pull image.

### How to reproduce

1. Go to your values.yaml
2. Specify custom image from private registry for singluser along with the necessary pullSecret
3. Apply chart
4. Spawn notebook
5. See error

### Your personal set up

 - OS: Linux, Manjaro 20.1 Mikah
 
 - Version: 0.9.1 (chart)
 
 - Configuration: 
 
```yaml
chart: jupyterhub/jupyterhub
version: 0.9.1
release: dev
namespace: jupyterhub

scheduling:
  userScheduler:
    enabled: false
  userPlaceholder:
    enabled: false
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

singleuser:
  image:
    name: MY_PRIVATE_REGISTRY
    pullPolicy: Always
    tag: latest
    pullSecrets:
      - private-registry-secret
  cloudMetadata:
    enabled: true
  networkPolicy:
    enabled: true
    egress:
      - ports:
          - port: 53
            protocol: UDP
  defaultUrl: "/lab"
  memory:
    limit: 32G
    guarantee: 8G
  cpu:
    limit: 8
    guarantee: 4
  storage:
    capacity: 2Gi
    dynamic:
      storageClass: rook-ceph-block
```
