### ISSUE TITLE
orgWhiteList not restricting users

### ISSUE THREAD

**Issue by psschwei** [jupyterhub/zero-to-jupyterhub-k8s#1789]
### Bug description

I'm trying to set up Jupyterhub and restrict access to only the members of a specific organization, as [detailed in the docs](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html#giving-access-to-organizations-on-github).

However, I'm finding that the whitelist is not working, as users not part of that organization are still able to authenticate (note: I am using GitHub Enterprise, not github.com). 

I also had similar problems when using a whitelist of individual users, where anyone could authenticate, not just the users on the list. 

Outside of the whitelist not working, the OAuth app seems to function as it should -- it shows up as an "Authorize OAuth App" for each user once that have given it permission (even those not in the org).

#### Expected behaviour

Only members of a specific organization would be able to authenticate to JupyterHub.

#### Actual behaviour

Users not in the specified organization are also able to authenticate to JupyterHub.

### How to reproduce

1. Create JH instance on k8s 
1. Set up ingress to access JH instance
1. Set up OAuth application in GHE
    * note: using `<jh-hostname>/hub/oauth_callback` as the callback URL
1. Update `config.yaml` (see configuration section below)
1. update JH via `helm upgrade <release> jupyterhub/jupyterhub --version=0.8.2 --values config.yaml`
1. Go to `<hostname>` and click "Sign in with GitHub" button

### Your personal set up
 
 - Version:
0.8.2
 - Configuration:
```yaml
proxy:
  secretToken: <token>
singleuser:
  memory:
    guarantee: 16G
  cpu:
    guarantee: 4
  image:
    name: jupyter/minimal-notebook
    tag: latest
  storage:
    extraVolumes:
      - name: jupyterhub-shared
        persistentVolumeClaim:
          claimName: shared-volume
    extraVolumeMounts:
      - name: jupyterhub-shared
        mountPath: /home/jovyan/shared
  profileList:
    - display_name: "Minimal Environment"
      description: "Base Python Environment"
      default: true
    - display_name: "Data Science Environment"
      description: "Enhanced Data Science environment supporting Python, R, and Julia"
      kubespawner_override:
        image: jupyter/datascience-notebook:latest
cull:
  timeout: 86400    
auth:
  type: github
  github:
    clientId: "<client-id>"
    clientSecret: "<client-secret>"
    callbackUrl: "<jh-hostname>/hub/oauth_callback"
    orgWhiteList:
      - "<org-name>"
  scopes:
    - "read:user"
  admin:
    users:
      - <id>
hub:
  extraEnv:
    GITHUB_HOST: "<ghe-hostname>"
```
