### ISSUE TITLE
Disallow https configurations that likely are faulty

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1806]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1758 introduced a breaking change by letting `proxy.https.enabled` default to `false` in order to solve another issue, but the Helm chart users have previously not required specifying that in order to use HTTPS.

I think we should stick with forcing users to explicitly set it, but we could do something to help users migrate. We can spot where it seems like they have actively configured HTTPS but not actively enabled it through the `proxy.https.enabled` flag, and then trigger a Helm template rendering `fail` if so.

To identify these situations, we can look for the following pattern, which indicates that they have tried to use HTTPS by adding configuration for it, but not explicitly enabled it.

```yaml
proxy:
  https:
    enabled: false # if this is falsy and...
    type: letsencrypt # a) this isn't letsencrypt, or
    letsencrypt:
      contactEmail: '' # b) this isn't falsy
```

@yuvipanda what do you think?
