### ISSUE TITLE
Rework of Authenticator configuration (General Python class traitlets configuration)

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1871]
After looking through all the issues in this repo, the most recurring issue related to configuration of the JupyterHub Authenticator inside the `hub` pod where JupyterHub run's through the Helm chart's template values.

## How it works now
This is the current flow of configuration.

1. Helm chart users update their config.yaml
2. Helm chart renders a k8s Secret resource with the users config.yaml merged with the Helm chart's default values.yaml
3. The hub pod mounts the merged values as a .yaml file
4. The hub pod starts jupyterhub with a jupyterhub_config.py file that in turn will parse the values in the .yaml file
5. One configuration option at the time, the passed values will update configuration of Python classes like KubeSpawner or GitHubOAuthenticator.

## Outcome of that
[Issue 0](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/521), [Issue 1](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/644#issuecomment-703857662), [Issue 2](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/673), [Issue 3](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/968), [Issue 4](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1166), [Issue 5](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1167), [Issue 6](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1171), [Issue 7](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1349), [Issue 8](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1789), [Issue 9](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/authentication.html#authenticating-with-ldap), [Issue 10](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1435), [Issue 11](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1551#issuecomment-705104894), [Issue 12](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1600)

## Underlying issue diagnosis
There are many issues stemming from step 5.
1. The config.yaml -> Authenticator class configuration mapping require constant maintenance.
2. The config.yaml -> Authenticator class configuration mapping has documented examples which also need constant maintenance.
3. Since the config.yaml -> Authenticator class configuration mapping is camelCase (YAML in general) to snake_case (Python class), we cannot just refer to the Authenticator's own documentation (clientSecret -> client_secret)
4. Since the config.yaml -> Authenticator class configuration mapping also nests configuration, we cannot just refer to the Authenticator's own documentation ([examples here](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/8d5503db66a8c8b16ee36d57e18ac1326736ef91/jupyterhub/files/hub/jupyterhub_config.py#L356-L368)).

## Solution idea
We can make a X:X mapping of the configuration that won't need maintenance instead, like described in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1396.

## Action points
- [x] Suggest a configuration syntax
- [x] Iterate and come to an agreement on the configuration syntax
- [x] Implement the configuration syntax in parallel to the old configuration under `auth` and let it start emit deprecation warnings when using `auth` in NOTES.txt.

**Comment by manics** [comment]
Sounds sensible, I found the ldap configuration particularly frustrating. Will something like this work:
```yaml
auth:
  type: LDAPAuthenticator
  config:
    LDAPAuthenticator:
      property-name: <JSON or YAML value>
      ...
```
Using `type: LDAPAuthenticator` means exposing some of the configuration, but on the other hand it avoids mapping `ldap` to `LDAPAuthenticator`, and provides an easy way to distinguish between the old (`type: ldap|github|gitlab...`) and new formats. Alternatively could keep `type: ldap` and use the presence of `auth.config` to identify the new format?

This also keeps the current feature of allow multiple configurations 
```yaml
  config:
    LDAPAuthenticator:
      ..
    GitHubOAuthenticator:
      ..
```
and switching between them using `type` which can be quite useful when deploying new setups.

Downside of this is someone could insert non-Authenticator configuration, e.g.
```yaml
auth:
  config:
    JupyterHub:
      ..
```
but maybe that's acceptable in return for the flexibility it offers of configuring new authenticators? For example if someone extends the default hub image and installs `MyCustomAuthenticator` they could use the standard Z2JH config:
```yaml
auth:
  type: MyCustomAuthenticator
  config:
    MyCustomAuthenticator:
      ...
```

**Comment by consideRatio** [comment]
I prefer to deprecate the entire `auth` section and make a clean decisive transition to something like.

```yaml
pythonClassConfiguration:
  GitHubOAuthenticator:
    client_secret: asdf
    # ...
```

This way, we introduce a general system that can extend to KubeSpawner and JupyterHub configuration as well.

I think the only section in `auth` I think I'd be in favor of retaining, would be something like `auth.type` allowing us to specify the authentication class with `github` or similarly, but I think perhaps its better to also exclude that for better transparency on how things actually work.

**Comment by manics** [comment]
OK, I get what you're thinking. Maybe rename this issue to indicate it's not just for auth? If this is a general trailets configuration then perhaps the only time the Z2JH config overlaps with traitlets is for things like baseurl which affect both the application (JupyterHub) and a K8s object (e.g. ingress)?

**Comment by consideRatio** [comment]
> Maybe rename this issue to indicate it's not just for auth?

I want to focus my thoughts to solve the auth class configuration primarily even though i want to plan towards making this generally useful. For example, I want the authentication documentation sections to be updated to use this system, but not the JupyterHub and KubeSpawner configuration initially. After the many issues and questions surrounding the Authentication class configuration, I don't want to loose focus on solving that.

I realize also that we should nest this kind of configuration under the hub pod, so we can use something like this separately for the user pods.

```yaml
# Configuration of Python "traitlets" within k8s pod where JupyterHub run
hub:
  traitlets:
    AnyClassNameHere:
      any_traitlet_here: any valid YAML here but not python code
```

**Comment by minrk** [comment]
I'd particularly like to get @yuvipanda's input on this, since z2jh is in a very different place today from where it was when the chart started coming together. There is (or was) a substantial difference in audience between the two, where JupyterHub is a low-level component, while z2jh started as an opinionated *distribution* of JupyterHub, making it easy to do *a* sensible deployment of jupyterhub on Kubernetes. z2jh has shed many of its opinions over time, and serves a much wider variety of deployments now.

Taking for example, a common configuration:

```yaml
auth:
  type: github
  github:
```

- JupyterHub's traitlets-based config system is a rather blunt, but powerful mechanism to expose everything that's possibly configurable. This makes it hard to, for instance, separate 'common, simple' configuration from the more esoteric tuning options
- zero-to-jupyterhub has some different goals, and wants to make simple things simple and clear, have kubernetes-specific defaults, make certain assumptions and validations, and group things a little differently in a more kubernetes-friendly way. In particular, z2jh *doesn't* require knowing class names to configure it, but jupyterhub does. I'm not sure how much of an issue that is. By adding its own config structure, it's saying "z2jh knows how to do these things, and can passthrough/validate/group configuration as appropriate."

Some pros and cons of the two ways:

- Having only passthrough config makes it easier and more consistent to do *everything* but can also make it harder to tease out what should be those "high visibility" basic setup options.
- Having only transformed config makes it a lot of maintenance work to expose all options, but easier for new users to see what's there, organize what is supported in a clearer, simpler way, especially for folks familiar with the helm way of doing things and not the traitlets way
- Having *both* passthrough and transformed config can make it confusing when you have that one option that `auth.github` doesn't support and needs to go in `hub.config.GitHubOAuthenticator`. It's a bit of both the best and worst of both
  - everything's *available*
  - simple things are simple
  - but advanced stuff is *extra* advanced because it's a whole new way of doing things beyond what's been configured so far

A few points:

1. I think supporting passthrough config for structured data like we do in [binderhub](https://github.com/jupyterhub/binderhub/blob/404c3ee16a24ad13c29b54beba5320a5be69805c/helm-chart/binderhub/values.yaml#L37-L38) is great and uncontroversial. To me, it eliminates the need to put "advanced options" in the chart that other parts of the chart don't need to understand. I think we can and should do this regardless of whether we deprecate the existing structure.
2. I don't think the word `traitlets` should appear. `config` would be my choice, since that's what gets created by this (`app.config`).
3. this gets complicated for any options where there might be logic in the charts taking these as input (maybe not an issue for auth?) Could be if we were doing similar things for e.g. singleuser resource config, which we duplicate onto the placeholder pods.
4. For passthrough, I don't think auth should be treated specially, so if we want `hub.config.Class.trait` it should be the same path for any class. Putting it on the hub section, e.g. `hub.config` does make sense.

**Comment by consideRatio** [comment]
Thank you @minrk for this thorough writeup! I want to iterate on the action plan forward a bit and summarize what I currently think is a good way forward.

## Min's three ways

Min described three strategies, __only passthrough config__, __only transformed config__, and __having both__. I want to add another dimension to consider and that is the scope of these options. We could have a section with only passthrough config, and another with only transformed config, and another with mostly passthrough config except one part or similar.

- __My :-1: option__: to __only__ passthrough config of the __entire__ Helm chart, it would mean deprecating loads of options as we currently are mostly using transformed config.
- My :unamused: option__: to __both__ passthrough config and transformation config of the __entire__ Helm chart at this point in time. I think it is good, but I'm afraid of the complexities of support two ways to configure one thing. I would love to see this done well, but I'm afraid of the burden to do it well. To do it well, we need to be mindful of all the configuration that influence the templates as well as the traitlets, so our templates render correctly when someone configures something like this. A big concern I have is that we set out to do this, but fail midway of getting it done satisfactory for some complexity such as lists being overridden rather than merged or options being configured with conflicts in between the dedicated Helm values and the general section.
- __My :+1: option__: to __mostly__ passthrough config of the __auth section__ of the Helm chart. We can help users set the authentication class nicely, but otherwise make it clear how they use passthrough configuration and the reference documentation of the authenticators to configure the authentication. I'm confident transforming the auth config to be mostly passthrough will be fine, because it is not intertwined with other configuration or template rendering.

We need to put in work to do any improvement, and I feel confident that I can make my :+1: option work sensibly, but I'm not confident I can make the :unamused: option work all the way satisfactory and is very cautious to invest my time in it therefore.

I want a safe time investment to something good enough to solve the most commonly reported issue with z2jh about authentication at this point, and feel my :+1: option represents that.

**Comment by yuvipanda** [comment]
I thought about this when starting the project, and made an explicit choice to do the transformations and keep traitlets out of it. The goal at that time for the abstraction layer to be different - that if you're using z2jh, you don't actually need to know anything about JupyterHub *or* Kubernetes. The docs were written to that effect too. At that time, if you wanted a JupyterHub you really needed to build it from scratch, needed to know how JupyterHub worked *and* how your spawning setup worked, etc. This was also before Kubernetes emerged as a clear winner in the container orchestration wars. I wanted to be able to do a 2h JupyterCon tutorial where folks can walk in without any Kubernetes *or* JupyterHub understanding, and walk out with a very functional JupyterHub.

I think right now, [TLJH](https://tljh.jupyter.org) fills that niche *very* well - you don't need to know systemd or JupyterHub (or even any commandline tooling) to use it well. I think many one-node z2jh instances are now instead better done as TLJHs, and that's great.

So for me, the general question now is, to use z2jh, what level of JupyterHub & Kubernetes knowledge do you need? I'm not sure what the correct answer is, but that's how I'd like us to think about this in general.

But specifically for auth, I think 100% passthrough is probably the right thing to do! Most docs about authenticators are in the repo of the authenticator itself (oauthenticator, LTI, etc), and not in z2jh. So this is duplication that should go away for the benefit of both users and maintainers. We can still keep some common options in z2jh as we do now. 

So if I understand @consideRatio's plan correctly, the steps would be:

1. Use passthrough only for auth config (basically a generalization of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/files/hub/jupyterhub_config.py#L410)
2. Fail hard in helm if older style config is used

This would basically be the same as if only what is currently `type: custom` is supported for auth anywhere. I like that, and I wish that was the choice I had made for this early on. 

I hope this is useful!

**Comment by minrk** [comment]
> except perhaps for the auth class name 

I think we can use the jupyterhub entry points config to allow this to be passthrough as well, unless you are referring to the *key* (auth.type -> JupyterHub.authenticator_class) instead of the *value*. `c.JupyterHub.authenticator_class = 'github'` works because of [this line](https://github.com/jupyterhub/oauthenticator/blob/922d1432e4b800022d1a14fbbe2462f962a4962f/setup.py#L70).

I think specifically making `auth` 100% passthrough is a great idea. So current config like:

```yaml
auth:
  type: github
  github:
    clientId: "abc123"
    clientSecret: "abc123"
    orgWhitelist:
      - jupyterhub
  whitelist:
    users:
      - consideRatio
  admin:
    access: True
    users:
      - yuvipanda
```

would look like:

```yaml
auth:
  type: github # or oauthenticator.GitHubOAuthenticator
  config: # technically a fully arbitrary passthrough config object
    JupyterHub:
      admin_access: True
    GitHubOAuthenticator:
      client_id: "abc123"
      client_secret: "abc123"
      admin_users:
        - yuvipanda
      allowed_users:
        - consideratio
      allowed_organizations:
        - jupyterhub
```

I think this is great. Specifically, things that are removed:

1. camelCase->snake_case transforms that hide when you are writing traitlets config vs helm fields
2. if existing config is detected, e.g. `auth.github` or `auth.whitelist` sections are defined at all, fail immediately to avoid ignoring important config, don't try to preserve deprecated config

Steps not taken (at least not yet):

- adopt passthrough config for other things. We can do this section by section. Most specifically, having a place for passthrough eliminates the need for *new* options to get a mapping. All *new* options can be assigned via passthrough unless they need to be handled elsewhere in the chart.

Remaining questions:

- The above proposal example assumes a transparent config object passthrough under the `auth` key. However, this is generic to all config. Should we have only one of these on the `hub` object? Is it okay to create multiple passthrough config objects? The code doesn't care, loading several config objects is fine, so it's mostly a matter of clarity (auth config in auth section vs single passthrough config all in one place).
- `custom` currently infers the class name so the class name can be omitted at the top level of the config object (i.e. `auth.custom.config.allowed_users = {'...'}` instead of `auth.custom.config.CustomConfigClass.allowed_users = {...}` ). Is it okay to lose this, or should we try to preserve it?

**Comment by consideRatio** [comment]
> * The above proposal example assumes a transparent config object passthrough under the `auth` key. However, this is generic to all config. Should we have only one of these on the `hub` object? Is it okay to create multiple passthrough config objects? The code doesn't care, loading several config objects is fine, so it's mostly a matter of clarity (auth config in auth section vs single passthrough config all in one place).

I like your proposal! No matter what we do is a compromise, and I think this is the best compromise in the current situation.

__Pros__
- Groups related configuration for readability for users
- Hints to users that this general passthrough configuration is meant for configuration of the authenticator class.

__Cons__
- We could run into issues of manipulating the same configuration in two places, but I don't think we will for this auth configuration.

> * `custom` currently infers the class name so the class name can be omitted at the top level of the config object (i.e. `auth.custom.config.allowed_users = {'...'}` instead of `auth.custom.config.CustomConfigClass.allowed_users = {...}` ). Is it okay to lose this, or should we try to preserve it?

I think we should lose it because the alternative improves readability significantly in my mind.

**Comment by consideRatio** [comment]
## Decision: one generic passthrough config?

I now believe using a general passthrough config straight away is best. I changed my mind =)

Before I hesitated because of troubles I've seen reported by users stemming from configurations like `hub.baseUrl` that is needed by the Helm chart templates as well as by JupyterHub itself. But, this is an issue no matter what when `hub.extraConfig` is used for example, so I think the right call is to embrace the issue. I also think the best way to mitigate it in general, is to be clear what config is used by the Helm templates as well.

With one generic passthrough config, we could also migrate some chart options in the future, like `hub.baseUrl` if we want.

:+1: one config, example: `config.JupyterHub.admin_access`)
:-1: multiple configs, example: `config.myAuthConfig.JupyterHub.admin_access`

**Comment by consideRatio** [comment]
## Decision: one or multiple passthrough configs?

@minrk raised a question if we should nest configuration, so instead of `config.JupyterHub.admin_access` it would for example be `config.auth.JupyterHub.admin_access`.

> The above proposal example assumes a transparent config object passthrough under the auth key. However, this is generic to all config. Should we have only one of these on the hub object? Is it okay to create multiple passthrough config objects? The code doesn't care, loading several config objects is fine, so it's mostly a matter of clarity (auth config in auth section vs single passthrough config all in one place).

We support it for `hub.extraConfig` because we want to pass one or more large strings, but without multiple keys, we would only be able to pass one. This is not a problem for our new configuration passthrough though, because it won't be a string value but instead a dictionary, and Helm will merge it without trouble.

__We cant choose use both config systems__
`hub.extraConfig` actually supports either a string, or, a dictionary having keys with string values. That is possible because its easy to distinguish a string from a dictionary, but, we won't be able to do that for our new passthrough configuration as we cannot distinguish a dict from a dict.

__My suggestion__
I suggest we go for a single passthrough config, so something like `config.JupyterHub.admin_access` instead of `config.auth.JupyterHub.admin_access`.

:+1: suggestion sounds good
:-1: I disagree and suggest ...

**Comment by consideRatio** [comment]
## Decision: config location

This config currently only influence the hub, so it could make sense to have under hub. I made that case before. But at the same time, if we configure `config.JupyterHub.base_url`, and later deprecate `hub.baseUrl`, it may bleed out to not influence only the hub pod, but also for example the proxy pod etc.

## Suggestions
Please edit this post and add more and perhaps put your name behind one to vote for an option.

- config (Erik)
- traitlets
- hub.config
- hub.traitlets

__Vote comments__
- Erik: I like that `config` is short, and by not being next to `hub.extraConfig` we distinguish those a bit better.

**Comment by consideRatio** [comment]
## Status update: config transition message

I think its important to help users transition their old config to the new config system. The idea is that when a user has any configuration in `auth`, Helm template rendering will fail with a nice error message saying what should be configured instead.

Note that it is terrible to work with Helm template logic, so I'm not looking to do much fine tuning of the logic. Currently the implementation relies to a large extent on a transformation of z2jh config structure to what it mapped to, as well as a section declaring detected "UnrecognizedConfig" that was ignored by z2jh.

I've managed to make the following Helm values render into the transition message below

```yaml
# values.yaml
auth:
  asdf: ggg
  fdfd:
    apa: get
  type: github
  google:
    clientSecret: test-secret
    clientId: test-id
    callbackUrl: callback-url
  custom:
    className: my.pkg.TestClass
    config:
      key1: val1
  scopes:
    - profile
    - email
  state:
    enabled: true
  admin:
    access: true
    users:
      - cat
  whitelist:
    users:
      - kitten1
  allowedUsers: # maps to the same as whitelist.users
    - kitten2
```

```
Example of what can be part of the config transition message when the
Helm template rendering fails.

When we have decided on the passthrough config location, I'll update
the config to be copy-pastable.

Authenticator:
  admin_users:
  - cat
  allowed_users:
  - kitten1
  enable_auth_state: true
GoogleOAuthenticator:
  client_id: test-id
  client_secret: test-secret
  oauth_callback_url: callback-url
JupyterHub:
  admin_access: true
  authentication_class: oauthenticator.github.GitHubOAuthenticator
OAuthenticator:
  scope:
  - profile
  - email
UnrecognizedConfig:
  asdf: ggg
  fdfd.apa: get
```
