### ISSUE TITLE
Support for hashicorp vault with extraEnvs

### ISSUE THREAD

**Issue by np-hg** [jupyterhub/zero-to-jupyterhub-k8s#1875]
### Proposed change
Add support for hashicorp secrets for jupyterhub secrets. Example config of its done currently on `values.hub`

```yaml
extraEnv: 
  OAUTH_CLIENT_ID: jupyterhub
  OAUTH_CLIENT_SECRET:
    valueFrom:
      secretKeyRef:
        name: jupyter-secret
        key: jupyter-secret-key
```

and how it would work with this proposed change

```yaml
annotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
  vault.security.banzaicloud.io/vault-role: "jupyterhub_secrets_reader"
  vault.security.banzaicloud.io/vault-skip-verify: "true"
extraEnv: 
  OAUTH_CLIENT_ID: jupyterhub
  OAUTH_CLIENT_SECRET: vault:secret/jupyterhub#client-secret
```

### Alternative options
Based on this [thread](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1103) and the [docs](https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html?highlight=secrets#hub-extraenv) jupyterhub supports secrets but only from k8s.

### Who would use this feature?
Anyone using large amount of secrets and managing them in a more secure way inside vault as well as users of generic auth (keycloak in our case requires us to use env var, which we would like to use secrets for)

**Comment by consideRatio** [comment]
I had to read up because I don't know exactly how Hashicorp's Vault is meant to work, but, I guess it is something like this.

1. By adding annotations to a pod, you interact with a Mutating Webhook, for example as described [here](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/)
2. When the pod is being registered with the k8s api-server, the webhook will first modify the Pod specification, replacing parts of it and doing something else which is considered more secure, such as adding a initContainer to inject it or something.

By using this Helm chart, configuration in hub.extraEnv for example will render into Deployment resource specification which in turn contains a pod specification that will end up being rendered at some point. This is what the Vault MutatingWebhook will end up manipulating when it is becoming registered with the k8s api-server. I don't think you are limited by this Helm chart because it allows you to set the environment variables in any valid k8s way, which is what I think you need for Vault.

For example, you are allowed to specify...

```yaml
# Helm chart config
hub:
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
    vault.security.banzaicloud.io/vault-role: "jupyterhub_secrets_reader"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
  extraEnv: 
    OAUTH_CLIENT_ID: "jupyterhub"
    OAUTH_CLIENT_SECRET: "vault:secret/jupyterhub#client-secret"
```

It would render to something like...

```yaml
# examplified rendered hub Pod specification given Helm chart config above
metadata:
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
    vault.security.banzaicloud.io/vault-role: "jupyterhub_secrets_reader"
    vault.security.banzaicloud.io/vault-skip-verify: "true"
spec:
  containers:
  - name: mycontainer
    # ...
    env:
    - name: "OAUTH_CLIENT_ID"
      value: "jupyterhub"
    - name: "OAUTH_CLIENT_SECRET"
      value: "vault:secret/jupyterhub#client-secret"
```

**Comment by np-hg** [comment]
Thanks for the reply, I had attempted the above with various permutations and for one reason or another jupyterhub seemed to launch directly without injecting the secret.  SSH-ing into the pod and `echo $OAUTH_CLIENT_SECRET` printed `vault:secret/jupyterhub#client-secret` verbatim. There is some disconnect in how either the webhook is running or how extraEnv is different that say env.

I am following the same setup for other services which all seem to work fine except for jupyterhub.

**Comment by consideRatio** [comment]
I recommend using `helm template` to render the Helm chart's k8s resources, and inspect if they would work. I'm very confident that the mutating webhook acts on resources passed to the k8s api-server, and that Helm will render the templates first, and then pass the rendered k8s resources to the k8s-apiserver, which means that as long as you have the output you think makes sense in the templates, it isn't a problem of the Helm chart but how your mutating webhook works.

Btw, if you are using Helm 3, you can use the `--show-only templates/hub/deployment.yaml` flag as well to only inspect the relevant resource for your example.

A guess of something that can be wrong, is that the webhook is only caring about Pods in a specific namespace or similar. You can also inspect the logs of the server doing the mutations on the pod specification, did it process the pod as it should?

**Comment by np-hg** [comment]
So I tried adding the following annotations to my chart
```yaml
        vault.security.banzaicloud.io/vault-addr: "https://vault.default:8200"
        vault.security.banzaicloud.io/vault-role: "jupyterhub_secrets_reader"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/inline-mutation: "true"
```
which is what I was missing I believe but I ran into another issue that seems to be an open bug within kubernetes corresponding to this thread https://github.com/kubernetes/kubernetes/issues/82296
