### ISSUE TITLE
autohttps cannot get SSL certificate

### ISSUE THREAD

**Issue by EnziinSystem** [jupyterhub/zero-to-jupyterhub-k8s#1888]
My environment:

`jupyterhub: 0.10.0`

And config file:

```
proxy:
  secretToken: "*********************************"
  https:
    enabled: true
    hosts:
      - domain.com
    type: letsencrypt
    letsencrypt:
      contactEmail: ***@gmail.com
...
ingress:
  enabled: true
  hosts:
    - domain.com
```
I run the command

`helm upgrade --cleanup-on-fail --install jupyterhub jupyterhub/jupyterhub --namespace jupyterhub --version=0.10.0 --values config.yaml`

After waiting for a long time, not anything happens. I cannot get SSL success.

```
kubectl describe deploy/autohttps -n jupyterhub
```
```
Name:                   autohttps
Namespace:              jupyterhub
CreationTimestamp:      Fri, 30 Oct 2020 10:29:47 +0100
Labels:                 app=jupyterhub
                        app.kubernetes.io/managed-by=Helm
                        chart=jupyterhub-0.10.0
                        component=autohttps
                        heritage=Helm
                        release=jupyterhub
Annotations:            deployment.kubernetes.io/revision: 1
                        meta.helm.sh/release-name: jupyterhub
                        meta.helm.sh/release-namespace: jupyterhub
Selector:               app=jupyterhub,component=autohttps,release=jupyterhub
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=jupyterhub
                    component=autohttps
                    hub.jupyter.org/network-access-proxy-http=true
                    release=jupyterhub
  Annotations:      checksum/static-config: 3b9fe307a78e06fbd9a69439bf6b73678e06b897dbbf5306332883ea7d553cd4
  Service Account:  autohttps
  Init Containers:
   load-acme:
    Image:      jupyterhub/k8s-secret-sync:0.10.0
    Port:       <none>
    Host Port:  <none>
    Args:
      load
      proxy-public-tls-acme
      acme.json
      /etc/acme/acme.json
    Environment:
      PYTHONUNBUFFERED:  True
    Mounts:
      /etc/acme from certificates (rw)
  Containers:
   traefik:
    Image:        traefik:v2.3.2
    Ports:        8080/TCP, 8443/TCP
    Host Ports:   0/TCP, 0/TCP
    Environment:  <none>
    Mounts:
      /etc/acme from certificates (rw)
      /etc/traefik from traefik-config (rw)
   secret-sync:
    Image:      jupyterhub/k8s-secret-sync:0.10.0
    Port:       <none>
    Host Port:  <none>
    Args:
      watch-save
      --label=app=jupyterhub
      --label=release=jupyterhub
      --label=chart=jupyterhub-0.10.0
      --label=heritage=secret-sync
      proxy-public-tls-acme
      acme.json
      /etc/acme/acme.json
    Environment:
      PYTHONUNBUFFERED:  True
    Mounts:
      /etc/acme from certificates (rw)
  Volumes:
   certificates:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   traefik-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      traefik-proxy-config
    Optional:  false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  autohttps-75887f8cc6 (1/1 replicas created)
NewReplicaSet:   <none>
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  12m   deployment-controller  Scaled up replica set autohttps-75887f8cc6 to 1
```

**Comment by consideRatio** [comment]
- Did you follow the procedure to point your domain to the external ip of your proxy-public k8s service, or your ingress controllers IP?
- Do you have an ingress controller? If not, disable ingress.enabled.
- Was this an upgrade to 0.10.0 from an installation with issues already?
- What are the logs observed in the autohttps pod?

**Comment by EnziinSystem** [comment]
> * Did you follow the procedure to point your domain to the external ip of your proxy-public k8s service, or your ingress controllers IP?
> * Do you have an ingress controller? If not, disable ingress.enabled.
> * Was this an upgrade to 0.10.0 from an installation with issues already?
> * What are the logs observed in the autohttps pod?

I point the domain to IP.
The logs in autohttps:
```
 time="2020-10-30T10:12:59Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yaml"                                                                                     │
│ time="2020-10-30T10:13:09Z" level=error msg="Unable to obtain ACME certificate for domains \"datascience.enziin.com\" : unable to generate a certificate for the domains [datascience.enzi │
│ 
```

**Comment by consideRatio** [comment]
- Are you using an ingress controller that motivates having ingress.enabled true?
- Are you domain IP pointing to the proxy-public service or the ingress controllers exposed IP?
- Note that for all change in config, you are required to manually restart the autohttps pod to re-attempt cert acquisition I think, or wait longer than I ever have so I'm not sure how long you would need to wait.

**Comment by EnziinSystem** [comment]
Hello,
Did you mean even though I have declared the ingress in the config.yaml file but do I still need to create an external ingress?
```
proxy:
  secretToken: "******************"
  https:
    enabled: true
    hosts:
      - domain.com
    type: letsencrypt
    letsencrypt:
      contactEmail: aaa@gmail.com
...
ingress:
  enabled: true
  hosts:
    - domain.com
```
I will need to create an ingress:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: xxx-service
  labels:
    app: xxx-service
spec:
  tls:
    - hosts:
        - domain.com
  rules:
    - host: domain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: xxx-service
              servicePort: 80
```

**Comment by consideRatio** [comment]
@EnziinSystem you will get an k8s `Ingress` resource created by having `ingress.enabled=true`, but your k8s cluster need to have something that cares about Ingress resources - an ingress controller. And, if you are using that, you are bypassing the `proxy-public` service public IP.

To conclude, if you have ingress.enabled=true, you should probably have `proxy.service.type=ClusterIP` as well because you are no longer using the k8s Service of the JupyterHub helm chart to acquire an external IP if you aim to direct traffic to it through an Ingress controller, which has picked up on how to direct traffic based on the Ingress resource.

**Comment by EnziinSystem** [comment]
I still cannot get SSL certificate on kubernetes Google cloud with LoadBalancer public IP. 
```
NAME           TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)                      AGE
proxy-public   LoadBalancer   10.60.3.186   xx.yyy.zzz.aa   443:31556/TCP,80:32596/TCP   111s
```
Domain point to EXTERNAL-IP (xx.yyy.zzz.aa)
My config:
```
proxy:
  secretToken: "***********************"
  https:
    enabled: true
    hosts:
      - domain.com
    type: letsencrypt
    letsencrypt:
      contactEmail: "xxx@gmail.com"
...
ingress:
  enabled: true
  hosts:
    - domain.com
```
Please help.
