### ISSUE TITLE
Harmless error in user-scheduler logs is distracting debugging efforts

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#1894]
I want to resolve what I think to be a harmless error in order to avoid having it raise more questions or make non-harmless errors look troublesome.

The user-scheduler, which is just a customly configured `kube-scheduler`, logs the following every ~5 seconds.

```
E1030 19:09:07.060325       1 reflector.go:127] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:jupyterhub:user-scheduler" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
```

From https://github.com/kubernetes/kubernetes/pull/72474, I learned that this can be disabled with a [flag for kube-scheduler](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/).

> `--authentication-skip-lookup` (default to false)
> If false, the authentication-kubeconfig will be used to lookup missing authentication configuration from the cluster.

But, we can also provide the following permissions to the user-scheduler ClusterRole resource we create for the user-scheduler.

```yaml
# ClusterRole rule needed to have --authentication-skip-lookup=false (default)
rules:
- apiGroups:
  - ""
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
```

I don't know yet if anyone would benefit from this, so instead of adding things that I don't know the security implications of, I'll go ahead and set `--authentication-skip-lookup=true` to disable what comes to cause the errors.
