### ISSUE TITLE
Authenticator not honoring the auth.whitelist.users key

### ISSUE THREAD

**Issue by TiemenSch** [jupyterhub/zero-to-jupyterhub-k8s#1914]
### Bug description

The user whitelist is not being honored when using the Gitlab OAuthenticator.

#### Expected behaviour

Only users in the whitelist should be able to login to the JupyterHub.

#### Actual behaviour

Any (Gitlab) user is able to login and use the JupyterHub instance.

### How to reproduce

Try logging in with a account not in the whitelist.

### Your personal set up

```yaml
auth:
  whitelist:
    users:
      - user1
      - user2
  admin:
    access: true
    users:
      - <REDACTED>
  type: gitlab
  gitlab:
    clientId: <REDACTED>
    clientSecret: <REDACTED>
    callbackUrl: <REDACTED>
  scopes:
    - "read_user"
```
 - OS: Linux
 - Version: Chart 0.10.2
 - Configuration: See above.

**Comment by TiemenSch** [comment]
Ah, this appears to be related to JupyterHub's own changelog which moved the whitelist management to the config key ``allowed_users``.

https://jupyterhub.readthedocs.io/en/latest/changelog.html?highlight=whitelist#id3

Setting them using the ``c.Authenticator.allowed_users`` works.

Although this is slightly confusing as the ``whitelist`` key in the Helm chart still exists, but does not appear to do anything.

**Comment by manics** [comment]
It looks like the current chart sets `c.Authenticator.whitelist`:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/f34bf9950841bedba76174a7d1c5c21e4ecbbb18/jupyterhub/files/hub/jupyterhub_config.py#L391

Although the property is deprecated in JupyterHub, there should be logic to still use the original property if the new property isn't set.

**Comment by TiemenSch** [comment]
I guess that line should now say:
```python
set_config_if_not_none(c.Authenticator, 'allowed_users', 'auth.whitelist.users') 
```
for newer versions?

Or is allowed users a substantial different property than the old whitelist?

**Comment by manics** [comment]
I think that would work, there's no change to the format of the value.

However I'm still concerned that it's not currently working for you. Backwards compatibility was deliberately included in the relevant PRs:
- https://github.com/jupyterhub/jupyterhub/pull/3090
- https://github.com/jupyterhub/oauthenticator/pull/366

**Comment by TiemenSch** [comment]
From a security perspective this isn't very nice, but luckily in my case it was a deployment for a relatively small course on uni where users only had access to their own volumes and no other sensitive resources.

For full disclosure: I do have custom initContainers and some other settings set, but I don't think these come into play until after authentication has succeeded? 

Some additional remarks:

Any chance the logic of the Gitlab OAuthenticator and the allowed groups or allowed projects may interfere in this specific case?

Is there a test in place that still tests a config with the old whitelist config key in place?

Besides debugging the code directly, would you know of any messages that I can find in my logs from the past days that may be helpful to investigate this further? I couldn't find any myself and I guess there probably isn't one stating the whitelist now and again. The only one that may be vaguely remotely related that I can find is this one:

**Comment by naterush** [comment]
To add on here, I'm currently using the following config:
```
auth:
  type: google
  google:
    clientId: ...
    clientSecret: ...
    callbackUrl: ...
	whitelist:
    users:
      - naterush1997@gmail.com
      - aarondi@wharton.upenn.edu
```

However, the signin is letting _anyone_ sign in with google not just these accounts. Is there a workaround, or is the whitelist field just non-functional? 

Thanks!
