### ISSUE TITLE
defaultUrl not consistently bringing user to file created in postStart script

### ISSUE THREAD

**Issue by naterush** [jupyterhub/zero-to-jupyterhub-k8s#1972]
### Bug description

I have the following YAML in my  config file:

```
singleuser:
  defaultUrl: "/lab/tree/Introduction.ipynb"
  image:
    name: <name>
    tag: <tag>
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            rm -rf /home/jovyan/lost+found;
            if [ -z `ls /home/jovyan/*` ]; then cp -r /tutorial/. /home/jovyan/; fi
```

Essentially, it copies over files from a tutorial folder (that I create in my docker image), one of them being `Introduction.ipynb`. When users then show up and log in for the first time, I want them to get taken to this file (rather than a launcher).

#### Expected behaviour

Users would get taken to the `Introduction.ipynb` file upon first log in.

#### Actual behaviour

When creating an account, the `Introduction.ipynb` is copied successfully to the files, and appears on the RHS in the file navigator.

Sometimes (happening currently), users get taken to the URL `https://staging.trymito.io/user/<USERNAME>/lab/workspaces/auto-b/tree/Introduction.ipynb`, but the file does not load. It just stays at the JupyterHub launcher. When the page is refreshed, the `Introduction.ipynb` file then loads.

It seems related to the workspaces part of the URL - any idea why that is there? When it works, the workspaces part of the URL disappears...

### How to reproduce

1. Deploy a base instance of Kuberenetes JupyterHub.
2. Create a docker image like the one below.
3. Add a script that copies these files over to the home page in the `postStart` lifecycle method. Feel free to copy the code above and below :0
4. Set the `defaultUrl` to one of these files. 
4. Create a new account and log in on that JupyterHub for the first time. This file will not load.

### Your personal set up

Running on AWS ECS. Very standard EC2 managed + autoscaled AWS EC2 instances! 

The docker image itself:
```
FROM jupyter/base-notebook:hub-1.2.1

# Installs a pip package, and rebuilds Jupyter Lab
RUN pip install mitosheet==$version
RUN python -m jupyter labextension install @jupyter-widgets/jupyterlab-manager@2

# Add some files for the tutorial
COPY Introduction.ipynb /tutorial/Introduction.ipynb
```

We're also using Google Auth. It currently allows anyone with a Google Account anywhere to come sign up on our kuberenetes instance.
