### ISSUE TITLE
Cannot connect to kernel

### ISSUE THREAD

**Issue by bartgras** [jupyterhub/zero-to-jupyterhub-k8s#2013]
I've had existing (AWS) EKS cluster on which I (almost) successfully installed z2jh.
What works:
* I have working SSL setup
* I can login and manage servers
* I can create notebook

The only issue I have is that I cannot connect to kernel. 

Here is log from my `jupyter-<name>` pod:
```
[W 2021-01-26 08:18:57.030 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[I 2021-01-26 08:18:57.260 SingleUserNotebookApp extension:168] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 2021-01-26 08:18:57.260 SingleUserNotebookApp extension:169] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2021-01-26 08:18:57.262 SingleUserNotebookApp singleuser:406] Starting jupyterhub-singleuser server version 0.9.4
[W 2021-01-26 08:18:57.269 SingleUserNotebookApp _version:50] jupyterhub version 1.3.0 != jupyterhub-singleuser version 0.9.4. This could cause failure to authenticate and result in redirect loops!
[I 2021-01-26 08:18:57.269 SingleUserNotebookApp notebookapp:1712] Serving notebooks from local directory: /home/jovyan
[I 2021-01-26 08:18:57.270 SingleUserNotebookApp notebookapp:1712] The Jupyter Notebook is running at:
[I 2021-01-26 08:18:57.270 SingleUserNotebookApp notebookapp:1712] http://(jupyter-bart or 127.0.0.1):8888/user/bart/
[I 2021-01-26 08:18:57.270 SingleUserNotebookApp notebookapp:1713] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2021-01-26 08:19:01.524 SingleUserNotebookApp log:158] 302 GET /user/bart/ -> /user/bart/tree? (@192.168.41.86) 0.59ms
[I 2021-01-26 08:19:01.642 SingleUserNotebookApp log:158] 302 GET /user/bart/ -> /user/bart/tree? (@103.73.243.180) 0.55ms
[I 2021-01-26 08:19:01.695 SingleUserNotebookApp log:158] 302 GET /user/bart/tree? -> /hub/api/oauth2/authorize?client_id=jupyterhub-user-bart&redirect_uri=%2Fuser%2Fbart%2Foauth_callback&response_type=code&state=[secret] (@103.73.243.180) 3.31ms
[I 2021-01-26 08:19:01.879 SingleUserNotebookApp auth:875] Logged-in user {'kind': 'user', 'name': 'bart', 'admin': False, 'groups': [], 'server': '/user/bart/', 'pending': None, 'created': '2021-01-26T08:12:39.756512Z', 'last_activity': '2021-01-26T08:19:01.873391Z', 'servers': None}
[I 2021-01-26 08:19:01.880 SingleUserNotebookApp log:158] 302 GET /user/bart/oauth_callback?code=[secret]&state=[secret] -> /user/bart/tree? (@103.73.243.180) 62.36ms
[I 2021-01-26 08:19:02.023 SingleUserNotebookApp log:158] 200 GET /user/bart/tree? (bart@103.73.243.180) 93.36ms
[I 2021-01-26 08:19:02.248 SingleUserNotebookApp log:158] 200 GET /user/bart/api/config/common?_=1611649142160 (bart@103.73.243.180) 2.82ms
[I 2021-01-26 08:19:02.251 SingleUserNotebookApp log:158] 200 GET /user/bart/api/config/tree?_=1611649142159 (bart@103.73.243.180) 2.51ms
[I 2021-01-26 08:19:02.293 SingleUserNotebookApp log:158] 200 GET /user/bart/api/terminals?_=1611649142161 (bart@103.73.243.180) 1.03ms
[I 2021-01-26 08:19:02.331 SingleUserNotebookApp log:158] 200 GET /user/bart/api/sessions?_=1611649142162 (bart@103.73.243.180) 2.34ms
[I 2021-01-26 08:19:02.333 SingleUserNotebookApp log:158] 200 GET /user/bart/api/terminals?_=1611649142163 (bart@103.73.243.180) 1.04ms
[I 2021-01-26 08:19:02.384 SingleUserNotebookApp log:158] 200 GET /user/bart/api/contents?type=directory&_=1611649142164 (bart@103.73.243.180) 2.91ms
[I 2021-01-26 08:19:07.477 SingleUserNotebookApp log:158] 200 GET /user/bart/notebooks/Untitled.ipynb (bart@103.73.243.180) 312.98ms
[I 2021-01-26 08:19:07.748 SingleUserNotebookApp log:158] 200 GET /user/bart/api/config/common?_=1611649147645 (bart@103.73.243.180) 2.54ms
[I 2021-01-26 08:19:07.751 SingleUserNotebookApp log:158] 200 GET /user/bart/api/config/notebook?_=1611649147644 (bart@103.73.243.180) 2.63ms
[I 2021-01-26 08:19:07.783 SingleUserNotebookApp log:158] 200 GET /user/bart/api/contents/Untitled.ipynb?type=notebook&_=1611649147646 (bart@103.73.243.180) 11.60ms
[I 2021-01-26 08:19:07.901 SingleUserNotebookApp kernelmanager:164] Kernel started: 8ccbb47f-5580-4cb0-9cb1-85675a04ab83
[I 2021-01-26 08:19:07.902 SingleUserNotebookApp log:158] 201 POST /user/bart/api/sessions (bart@103.73.243.180) 30.43ms
[I 2021-01-26 08:19:07.907 SingleUserNotebookApp log:158] 200 GET /user/bart/api/contents/Untitled.ipynb/checkpoints?_=1611649147647 (bart@103.73.243.180) 1.71ms
[I 2021-01-26 08:19:08.541 SingleUserNotebookApp handlers:190] Adapting to protocol v5.1 for kernel 8ccbb47f-5580-4cb0-9cb1-85675a04ab83
[W 2021-01-26 08:19:08.543 SingleUserNotebookApp log:158] 400 GET /user/bart/api/kernels/8ccbb47f-5580-4cb0-9cb1-85675a04ab83/channels?session_id=fc3d7721c75c4be09bcd8a65da9b7a85 (bart@103.73.243.180) 504.01ms
[W 2021-01-26 08:19:09.692 SingleUserNotebookApp handlers:254] Replacing stale connection: 8ccbb47f-5580-4cb0-9cb1-85675a04ab83:fc3d7721c75c4be09bcd8a65da9b7a85
```

After I hit "Reload kernel" button, following lines are added to log:
```
[W 2021-01-26 08:28:50.269 SingleUserNotebookApp handlers:252] Replacing stale connection: c8f56f02-078f-4818-81fb-d0b42c095c15:c5e1b6f33274463aac0e52506c611f58
[I 2021-01-26 08:28:59.045 SingleUserNotebookApp multikernelmanager:300] Kernel restarted: c8f56f02-078f-4818-81fb-d0b42c095c15
[I 2021-01-26 08:28:59.048 SingleUserNotebookApp log:181] 200 POST /user/bart/api/kernels/c8f56f02-078f-4818-81fb-d0b42c095c15/restart (bart@103.73.243.180) 210.52ms
[W 2021-01-26 08:29:49.437 SingleUserNotebookApp handlers:252] Replacing stale connection: c8f56f02-078f-4818-81fb-d0b42c095c15:c5e1b6f33274463aac0e52506c611f58
[W 2021-01-26 08:29:51.617 SingleUserNotebookApp handlers:252] Replacing stale connection: c8f56f02-078f-4818-81fb-d0b42c095c15:c5e1b6f33274463aac0e52506c611f58
[W 2021-01-26 08:30:53.986 SingleUserNotebookApp handlers:252] Replacing stale connection: c8f56f02-078f-4818-81fb-d0b42c095c15:c5e1b6f33274463aac0e52506c611f58
[W 2021-01-26 08:31:53.570 SingleUserNotebookApp handlers:252] Replacing stale connection: c8f56f02-078f-4818-81fb-d0b42c095c15:c5e1b6f33274463aac0e52506c611f58
[W 2021-01-26 08:32:09.770 SingleUserNotebookApp handlers:252] Replacing stale connection: c8f56f02-078f-4818-81fb-d0b42c095c15:c5e1b6f33274463aac0e52506c611f58
```

And it continues with `Replacing stale connection` but never connects to the kernel.

My `config.yaml`:
```
proxy:
  secretToken: <token>
  https:
    enabled: true
    type: offload
  service:
    annotations:
      # Certificate ARN
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<ARN>"
      # The protocol to use on the backend, we use TCP since we're using websockets
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      # Which ports should use SSL
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"

ingress: 
  enabled: true
  hosts:
    - <host>

hub:
  cookieSecret: <token>
  config:
    Authenticator:
      admin_users:
        - admin
      allowed_users:
        - <user>
    DummyAuthenticator:
      password: <password>
    JupyterHub:
      authenticator_class: dummy

singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: 177037d09156
  memory:
    limit: 16G
    guarantee: 2G
  nodeSelector:
    memory: 32gb
  cpu:
    limit: 8
    guarantee: 4
  storage:
    capacity: 5Gi
```

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead? Thanks!

**Comment by bartgras** [comment]
Just found the solution so I'd like to share it if anyone has the same problem in the future.

It was incorrectly set ingress controller service.

If you follow setup for nginx-ingress for AWS, then the `ingress-nginx/templates/controller-service.yaml` by default has:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    [...]
```

Changed `http` and `tcp` will fixe the issue.
