### ISSUE TITLE
GithubOA does't works.

### ISSUE THREAD

**Issue by lidongze0629** [jupyterhub/zero-to-jupyterhub-k8s#2050]
### Bug description

I try to deploy jupyterhub on k8s with Github OA following this [tutorials](https://zero-to-jupyterhub.readthedocs.io/en/stable/). But the Dummy Authenticator is always.

#### Expected behaviour
Github Authentication appears.

#### Actual behaviour

DummyAuthenticator.

### How to reproduce

Here is my config.yaml
```yaml
proxy:
  secretToken: "a92efe26f5a8a8870090005e71a85701c519f62917ad5281729a785c080fa2ad"

singleuser:
  memory:
    limit: 3G
    guarantee: 2G
  cpu:
    limit: 10
    guarantee: 1
    storage:
      capacity: "20Gi"
      dynamic:
        storageClass: alicloud-disk-ssd

hub:
  db:
    pvc:
      storageClassName: alicloud-disk-ssd
      storage: 20Gi
  config:
    GitHubOAuthenticator:
      admin_users:
        - lidongze0629
      client_id: myid
      client_secret: mysecret
      oauth_callback_url: https://extenal_ip:podt/hub/oauth_callback
      scope:
        - public_repo
        - user:email
    JupyterHub:
      authenticator_class: github
```

### Your personal set up

 - OS: ubuntu20.04
 
 - Version(s): 0.10.6
 
- K8s cluster: Aliyun ACK
- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>
