### ISSUE TITLE
Not able to configure JupyterHub helm chart to use github authentication

### ISSUE THREAD

**Issue by mzabuawala** [jupyterhub/zero-to-jupyterhub-k8s#2074]
I am new to helm chart and Kubernetes, I am trying to install JupyterHub on my local machine (using `kind` cluster) with helm chart `jupyterhub/jupyterhub`, I am running following command

```
helm upgrade --cleanup-on-fail \                                                                                                                                       ─╯
  --install mzjhub jupyterhub/jupyterhub \
  --namespace mzjhub \
  --create-namespace \
  --version=0.10.6 \
  --values config_github.yaml
```

and do the port forwarding using

```
kubectl port-forward -n mzjhub svc/proxy-public 8080:80 &
```

content of my `config_github.yaml` as below (I've masked my github details)

```
proxy:
  secretToken: "511af7fdb8ba1e8252599182aaed26a4e36af42cac257601ea7d2583fbdb1e65"
hub:
  config:
    JupyterHub:
      authenticator_class: github
    GitHubOAuthenticator:
      client_id: xxxxxxxxxxx
      client_secret:  xxxxxxxxxxxxxxxxxxx
      oauth_callback_url: https://api.xxxxxx.com/auth/
```

Everything runs fine and I can able to access the JupyterHub login page but it does not give any GitHub authentication options, if I enter any values in username/password field and click login button, it authenticates it without any issue.

[![enter image description here][1]][1]

I'm referring this official guide for my setup 
- https://zero-to-jupyterhub.readthedocs.io/en/stable/jupyterhub/installation.html#prepare-configuration-file
- https://zero-to-jupyterhub.readthedocs.io/en/stable/administrator/authentication.html

Please let me know if I am missing anything here for GitHub login authentication?

  [1]: https://i.stack.imgur.com/w5udm.png
