### ISSUE TITLE
Documentation for configuring dummy password is wrong

### ISSUE THREAD

**Issue by amit-chandak-unskript** [jupyterhub/zero-to-jupyterhub-k8s#2084]
Documentation about configuring dummy password is wrong [here](https://zero-to-jupyterhub.readthedocs.io/en/stable/administrator/authentication.html#allowed-users-admin-users)

Looking at the jupyterhub_config.py code, looks like the config should be something like this

```
auth:
  type: dummy
  dummy:
    password: <password>
```
