### ISSUE TITLE
Add schema.yaml validation for extraFiles.data structure

### ISSUE THREAD

**Issue by roelbaz** [jupyterhub/zero-to-jupyterhub-k8s#2095]
### Bug description

Template parsing error of the extraFile mountPath in:

jupyterhub/templates/_helpers.tpl:382:29: executing "jupyterhub.extraFiles.validate-file" at $file_details.mountPath>: can't evaluate field mountPath in type string                         

This was introduced in this PR: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2006

This is in versions  0.11.1-n113.hc841983b through 0.11.1-n301.hc86268b1 (Didn't try em all obviously, but those two are the 'bookends')

#### Expected behaviour

No parsing complaints from the _helpers.tpl

#### Actual behaviour

ubuntu@jhub-controller:~/jhub/kubernetes$
```
ubuntu@jhub-controller:~/jhub/kubernetes$ helm upgrade --cleanup-on-fail   --install jhub jupyterhub/jupyterhub   --namespace jhub   --create-namespace   --version=0.11.1-n301.hc86268b1
Error: UPGRADE FAILED: template: jupyterhub/templates/singleuser/secret.yaml:9:9: executing "jupyterhub/templates/singleuser/secret.yaml" at <include "jupyterhub.extraFiles.data" .Values.singleuser.extraFiles>: error calling include: template: jupyterhub/templates/_helpers.tpl:343:8: executing "jupyterhub.extraFiles.data" at <include "jupyterhub.extraFiles.data.withNewLineSuffix" .>: error calling include: template: jupyterhub/templates/_helpers.tpl:336:12: executing "jupyterhub.extraFiles.data.withNewLineSuffix" at <include "jupyterhub.extraFiles.validate-file" (list $file_key $file_details)>: error calling include: template: jupyterhub/templates/_helpers.tpl:382:29: executing "jupyterhub.extraFiles.validate-file" at <$file_details.mountPath>: can't evaluate field mountPath in type string

```
### How to reproduce

Near as I can tell, a standard config.yaml for helm3 is going to provoke this. 

- Note that I did upgrade the cluster from helm 2 to 3. (
- Basic cluster as described in the install guide with the optional dedicated user pool.

### Your personal set up

 - OS:
 ubuntu@jhub-controller:~/jhub/kubernetes$ cat /etc/issue
Ubuntu 20.04.1 LTS \n \l
 
- <details><summary>Configuration</summary>
Jupyterhub 1.3.0
Helm chart version: 0.11.1-n301.hc86268b1 (march 11th) but tried all the way back to 0.11.1-n113.hc841983b  (feb 1st) when the aforementioned PR got introduced. 

jupyterhub_config.py is unmodified from what is in the helm chart.

```
ubuntu@jhub-controller:~/.config/helm$ cat repositories.yaml 
apiVersion: v1
generated: "2021-02-09T20:21:27.59853531Z"
repositories:
- caFile: ""
  cache: /home/ubuntu/.helm/repository/cache/stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  password: ""
  url: https://charts.helm.sh/stable
  username: ""
- caFile: ""
  cache: /home/ubuntu/.helm/repository/cache/local-index.yaml
  certFile: ""
  keyFile: ""
  name: local
  password: ""
  url: http://127.0.0.1:8879/charts
  username: ""
- caFile: ""
  cache: /home/ubuntu/.helm/repository/cache/jupyterhub-index.yaml
  certFile: ""
  keyFile: ""
  name: jupyterhub
  password: ""
  url: https://jupyterhub.github.io/helm-chart/
  username: ""
```
</details>

- <details><summary>Logs</summary>
```
Error: UPGRADE FAILED: template: jupyterhub/templates/singleuser/secret.yaml:9:9: executing "jupyterhub/templates/singleuser/secret.yaml" at <include "jupyterhub.extraFiles.data" .Values.singleuser.extraFiles>: error calling include: template: jupyterhub/templates/_helpers.tpl:343:8: executing "jupyterhub.extraFiles.data" at <include "jupyterhub.extraFiles.data.withNewLineSuffix" .>: error calling include: template: jupyterhub/templates/_helpers.tpl:336:12: executing "jupyterhub.extraFiles.data.withNewLineSuffix" at <include "jupyterhub.extraFiles.validate-file" (list $file_key $file_details)>: error calling include: template: jupyterhub/templates/_helpers.tpl:382:29: executing "jupyterhub.extraFiles.validate-file" at <$file_details.mountPath>: can't evaluate field mountPath in type string

```
</details>

**Comment by roelbaz** [comment]
An prematurely apologies if this an 'obvious' error. Based on my tinkering however I think this is an actual error in _helpers.tpl.

**Comment by consideRatio** [comment]
@roelbaz I can't reproduce this, and feel quite confident that the helm chart is given some configuration that has been invalid.

It smells to me like an issue caused by for example terraform modifying the config in a faulty way. If it were an issue, it should be able to reproduce like this:

```
helm template hub1 jupyterhub --repo=https://jupyterhub.github.io/helm-chart/ --version=0.11.1-n301.hc86268b1
```

Technically, I think this is an error caused by a config like...

```yaml
hub:
  extraFiles:
    test: "hi"
```

I can reproduce it like this...

```
helm template hub1 jupyterhub --repo=https://jupyterhub.github.io/helm-chart/ --version=0.11.1-n301.hc86268b1 --set hub.extraFiles.test=string-here
```

So, I assume this is a misconfiguration, and potentially caused by an external tool out of this helm charts control. I'll go ahead and close it for now but do followup if you can pinpoint this as an issue with the Helm chart.
