### ISSUE TITLE
Can't connect to jupyterhub managed services w/ url

### ISSUE THREAD

**Issue by kafonek** [jupyterhub/zero-to-jupyterhub-k8s#2102]
### Bug description
I am having trouble deploying a [Jupyterhub-managed service](https://jupyterhub.readthedocs.io/en/stable/reference/services.html#hub-managed-services) that exposes a `url`.  The configurable-http-proxy is unable to proxy to hosts `localhost`, `127.0.0.1`, or `0.0.0.0`.

### How to reproduce
Run a simple web server that copies syntax from [Tornado docs](https://www.tornadoweb.org/en/stable/#hello-world) and [`jupyterhub/examples/service-whoami`](https://github.com/jupyterhub/jupyterhub/tree/master/examples/service-whoami):

```
# config.yaml
hub:
  services:
    hello:
      admin: false
      command: ["python3", "hello.py"]
      url: 'http://127.0.0.1:8888'

  extraFiles:
    hello:
      mountPath: /srv/jupyterhub/hello.py
      stringData: |
        import tornado.ioloop
        import tornado.web

        class MainHandler(tornado.web.RequestHandler):
            def get(self):
                self.write("Hello, world")

        def make_app():
            return tornado.web.Application([
                (r"/?", MainHandler),
            ])

        if __name__ == "__main__":
            app = make_app()
            app.listen(8888)
            tornado.ioloop.IOLoop.current().start()
```

The "hello" service shows up in the Jupyterhub web UI.  Kubectl logs for `deploy/hub` and `deploy/proxy` show the service being spawned, connected, and proxy routes set.

```
# kubectl logs deploy/proxy
12:28:51.378 [ConfigProxy] info: Adding route /services/hello -> http://127.0.0.1:8888
12:28:51.378 [ConfigProxy] info: Route added /services/hello -> http://127.0.0.1:8888
12:28:51.379 [ConfigProxy] info: 201 POST /api/routes/services/hello 
```

Curling `http://127.0.0.1:8888` while exec'd into the Hub pod works.  Trying to curl `http://proxy-public/services/hello` or opening the service in the web UI shows errors such as:

```
#kubectl logs deploy/proxy
12:36:32.721 [ConfigProxy] debug: PROXY WEB /services/hello to http://127.0.0.1:8888
12:36:32.722 [ConfigProxy] error: 503 GET /services/hello connect ECONNREFUSED 127.0.0.1:8888
```
### Alternative attempt - 0.0.0.0
I tried changing the `hub.services.hello.url` to `0.0.0.0` and got a different error in `deploy/proxy` logs:

```
12:42:05.037 [ConfigProxy] info: Adding route /services/hello -> http://hub-74c5cf68bd-cdg5t:8888
12:42:05.037 [ConfigProxy] info: Route added /services/hello -> http://hub-74c5cf68bd-cdg5t:8888
12:42:05.037 [ConfigProxy] info: 201 POST /api/routes/services/hello 
12:42:23.838 [ConfigProxy] debug: PROXY WEB /services/hello/ to http://hub-74c5cf68bd-cdg5t:8888
12:42:28.850 [ConfigProxy] error: 503 GET /services/hello/ Error: getaddrinfo EAI_AGAIN hub-74c5cf68bd-cdg5t
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'hub-74c5cf68bd-cdg5t'
}
12:42:28.850 [ConfigProxy] debug: Requesting custom error page: http://hub:8081/hub/error/503?url=%2Fservices%2Fhello%2F
12:42:28.875 [ConfigProxy] debug: Not recording activity for status 503 on /services/hello
```

### Your personal set up
Running from local (git clone) master branch of this repo.

**Comment by consideRatio** [comment]
@kafonek hmmm I think that when you specify a service with a certain URL, the proxy that jupyterhub controls will be configured to proxy traffic to that URL, but, as it is 127.0.0.1, it means that it tries to access something in the proxy pod - which certainly isn't a place where you have started webserver - right?

**Comment by yuvipanda** [comment]
I literally just fought with this, haha!

So the hub adds the wrong route to the proxy - if you see `Error: getaddrinfo EAI_AGAIN hub-74c5cf68bd-cdg5t`, that's because the hub decided that's the value of `0.0.0.0` and sent that to the proxy. This works when the proxy is on the same host as hub, but otherwise doesn't.

You need a separate k8s service, like:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: <your-service>
  labels:
    app: jupyterhub
    component: <your-service>
spec:
  type: ClusterIP
  ports:
    - name: http
      port: <your-service-port>
      targetPort: <your-service-port>
  selector:
    app: jupyterhub
    component: hub
```

And then the `url` property of the service in z2jh should be set to `http://<your-service-name>:<your-service-port>`. This will tell the proxy where to send the traffic to, and things will end up working. You might also need to adjust networkpolicy if needed.

**Comment by yuvipanda** [comment]
Allowing additional ports to be opened in the hub service will probably help here, so we can just expose the ports used by the managed service rather than create a new service object.

**Comment by consideRatio** [comment]
Ah yes so to conclude, z2jh does not support fully JupyterHub managed services to run in the hub pod, only what is referred to as Externally-Managed Services in the JupyterHub docs. And, for such externally managed services, you would need to deploy the service yourself in a new k8s Deployment or similar and provide a dedicated k8s Service to reference its pods etc.

**Comment by consideRatio** [comment]
@kafonek your issues/prs are amazing, it is so great to read them with relevant links and such included! :heart: :tada:

**Comment by yuvipanda** [comment]
I don't think we need to automate this, but we can allow hooks to let people do this easily.

Only additional thing needed is to allow configuring extra ports in the [hub service](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/acc6c6c17c8737e81613d6018be8a10953f317be/jupyterhub/templates/hub/service.yaml#L32). This will remove need for extra service object. Other than that, I think it's mostly documentation.

I also needed to add more things to `hub.networkPolicy.ingress`:

```yaml
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  app: jupyterhub
                  component: hub
          ports:
            - port: 8081
              protocol: TCP
        - from:
            - podSelector:
                matchLabels:
                  app: jupyterhub
                  component: proxy
            - podSelector:
                matchLabels:
                  app: jupyterhub
                  component: hub
          ports:
            - port: <my-service-port-number>
              protocol: TCP
```

This allows:

1. Proxy to talk to the hub pod at the port of my service
2. The *hub* to talk to my service at the service of my port. Hub doesn't talk via localhost, but via the service name you give. So it needs to have a port opened 
3. The service to talk to the hub API. Same as (2) :D
