### ISSUE TITLE
We silently ignore configuring hub.config.<2 of 3 seeded configs>

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2108]
I need to think more about this, because there can be a lot of consequences or complexity related to this, but anyhow currently, the following config is silently ignored:

```yaml
hub:
  config:
    ConfigurableHTTPProxy:
      auth_token: aaaa1111 # proxy.secretToken accepted
    JupyterHub:
      cookie_secret: bbbb2222 # hub.cookieSecret accepted
    # this setting is NOT ignored because we fully removed the
    # old configuration option and transitioned to this, hmm...
    CryptKeeper:
      keys: [cccc3333]
```

I lean to think that we should accept a specification of these options for consistency. I was just about to configure these options to avoid autogenerating changes in templates that obfuscates my template rendering diff during development, but realized i must use proxy.secretToken and hub.cookieSecret instead.

## Action points
- [ ] Verify my guess, that we only need to update _helpers-passwords.tpl
- [ ] Make a decision for what config option takes precedence - the new option I guess...
- [ ] Make the change.
- [ ] Update lint-and-validate-config.yaml to use options under hub.config instead
