### ISSUE TITLE
JupyterHub not reachable via external IP anymore after enabling HTTPS

### ISSUE THREAD

**Issue by marcelbo2021** [jupyterhub/zero-to-jupyterhub-k8s#2164]
### Bug description
I attempted to manually activate HTTPS for my JupyterHub installation an Azure Kubernetes Cluster following this tutorial: https://zero-to-jupyterhub.readthedocs.io/en/stable/administrator/security.html#set-up-manual-https
I tried both "Specify certificate in config.yaml" and "Specify certificate through Secret resource". The result however, remains the same, namely that calling the external IP from my browser (I tried both Firefox and Edge) returns a timeout error. Without adding
```
 https:
    enabled: true
    hosts:
      - <EXTERNAL_IP_OF_PROXY_PUBLIC_SERVICE>
    type: secret
    secret:
      name: example-tls
```
to the config.yaml, access via HTTP works just fine.
#### Expected behaviour
JupyterHub can be accessed

#### Actual behaviour
A timeout error is returned:
![Capture](https://user-images.githubusercontent.com/81307664/115538624-9c37f980-a28b-11eb-972f-ccb60d27fbc6.PNG)

### How to reproduce
1. Create SSL key and certificate:
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=foo.bar.com"
```
2. Add secret resource with type kubernetes.io/tls containing the certificate:
```
kubectl create secret tls example-tls --key="tls.key" --cert="tls.crt"
```
3. Use the following config.yaml:
```
proxy:
  secretToken: "***"
  https:
    enabled: true
    hosts:
      - <EXTERNAL_IP_OF_PROXY_PUBLIC_SERVICE>
    type: secret
    secret:
      name: example-tls
hub:
  config:
    Authenticator:
      admin_users:
        - admin
    DummyAuthenticator:
      password: ***
    JupyterHub:
      authenticator_class: dummy
  extraConfig: |-
    from kubespawner import KubeSpawner
    from tornado import gen
    import yaml

    class CustomKubeSpawner(KubeSpawner):
        def get_env(self):
            env = super().get_env()

            env['KERNEL_USERNAME'] =  self.user.name

            return env
    c.JupyterHub.spawner_class = CustomKubeSpawner
    c.Spawner.start_timeout = 500

singleuser:
  defaultUrl: "/lab"
  image:
    name: elyra/elyra
    # change to a specific release version as appropriated
    tag: 2.2.1
    # disable this in a production environment
    pullPolicy: "Always"
  storage:
    dynamic:
      storageClass: default
  extraEnv:
    JUPYTER_GATEWAY_URL: http://enterprise-gateway.enterprise-gateway:8888
    JUPYTER_GATEWAY_REQUEST_TIMEOUT: "120"
```
4. Deploy it with
```
helm upgrade --cleanup-on-fail   --install jhub jupyterhub/jupyterhub   --namespace jhub   --create-namespace   --version=0.10.6   --values config.yaml
```
5. Wait a few minutes
6. Try to access <EXTERNAL_IP_OF_PROXY_PUBLIC_SERVICE> with a web browser
