### ISSUE TITLE
Using GRANT_SUDO and --allow-root crashes notebook

### ISSUE THREAD

**Issue by haf** [jupyterhub/zero-to-jupyterhub-k8s#2177]
### Bug description
According to the documentation here https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1021#issuecomment-629468352 — the way to make it possible for users of this project to install dependencies, is to configure `singleuser` like this:

```yaml

singleuser:
  defaultUrl: /lab

  image:
    # You should replace the "latest" tag with a fixed version from:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
    name: jupyter/datascience-notebook
    tag: latest

  uid: 0

  extraEnv:
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
```

However, when a pod is launched and has a browser connected to it, it immediately exists with logs:

```
jupyter-henrik notebook [I 2021-05-05 15:59:43.348 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
jupyter-henrik notebook [I 2021-05-05 15:59:43.354 SingleUserNotebookApp mixins:567] Starting jupyterhub-singleuser server version 1.4.0
jupyter-henrik notebook [W 2021-05-05 15:59:43.363 SingleUserNotebookApp _version:70] jupyterhub version 1.3.0 != jupyterhub-singleuser version 1.4.0. This could cause failure to authenticate and result in redirect loops!
jupyter-henrik notebook [C 2021-05-05 15:59:43.364 SingleUserNotebookApp notebookapp:2297] Running as root is not recommended. Use --allow-root to bypass.
- jupyter-henrik › notebook
```

The minus here denotes the exiting of the notebook.

Why? Because I want to mimick how colab works, and because the roles that 1) update the infrastructure, and 2) work with notebooks are two different ones — requiring the infra person to upgrade a dockerfile to install a package is more work than needed — instead the infra role can use network policies, istio network security and other mechanisms to have trusted co-workers being able to sudo inside a container.

Thera are some issues at play here:

- Except the linked comment, I can't find documentation on how to run the notebook as root
- The notebook crashes immediately when used according to the comment/docs
- The `NOTEBOOK_ARGS` flag doesn't seem to work, or the notebook shouldn't crash as it does

#### Expected behaviour

It should be documented how to opt-out of the extra security. Furthermore, the documented way to do it should work.

#### Actual behaviour
It's not documented (besides the comment) and the notebook crashes immediately.

I'm documenting it here, and I'm going to try not to set `uid` now, to see whether the default user can `sudo` from the `GRANT_SUDO` flag alone. The `NOTEBOOK_ARGS` flag doesn't seem to work (since the crash tells me to do something I'm already doing), so I'm going to remove it

### How to reproduce

With the config above, do:

```bash
helm template jhub jupyterhub/jupyterhub --namespace flows --version 0.11.1 --values config.yaml --output-dir k8s/template
cp -r k8s/template/jupyterhub/templates/ k8s/base/
kustomize build k8s/prod | kubectl apply -f -
open https://jhub.example.com
```

### Your personal set up

Latest Helm chart on GKE with the above configuration.

<details><summary>Configuration</summary>

```yaml
# https://zero-to-jupyterhub.readthedocs.io/en/stable/administrator/authentication.html#google
hub:
  config:
    GoogleOAuthenticator:
      client_id: 326xxxxxxxxxxxxxxxxppcqpfhglr1vbft5b64ni8.apps.googleusercontent.com
      client_secret: -xxxxxxxxxxxxxxx
      oauth_callback_url: https://jhub.xxxxxxx.xxx/hub/oauth_callback
      hosted_domain:
      - xxxxxx.xxx
      login_service: XXXX
    JupyterHub:
      authenticator_class: google
      authenticate_prometheus: False
    admin:
      users:
      - henrik
      - max
```
</details>

- As a side-note: `/lab` only shows a white page, but going to `/tree` lets you see the default interface when testing without `uid` in the `config.yaml` file.
