### ISSUE TITLE
Clarify documentation about the culling configuration

### ISSUE THREAD

**Issue by cdibble** [jupyterhub/zero-to-jupyterhub-k8s#2244]
### Bug description

There might be more than one thing going on here, so happy to separate into multiple issues if appropriate.

EDIT- there are two things going on indeed: see [this issue ](https://github.com/jupyterlab/jupyterlab/issues/6893) related to JupyterLab and failing to avoid culling active Lab servers.
This issue should focus on `idle-culler` and the problem of configuring to avoid culling named servers.

I am seeing named servers culled after the timeout interval when that is set to false. This occurs with terminal processes running and the browser/client disconnected (i.e., on overnight jobs).

My `config.yaml` file used to install the official helm chart (v0.11.1) has the following cull configs:

```
cull:
  enabled: true
  users: false
  removeNamedServers: false
  timeout: 3600
  every: 600
  concurrency: 10
  maxAge: 0
```
The hub logs confirm this:
```
[I 210608 02:28:03 __init__:191] Culling server <user-name>/<server-instance-name> (inactive for 01:05:49)
```

#### Expected behaviour

Named servers would not be culled ever.

Servers with running terminal processes would not be culled.

#### Actual behaviour

After the configured interval, the culler kills the pods.

### How to reproduce

See above snippet for the relevant portions of the `config.yaml` file. 

### Your personal set up

Running on AWS EKS with helm chart v0.11.1.

The `singleUser` image uses the base image `jupyter/datascience-notebook:python-3.8.8`

Other images in helm:
```
hub:
  image:
    name: jupyterhub/k8s-hub
    tag: 0.10.6-n211.h2e3a73af 

proxy:
  chp:
    image:
      name: jupyterhub/configurable-http-proxy
      tag: 4.3.2
  traefik:
    image:
      name: traefik
      tag: v2.4.8 

singleuser:
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: 0.11.1-n221.h84f79652 # "set-by-chartpress"

scheduling:
  userScheduler:
    image:
      name: k8s.gcr.io/kube-scheduler
      tag: v1.19.10

prePuller:
  hook:
    image:
      name: jupyterhub/k8s-image-awaiter
      tag: 0.11.1-n362.h81fdd6e0 # "set-by-chartpress"
  pause:
    image:
      name: k8s.gcr.io/pause
      tag: "3.2"
```

 - OS:
 
 - Version(s):
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
# this is truncated for brevity. can provide more details if needed.
jupyter-client                    6.1.12
jupyter-contrib-core              0.3.3
jupyter-contrib-nbextensions      0.5.1
jupyter-core                      4.7.1
jupyter-highlight-selected-word   0.2.0
jupyter-latex-envs                1.4.6
jupyter-nbextensions-configurator 0.4.1
jupyter-packaging                 0.10.1
jupyter-resource-usage            0.6.0
jupyter-server                    1.6.4
jupyter-server-mathjax            0.2.2
jupyter-telemetry                 0.1.0
jupyterhub                        1.4.0
jupyterlab                        3.0.14
jupyterlab-git                    0.30.1
jupyterlab-pygments               0.1.2
jupyterlab-server                 2.5.0
jupyterlab-widgets                1.0.0
nbclient                          0.5.3
nbconvert                         6.0.7
nbdime                            3.1.0
nbformat                          5.1.3
nbgitpuller                       0.9.0
notebook                          6.3.0
nteract-on-jupyter                2.1.3
oauthlib                          3.0.1
prometheus-client                 0.10.1
widgetsnbextension                3.5.1
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by cdibble** [comment]
It seems the problem with culling running processes is related to JupyterLab (though it can be accomplished with classic notebooks) and there is an open issue here: https://github.com/jupyterlab/jupyterlab/issues/6893

So this issue should really just be focused on the Helm configuration to direct `idle-culler` to skip named servers.

**Comment by consideRatio** [comment]
@cdibble first of all thank you for your care and effort to consider the scope of the issue and writing such a clear issue!!! :heart:

When i read that configuration option, which is passed to `jupyterhub-idle-culler` which is now a standalone script, I'm thinking that I'm not sure what it actually means. Does it mean that the user servers shouldn't be culled, or that they shouldn't be deleted entirely after being stopped?

Reading in https://github.com/jupyterhub/jupyterhub-idle-culler#as-a-standalone-script i conclude that `--remove-named-servers` is a config option to not delete the named servers entirely after stopping (culling) them. I think it defaults to false as well btw.

So in practice, I don't think the jupyterhub-idle-culler package supports not stopping the named servers specifically, it simply stops any server or not.

---

I think we should change the Helm chart to be more clear that the options are flags to the jupyterhub-idle-culler package, for example by having something like this...

```yaml
jupyterhubIdleCuller:
  flags:
    - `--remove-named-servers=false`
    # ...
```

Rather than exposing configuration named like we currently do:

```yaml
cull:
  enabled: true
  users: false
  removeNamedServers: false
  timeout: 3600
  every: 600
  concurrency: 10
  maxAge: 0
```

**Comment by cdibble** [comment]
Ah yes thanks, @consideRatio . The stand-alone script docs do make it quite clear that I was misunderstanding the intended behavior:

```
  --remove-named-servers           Remove named servers in addition to stopping
                                   them.  This is useful for a BinderHub that
                                   uses authentication and named servers.
                                   (default False)
```
I agree that it could be a little more clear in the Helm chart that `cull` refers to the configuration for the `jupyterhub-idle-culler`, although that could probably be taken care of in documentation. In general, the ztjh docs for the Helm installation are really good, so perhaps the easiest path would be to simply add a little clarity around [here](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-management.html#culling-user-pods) that helps users understand the `jupyterhub-idle-culler` options and its distinct but related counterpart in the notebook/server configuration.

FWIW to future sleuths- the notebook culling behavior (that is separate from the `jupyterhub-idle-culler` service) is documented [here](https://jupyter-notebook.readthedocs.io/en/stable/config.html) - take a look at `MappingKernelManager.cull_idle_timeout`, `MappingKernelManager.cull_interval`, `MappingKernelManager.cull_connected`, and `NotebookApp.shutdown_no_activity_timeout`.

I could do a PR on the docs if you'd like, but your proposal warrants further discussion and there may be reasons for it that I am failing to appreciate. 

Thanks for the reply and this great project!

**Comment by cdibble** [comment]
This should get re-labeled from `bug` to maybe `question` or `documentation` but I don't think I have the ability to do that.

**Comment by consideRatio** [comment]
> I could do a PR on the docs if you'd like

:heart: :tada: You're most welcome to! :heart: :tada:

I agree with your suggestion on adding clarity in the linked section. You seem to have acquired a great overview of various culling mechanisms :) I find having a good overview is really helpful when documenting something!

Thank you for the encouraging words and contributing to this project! :heart:

I retitled this issue to represent the need to have some documentation that clarifies the culler a bit.

If you want, I think it could be useful also to make a comment in the values.yaml files just above `cull:` like we have for the `hub:` section, and let that comment clarify that the `cull` section configures the `jupyterhub-idle-culler` by similar command line flags.

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/95982ad397136ff90e4e8830f6814d63599e31f1/jupyterhub/values.yaml#L23-L28

**Comment by cdibble** [comment]
I'd be happy to do that. I'll make those changes and submit a PR :)

**Comment by viktoriaas** [comment]
Hi @cdibble @consideRatio,

I came across this post because I'm dealing with a similar problem as was originally asked (kernel processes running and the browser/client disconnected (i.e., on overnight jobs, training models)) and I wanted to ask whether my understanding is right.

I am struggling in recognizing what culling option is provided by which configuration. I have deployed `z2jh on kubespawner` with culling configuration:

```
cull:
  enable: true
  timeout: 18000
```

which I thought would remove idle notebooks after 5 hours and works this way:
1.  check if no process is running
2. if no process is running and notebook is closed -> remove the notebook
3. if no process is running and notebook is opened -> do nothing 
4. if process is running and notebook is in whatever state -> do nothing
 
But I was wrong and a couple of days ago a user told me he was performing a training in cell overnight (therefore long-running job, web-browser closed) and the notebook was removed with half-computed model.

I went through:
- [this issue](https://github.com/jupyter/enterprise_gateway/issues/665#issue-443093153)
- [this discourse question](https://discourse.jupyter.org/t/which-is-the-correct-way-to-cull-idle-kernels-and-notebook/8123/8)
- [this documentation part](https://jupyterhub.readthedocs.io/en/stable/reference/config-user-env.html#example-enable-a-jupyter-notebook-configuration-setting-for-all-users)

and I'm still unsure what options should be turned on in what way to reach desired functionality. I assume original [jupyterhub-idle-culler](https://github.com/jupyterhub/jupyterhub-idle-culler) does not perform any specific culling apart from asking whether web connection exists. Therefore I need more granular checking in form of specific options (the ones @cdibble suggest looking on) and disabling the native culling in `values.yaml` ?

My current setup in `values.yaml`
```
...
hub:
  extraConfig:
    extra-features: |
      c.MappingKernelManager.cull_idle_timeout = 3600
      c.MappingKernelManager.cull_connected = False
      c.MappingKernelManager.cull_busy = False

      c.NotebookApp.shutdown_no_activity_timeout = 3600

cull:
  enable: false
  timeout: 18000
```

Will this ensure that notebooks with no running processes and with closed web interface will be shutdown after 1 hour? (and no other?) If not, could you explain me the possible combinations of options?

Thanks!

**Comment by consideRatio** [comment]
In the JupyterHub helm chart, there are separate pods or containers running. If you use `hub.extraConfig` it will configure software on the hub pod only.

I think what you referenced in the end about c.NotebookApp and c.MappingKernelManager relates to the user pods though. If you want to configure that, perhaps you want something like a `jupyter_notebook_config.py` file in a location on the user pods where it is automatically read?

```yaml
singleuser:
  extraFiles:
    jupyter_notebook_config:
      mountPath: /usr/local/etc/jupyter/jupyter_notebook_config.py
      stringData: |
        c.MappingKernelManager.cull_idle_timeout = 3600
        c.MappingKernelManager.cull_connected = False
        c.MappingKernelManager.cull_busy = False

        c.NotebookApp.shutdown_no_activity_timeout = 3600
```

---

I don't overview the complexity of culling so well, but note that "notebook is open" is a bit vague. What does it mean for a notebook to be open? I think there is a kernel associated with a notebook, and then there is a user interface presenting the notebook.

I think this is relevant for the JupyterHub idle culler running in the jupyterhub pod.

1. Does the user pod report itself to be active? If not, stop that server after a while.
2. When does the user pod report itself to be active?
   1. When it has a running kernel
   2. When it has an active user, a user that interacts with the server somehow by using a browser that communicates back to the notebook server - and perhaps it does so by regular keep-alive pings by simply being in a browser window that isn't closed or made inactive by some memory-saving extensions for browsers etc.
   
   
I've now gone a bit beyond what I know, but I figure it can be relevant to the documentation to document as part of this issue, but not really - I would say its part of the documentation of the jupyterhub-idle-culler itself rather than this Helm chart's documentation that this kind of info belongs.
