### ISSUE TITLE
Providing extraEnv as list not possible due to values.schema.json

### ISSUE THREAD

**Issue by mseiwald** [jupyterhub/zero-to-jupyterhub-k8s#2290]
### Bug description
When providing `extraEnv` as a list like below the value schema validation fails since the value's type is set to `object`.
```
        extraEnv:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
```

#### Expected behaviour
`extraEnv` should accept both map and array to support rich environment variables (e.g. reference secrets)

#### Actual behaviour
```  
  Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
  jupyterhub:
  - hub.extraEnv: Invalid type. Expected: object, given: array
```
