### ISSUE TITLE
Connection is not secure with automatic HTTPS

### ISSUE THREAD

**Issue by cnchann** [jupyterhub/zero-to-jupyterhub-k8s#2339]
### Bug description
I am deploying my JupyterHub, using the distribution zero-to-jupyterhub, on Google Cloud Platform using Kubernetes. I want to set up automatic HTTPS from letsencrypt with the configuration setting described in the config.yaml file. However, even though it was successfully deployed using Helm, I am not able to establish a secure connection when accessing the site. 

It seems to me that letsencrypt is not able to provide a certificate. 
![image](https://user-images.githubusercontent.com/24472833/127842294-8e682a71-11e9-4884-a1a5-717673ad5f9d.png)

Please advise on what can be done to debug. Thank you in advance.
```
#config.yaml
proxy:
  secretToken: "redacted"
  https
    enabled: true
    hosts:
    - redacted.com
    letsencrypt:
      contactEmail: redacted@email.com
  service:
    loadBalancerIP: redacted
```
</details>
