### ISSUE TITLE
Need Support for Container Security Context Single user POD 

### ISSUE THREAD

**Issue by anurag4516** [jupyterhub/zero-to-jupyterhub-k8s#2353]
### Bug description

Z2JH only supports CSC at Hub Pod level. When we set something like 

```yaml
hub:
  containerSecurityContext:
    runAsUser:  1234
    runAsGroup: 4567
    readOnlyRootFilesystem: true 
    allowPrivilegeEscalation: false
```

in values.yaml , hub is running with this Container Security Context , as well as Single user Pod notebook container also runs with same security context . As per Kubespawnner documentation setting below should help
 c.KubeSpawner.container_security_context ,
But somehow , this value is not picked up and its overriden via hub containerSecurityContext

#### Expected behaviour

Should be able to set  different CSC at both hub and single notebook container level . 

#### Actual behaviour

Only able to set value at hub level
