### ISSUE TITLE
Nginx Ingress - Kernel stuck on Connecting

### ISSUE THREAD

**Issue by arghya18** [jupyterhub/zero-to-jupyterhub-k8s#2366]
I am running z2jh on EKS and trying to configure Ingress but facing error connecting to kernel, this works with LoadBalancer or NodePort service. For Ingress everything else is working except connecting with kernel

My ingress config looks like below

```
ingress:
  enabled: true
  hosts: ["<host_url>"]
```

And my nginx ingress controller config is below
```
controller:
  service:
    targetPorts:
      http: http
      https: http
    internal:
      enabled: 'true'
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
      service.beta.kubernetes.io/aws-load-balancer-internal: 'true'
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'cert-arn'
```

Error:
```
[W 2021-08-26 17:32:33.408 SingleUserNotebookApp log:189] 400 GET /user/11111/api/kernels/cd0584c0-c1db-4e3b-b84d-95a6a6a34c7c/channels?session_id=829bb706-cdc2-4d05-b4c4-523c1b15feec (11111@10.219.35.57) 5.52ms
[W 2021-08-26 17:32:34.163 SingleUserNotebookApp log:189] 400 GET /user/11111/api/kernels/cd0584c0-c1db-4e3b-b84d-95a6a6a34c7c/channels?session_id=533997d2-0c61-4b92-85b7-5a561309c517 (11111@10.219.35.57) 2.08ms
[W 2021-08-26 17:32:34.921 SingleUserNotebookApp log:189] 400 GET /user/11111/api/kernels/cd0584c0-c1db-4e3b-b84d-95a6a6a34c7c/channels?session_id=8982ed28-1250-48e4-9892-81325d9a7241 (11111@10.219.35.57) 1.99ms
[W 2021-08-26 17:32:35.677 SingleUserNotebookApp log:189] 400 GET /user/11111/terminals/websocket/1 (11111@10.219.35.57) 1.34ms
[W 2021-08-26 17:32:36.436 SingleUserNotebookApp handlers:366] Replacing stale connection: cd0584c0-c1db-4e3b-b84d-95a6a6a34c7c:829bb706-cdc2-4d05-b4c4-523c1b15feec
[W 2021-08-26 17:32:43.872 SingleUserNotebookApp handlers:366] Replacing stale connection: a15bc2b9-f405-48bc-8114-6d3d37e5d854:65fcd46f-2e49-4dbc-9c04-52451a830cc5
[W 2021-08-26 17:32:43.916 SingleUserNotebookApp handlers:366] Replacing stale connection: a15bc2b9-f405-48bc-8114-6d3d37e5d854:3721350b-f6f3-44ab-971f-cf0f0cd82ce9

```

I have also tried couple of config to enable websocket using annotation nginx.ingress.kubernetes.io/server-snippet but without any luck.
I am not sure if its a bug or configuration issue but default config does not work and I looked into couple of post and discussion around it but nothing worked.
