### ISSUE TITLE
deprecated apiVersion for ingress

### ISSUE THREAD

**Issue by MattiasVahlberg** [jupyterhub/zero-to-jupyterhub-k8s#2374]
### Bug description

When deploying jupyterhub helm chart with config.yaml containing ingress configuration it deploys an old apiVersion for ingress. 
#### Expected behaviour

Expecting apiVersion for ingress object in Kubernetes to be
```
apiVersion: networking.k8s.io/v1 
kind: Ingress
```
#### Actual behaviour

Ingress apiVersion deployed is:
```
apiVersion: extensions/v1beta1
kind: Ingress
```
### How to reproduce

1. `helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/`
2. `helm repo update`
3. Create config.yaml:
```
proxy:
  secretToken: "xxxx"
  service:
    type: ClusterIP
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/client-max-body-size: "250m"
    nginx.ingress.kubernetes.io/proxy-body-size: "250m"
  hosts: 
    - someurl.com
  pathSuffix:
  pathType: Prefix
  tls: 
    - hosts:
      - someurl.com
      secretName: tls
```
5. Deploy to kubernetes:
```
helm upgrade --cleanup-on-fail \                              
  --install jupyterhub jupyterhub/jupyterhub \
  --namespace <yournamespace> \
  --version=1.1.3 \
  --values config.yaml
```
6. Verify ingress: `kubectl -n <yournamespace> get ingress jupyterhub -o yaml`

### Your personal set up

AKS cluster version 1.19.11
NGINX deployed with helm:
 - app version: `0.45.0`
 - chart version: `ingress-nginx-3.27.0`
 - OS:
 
 - Version(s):
 Jupyterhub chart version: 1.1.3
Default installation except for ingress, followed https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/installation.html#install-jupyterhub guide
