### ISSUE TITLE
Support configuring ingressClassName

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#2380]
Previously, a user could configure the ingress controller to use by setting an annotation (kubernetes.io/ingress.class) on the ingress resource. Now though. there is a new field under `spec` that should be used instead called `ingressClassName`. This is not yet configurable via our Helm chart and we should make it configurable.

https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

One can still rely on a default ingressClass, one can for example configure the ingress-nginx helm chart like this. Below I provide some other common useful configuration options for running with a z2jh deployment, but only the part about ingressClass is relevant to this issue in practice.

```yaml
controller:
  # To make our Ingress resources able to rely on a default IngressClass,
  # we need to also configure watchIngressWithoutClass.
  ingressClassResource:
    default: true
  watchIngressWithoutClass: true
  
  # Below is additional config relevant to the ingress-nginx Helm chart used
  # to proxy traffix to a JupyterHub Helm chart deployment.

  config:
    # allow POSTs of upto 64MB, to support saving large notebooks.
    proxy-body-size: 64m

  # allow access to the proxy-public service
  podLabels:
    hub.jupyter.org/network-access-proxy-http: "true"
```

### References

- [K8s api reference on Ingress resources about spec.ingressClassName](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#ingressspec-v1-networking-k8s-io)
