### ISSUE TITLE
Ingress routes not working on OpenShift 4.6

### ISSUE THREAD

**Issue by vemonet** [jupyterhub/zero-to-jupyterhub-k8s#2387]
### Bug description

The main Ingress route generated for access the JupyterHub UI does not work on OpenShift 4.6 (we are using the [OKD open source](https://github.com/openshift/okd/) version)

#### Expected behaviour

I expect to access the JupyterHub UI at the URL created by the chart at install time

#### Actual behaviour

There is nothing at the URL location created by the route

### How to reproduce

1. Install OpenShift or minishift locally
2. Define this `config.yaml` file, I added some comments inline if you are wondering why we use certain configs

In this config we defined the cluster URL as: `apps.clusterUrl.com` feel free to change for your tests

```yaml
singleuser:
  serviceAccountName: anyuid
  storage:
    capacity: 2Gi
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

imagePullSecret:
  create: true
  automaticReferenceInjection: true
  registry: docker.io
  username: myuser
  password: mypass
  email: myemail

hub:
  config:
    OpenShiftOAuthenticator:
      # https://oauthenticator.readthedocs.io/en/latest/api/gen/oauthenticator.openshift.html
      oauth_callback_url: https://hub-namespace.apps.clusterUrl.com/hub/oauth_callback
    JupyterHub:
      authenticator_class: openshift
      # authenticator_class: dummy

  service:
    type: ClusterIP
    ports:
      nodePort:
    extraPorts: []
    loadBalancerIP:
  baseUrl: /
  fsGid: 1000
  concurrentSpawnLimit: 64
  consecutiveFailureLimit: 5
  activeServerLimit:
  deploymentStrategy:
    type: Recreate
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      subPath:
      storageClassName:
    url:
    password:
  command: []
  image:
    name: jupyterhub/k8s-hub
   # This dirty chartpress thing is breaking 1 time out of 2 ending up in manifests unknown, so we set the version manually, just for this one. You should avoid to use such inconsistent scripts
    # tag: "set-by-chartpress"
    tag: "1.1.3"
    pullPolicy:
    pullSecrets: []
  resources: {}
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    allowPrivilegeEscalation: false
  lifecycle: {}
  services: {}
  pdb:
    enabled: false
    maxUnavailable:
    minAvailable: 1
  networkPolicy:
    enabled: true
    # We added this to solve issue with Network Policy in OpenShift, not really working the same object needs to be manually added on the side
    ingress:
      - from:
        - podSelector: {}
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
    interNamespaceAccessLabels: ignore
    allowedIngressPorts: []
  allowNamedServers: false

ingress:
  enabled: true
  hosts:
    - hub-namespace.apps.clusterUrl.com
      # paths: ["/"]
  tls: []
  # pathSuffix:
  # pathType: Prefix
```

3. Deploy the chart 

```bash
helm install jupyterhub jupyterhub/jupyterhub \
  --version=1.1.3 \
  --values config.yaml
```

4. Access the route URL generated by the chart : not working
5. You can check if the proxy is properly deployed by port-forwarding it on your local laptop:

```bash
oc port-forward svc/proxy-public 8081:80
```

Access it on http://localhost:8081 : the port-forward works

Note that I am getting the same behavior (route not working) even when I am creating the Route manually through OpenShift (which usually works for most services), or if I am trying to create the root on the `hub` pod instead of the `proxy` pod 

I also tried enabling `tls` when creating an OpenShift Route directly, but still getting the same problem

### Your personal set up

 - OS: My laptop is Ubuntu 20.04, but the issue here is on the OpenShift nodes, which are running RHEL7 and OpenShift 4.6
 - Version(s): any version of JupyterHub, currently trying with the latest, 1.1.3

Checkout the `config.yaml` for the rest everything is defined in there

Any idea why exposing the proxy services does not work on OpenShift 4.6 ? Seems like there is some additional setup to do there. Note that we deployed dozens of services with routes on OpenShift, and it is the first time we are meeting such behavior: normally if the service can be port-forwarded, then the route should work
