### ISSUE TITLE
iPython Kernel Cannot Connect

### ISSUE THREAD

**Issue by chriscardillo** [jupyterhub/zero-to-jupyterhub-k8s#2402]
### Bug description

Trying to deploy [v1.1.3 of the JupyterHub Chart](https://jupyterhub.github.io/helm-chart/) on AKS. I am successfully able to use the GithubAuthenticator and spin up a Jupyter Notebook for myself, but the iPython Kernel won't connect.

#### Expected behaviour

I expect to be able to run Python code.

#### Actual behaviour

I am unable to run Python code. I try to run `2 + 2` and the kernel just hangs.

### How to reproduce

I am deploying on AKS, v1.1.3 of the JupyterHub Helm Chart. 

I am using Contour as my ingress controller.

I am using JetStack's cert-manager to manage certificates. I have a ClusterIssuer named `letsencrypt-prod`.

My config.yaml looks like this:

```
jupyterhub:
  singleuser:
    defaultUrl: "/lab"
  hub:
    db:
      pvc:
        storage: 8Gi
    config:
      GitHubOAuthenticator:
        client_id: my-id
        client_secret: my-secret
        oauth_callback_url: https://hub.example.com/hub/oauth_callback
      JupyterHub:
        authenticator_class: github
        Authenticator:
          admin_users:
            - chriscardillo
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
    hosts:
      - hub.example.com
    tls:
      - secretName: jupyterhub-tls
        hosts:
          - hub.example.com
  proxy:
    service:
      type: ClusterIP
```

(I have testing a proxy service type of LoadBalancer, as well but it does not change anything)

### Your personal set up

 - OS: ubuntu 20.04
 
 - Version(s): JupyterHub Helm Chart v1.1.3
 

- <details><summary>Full environment</summary>

N/A
```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```
jupyterhub:
  singleuser:
    defaultUrl: "/lab"
  hub:
    db:
      pvc:
        storage: 8Gi
    config:
      GitHubOAuthenticator:
        client_id: my-id
        client_secret: my-secret
        oauth_callback_url: https://hub.example.com/hub/oauth_callback
      JupyterHub:
        authenticator_class: github
        Authenticator:
          admin_users:
            - chriscardillo
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
    hosts:
      - hub.example.com
    tls:
      - secretName: jupyterhub-tls
        hosts:
          - hub.example.com
  proxy:
    service:
      type: ClusterIP
```

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>
