### ISSUE TITLE
Support SSL key/cert files

### ISSUE THREAD

**Issue by minrk** [jupyterhub/zero-to-jupyterhub-k8s#244]
#229 adds handy support for SSL via letsencrypt. We should have similarly simple support when users have existing SSL key/cert files. config should probably look something like:

```yaml
proxy:
  https:
    hosts:
      - needed?
    kind: files
    files:
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----
      cert: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
```
