### ISSUE TITLE
Helm Chart fails to get the specified configuration `containerSecurityContext`

### ISSUE THREAD

**Issue by Jiafi** [jupyterhub/zero-to-jupyterhub-k8s#2467]
### Bug description

When I use this values.yaml file, I expect to see capabilities.drop set. But I don't actually see it set (see the result of helm template below)
```yaml
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false
  pause:
    containerSecurityContext:
      capabilities:
        drop: [ALL]
```

The resulting helm chart fails to populated 
```yaml
pause:
    containerSecurityContext:
      capabilities:
        drop: [ALL]
```
#### Expected behaviour

The helm chart should have the specified configuration.
#### Actual behaviour

The helm chart fails to have the specified configuration.
### How to reproduce

1. Set 
```yaml
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false
  pause:
    containerSecurityContext:
      capabilities:
        drop: [ALL]
```
2. `helm template jupyterhub/jupyterhub -f foo.yaml > /tmp/jupyter-templated.yaml`

**Comment by consideRatio** [comment]
I failed to reproduce an issue about this. The pause container is used by the prePuller hook-image-puller and continuous-image-puller daemonsets, and if you disable them both, you won't have any such securitycontext set. This is expected. It is set if you do enable them though.

```
helm template jupyterhub jupyterhub --repo https://jupyterhub.github.io/helm-chart/ --values ../test.yaml --set prePuller.continuous.enabled=true | grep -A5 -B5 ALL
          image: k8s.gcr.io/pause:3.5
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsGroup: 65534
            runAsUser: 65534
---
# Source: jupyterhub/templates/hub/deployment.yaml
apiVersion: apps/v1
```
