### ISSUE TITLE
Binding other storage to profile

### ISSUE THREAD

**Issue by fritterhoff** [jupyterhub/zero-to-jupyterhub-k8s#2520]
Good morning :)

I'm trying to use zero-to-jupyterhub-k8s in combination with the profile functionality. In detail I want to assign different volumes for different profiles so they have a strict seperation of all folders/files.

My current attempt was to use the following pattern:
```
  storage:
    capacity: 4Gi
  
  profileList:
    - display_name: "Default Profile"
      description: "The default profile for the most common use cases including Python, code-server and some helpful extensions."
      default: true
    - display_name: "Development Profile"
      description: "The devlopment branch of the default profile. Warning: This profile could be unstable and cause unexpected behavior. The mounted volumes are not equal to the default profile."
      kubespawner_override:
        image: ghcr.io/fritterhoff/jupyter-code:dev
        storage:
          capacity: 4Gi
          dynamic:
            pvcNameTemplate: claim-{username}-dev
            storageAccessModes:
              - ReadWriteOnce
            volumeNameTemplate: volume-{username}-dev
          homeMountPath: /home/jovyan
          type: dynamic
```

Due to an unknown reason that does not work. The development profile stil only gets the normal claim/...

Is there any hint getting that working?
