### ISSUE TITLE
Are the docs regarding dedicated node pools correct?

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/zero-to-jupyterhub-k8s#2561]
### Bug description
I created a dedicated *`jupyter`* node pool in my AKS cluster to run my JupyterLab containers.
I added the `hub.jupyter.org/node-purpose=user` label and `hub.jupyter.org/dedicated=user:NoSchedule` taint as described in the docs:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/291b58a8992c74038e0e89927f8877011adaec58/docs/source/administrator/optimization.md#L272-L280

I then added `scheduling.userPods.nodeAffinity.matchNodePurpose: require` to my `values.yaml` as shown in the docs:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/291b58a8992c74038e0e89927f8877011adaec58/docs/source/administrator/optimization.md#L289-L302

#### Expected behaviour
I expected that when I started my server, it would trigger a scale-up of the `jupyter` node-pool and my pod would be deployed on the new node.

#### Actual behaviour
The `jupyter` node pool didn't scale up (no node was created) and my pod was scheduled on my default *`compute`* node pool.

#### What actually did work for me

I was able to get the desired behaviour (`jupyter` node pool scaling up and my JupyterLab pod being deployed on it) by using `singleuser.nodeSelector`:
```yaml
singleuser:
  nodeSelector:
    hub.jupyter.org/node-purpose: user
```

----

So, the question is, are the docs correct? Is `nodeAffinity.matchNodePurpose: require` supposed to trigger a scale up of a node pool instead of deploying on an already available node without the label?

The phrase *"Make user pods require to be scheduled on the node pool setup above"* suggests to me that your pod won't be scheduled on a node without the label - but that isn't what I observed in practice.

**Comment by consideRatio** [comment]
The docs is correctly describing the intended and wanted behavior, why it doesnt happen i don't know - so a bug or misconfiguration of something.

What chart version is used and with what custom chart configuration? Have you used kubespawner_override and profile_list etc?

Can you verify the state of the spawned pod: did it or did it not include nodeAffinity/nodeSelector to target nodes with the label? Did your node have the label?

**Comment by dhirschfeld** [comment]
* I'm on version `1.2.0` of the chart.
* The spawned pod had no `nodeSelector` attribute until I specifically added it in the `values.yaml`. The config as documented didn't result in a `nodeSelector` attribute being added to the pod.
* No `kubespawner_override` or `profile_list` are being used.

I'll have to check the rest in the morning!

**Comment by consideRatio** [comment]
> The spawned pod had no nodeSelector attribute until I specifically added it in the values.yaml. The config as documented didn't result in a nodeSelector attribute being added to the pod.

They are supposed to have `nodeAffinity` rather than `nodeSelector` when you set `scheduling.userPods.nodeAffinity.matchNodePurpose: require` - you didn't observe that?

**Comment by dhirschfeld** [comment]
I don't *think* so - I think I looked for affinity but I wasn't really sure what I was looking for so maybe I missed it.

I'll have to check again in the morning. I've shut everything down for now. Just wanted to post my observations before calling it a day!

**Comment by consideRatio** [comment]
> Will nodeAffinity definitely force a pod to be scheduled on a node with the label?

You can have different kinds of affinity, required (`requiredDuringSchedulingIgnoredDuringExecution`) or preferred (`preferredDuringSchedulingIgnoredDuringExecution`). When you choose `require` or `prefer` that is the difference. See the two examples below from [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes-using-node-affinity/).

If you have the `required` option, it will be the same as `nodeSelector` - it is strictly required. 

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd            
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd          
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
```
