### ISSUE TITLE
Kube Proxy unhealthy

### ISSUE THREAD

**Issue by mateskoo** [jupyterhub/zero-to-jupyterhub-k8s#2565]
### Bug description
Readiness probe failing every few minutes, which causes the GUI to not work properly.

#### Expected behaviour
GUI (notebooks) works without interuptions.

### How to reproduce
Install jupyterhub from the official helm chart, set up persistant storage and try to run the GUI with default proxy values.

### Your personal set up
I am running kubernetes 1.22, with two nodes (master, worker).
Chart version: jupyterhub-1.1.3
App version: 1.4.2

 - OS:
 Oracle Linux 7.9 on both master and workers
 - Version(s):
Chart version: jupyterhub-1.1.3
App version: 1.4.2

- <details><summary>Configuration</summary>
DummyAuthenticator - 2 local users created
https enabled with selfsigned certificates
</details>

- <details><summary>Logs</summary>
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  9m24s                 default-scheduler  Successfully assigned jupyter-hub/proxy-58f94b7d59-hmx4s to dcpoth24213058
  Normal   Pulled     9m23s                 kubelet            Container image "jupyterhub/configurable-http-proxy:4.5.0" already present on machine
  Normal   Created    9m23s                 kubelet            Created container chp
  Normal   Started    9m23s                 kubelet            Started container chp
  Warning  Unhealthy  5m4s (x3 over 8m39s)  kubelet            Readiness probe failed: Get "https://10.44.0.2:8443/_chp_healthz": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
</details>

I have tried to change the tresholds for the readinessProbe and livenessProbe:

```
livenessProbe:
          failureThreshold: 85
          httpGet:
            path: /_chp_healthz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 1000
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30

readinessProbe:
          failureThreshold: 3000
          httpGet:
            path: /_chp_healthz
            port: https
            scheme: HTTPS
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
```

I found that this may help in other threads, there were also some values listed.
This configuration makes it better, but it is still not the user experience I've expected. 

I am fairly new to Kubernetes, and this is my first big deployment, so I would be really gratefull for any hints.
