### ISSUE TITLE
services "proxy-public" not found

### ISSUE THREAD

**Issue by MattPChoy** [jupyterhub/zero-to-jupyterhub-k8s#2573]
### Bug description
When running the `helm upgrade ...` command, the following message will appear.
```bash
Release "$release" does not exist. Installing it now.
Error: failed pre-install: timed out waiting for the condition
Error from server (NotFound): services "proxy-public" not found
```

```bash
helm upgrade --cleanup-on-fail \
   --install $release jupyterhub/jupyterhub \
   --namespace $namespace \
   --create-namespace \
   --version=1.2.0 \
   --values config.yaml
```

#### Expected behaviour

Error does not appear on the CLI and the usual dialogue describing that KubeCTL has started up the JuPyTerHub server appears.
#### Actual behaviour

Error message appears on the screen 

### How to reproduce
Run the `helm upgrade ...` command shown above

### Your personal set up
 - OS: Oracle Linux 8 (Cluster created using Oracle Kubernetes Engine | OKE)
 - Version(s): N/A

- <details><summary>Configuration</summary>

```yaml
hub:
  config:
    Authenticator:
      admin_users:
        - $user1
        - $user2
        - $user3
    GitHubOAuthenticator:
      client_id: $redacted
      client_secret: $redacted
      oauth_callback_url: $redacted
    JupyterHub:
      authenticator_class: github

```
</details>

- <details><summary>Logs</summary>
```bash
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
kube-system   coredns-68474555d4-x7r5s               0/1     Pending   0          21h
kube-system   csi-oci-node-m5p7t                     1/1     Running   0          21h
kube-system   kube-dns-autoscaler-84cdfb8898-x4fx8   0/1     Pending   0          24h
kube-system   kube-flannel-ds-djbck                  1/1     Running   0          21h
kube-system   kube-proxy-5mkjv                       1/1     Running   0          21h
kube-system   nvidia-gpu-device-plugin-vvzqk         1/1     Running   0          24h
kube-system   proxymux-client-q68ds                  1/1     Running   0          24h
neuro-k1      hook-image-awaiter-xh6sj               0/1     Pending   0          23m
neuro-k2      hook-image-awaiter-l5qjq               0/1     Pending   0          22h
```

```
# paste relevant logs here, if any
```
</details>
