### ISSUE TITLE
extraVolumeMounts and extraVolumes doesn't work

### ISSUE THREAD

**Issue by shrinandj** [jupyterhub/zero-to-jupyterhub-k8s#2609]
### Bug description
I wanted z2jh-k8s to use an existing PVC and mount that into the pod running jupyter-hub. I specified that with the `extraVolumes` and `extraVolumeMounts`. However, the pod that came up did not have this extra volume mounted.

#### Expected behaviour
The pod should've come up with the additional volume mounted.

#### Actual behaviour
The pod had no extra volumes.

### How to reproduce
This was the config.json that I used:
```
hub:
  config:
    singleuser:
      storage:
        capacity: 2Gi
        type: none
        dynamic:
          storageClass: standard
        extraVolumes:
          - name: my-pvc
            persistentVolumeClaim:
              claimName: my-pvc
              storageClass: ""
        extraVolumeMounts:
          - name: my-pvc
            mountPath: /my-vol
    scheduling:
      userScheduler:
        enabled: false
    prePuller:
      continuous:
        enabled: false
```

1. Run the helm upgrade command:
```
$ helm upgrade --cleanup-on-fail --install jupyter-k8s jupyterhub/jupyterhub --namespace myns --create-namespace --values config.yaml
```

### Your personal set up

 - OS:
Mac OSX Monterey v12.2.1
 - Version(s):
Helm: `version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}`
Kubernetes: kind cluster running v1.21.1 of Kubernetes

The hub pod was using image version `jupyterhub/k8s-hub:1.2.0`.

```python
# jupyterhub_config.py
```
</details>

I looked at the `values.yaml` file in the secret `hub`. It had an empty array for the `extraVolumes` and `extraVolumeMounts` section under `singleuser` (you can see the actual config after base64 decoding of the values.yaml)

I then manually modified the config to explicitly add the specific volumes I needed, base64 encoded the new contents and put them back into the secret. After this, the pod came up with the required extra volumes.

**Comment by consideRatio** [comment]
Misconfiguration, dont nest what you have under hub.config, but directly. See for example https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-storage-extravolumes - its not to be nested under hub.config.

**Comment by shrinandj** [comment]
Is there a sample config.yaml I can look at? I tried this and it didn't work:

```
hub:
  extraVolumes:
  - name: my-pvc
    persistentVolumeClaim:
      claimName: my-pvc
  extraVolumeMounts:
  - name: my-pvc
    mountPath: /mypath
  config:
    singleuser:
      storage:
        capacity: 2Gi
        type: none
        dynamic:
          storageClass: standard
    scheduling:
      userScheduler:
        enabled: false
    prePuller:
      continuous:
        enabled: false
```

Then, I tried this:
```
hub:
  singleuser:
    storage:
      extraVolumes:
      - name: my-pvc
        persistentVolumeClaim:
          claimName: my-pvc
      extraVolumeMounts:
      - name: my-pvc
        mountPath: /mypath
  config:
    singleuser:
      storage:
        capacity: 2Gi
        type: none
        dynamic:
          storageClass: standard
    scheduling:
      userScheduler:
        enabled: false
    prePuller:
      continuous:
        enabled: false
```

Here's `helm upgrade` itself failed with:
`- hub: Additional property singleuser is not allowed`
