### ISSUE TITLE
PodDisruptionBudget not using the correct API Version in Kubernetes v1.20

### ISSUE THREAD

**Issue by geoffo-dev** [jupyterhub/zero-to-jupyterhub-k8s#2649]
### Bug description
When attempting to deploy a helm chart to the cluster, both of the default PDB resources cannot deploy giving the error:

`server could not find the requested resource`

Having a look at the helm chart itself:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/5c0d0c5c74bc97bf403844ced6b8e79cc089498d/jupyterhub/templates/scheduling/user-scheduler/pdb.yaml#L2 

It looks like this is checking if only `policy/v1` exists on the cluster - which I believe it does - however PDB v1 does not. Should this not be `policy/v1/PodDisruptionBudget`? As this does not exist on K8s version 1.20 and therefore would default to `policy/v1beta1`.

I have tried deploying both versions manually and only `policy/v1beta1` works

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: jupyterhub
```

### Your personal set up
 - Kubernetes Version:
v1.20
 - Version(s):
Jupyterhub Helm Chart: 1.2.0

**Comment by consideRatio** [comment]
Happy to accept a PR checking for the specific resource instead of the policy/v1 api as a whole!

**Comment by geoffo-dev** [comment]
Apologies for the delay - will get this done in the next couple of days :-)

**Comment by Ruben-Wienigk** [comment]
Hello all, 

Unfortunately this bug still exist for at least my k8s version v1.25.4.

`kubectl api-resources | grep pdb`

poddisruptionbudgets - pdb - policy/v1 - true - PodDisruptionBudget

[My Chart Version is 2.0.0](https://jupyterhub.github.io/helm-chart)

**Necessary Change:** in pdb.yaml (line 2)

From:

`
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
`

to:

`
{{- if .Capabilities.APIVersions.Has "policy/v1" -}}
`

Thank you very much!

**Comment by consideRatio** [comment]
It should be in 2.0.0, note that if you use "helm template", this kinds of evaluations are weird as no k8s api-server should be assumed to ask for capabilities.

If you use helm upgrade --dry-run --debug, maybe you get to see rendered templates? I dont remember fully, but if so, check those for the actually rendered version against your k8s cluster.

**Comment by Ruben-Wienigk** [comment]
Sorry for the uncertainty. I have now performed a dry-run of the Helm chart and actually come to the correct result. 

The problem is weird.
We use ArgoCD with the following HelmChartInflationGenerator. 

```
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: jupyterhub-helm-generator
name: jupyterhub
repo: https://jupyterhub.github.io/helm-chart/
version: 2.0.0
valuesFile: ./helm/values.yaml
namespace: jupyterhub
releaseName: jupyterhub
includeCRDs: true
```

This results in this desired manifest in Argocd:

```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: jupyterhub
    argocd.argoproj.io/instance: jupyterhub
    chart: jupyterhub-2.0.0
    component: user-scheduler
    heritage: Helm
    release: jupyterhub
  name: user-scheduler
  namespace: jupyterhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: jupyterhub
      component: user-scheduler
      release: jupyterhub
```
