### ISSUE TITLE
Cull doesnt respect timeout, terminates singleuser web sessions 

### ISSUE THREAD

**Issue by ospiegel91** [jupyterhub/zero-to-jupyterhub-k8s#2735]
### Bug description

Using a long cull timeout of 3 days, Jupyterhub singleUser pods get terminated after short period of time. 

#### Expected behaviour

Considering a long cull timeout I would expect the singleUser pod to remain alive for at least that specified timeout duration

#### Actual behaviour

Jupyterlab singleuser pod is terminated unless the user is actively on the broswer tab session engaging with it. 

### How to reproduce

use these cull settings 
```
cull:
  enabled: true
  users: false # --cull-users
  removeNamedServers: false # --remove-named-servers
  timeout: 259200 # --timeout 259200s = 3 days
  every: 600 # --cull-every
  concurrency: 10 # --concurrency
  maxAge: 259200 # --max-age
```
 using the helm chart https://jupyterhub.github.io/helm-chart version 1.2.0

### Your personal set up
```
cull:
  enabled: true
  users: false # --cull-users
  removeNamedServers: false # --remove-named-servers
  timeout: 259200 # --timeout 259200s = 3 days
  every: 600 # --cull-every
  concurrency: 10 # --concurrency
  maxAge: 259200 # --max-age
```
 using the helm chart https://jupyterhub.github.io/helm-chart version 1.2.0,
on an EKS cluster

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>
