### ISSUE TITLE
Add `singleuser.extraEnvFrom`

### ISSUE THREAD

**Issue by dingobar** [jupyterhub/zero-to-jupyterhub-k8s#2817]
### Proposed change

Our users frequently want new secrets added to their environments. To make this as easy as possible to manage, I would like to just have one secret that is updated, so that I don't have to change the `values.yml` config for the chart every time.

### Who would use this feature?

Jupyterhub admins who are tired of constant change request to the singleuser environment.

### (Optional): Suggest a solution

Should be pretty straight forward to implement. I don't mind taking a stab at it.

**Comment by consideRatio** [comment]
This is already supported! At least in the latest release 1.2.0, see examples provided at https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-extraenv.

**Comment by dingobar** [comment]
Awesome! It should be added to the config reference: https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-extraenv

**Comment by dingobar** [comment]
@consideRatio I may be missing something here, but I don't think it is. I would like a pattern like this, where I don't have to specify the name of the env variable in the config, but the key from the k8s secret is taken directly:

```yaml
singleuser:
    extraEnvFrom:
        - my-awesome-secret
        - another-secret
```

**Comment by consideRatio** [comment]
Oh sorry I see, hmmm...

**Comment by consideRatio** [comment]
This is not supported by [kubespawner](https://github.com/jupyterhub/kubespawner) configuration, so we can't add an option in this helm chart to configure kubespawner with it.

We can get this done by using c.KubeSpawner.extra_container_config though, see it documented [here](https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html).

So in practice, something like...

```yaml
hub:
  config:
    KubeSpawner:
      extra_container_config:
        # Entries in envFrom should follow this pattern:
        # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#envfromsource-v1-core
        envFrom:
          - secretRef:
              name: my-awesome-secret
          - secretRef:
              name: another-secret
```

I don't want KubeSpawner and Z2JH to add this passthrough configuration, it has been unsustainable to add everything and keep everything up to date like that - so let's rely on extra_container_config in KubeSpawner. Note that while `singleuser.extraPodConfig` is available directly to map to `c.KubeSpawner.extra_pod_config` there isn't such mapping for `singleuser.extraContainerConfig`, so we use the direct general approach mapping `hub.config.KubeSpawner.extra_container_config` that works just like passing things to `c.KubeSpawner.extra_container_config` would as well.
