### ISSUE TITLE
Server culling along with the PVC in GKE

### ISSUE THREAD

**Issue by franklin-degirum** [jupyterhub/zero-to-jupyterhub-k8s#2854]
```
cull:
  enabled: true
  users: false # --cull-users
  removeNamedServers: false # --remove-named-servers
  timeout: 3600# --timeout
  every: 1800# --cull-every
  concurrency: 10 # --concurrency
  maxAge: 12 # --max-age
```
I am using this configuration for IDLE-CULLER

I want my server to shutdown when not active for an hour and when logged back in, it should still have the data inside.

when I recreate the same env without letsencrypt and Auth0, the PVC still is there, but not when they are being used. Any fix or workaround would be great.
