### ISSUE TITLE
`singleuser.image` is not picked up

### ISSUE THREAD

**Issue by pebabion** [jupyterhub/zero-to-jupyterhub-k8s#2869]
### Bug description

Custom Image under `singleuser` is not working.

#### Expected behaviour

My `values.yaml` file is as below as I want to use `jupyter/datascience-notebook` to be the base image when use launch. The motivation is that I won't have to install extra common packages such as pandas.

```
singleuser:
  storage:
    type: dynamic
    extraLabels: {}
    extraVolumes: []
    extraVolumeMounts: []
    static:
      pvcName:
      subPath: "{username}"
    capacity: 10Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass:
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
  image:
    name: jupyter/datascience-notebook
    tag: "set-by-chartpress"
    pullPolicy:
    pullSecrets: []
  startTimeout: 300
  cpu:
    limit:
    guarantee:
  memory:
    limit:
    guarantee: 1G
  extraResource:
    limits: {}
    guarantees: {}
  cmd: null
  defaultUrl:
  extraPodConfig: {}
```

#### Actual behaviour

When I run `kubectl describe pod jupyter-pebabion` it shows that the notebook container is still `jupyterhub/k8s-singleuser-sample:1.2.0`.

### Your personal set up

 - OS: I'm using Macbook M1. K8S is running on DigitalOcean. 
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>
