### ISSUE TITLE
Error when hub.extraFiles added using --set-file following the docs

### ISSUE THREAD

**Issue by lucianolacurcia** [jupyterhub/zero-to-jupyterhub-k8s#2895]
### Bug description

When I try to helm upgrade current deployment now adding hub.extraFiles.stringData I get the following error:
```
$ helm upgrade jupyterhub-stable jupyterhub/jupyterhub -f values_test.yml --version=2.0.0 --set-file hub.extraFiles.mi_config.stringData=$(pwd)/pre_spawn_config.py
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
jupyterhub:
- hub.extraFiles.mi_config: mountPath is required
```

But my values.yml already has the required value:
```yaml
hub:
  extraFiles:
    mi_config:
      mountPath: "/usr/local/etc/jupyterhub/jupyterhub_config.d/my_jupyterhub_config.py"
```

#### Expected behaviour

I would expect helm to not ask me for a value I already have.

#### Workaround
As a work around, I use the following command:
```
helm upgrade jupyterhub-stable jupyterhub/jupyterhub -f values_test.yml --version=2.0.0 --set-file hub.extraFiles.mi_config.stringData=$(pwd)/pre_spawn_config.py -
-set  hub.extraFiles.mi_config.mountPath="/usr/local/etc/jupyterhub/jupyterhub_config.d/my_jupyterhub_config.py"
```
and comment out the extraFile lines:
```
hub:
  # extraFiles:
  #   mi_config:
      # mountPath: "/usr/local/etc/jupyterhub/jupyterhub_config.d/my_jupyterhub_config.py"
```

**Comment by consideRatio** [comment]
If I'm using this config, saved into test.yaml.

```yaml
hub:
  extraFiles:
    mi_config:
      mountPath: "/usr/local/etc/jupyterhub/jupyterhub_config.d/my_jupyterhub_config.py"
```

Then the error I get is the following, which makes sense to me given that config.

```
helm template --repo=https://jupyterhub.github.io/helm-chart jupyterhub --values test.yaml
Error: values don't meet the specifications of the schema(s) in the following chart(s):
jupyterhub:
- hub.extraFiles.mi_config: Must validate one and only one schema (oneOf)
- hub.extraFiles.mi_config: data is required
```

You have not provided something to put in the file via `data`, `stringData`, or `binaryData`. In the case of a `.py` file, you should go for `stringData`.

Using this configuration, there is no error and you should end up with a mounted file containing two print statements.

```yaml
hub:
  extraFiles:
    mi_config:
      mountPath: "/usr/local/etc/jupyterhub/jupyterhub_config.d/my_jupyterhub_config.py"
      stringData: |
        print("hi")
        print("hi again")
```
