### ISSUE TITLE
error: 'unable to validate against any security context constraint' when spawning user container

### ISSUE THREAD

**Issue by BlueCog** [jupyterhub/zero-to-jupyterhub-k8s#2896]
Scenario:

Deploying latest Helm Chart (2.0.0) of [zero-to-jupyterhub-k8s](https://github.com/jupyterhub/zero-to-jupyterhub-k8s) on OpenShift 4.10. 

By setting:

```
  hub:
    podSecurityContext: false
    containerSecurityContext: false
  proxy:
    chp:
      containerSecurityContext: false
```
I'm able to let OpenShift decide the SecurityContext for me. De Hub and Proxy pods are starting without a problem.

But i'm struggling with setting the SecurityContext for the **singleuser** container. 

```
  hub:
    singleuser:
      uid: disable
      fsGid: disable
```
or: 

```
  hub:
    singleuser:
      uid: null
      fsGid: null
```
Seems not be working for me. 

I'm getting `unable to validate against any security context constraint` kind of error message's when trying to spawn a user container. 

As far as I can see at the moment there is no possiblility to disable any SecurityContext for the singleuser container.

### Proposed change
Be able to disable SecurityContext for the singleuser container like Hub and Proxy.

### Who would use this feature?
All users of a more strict k8s platform like OpenShift

**Comment by BlueCog** [comment]
I've tried some installations by hand via `helm install` and I see that the   `hub.podSecurityContext: false` also isn't tolerated. So it seems this affects all places in the Helm chart where a `podSecurityContext` or `containerSecurityContext` is set

**Comment by consideRatio** [comment]
### Helm chart specifics

The Helm chart allows you to configure all pods that it directly creates in one way, where there is `podSecurityContext` and `containerSecurityContext` configuration available that you can either update field in or set to `false` to unset default values.

Only `hub.podSecurityContext` is provided with default values, looking like...

```
hub:
  podSecurityContext:
    fsGroup: 1000
```

Besides that, most `<something>.containerSecurityContext` look like this...

```yaml
proxy:
  chp:
    containerSecurityContext:
      runAsUser: 65534 # nobody user
      runAsGroup: 65534 # nobody group
      allowPrivilegeEscalation: false
```

### KubeSpawner specifics

All helm chart configuration under `singleuser` is pretty much pass through configuration to KubeSpawner, which in turn is creating k8s pods for users. So, to influence how users pods are started, you need to consider how KubeSpawner is configured by default, what z2jh overrides, and what you want to accomplish etc.

You have the following configuration in the Helm chart, influencing KubeSpawner:

```yaml
singleuser:
  uid: 1000
  fsGid: 100
```

To make KubeSpawner not be explicitly configured by the helm hcart, you can provide null values instead...

```yaml
singleuser:
  uid:
  fsGid:
```

I note that KubeSpawner's [`fs_gid`](https://github.com/jupyterhub/kubespawner/blob/0f22abf096459b5424325fa93ff4b30bef568391/kubespawner/spawner.py#L869-L874) is set to None by default, and [so is `uid`](https://github.com/jupyterhub/kubespawner/blob/0f22abf096459b5424325fa93ff4b30bef568391/kubespawner/spawner.py#L817-L822).

That means, that if you want to have all the users (pod/container) securityContexts be omitted when user servers are spawned by KubeSpawner, you can probably do...

```yaml
singleuser:
  uid:
  fsGid:
```

---

You can also update KubeSpawner config directly, which is documented to override things, if set to something truthy at least.

- https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.container_security_context
- https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner.pod_security_context
