### ISSUE TITLE
503 Sevice unavailable when a second user log in the system.

### ISSUE THREAD

**Issue by Francesko90** [jupyterhub/zero-to-jupyterhub-k8s#2957]
### Bug description

Sevice unavailable when a second user log in the system.

#### Expected behaviour

All users can be use jupyterhub at the same time.

#### Actual behaviour

Hello guys! Thanks for your works! I used jupyterhub in the past without this problem, now I deployed jupyterhub 2.0.0 on k3s v1.24.6+k3s1 and I have the following problem. The login of first user works without problem but when a second user spawn his pod the first user receive this error

![image](https://user-images.githubusercontent.com/6740590/203753900-99cd9f27-8b68-4b41-8ba8-e8c674398a9b.png)
 
And if try to refresh page 

![image](https://user-images.githubusercontent.com/6740590/203754075-6583cf5c-debd-4da1-a244-9e481370f9a9.png)

The pods are up and running for the all users.

### Your personal set up
```
hub:
  db:
    type: sqlite-memory
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      bind_dn_template:
        - cn={username},ou=users,dc=organization,dc=com
      server_address: ldap.organization.com
singleuser:
  image:
    pullPolicy: "Always"
    pullSecrets:
      - "image-pull-secret"
  profileList:
    - display_name: "name"
      description: "description
      kubespawner_override:
        image: <my_image_that_Extend_ jupyterhub/k8s-singleuser-sample:2.0.0>
#ingress:
#  enabled: false
#  ingressClassName: traefik

proxy:
  service:
    nodePorts:
      http: 30000
```

Kubernets: k3s v1.24.6 with containerd
OS:Almalinux
StorageClass: NFS

I tried with ingress and nodeport but I have the same error

### Log description

First user is fcaronte
Second user is mrossi

At the first spawn of mrossi the pod is corecctly spawned but the hub don't see the pod

Logs

- [hub-5b7694c496-rctsq.log](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/10083319/hub-5b7694c496-rctsq.log)
- [jupyter-fcaronte.log](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/10083320/jupyter-fcaronte.log)
- [jupyter-mrossi.log](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/files/10083321/jupyter-mrossi.log)
