### ISSUE TITLE
Using nohup at lifecycleHooks with GKE containerd node

### ISSUE THREAD

**Issue by wjdqlsdlsp** [jupyterhub/zero-to-jupyterhub-k8s#2989]
### Bug description

I have some problem using nohup at lifecycleHooks.postStart.exec.command with containerd node image.

My env

- GKE: 1.22.15-gke.100 [ using Container-Optimized OS(cos_containerd) ]
- Jupyterhub: JupyterHub 3.1.0.dev
I use custom image with zero-to-jupyterhub-k8s chart

Recently i upgrade my node image from docker node to containerd node.
When i use Docker node, It worked well. But It's not work on containerd node
It's pending more than 1200s and timeout.
 
I try many ways and Finally found the cause. That's nohup!

```shell
# initialize.sh
function check_interval {
  SLEEP_INTERVAL_SECONDS=60
  while true; do
      echo "some Function work in this"
      sleep "${SLEEP_INTERVAL_SECONDS}"
  done
}

export -f check_interval
nohup bash -c check_interval &
``` 
 I use intialize.sh file in lifecycleHooks to delete not use resource.
```yaml
singleuser:
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "/bin/bash"
          - "-c"
          - "/init.d/initialize.sh"

```

#### Expected behaviour

Work nohup command at lifecycleHooks in containerd node

#### Actual behaviour

not work properly. pending forever. ( while true )

### How to reproduce

I tried in zero-to-jupyterhub-k8s 2.0. and it have same problem

### Your personal set up

Using GKE cluster. containerd node.
