### ISSUE TITLE
`singleuser: extraPodConfig:` does not get set by the helm chart

### ISSUE THREAD

**Issue by goseind** [jupyterhub/zero-to-jupyterhub-k8s#3021]
### Bug description

I'm trying to set `fsGroupChangePolicy: "OnRootMismatch"` to the `securityContext` of my single user containers - as this is required by my cloud provider - like so:

```yaml
singleuser:
   extraPodConfig:
     securityContext:
       fsGroupChangePolicy: "OnRootMismatch"
```

However, it doesn't work and the value does not get set once a user starts a session.

#### Expected behaviour

Once a user starts a notebook, the pod `securityContext` should contain the above value, like so:

```yaml
kind: Pod
metadata:
  name: user-pod
spec:
  containers:
    securityContext:
      fsGroupChangePolicy: "OnRootMismatch"
```

#### Actual behavior

The value does not get set, instead, the standard values are applied, so the values `fsGroupChangePolicy: "OnRootMismatch"` does not get set at all.

### How to reproduce

Default helm installation with just the above config set in it.

### Your personal set up

 - OS: default images (K8s helm installation)
 
 - Version(s): zero-to-jupyterhub with jupyterhub official release [2.0.0](https://jupyterhub.github.io/helm-chart/jupyterhub-2.0.0.tgz) and [2.0.1-0.dev.git.5994.hdf257a2c](https://jupyterhub.github.io/helm-chart/jupyterhub-2.0.1-0.dev.git.5994.hdf257a2c.tgz) both not working as expected
 

<details><summary>Full environment</summary>

n/a

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

default

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

n/a

```
# paste relevant logs here, if any
```
</details>

**Comment by wiegerthefarmer** [comment]
Any update on this? I've tried so many ways to get fsGroupChangePolicy set.  The only way it works is if I have it in a yaml file that I manually start pods with, but that's not how our system works.

**Comment by lust4life** [comment]
seems it works now in helm => jupyterhub-4.1.0

```
singleuser:
  extraPodConfig:
    securityContext:
      fsGroupChangePolicy: "OnRootMismatch"
```

then:

<img width="405" alt="Image" src="https://github.com/user-attachments/assets/1725663c-57ef-4627-aa35-ad60b9851538" />
