### ISSUE TITLE
JupyterHub 2.0.0 has issues connecting other pods on AKS cluster 1.25+ [Connection timed out]

### ISSUE THREAD

**Issue by mananpreetsingh** [jupyterhub/zero-to-jupyterhub-k8s#3110]
### Bug description

I have an AKS cluster running on 1.26 and JupyterHub 2.0.0 deployed using helm3. Installation finishes without any error and able to log in as well. but In the Jupyterhub user pod It is not able to connect to any service endpoints in other pods, In python I try to do get responses for other service endpoints but it always timeout. If I perform the same operation in any other pod like hub pod, it works as expected. I have experienced this issue in AKS 1.25 as well but at that time we choose not to upgrade due to this bug but now old helm versions are not compatible with AKS 1.26.

#### Expected behavior

Should work as before, If we try to do a get request in python3 It should get a response rather than a timeout. 

#### Actual behavior

* Login to JH or SSH to JH user pod.
* Do a get requests.get("http://other-service-pod-url")
* I have used the following code:

```
!pip install requests

import requests

# This is a test of the nginx ingress controller endpoint.
# I tried to remove/increase timeout as well but it seems it gets timeout after around 4 minutes.
requests.get("http://10.200.3.5/healthz", timeout=300)

# this is an example of any request you can try to do to any internal service or just use pod IP
# requests.get("http://SERVICE.NAMESPACE.svc.cluster.local:3000/", timeout=300)

# This works fine
# requests.get("https://google.com", timeout=300)

```
**NOTE:** 
* If I run the same code on another Python pod either in the same NS as JH pod or run it on the Hub pod it works fine. 
* The issue only occurs in the JH user pod and also on AKS only. 
* The same setup works fine on EKS side.
* Older version of JH 1.2.0 used to work fine with the same setup.

### How to reproduce

Same as above

### Your personal setup

**Cluster**: AKS 1.26
**Jupyterhub**:  zero-to-jupyterhub 
**JupyterHub Version**: 2.0.0
Installed using helm, here is the config file:

```
hub:
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      server_address: example.ldap.okta.com
      bind_dn_template:
        - uid={username},ou=users,dc=example,dc=okta,dc=com
      valid_username_regex: ^[a-z][.a-z0-9@_-]*$

  baseUrl: /jupyterhub

proxy:
  service:
    type: ClusterIP

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  ingressClassName: internal-ingress-nginx
  hosts:
    - abc.example.com
  pathSuffix:
  pathType: ImplementationSpecific
  tls:
    - hosts:
        - abc.example.com
      secretName: aks-ingress-tls

singleuser:
  storage:
    capacity: 2Gi

```

```
# output of `pip freeze` output:
alembic==1.8.1
anyio==3.6.1
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.8
async-generator==1.10
attrs==22.1.0
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.1
bleach==5.0.1
certifi==2022.6.15.1
certipy==0.1.3
cffi==1.15.1
charset-normalizer==2.1.1
cryptography==38.0.1
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
dnspython==2.2.1
entrypoints==0.4
executing==1.0.0
fastjsonschema==2.16.1
greenlet==1.1.3
idna==3.3
importlib-metadata==4.12.0
ipykernel==6.15.2
ipython==8.5.0
ipython-genutils==0.2.0
ipython-sql==0.5.0
jedi==0.18.1
Jinja2==3.1.2
joblib==1.2.0
json5==0.9.10
jsonschema==4.16.0
jupyter-core==4.11.1
jupyter-server==1.18.1
jupyter-telemetry==0.1.0
jupyter_client==7.3.5
jupyterhub==3.0.0
jupyterlab==3.4.6
jupyterlab-pygments==0.2.2
jupyterlab_server==2.15.1
lxml==4.9.1
Mako==1.2.2
MarkupSafe==2.1.1
matplotlib-inline==0.1.6
mistune==2.0.4
nbclassic==0.4.3
nbclient==0.6.7
nbconvert==7.0.0
nbformat==5.4.0
nbgitpuller==1.1.0
nest-asyncio==1.5.5
notebook==6.4.12
notebook-shim==0.1.0
numpy==1.23.5
oauthlib==3.2.0
packaging==21.3
pamela==1.0.0
pandas==1.5.2
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
plotly==5.11.0
prettytable==3.7.0
prometheus-client==0.14.1
prompt-toolkit==3.0.31
psutil==5.9.2
psycopg2-binary==2.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
Pygments==2.13.0
pymongo==4.3.3
pyOpenSSL==22.0.0
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
python-json-logger==2.0.4
pytz==2022.2.1
pyzmq==23.2.1
requests==2.28.1
retrolab==0.3.21
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
scikit-learn==1.2.2
scipy==1.9.3
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
SQLAlchemy==2.0.12
sqlparse==0.4.4
stack-data==0.5.0
tenacity==8.1.0
terminado==0.15.0
threadpoolctl==3.1.0
tinycss2==1.1.1
tornado==6.2
traitlets==5.3.0
typing_extensions==4.5.0
urllib3==1.26.12
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.1
zipp==3.8.1
```
</details>

<details><summary>Logs</summary>

**Error thrown by Python:**

```
ConnectionError: HTTPConnectionPool(host='10.200.3.5', port=80): Max retries exceeded with url: /healthz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4f5ea8a30>: Failed to establish a new connection: [Errno 110] Connection timed out'))

```
</details>

**Comment by consideRatio** [comment]
I think this is a breaking change described a bit in the 2.0.0 changelog. If you want the user pods to be able to network with other pods, you must opt-in to that since 2.0.0.

The changelog didnt clarify that it was relevant to revise the network config if you wanted to permit this. If you want the previous behavior, you can make changes to this config.

```yaml
singleuser:
  networkPolicy:
    egressAllowRules:
      privateIPs: true
```

Changelog: https://z2jh.jupyter.org/en/stable/administrator/upgrading/upgrade-1-to-2.html#upgrade-1-2-security-breaking-change
Config reference: https://z2jh.jupyter.org/en/stable/resources/reference.html#singleuser-networkpolicy-egressallowrules-privateips

Does this resolve your issue?
