### ISSUE TITLE
`singleuser.allowPrivilegeEscalation` does not work in JupyterHub 2.0.0

### ISSUE THREAD

**Issue by mananpreetsingh** [jupyterhub/zero-to-jupyterhub-k8s#3112]
### Bug description

singleuser.allowPrivilegeEscalation = true configuration does not let me run sudo command on JH User pod. 

#### Expected behaviour

I should be able to do sudo or run sudo commands if I enable the `singleuser.allowPrivilegeEscalation = true`

#### Actual behaviour
Login to JupyterHub and open the terminal and try to run sudo command it gives error sudo not found.
![Screenshot 2023-05-09 at 2 11 40 PM](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/assets/27379172/fd7b4844-410f-4ff2-84cf-d7178c4212f9)

### How to reproduce

1. Install JH on k8 using  below config.
2. Login to Jupyter hub
3. Open the terminal
4. run any command with sudo `sudo -s` or. `sudo apt-get update`

### Your personal setup

**Cluster**: K8 1.26
**Jupyterhub**:  zero-to-jupyterhub 
**JupyterHub Version**: 2.0.0
Installed using helm, here is the config file:

```
hub:
  config:
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      server_address: example.ldap.okta.com
      bind_dn_template:
        - uid={username},ou=users,dc=example,dc=okta,dc=com
      valid_username_regex: ^[a-z][.a-z0-9@_-]*$

  baseUrl: /jupyterhub

proxy:
  service:
    type: ClusterIP

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  ingressClassName: internal-ingress-nginx
  hosts:
    - abc.example.com
  pathSuffix:
  pathType: ImplementationSpecific
  tls:
    - hosts:
        - abc.example.com
      secretName: aks-ingress-tls

singleuser:
  allowPrivilegeEscalation: true
  storage:
    capacity: 2Gi

```

<details><summary>Logs</summary>

**Error thrown by Python:**

```
/bin/sh: 9: sudo: not found
```
</details>

**Comment by manics** [comment]
`singleuser.allowPrivilegeEscalation` means your pod is _allowed_ to run escalated processes. However your singleuser image needs to be configured to allow privilege escalation.

**Comment by mananpreetsingh** [comment]
> `singleuser.allowPrivilegeEscalation` means your pod is _allowed_ to run escalated processes. However your singleuser image needs to be configured to allow privilege escalation.

I there JH official image version that I can use or do I have to build one myself? IS there any example I can look into.

**Comment by justmike1** [comment]
@mananpreetsingh 
add to that:

```yaml
singleuser:
  extraEnv: 
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
  uid: 0
```
