### ISSUE TITLE
Custom Scheduler Incompatible with Kubernetes 1.27

### ISSUE THREAD

**Issue by xrl** [jupyterhub/zero-to-jupyterhub-k8s#3128]
### Bug description

AWS EKS recently released Kubernetes 1.27 for general availability. I upgraded and today jupyterhub users were saying their singleuser notebook servers couldn't boot. The pods appeared in the correct namespace but never left Pending, no Events attached to debug or anything.

#### Expected behaviour

Notebook servers boot on 1.27.

#### Actual behaviour

Turns out the pods used a custom scheduler and that scheduler had a unrecoverable error:

```
W0530 17:41:37.219051       1 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1beta1.CSIStorageCapacity: the server could not find the requested resource
E0530 17:41:37.219068       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: the server could not find the requested resource
```

which makes sense, on Kubernetes 1.27 those APIs have been upgraded:

```
W0530 17:41:37.219051       1 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1beta1.CSIStorageCapacity: the server could not find the requested resource
E0530 17:41:37.219068       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSIStorageCapacity: failed to list *v1beta1.CSIStorageCapacity: the server could not find the requested resource
```

after manually patching the scheduler deployment to use 1.27.1:

        image: registry.k8s.io/kube-scheduler:v1.27.1

and that had another error about lease type, fixed by setting the scheduler configmap to change `endpoints` to `leases`:

```
data:         
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      resourceLock: leases # used to be endpoints
      resourceName: jupyterhub-user-scheduler-lock
      resourceNamespace: "datascience"

```

### How to reproduce

1. Use Kubernetes 1.27
2. Run the latest stable helm chart with:

	helm upgrade --install \
	  jupyter-hub jupyterhub/jupyterhub \
	  --namespace datascience  \
	  --version 2.0.0 \
	  --values config.yaml

### Your personal set up

EKS 1.27
