### ISSUE TITLE
hub.db.password perhaps not functioning

### ISSUE THREAD

**Issue by vivian-rook** [jupyterhub/zero-to-jupyterhub-k8s#3156]
hub.db.password doesn't seem to do result in attempting to use a password for mysql authentication.

```
    db:
      url: "mysql+pymysql://mysql:3306/paws?charset=utf8mb4"
      type: mysql
      password: password
      upgrade: false
```
gives:
```
2023-07-10T16:31:08.954745Z 35 [Note] Access denied for user 'paws'@'172.17.0.2' (using password: NO)
```
In the mysql db logs.

Using:
```
    db:
      url: "mysql+pymysql://root:localpassword@mysql:3306/paws?charset=utf8mb4"
      type: mysql
      upgrade: false
```

Seems to work fine.

### How to reproduce

```
git clone https://github.com/toolforge/paws.git
cd paws
git checkout be3e177849da8cdac9d3a87e9735c297b3b69843
```
(Follow the instructions in README.md for setting up minikube)
After the helm deploy, watch the mysql logs
```
kubectl  logs deployment/mysql -f
```

"(using password: NO)" Where I would hope to see "(using password: YES)"
