### ISSUE TITLE
Mount > 1 Volume

### ISSUE THREAD

**Issue by pastram-i** [jupyterhub/zero-to-jupyterhub-k8s#3175]
### Bug description

Unable to mount more than 1 volume

#### Expected behaviour

All volumes are mounted without issue.

Directory on the pod exists as:
- /
  - home
    - custom
      - {username}
      - shared
Directory on the efs exists as:
- /
  - {username}
  - {shared}

#### Actual behaviour

Each volume can be mounted independently. When both are included, the lab errors our on spawn.

### How to reproduce
See `config.yaml` example below. I have taken the suggestion on mounting a persistent-storage from [this comment](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/421#issuecomment-1044193066), which on it's own works as expected.

If you comment out `extraVolumes`, `extraVolumeMounts`, and `initContainers`, the pod spawns as expected.
If you change storage to `type: none` the pod spawns as expected.
If you run the below without changes, you are provide with the error:

> 2023-07-27T22:25:54Z [Warning] Unable to attach or mount volumes: unmounted volumes=[home], unattached volumes=[], failed to process volumes=[home]: timed out waiting for the condition

```
  storage:
    type: static
    homeMountPath: /home/custom/{username}
    static:
      pvcName: static-pvc
      subPath: "{username}"
    extraVolumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: shared-pvc
    extraVolumeMounts:
      - name: persistent-storage
        mountPath: /home/custom/shared
        # subPath: home/custom
        subPath: shared
    capacity: 5Gi
  initContainers:
    - name: nfs-fixer
      image: alpine
      securityContext:
        runAsUser: 0
      volumeMounts:
      - name: persistent-storage
        mountPath: /nfs
        # subPath: home/custom/personal/{username}
        subPath: shared
      command:
      - sh
      - -c
      - (chmod 0775 /nfs; chown -R 1000:100 /nfs) 
```

### Your personal set up
Cloud - AWS + EKS + EFS (storage)
Images - `jupyterhub/k8s-hub:3.0.0-beta.3` for `Dockerfile.hub` and `--platform=linux/arm64/v8 jupyter/minimal-notebook:2023-07-17` (Which created the `/home/custom` directory and used docker-stacks `fix-permissions`)

Not sure that any logs would be relevant in this scenario, but willing to provide on request.
