### ISSUE TITLE
Unable to access managed service with Cilium 

### ISSUE THREAD

**Issue by Ph0tonic** [jupyterhub/zero-to-jupyterhub-k8s#3187]
### Bug description

I configured a basic managed service as described here:
- https://z2jh.jupyter.org/en/stable/administrator/services.html?highlight=service#example-service

However, when accessing it I get a 504 Gateway Time-out response page and in the logs of nginx, the same error as the previously fixed issue #3167.

#### Expected behaviour

I would expect the config to work.

#### Actual behaviour

The access is broken.

### How to reproduce

1. Create GKE autopilot cluster (Dateplane V2 & kube-dns is enabled by default)
2. Install Jupyterhub

```
helm upgrade --cleanup-on-fail   --install testjupyterhub jupyterhub/jupyterhub   --namespace testjupyterhubdev   --create-namespace   --version=2.0.0   --values config.yaml
```

**Notes :**, I needed to apply fixes of #3167 to make my server able to start.

config.yaml content:
```yaml
hub:
  services:
    flask:
      url: http://hub:5000
      command:
        - /usr/local/bin/python3
        - /my-service/cli.py
  readinessProbe: # TODO: Temp fix before z2jh v3.0.0
    initialDelaySeconds: 60
  networkPolicy:
    ingress:
      - ports:
          - port: 5000
        from:
          - podSelector:
              matchLabels:
                hub.jupyter.org/network-access-hub: "true"
                hub.jupyter.org/network-access-proxy-api: "true"
                hub.jupyter.org/network-access-proxy-http: "true"
    egress: # TODO: Temp fix before z2jh v3.0.0
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: kube-system
        ports:
          - protocol: UDP
            port: 53
          - protocol: TCP
            port: 53
  service:
    extraPorts:
      - port: 5000
        targetPort: 5000
        name: flask
proxy: # TODO: Temp fix before z2jh v3.0.0
  chp:
    networkPolicy:
      egress:
        - to:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: kube-system
          ports:
            - protocol: UDP
              port: 53
            - protocol: TCP
              port: 53
singleuser:
  cloudMetadata: # TODO: Temp fix before z2jh v3.0.0
    blockWithIptables: false
  networkPolicy:
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: kube-system
        ports:
          - protocol: UDP
            port: 53
          - protocol: TCP
            port: 53
```

### Your personal set up

 - OS:
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>
```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>
                                                                                         
```
* Running on all addresses (0.0.0.0)
* Running on http://127.0.0.1:5000
[W 2023-08-10 06:22:13.355 JupyterHub app:2487] Cannot connect to managed service fastapi at http://hub:5000
```

**NGINX Logs**
```
XXX.XXX.XX.XX - - [10/Aug/2023:06:34:11 +0000] "GET /services/my-service/ HTTP/2.0" 499 0 "https://my-server.demo/hub/spawn-pending/gitlab-ctao_user-name" "Mozilla/5.0 (Windows NT 10.0 ; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0" 39 3.463 [jh-staging-system-proxy-public-http] [] 10.42.4.164:8000 0 3.463 - 42c9b28c9f04f1f4621aab5ebd6b503a                                           │
2023/08/10 06:35:13 [error] 983#983: *8439372 upstream timed out (110: Operation timed out) while reading response header from upstream, client: XXX.XXX.XX.XX, server: my-server.demo, request: "GET /services/my-service/ HTTP/2.0", upstream: "http://10.42.4.164:8000/services/my-service/", host: "my-server.demo", referrer: "https://my-server.demo/hub/spawn-pending/gitlab-ctao_user-name"
```

</details>

**Comment by consideRatio** [comment]
Can you try installing [3.0.0-beta.3.git.6268.h16086582](https://jupyterhub.github.io/helm-chart/jupyterhub-3.0.0-beta.3.git.6268.h16086582.tgz) by specifying `--version 3.0.0-beta.3.git.6268.h16086582` without any config? I see that the config you have is the config for a jupyterhub managed service combined with the workaround.

Note that the config you apply, besides a readinessProbe being delayed, is applied by default after #3167 and I'd like to see the test from that version. I don't think the readinessProbe delay should be there and have tried without it successfully.

If no config is applied successfully, you can trial this as well.

```yaml
hub:
  services:
    flask:
      url: http://hub:5000
      command:
        - /usr/local/bin/python3
        - /my-service/cli.py
  networkPolicy:
    ingress:
      - ports:
          - port: 5000
        from:
          - podSelector:
              matchLabels:
                # WARNING: This is a very stringent set of requirements
                # on what pods are allowed to access, no pod in the jupyterhub
                # chart or no user server spawned by KubeSpawner have all of these 
                # labels. You should probably instead define a new label and apply it 
                # to the pod, such as:
                # my-organization.org/network-access-my-service: "true"
                hub.jupyter.org/network-access-hub: "true"
                hub.jupyter.org/network-access-proxy-api: "true"
                hub.jupyter.org/network-access-proxy-http: "true"
  service:
    extraPorts:
      - port: 5000
        targetPort: 5000
        name: flask
```

**Comment by consideRatio** [comment]
Looking at the z2jh documented managed service example, I think the issue is that you have added two additional labels to the matchSelector. Make it like this instead:

```yaml
    ingress:
      - ports:
          - port: 5000
        from:
          - podSelector:
              matchLabels:
                hub.jupyter.org/network-access-hub: "true"
```

**Comment by Ph0tonic** [comment]
Hi,
Thank you for your feedback, so I tried to use the patched version you provided, to remove the 2 additional match selector but I still get the same error message: `Cannot connect to managed service flask at http://hub:5000`.

Here is the new config used :
```yaml
hub:
  services:
    flask:
      url: http://hub:5000
      command:
        - /usr/local/bin/python3
        - /my-service/cli.py
  networkPolicy:
    allowedIngressPorts:
      - 5000
    ingress:
      - ports:
          - port: 5000
        from:
          - podSelector:
              matchLabels:
                hub.jupyter.org/network-access-hub: "true"
  service:
    extraPorts:
      - port: 5000
        targetPort: 5000
        name: flask
```

And in Nginx I still have the following logs:
```
2023/08/10 12:42:19 [error] 1254#1254: *8794634 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 148.187.17.14, server: my-server.demo, request: "GET /services/flask/ HTTP/2.0", upstream: "http://10.42.4.148:8000/services/flask/", host: "my-server.demo"
XXX.XXX.XX.XX - - [10/Aug/2023:12:42:19 +0000] "GET /services/flask/ HTTP/2.0" 504 160 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0" 38 180.003 [jh-staging-system-proxy-public-http] [] 10.42.4.148:8000, 10.42.4.148:8000, 10.42.4.148:8000 0, 0, 0 60.001, 60.002, 60.000 504, 504, 504 6b99ab4e1047d6e004c8e961fd9e8fc1
```

**Comment by consideRatio** [comment]
@Ph0tonic is your setup functioning otherwise, allowing user servers to be accessed?

Assuming you have traffic going throuh nginx (ingress-nginx-controller pods for example, if using `ingress-nginx` helm chart), you need to ensure that pod - has the requires permissions to reach all the way. I think there are two networking flows.

1. the hub pod to reach the service, that is resolved
2. a user to reach the managed service, that isn't resolved
   - a) Users visit from outside the cluster, via nginx
   - b) nginx in turn goes to the proxy-public service / proxy pod (resolved if you have an otherwise functioning setup, label the ingress-nginx-controller pods to have proxy-public access)
   - c) the proxy pod in turn goes to the hub pod on port 5000 (resolved by label on the proxy pod already and custom rule I think)

**Comment by Ph0tonic** [comment]
Yes, in minikube default config the service is accessible through the standard adresse `IP/services/flask`.
Regarding the flows, I believe thinks to me that :
- Ingress to Service, seems OK, as I have some logs in nginx
- Service to Proxy, seems OK
- Proxy to Hub, seems OK as well, as the hub logs the request.
- Hub to managed service, seems to be blocking, no log from my flask app (which is working normally in minikube)
-

**Comment by Ph0tonic** [comment]
Hi, thank you very much for your help.
So I was able to identify the issue.
The problem is linked to the proxy's egress configuration.
#2148 added ingress rules to access the hub but nothing for egress at the proxy level.
When I manually add an egress rule to the hub with the port of my managed service then it works:
```yaml
  - ports:
    - port: 5000
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: jupyterhub
          component: hub
```

Here is the current helm config for the hub ingress netpol:
```yaml
  ingress:
    {{- with .Values.hub.networkPolicy.allowedIngressPorts }}
    # allow incoming traffic to these ports independent of source
    - ports:
      {{- range $port := . }}
      - port: {{ $port }}
      {{- end }}
    {{- end }}
...
```

And the proxy egress netpol config:
```yaml
  egress:
    # proxy --> hub
    - to:
        - podSelector:
            matchLabels:
              {{- $_ := merge (dict "componentLabel" "hub") . }}
              {{- include "jupyterhub.matchLabels" $_ | nindent 14 }}
      ports:
        - port: 8081

    # proxy --> singleuser-server
    - to:
        - podSelector:
            matchLabels:
              {{- $_ := merge (dict "componentLabel" "singleuser-server") . }}
              {{- include "jupyterhub.matchLabels" $_ | nindent 14 }}
      ports:
        - port: 8888

    {{- with (include "jupyterhub.networkPolicy.renderEgressRules" (list . .Values.proxy.chp.networkPolicy)) }}
    {{- . | nindent 4 }}
    {{- end }}
```

Here is the config added in my config file to fix the access:
```yaml
proxy:
  chp:
    networkPolicy:
      egress:
        - to:
            - podSelector:
                matchLabels:
                  app: jupyterhub
                  component: hub
          ports:
            - protocol: UDP
              port: 5000
            - protocol: TCP
              port: 5000
```

The current documentation here:
- https://z2jh.jupyter.org/en/stable/administrator/services.html
Is incomplete because it does not configure the proxy egress.

There are multiple ways to address this issue. Here are a few that I am thinking about:
1. Only update the doc to add an egress config 
2. Update the helm chart and add egress rules for all port on the hub
3. Add new settings to configure egress rules for the proxy towards the hub

I can make a PR once we have decided on the best way to go.
