### ISSUE TITLE
Full email as user name with Google OAuth

### ISSUE THREAD

**Issue by jinserk** [jupyterhub/zero-to-jupyterhub-k8s#3206]
### Bug description

When helm 2.0.0 with z2jh 3.x, Google OAuth2 works only with "username", not the full email address. However, after upgrading to helm 3.0.x with z2jh 4.0.x, it requires full email.

The problem is, when I change the username to full email address, the login name will be still truncated. In other words, when the user's email is `username@example.com`, the logged username will be `username`.

This `username` will be used for the single user's pod name, volume claims  and so on, as well as the admin page like this:
![Screenshot 2023-08-18 at 11 38 38 AM](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/assets/823222/3536e471-bebc-4f98-8bde-cc97dc7cfec7)

When I start the server from the user `username@example.com`, it doesn't use any attached claims or volumes with just the `username`. If the actual user didn't login, the admin cannot handle the user's singleuser instance at all.

**Comment by jinserk** [comment]
I just found that this is the case only for admin account. For the normal user, it just requires only `username`, not the full email address.

**Comment by consideRatio** [comment]
There is a bugfix related to this in oauthenticator, as found in z2jh 3.0.2 released a day or two ago, what version of the chart did you install exactly?

**Comment by consideRatio** [comment]
This bug relates to your config - what is your authenticator config? Do you have hosted_domain configured? The regression in oauthenticator related to a change for such config.

**Comment by jinserk** [comment]
```
│ .      __                          __                  __  __          __                                                                                                                                       │
│       / / __  __  ____    __  __  / /_  ___    _____  / / / / __  __  / /_                                                                                                                                      │
│  __  / / / / / / / __ \  / / / / / __/ / _ \  / ___/ / /_/ / / / / / / __ \                                                                                                                                     │
│ / /_/ / / /_/ / / /_/ / / /_/ / / /_  /  __/ / /    / __  / / /_/ / / /_/ /                                                                                                                                     │
│ \____/  \__,_/ / .___/  \__, /  \__/  \___/ /_/    /_/ /_/  \__,_/ /_.___/                                                                                                                                      │
│               /_/      /____/                                                                                                                                                                                   │
│                                                                                                                                                                                                                 │
│        You have successfully installed the official JupyterHub Helm chart!                                                                                                                                      │
│                                                                                                                                                                                                                 │
│ ### Installation info                                                                                                                                                                                           │
│                                                                                                                                                                                                                 │
│   - Kubernetes namespace: jupyterhub                                                                                                                                                                            │
│   - Helm release name:    jupyterhub                                                                                                                                                                            │
│   - Helm chart version:   3.0.2                                                                                                                                                                                 │
│   - JupyterHub version:   4.0.2                                                                                                                                                                                 │
│   - Hub pod packages:     See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/3.0.2/images/hub/requirements.txt                                                                                       │
│                                                                                                                                                                                                                 │
│ ### Followup links                                                                                                                                                                                              │
│                                                                                                                                                                                                                 │
│   - Documentation:  https://z2jh.jupyter.org                                                                                                                                                                    │
│   - Help forum:     https://discourse.jupyter.org                                                                                                                                                               │
│   - Social chat:    https://gitter.im/jupyterhub/jupyterhub                                                                                                                                                     │
│   - Issue tracking: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues
```
Looks the helm chart is `3.0.2`. BTW is this fixed?

```
    GoogleOAuthenticator:                                                                                
      client_id: *****************.apps.googleusercontent.com                
      client_secret: ***********************                                                            
      oauth_callback_url: https://jupyter.<company_domain>/hub/oauth_callback                                
      hosted_domain:                                                                                     
      - <company_domain>                                                                                                                                                                                                 
      login_service: Welcome!
```
As you said, I have `hosted_domain` setting. Where do I have to search for the change of this config?
