### ISSUE TITLE
extraNodeAffinity required doesn't generate the correct pod yaml

### ISSUE THREAD

**Issue by jabbera** [jupyterhub/zero-to-jupyterhub-k8s#3223]
### Bug description

The below configuration option doesn't do what one would expect and it seems like a bug.

```
singleuser:
    extraNodeAffinity:
    required:
      - matchExpressions:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: NotIn
          values: [spot]
userPods:
  nodeAffinity:
    matchNodePurpose: require
```

This generates 2 different match expressions as you can see below. If either of them match the pod is scheduled. 

```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/scalesetpriority
              operator: In
              values:
              - spot
          - matchExpressions:
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - user
```

Naively I would expect this to generate a single match expression that is the union of the two like so:

```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.azure.com/scalesetpriority
              operator: In
              values:
              - spot
            - key: hub.jupyter.org/node-purpose
              operator: In
              values:
              - user
```

I can workaround this by manually specifying the match expression in the single extraNodeAffinity but this seems to be wrong to me.

I'm running 3.0.2 on AKS 1.27.3.

**Comment by jabbera** [comment]
The following works around the issue but is ugly IMO:

```
singleuser:
  extraNodeAffinity:
    required:
      - matchExpressions:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: NotIn
          values: [spot]
        - key: hub.jupyter.org/node-purpose
          operator: In
          values:
            - user
scheduling:
  userPods:
    nodeAffinity:
      matchNodePurpose: ignore
```

**Comment by consideRatio** [comment]
I think I agree with that this is a bug, where the bug is that `matchNodePurpose=required` configuration doesn't combine with `extraNodeAffinity.required` as one would assume - requiring either rather than both.

There is probably also then a bug for `matchNodePurpose=preferred` in how it combines with `extraNodeAffinity.preferred` as well. It is probably also then a bug for user pods, core node pods, etc.

**Comment by jabbera** [comment]
As an aside I tried this (which is what I think they syntax should be and it creates an invalid pod yaml:

```
  extraNodeAffinity:
    required:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: NotIn
        values: [spot]
```
