### ISSUE TITLE
singleuser.storage.homeMountPath not working?

### ISSUE THREAD

**Issue by BlueCog** [jupyterhub/zero-to-jupyterhub-k8s#3258]
**Bug description**
When setting `singleuser.storage.homeMountPath:` to:  /opt/app-root/src  (https://z2jh.jupyter.org/en/stable/resources/reference.html#singleuser-storage-homemountpath) 

The home directory is `/opt/app-root ` (The Jupyter root dir) and not `/opt/app-root/src`. 
Note: The personal pvc of the user is mounted to `/opt/app-root/src` so this works correctly.

The issue is that when a user spawns a Notebook the users starts in `/opt/app-root` and not in `/opt/app-root/src`. 

When using older versions of the Helm Chart (v2) this was working correctly.

**Expected behaviour**
The home directory should be  /opt/app-root/src

**Actual behaviour**
The home directory is /opt/app-root

**personal set up**

- k8s (OpenShift)
- hub is installed on: ubi8-minimal:8.7-1107

Settings:

```
    storage:
      capacity: 5Gi
      dynamic:
        pvcNameTemplate: personal-claim-{username}
      homeMountPath:  /opt/app-root/src    
```
