### ISSUE TITLE
Unable to mount drives on Google GKE using the gcsfuse driver

### ISSUE THREAD

**Issue by jdbates** [jupyterhub/zero-to-jupyterhub-k8s#3261]
### Bug description

Server spawning fails when attempting to use the gcsfuse.csi.storage.gke.io driver to mount a GCS storage bucket as a shared volume in JupyterHub.

### How to reproduce

1. Create a fresh GKE cluster on Google Cloud following the steps outlined in the Z2JH guide here: https://z2jh.jupyter.org/en/stable/kubernetes/google/step-zero-gcp.html
2. Create a Google Cloud Storage bucket
3. Enable the gcsfuse driver and set up the appropriate service accounts following the steps here: https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver
4. Test the gcsfuse driver by applying the following chart in kubectl:
```
apiVersion: v1
kind: Pod
metadata:
  name: mount-test-bb
  labels:
    app: mount-test-bb
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  volumes:
  - name: gcs-vol
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: <your-bucket-name>
  serviceAccountName: <your-service-account>
  containers:
  - image: busybox
    command:
      - "/bin/sh"
      - "-c"
      - echo Success! >> /data/test.txt
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - name: gcs-vol
      mountPath: /data
  restartPolicy: Never
```
5. If the gcsfuse driver was set up correctly, you should now see a file named 'test.txt' in the GCS bucket.
6. Set up JupyterHub with the following config.yaml:
```
singleuser:
  startTimeout: 300
  storage:
    extraVolumes:
      - name: gcs-shared
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: <your-bucket-name>
            mountOptions: "implicit-dirs"
    extraVolumeMounts:
      - name: gcs-shared
        mountPath: /home/shared
  serviceAccountName: <your-service-account>
  extraAnnotations:
    gke-gcsfuse/volumes: "true"
```
7. Login - spawner will fail after 5 minutes.

#### Expected behaviour

JupyterHub should spawn a notebook with a directory mounted at /home/shared which points to the GCS bucket.

#### Actual behaviour

The Spawner will fail after 5 minutes with a couple of relevant errors:
`2023-10-28T20:40:08Z [Warning] Error: context deadline exceeded`
```
2023-10-28T20:40:08Z [Warning] Error: failed to reserve container name "notebook_jupyter-test_default_42e17b78-6c8f-4e2b-a8cc-e14971147aa7_0": name "notebook_jupyter-test_default_42e17b78-6c8f-4e2b-a8cc-e14971147aa7_0" is reserved for "1112825359e16e404bd00240402a40599273f72cf24f459c1245dc4a25aaa596"
```

Checking the logs shows that the gcsfuse sidecar container finishes mounting the drive, but the jupyter container hangs for several minutes, then exits with: 
`WARNING 2023-10-28T20:40:08Z [resource.labels.podName: jupyter-test] Error: context deadline exceeded
`, 
immediately followed by 
`WARNING 2023-10-28T20:40:08Z [resource.labels.podName: jupyter-test] Error: failed to reserve container name "notebook_jupyter-test_default_42e17b78-6c8f-4e2b-a8cc-e14971147aa7_0": name "notebook_jupyter-test_default_42e17b78-6c8f-4e2b-a8cc-e14971147aa7_0" is reserved for "1112825359e16e404bd00240402a40599273f72cf24f459c1245dc4a25aaa596"`.

Here are the contents of the two error messages in the log:
```
{
insertId: "qd8u5xf4g346b"
jsonPayload: {
apiVersion: "v1"
eventTime: null
involvedObject: {7}
kind: "Event"
lastTimestamp: "2023-10-28T20:40:08Z"
message: "Error: context deadline exceeded"
metadata: {6}
reason: "Failed"
reportingComponent: ""
reportingInstance: ""
source: {2}
type: "Warning"
}
logName: "projects/scg-datascience/logs/events"
receiveTimestamp: "2023-10-28T20:40:13.200707389Z"
resource: {2}
severity: "WARNING"
timestamp: "2023-10-28T20:40:08Z"
}
```
```{
insertId: "qd8u5xf4g346d"
jsonPayload: {
apiVersion: "v1"
eventTime: null
involvedObject: {7}
kind: "Event"
lastTimestamp: "2023-10-28T20:40:08Z"
message: "Error: failed to reserve container name "notebook_jupyter-test_default_42e17b78-6c8f-4e2b-a8cc-e14971147aa7_0": name "notebook_jupyter-test_default_42e17b78-6c8f-4e2b-a8cc-e14971147aa7_0" is reserved for "1112825359e16e404bd00240402a40599273f72cf24f459c1245dc4a25aaa596""
metadata: {6}
reason: "Failed"
reportingComponent: ""
reportingInstance: ""
source: {2}
type: "Warning"
}
logName: "projects/scg-datascience/logs/events"
receiveTimestamp: "2023-10-28T20:40:13.200707389Z"
resource: {2}
severity: "WARNING"
timestamp: "2023-10-28T20:40:08Z"
}
```
The "failed to reserve container name" error then repeats every ~10s until the spawner eventually times out and terminates.

### Your personal set up
I've encountered this same error using both GKE Standard and GKE Autopilot clusters.  In each case, I've used the default settings for both systems, with the exception of enabling workloadIdentity and the gcsfuse driver on the standard cluster (these are enabled by default on Autopilot).  Configuration settings were the same for both systems, with the exception of the need to set `cloudMetadata: blockWithIptables: false` for the Autopilot cluster (this does not appear to have any relevant effect on this issue).

### Full Logs
Full logs from the spawner pod: https://drive.google.com/file/d/1w9XX-ovmGeVKEGaqtWZYlsd7Pl-5o-wy/view?usp=sharing

**Comment by vizeit** [comment]
I have been using GCS bucket as a shared drive for a while now. You will need to include more mount options

```
"implicit-dirs,uid=1000,gid=100"
```

Also, make sure the workload identity has permission to access the bucket, ‘storage object admin’ role
You may also need the following settings

```
singleuser:
  networkPolicy:
    egressAllowRules:
      cloudMetadataServer: true
```

**Comment by jdbates** [comment]
Thank you for the help, @vizeit.  It was the networkPolicy which was the culprit; apparently the default setting were blocking the gcsfuse sidecar container from connecting with the bucket.  As a result, the sidecar never finished mounting the bucket, which in turn caused the notebook container to never finish spawning, which is what was responsible for the `context deadline exceeded` errors I was receiving.

I was able to connect successfully using:
```
singleUser:
  networkPolicy:
    enabled: false
```
Obviously this is not ideal; I'll need to figure out how to specify the exact egress rule I need (maybe just allow the IP of the bucket).  Also, the additional mountOptions ("uid=1000,gid=100") did not seem to matter for my specific use case.

This issue can be closed, since it turned out to be a configuration issue and not a bug.  However, it would be nice to have a little more documentation surrounding this, since none of the error messages I received were useful in diagnosing the problem.

**Comment by consideRatio** [comment]
@jdbates wasn't this configuration enough for you? If not, are you also using Cilium (part of GCP's dataplane v2)?

```yaml
singleuser:
  networkPolicy:
    egressAllowRules:
      cloudMetadataServer: true
```

**Comment by jdbates** [comment]
@consideRatio After further testing, it looks like just using
```
singleUser:
  networkPolicy:
    egressAllowRules:
      cloudMetadataServer: true
```
is sufficient.  As far as my environment, I'm using a GKE Autopilot cluster with whatever the default configuration is.

**Comment by jdbates** [comment]
As of right now, the following config seems to be working for me:
```
singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: latest
  cmd: null
  startTimeout: 600
  storage:
    dynamic:
      storageClass: premium-rwo
    extraVolumes:
    - name: gcs-shared
      csi:
        driver: gcsfuse.csi.storage.gke.io
        volumeAttributes:
          bucketName: scg-datascience-shared
          mountOptions: "implicit-dirs"
    extraVolumeMounts:
    - name: gcs-shared
      mountPath: /home/shared
  extraFiles:
    jupyter_notebook_config.json:
      mountPath: /etc/jupyter/jupyter_notebook_config.json
      data:
        MappingKernelManager:
          cull_idle_timeout: 3600 # default: 0
          cull_interval: 300 # default: 300
          cull_connected: true # default: false
          cull_busy: false # default: false
  serviceAccountName: gcsfuse
  extraAnnotations:
    gke-gcsfuse/volumes: "true"
  cloudMetadata:
    blockWithIptables: false
  networkPolicy:
    egressAllowRules:
      cloudMetadataServer: true
```

I'll keep an eye on this and check whether or not the "uid=1000,gid=100" mountOptions matter, but as of right now they don't seem to be affecting anything.

Also, I can't believe I didn't see the issue you had posted @vizeit - would have saved me a weeks worth of trouble if I had.  Closing this, since it's resolved and a duplicate.
