### ISSUE TITLE
Suggestion: Allow memory requirements and limits within a ProfileList without using kubespawner_override

### ISSUE THREAD

**Issue by jmunroe** [jupyterhub/zero-to-jupyterhub-k8s#3336]
I was confused recently (context https://github.com/2i2c-org/infrastructure/pull/3687) about setting memory requirements and limits when not using `profileList` and when using `profileList`. @sgibson91 steered me right to the z2jh docs and pointed out that [this](https://z2jh.jupyter.org/en/stable/jupyterhub/customizing/user-resources.html#set-user-memory-and-cpu-guarantees-limits) is the way to set memory requirements/limits:

```
singleuser:
  memory: 
    limit: 4G 
    guarantee: 4G 
```

But if I am using `profileList` , my understanding is needs to be something like

```
singleuser:
  profileList:
    - display_name: "4GB RAM"
      description: "Example for a 4GB profile"
      kubespawner_override:
        mem_guarantee: 4G
        mem_limit: 4G
```

From @sgibson91's explaination to me is that `memory: limit:` and `memory: guarantee:` are read directly as a z2jh helm chart values, whereas `kubespawner_override` and therefore `mem_guarentee` and `mem_limit` are parsed directly to the KubeSpawner python code. These are two separate GitHub repos (though connected by the helm chart), which might explain the different syntax expectations. The override means we're dropping more directly into the Python code of KubeSpawner and so that's why the syntax changes.

As pure a black box "just do this to make it work", I suppose that's fine, but it was a stumbling block for me.

### Proposed change

Given that `profileList` is a part of the z2jh helm chart, could it be extended that the following works?

```
singleuser:
  profileList:
    - display_name: "4GB RAM"
      description: "Example for a 4GB profile"
      memory: 
        limit: 4G
        guarantee: 4G 
```

It appears that the syntax is validated when I did a helm upgrade, but upon testing it, it did not appear to actually enforce that memory request on the profile.

(If this is just a misunderstanding on my part, perhaps there is no action needed at all.)
