### ISSUE TITLE
Improve the "prepopulating the home directory" section

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/zero-to-jupyterhub-k8s#335]
Currently we have kind of a hacky solution to tell people how to populate user environments with notebooks. This has been a point of confusion for a few folks now. We should make sure these instructions are clear since this is a really common step. I think we should:

1. Make sure that the instructions work well, and clarify what's going on under the hood. E.g., will this work on all docker images? What about images made with r2d?
2. Mention nbgitpuller as a possible solution for many use-cases. I think for many people this will be a better solution than baking files into the docker image.

**Comment by yuvipanda** [comment]
@choldgraf do you wanna take a shot at this?

**Comment by choldgraf** [comment]
sure - in terms of the actual commands that are up there:
```
singleuser:
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "test -f $HOME/.copied || cp -Rf /srv/app/src/. $HOME/; touch $HOME/.copied"]
```
is that technically correct? If so then I can write some clearer narrative around it, but wanna make sure that's correct
