### ISSUE TITLE
Openstack LoadBalancer

### ISSUE THREAD

**Issue by ianabc** [jupyterhub/zero-to-jupyterhub-k8s#340]
**N.B. I don't think this is an issue with zero-to-jupyterhub-k8s specifically, it's more likely to be a problem between my openstack and kubernetes installations, but I'm adding my experience here in case anyone has any insight.**

I've been trying to get JupyterHub going on Kubernetes, I was able to get things going on GCE just by following the documentation, but we have an allocation on an OpenStack installation which I'd like to use in place of GCE. I found that most things I wanted to do just worked, but there was some issue getting an external IP for the public-proxy LoadBalancer.

Here's what I've been doing...

1. Created a network + subnet in OpenStack. I had to do this as a separate step because my provider doesn't let me add a gateway to their external network (it eats up another of a small pool of public IPs). 

2. Created a kubernetes cluster (via kubespray + some terraform) - I then messed around creating deployments for a while to make sure things were working.

3. Followed the Zero-to-Juptyerhub docs up until the `helm install`

I found that I had to use Yuvi's 0.5.0 version because there was some problem with kubernetes RBAC and the v0.4 version. The install ran successfully (I think) up until the last service definition. It stays in the pending state

```
[ptty2u@manager1 ~]$ kubectl --namespace=j8s get svc
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
hub            ClusterIP      10.233.58.67    <none>        8081/TCP                     10m
proxy-api      ClusterIP      10.233.5.62     <none>        8001/TCP                     10m
proxy-http     ClusterIP      10.233.35.250   <none>        8000/TCP                     10m
proxy-public   LoadBalancer   10.233.7.251    <pending>     80:31271/TCP,443:30600/TCP   10m
```

I took a look at https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/ and as far as I can tell the problem will be with kubernetes dependence on openstack to create that load balancer. My guess is that I've either missed something in the kubernetes setup or my OpenStack provider doesn't trust me enough :-)

**Comment by manics** [comment]
@ianabc I've been following a similar process to you:
- Use kubespray with terraform and ansible to bring up a cluster on a private Openstack cloud (EMBL-EBI Embassy)
- helm install zero-to-jupyterhub off the `master` branch with `service.type: NodePort` (though I think `ClusterIP` would also work for my setup, AFAIK I don't have access to LBaaS)
- Use a kubernetes ingress controller with host-networking.

If it's helpful I can put our configs and instructions somewhere?

**Comment by yuvipanda** [comment]
Thanks for responding, @manics! The Ingress controller is what's missing here I think. Can you provide docs / put up your config somewhere?

Thanks for writing this up in a detailed fashion, @ianabc!

**Comment by ianabc** [comment]
Thanks guys, I tried changing values.yaml locally then installing _that_ chart,
```
diff --git a/values.yaml b/values.yaml
index 4616d94..0df43c6 100755
--- a/values.yaml
+++ b/values.yaml
@@ -42,7 +42,7 @@ rbac:
 proxy:
   secretToken: ''
   service:
-    type: LoadBalancer
+    type: NodePort
     labels: {}
     annotations: {}
     nodePorts:
```
This gives me running services 
```
NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
hub            ClusterIP   10.233.20.102   <none>        8081/TCP                     9m
proxy-api      ClusterIP   10.233.22.79    <none>        8001/TCP                     9m
proxy-http     ClusterIP   10.233.56.85    <none>        8000/TCP                     9m
proxy-public   NodePort    10.233.20.97    <none>        80:32561/TCP,443:30376/TCP   9m
```
but the hub pod stays in pending
```
NAME                     READY     STATUS    RESTARTS   AGE
hub-6f87944b4f-8c22k     0/1       Pending   0          9m
proxy-866db8d69d-t2hw8   2/2       Running   0          9m
```
I get the same behaviour with ClusterIP in place of NodePort. For the hub pod I get
```
$ kubectl --namespace=j8s describe pods hub-6f87944b4f-8c22k
...
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  37s (x15 over 3m)  default-scheduler  PersistentVolumeClaim is not bound: "hub-db-dir" (repeated 3 times)
```
I set up the kubespray as simply as I could (...I didn't bother adding distributed storage), I'll try to reconfigure things with distributed storage and try again.

**Comment by yuvipanda** [comment]
Yup, you need some persistent storage for the hub to store its database. Temporarily, you can disable that with:

```
hub:
  db: 
    type: sqlite-memory
```

This should allow the hub pod to launch without persistent storage. But this can't run on production - the hub will lose all knowledge of users and spawns when it restarts...

**Comment by manics** [comment]
Here's the config for our nginx ingress controller: https://github.com/openmicroscopy/kubernetes-platform/tree/19e8464a9a057a7b367d8a23a2a891f3c06de06d/ingress-nginx (there's some other details of the kubespray config in that repo too).

Currently our k8s cluster only has a single floating IP (attached to a master node) so the controller is deployed as a daemonset with a nodeSelector for master nodes only, and using hostNetwork to get access to ports 80 and 443.

Letsencrypt certs are autogenerated for the controller: `helm upgrade --install -f CONFIG.yml kube-lego stable/kube-lego`

zero-to-jupyterhub-config:
```yaml
# https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html

# Local deployment from git checkout of https://github.com/jupyterhub/zero-to-jupyterhub-k8s.git
# Commit 7e9089b46c23fc1177c17cf1bef74d137cbba2ef (v0.4-580-g7e9089b)

hub:
  baseUrl: /example/
  cookieSecret: XXXXXXXX
  db:
    type: sqlite-memory
  extraConfig: |
    # https://github.com/jupyterhub/jupyterhub/wiki/Debug-Jupyterhub
    c.JupyterHub.log_level = 'DEBUG'
    c.Spawner.debug = True

auth:
  dummy:
    password: XXXXXXXX

proxy:
  secretToken: XXXXXXXX
  service:
    type: NodePort

singleuser:
  storage:
    type: NONE

# Disable pre-puller, fails with rbac
# https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/118
prePuller:
  enabled: false

ingress:
  enabled: true
  hosts:
  - localhost
  - jupyter.EXAMPLE.org
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: 16m
    ingress.kubernetes.io/proxy-read-timeout: 3600
    ingress.kubernetes.io/proxy-send-timeout: 3600
    kubernetes.io/tls-acme: 'true'
  tls:
  - hosts:
    - "jupyter.EXAMPLE.org"
    secretName: example-tls
```

The end result should be a jupyterhub instance running at https://jupyterhub.EXAMPLE.org/EXAMPLE/
The config is intended for one-day training sessions, so we just sping up a deployment using dummy auth with a fixed password, and delete the deployment afterwards. I'm also working on a more permanent deployment using GitHub or some other OAuth provider with this helm chart, instead of our own [kubernetes manifests files](https://github.com/IDR/deployment/tree/IDR-0.4.4/ansible/kubernetes-spec/jupyterhub) which I wrote before I knew about this repo.

Remember to add a security group to give access on 80 and 443 and setup your external DNS before running all this, otherwise the letsencrypt certificate creation will fail since the `.well-known/acme-challenge` URL won't be reachable.

This is a very recent deployment, but eventually this config should be in one of our organisation repos, @openmicroscopy or @ome . Or if you think it's useful I could try and add something to the docs in this repo?
