### ISSUE TITLE
Using the pre-puller on a scalable kubernetes cluster

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterhub/zero-to-jupyterhub-k8s#345]
I've been struggling to get the pre-puller to work. This is probably down to RBAC issues that I could get to the bottom of if I tried. However when looking through how the pre-puller works I noticed that it calls a series of tasks using [helm hooks](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md).

I was wondering if anyone has any thoughts on how well this works on a kubernetes cluster which can autoscale?

I imagine the scenario where I deploy jupyterhub onto a cluster with two nodes, the image gets pre-pulled and jupyterhub gets up and running. Then some users log onto the cluster and that causes an extra two nodes to be added to the cluster by the cluster autoscaler. Do those two new nodes get the image pre-pulled also? I have a feeling the answer is no.

As a workaround for both this issue and also my general pre-pulling issues I've been using a `DaemonSet` which runs a pre-pull container as an `initContainer` and then the Google `pause` container ([original article](https://codefresh.io/blog/single-use-daemonset-pattern-pre-pulling-images-kubernetes/)). This results in the image being pulled on all nodes in the cluster, even if they are added at a later time. Using the `initContainer` and `pause` also avoids the container constantly repulling the image and restarting.

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: prepull
spec:
  selector:
    matchLabels:
      name: prepull
  template:
    metadata:
      labels:
        name: prepull
    spec:
      initContainers:
      - name: prepull
        image: docker
        command: ["docker", "pull", "{{ .Values.singleuser.image.name }}:{{ .Values.singleuser.image.tag }}"]
        volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      containers:
      - name: pause
        image: gcr.io/google_containers/pause
```

I can see some downsides, for instance a notebook may be created on the node before the pre-puller has finished causing it to be pulled twice. But over all this feels neater and more robust than the current method. I would be interested to hear from others, particularly @yuvipanda.
