### ISSUE TITLE
Config for generic OAuth2 authentication

### ISSUE THREAD

**Issue by avaranovich** [jupyterhub/zero-to-jupyterhub-k8s#348]
I am trying to configure a generic oauth2 endpoint (Azure AD) to work with Jupyter Hub.
The implementation is provided here
https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/oauth2.py

As I don't see a "generic" type to be supported in the config, I tried "custom" as follows:

```
auth:
 type: custom
  custom:
    class-name: oauthenticator.OAuthenticator
    clientId: "xxx"
    clientSecret: "xxx"
    callbackUrl: "http://host/hub/oauth_callback"
    token_url: "https://login.microsoftonline.com/tenantId/oauth2/token"
```

which leads to the following error upon the creation of the container
`File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/usr/local/lib/python3.5/dist-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/usr/local/lib/python3.5/dist-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/usr/local/lib/python3.5/dist-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/srv/jupyterhub_config.py", line 194, in &lt;module&gt;
        auth_class_name = full_class_name.rsplit('.', 1)[-1]
    AttributeError: 'NoneType' object has no attribute 'rsplit'`

Should we perhaps add an explicit oauth2 as a new type?
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/jupyterhub_config.py#L186

What is the issue with the custom type otherwise?

**Comment by avaranovich** [comment]
Figured out syntactically correct structure:

```
type: custom
  custom:
    className: 'oauthenticator.generic.GenericOAuthenticator'
    config:
      clientId: "xxx"
      clientSecret: "xxxx"
      callbackUrl: "https://mydomain.com/hub/oauth_callback"
      tokenUrl: "https://login.microsoftonline.com/xzy/oauth2/token"
      authorizeUrl: "https://login.microsoftonline.com/xyz/oauth2/v2.0/authorize"
```

I am now presented the "Sign in with GenericOauth2" button, after clicking getting "too many redirects", where the page is not getting redirected to the authorize_url

**Comment by avaranovich** [comment]
Implemented Azure AD authenticator in this fork https://github.com/oxygenanywhere/oauthenticator/blob/02b2a3b98e361474d67fe79cd27e06224b88e2e1/oauthenticator/azuread.py

**Comment by masonlr** [comment]
Do you intend to continue using the helm chart as an interface? i.e. something along the lines of the following (note also the de-indent on the `custom` field):

```
type: custom
custom:
  className: 'oauthenticator.azuread.AzureAdOAuthenticator'
  config:
    client_id: "xxx"
    client_secret: "xxxx"
    oauth_callback_url: "https://mydomain.com/hub/oauth_callback"
    token_url: "https://login.microsoftonline.com/xzy/oauth2/token"
```

**Comment by avaranovich** [comment]
Sure, I still have some things to clean up and then submit a pull request, to have Azure Auth supported

**Comment by masonlr** [comment]
When following the zero-to-juperhub-k8s approach, I'm trying to understand the point at which you need to install the latest custom/patched `oauthenticator` python module (to access this newer Azure AD authenticator). If you install `oauthenticator` within a custom docker image and then upgrade with `helm` (via this approach https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html) is this enough?

For example, we could upgrade with this mock custom image below, which has the oauthenticator/jwt dependencies installed.

```
FROM jupyter/minimal-notebook:c7fb6660d096

USER root

# python jwt is needed for oxygenanywhere/oauthenticator
# libssl-dev is needed for python jwt
RUN set -x && \
    apt-get update && \
    sudo apt-get -y install apt-utils && \
    sudo apt-get -y install apt-file && \
    sudo apt-get -y install build-essential libssl-dev libffi-dev && \
    apt-get install -y software-properties-common && \
    apt-get clean && \

RUN conda install --yes 'pip' && \
    # install custom OAuth2 handler
    git clone https://github.com/oxygenanywhere/oauthenticator.git && \
    pip install -e oauthenticator && \
    pip install jwt && \

USER $NB_USER
```

Or, do you need to somehow install the oxygenanywhere/oauthenticator `oauthenticator` version as part of the initial kubernetes jupyterhub image? (i.e. as part of the process of the initial jupyterhub install https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html).

**Comment by masonlr** [comment]
Apologies, I'm new to helm/kubernetes. My understanding is that I need to pass the hub image name and tag to `helm upgrade` when following this step https://zero-to-jupyterhub.readthedocs.io/en/latest/extending-jupyterhub.html.

For example we could add the hub image/tag to config.yaml or pass as an argument:

```
helm upgrade <YOUR_RELEASE_NAME> jupyterhub/jupyterhub --version=v0.5 -f config.yaml \
  --set hub.image.name=<IMAGE_URL>\
  --set singleuser.image.tag=<IMAGE_TAG> 
```

**Comment by avaranovich** [comment]
@masonlr, You are right, it is possible to extend a default k8s-hub image with custom authenticator or other dependencies. For instance I made an image that has Azure AD support available here
https://hub.docker.com/r/gigabit/jupyterhub/

My config looks like this

```
hub:
  #using custom Ox image
  image: 
    name: gigabit/jupyterhub
    tag: v0.5.33
  extraEnv:
    OAUTH2_TOKEN_URL: "https://login.microsoftonline.com/xxxx/oauth2/token"
    OAUTH2_AUTHORIZE_URL: "https://login.microsoftonline.com/xxx/oauth2/authorize"

....

auth:
 type: custom
  custom:
    className: 'oauthenticator.azuread.AzureAdOAuthenticator'
    config:
      client_id: "zzzz"
      client_secret: "yyy"
      oauth_callback_url: "https://mydomain/hub/oauth_callback"
      token_url: "https://login.microsoftonline.com/xxxx/oauth2/token"
      authorize_url: "https://login.microsoftonline.com/xxxx/oauth2/authorize"
```

I still need to find the way to avoid passing the environment variables, and getting all the values straight from the config section
