### ISSUE TITLE
Inconsistent memory req/lim between single-userserver and user-placeholder

### ISSUE THREAD

**Issue by dev-dsp** [jupyterhub/zero-to-jupyterhub-k8s#3539]
### Bug description

My configuration
```
singleuser:
  memory:
    limit: 1800M
    guarantee: 1800M
scheduling:
  userPlaceholder:
    enabled: true
    replicas: 4
```

Results in 
```
$ kubectl describe pod jupyter-...
Containers:
  notebook:
    Limits:
      cpu:     2
      memory:  1887436800
    Requests:
      cpu:     500m
      memory:  1887436800
---
$ kubectl describe pod user-placeholder-...

Containers:
  pause:
    Limits:
      cpu:     2
      memory:  1800M
    Requests:
      cpu:        500m
      memory:     1800M
```

So 1887436800 bytes obviously is 1800Mi(B), which is `1887,4368` M(B), so not what I've requested.
1800M is a correct notation for MB, and should result in 1800000000 bytes (~1717 MiB)

### Configuration

Z2JH 3.2.1
