### ISSUE TITLE
singleuser.extraFiles should allow for referencing secrets/configmaps 

### ISSUE THREAD

**Issue by Spazzy757** [jupyterhub/zero-to-jupyterhub-k8s#3577]
### Proposed change

Currently we have to inject some secret information into each SingleUser container (i.e ssh private keys, credential files etc), by using "extraFiles" setup this keeps all this information in plaintext and available. There should be a way to be able to store this information in a secret/configmap outside of the helm instalation 

### Alternative options

Potentially we can do this with an initContainer, however this seems slightly excessive.

### Who would use this feature?

Anybody that needs to setup a user environment to have access to external servers

### (Optional): Suggest a solution

Add a volume mount setup for the extra files that you can reference a secret or configmap. i.e

```yaml
singleuser:
  extraFiles:
    id_rsa:
      mode: 384
      mountPath: /home/jovyan/.ssh/id_rsa
      remoteRef:
         secretName: xxxx
         key: id_rsa
```
