### ISSUE TITLE
ExtraVolume and ExtraVolume for Configmap not working with singleuser

### ISSUE THREAD

**Issue by duc-dn** [jupyterhub/zero-to-jupyterhub-k8s#3579]
Hi,
I want to mount a configmap sparkmagic config to singleuser pod but it doesn't work for me.
I created a configmap file, tried to mount it into a hub pod, and found the config file of spark magic. 
However, in singleuser pod, I realized that it doesn't be mounted
singleuser in values.yaml:
```
singleuser:
  storage:
    extraVolumes:
      - name: spark-magic-config
        configMap:
          name: spark-magic-config
    extraVolumeMounts:
      - name: spark-magic-config
        mountPath: /home/config.json
        subPath: config.json
```
hub in values.yaml:
```
hub:
  extraVolumes:
    - name: spark-magic-config
      configMap:
        name: spark-magic-config
  extraVolumeMounts:
    - name: spark-magic-config
      mountPath: /home/config.json
      subPath: config.json
```

![image](https://github.com/user-attachments/assets/99e0098f-8d7a-4067-b047-3ee2e542e37c)
And I described notebook pod, it's none
![image](https://github.com/user-attachments/assets/6254e9ce-36e9-43cf-8219-5a98ba631b82)

Can you share with me some recommendations for this problem?
