### ISSUE TITLE
Z2JH 4.0.0 (JH ~5.0.0) can't handle extra managed services

### ISSUE THREAD

**Issue by dev-dsp** [jupyterhub/zero-to-jupyterhub-k8s#3608]
### Bug description

Related issue & PR in upstream:
- https://github.com/jupyterhub/jupyterhub/issues/4929
- https://github.com/jupyterhub/jupyterhub/pull/4930

---

With the default configuration including `readinessProbe.enabled`  it's now impossible to start JH whilst having a custom managed service.
Reason for that is the following infinite loops:
- start: hub Pod starts
- readinessProbe starts probing the hub, hub is not Ready until all its services are reachable
- hub launches the managed service with `"url": f"http://{get_name('hub')}:9090"`
- hub starts probing the service via HTTP because it has URL
- hub probe requests go to the K8s Service that can't forward traffic, because there are no Ready Pods
- hub Pod can't become Ready because of the managed service being unresponsive bc. ^
- hub shuts down after several retries; goto start

### How to reproduce

```
hub:
    service:
        extraPorts:
          - name: my-service
            port: 9090
            targetPort: 9090
    readinessProbe:
        enabled: true # default
    extraFiles:
        my_service.py:
            mountPath: /usr/local/etc/jupyterhub/my_service.py
            stringData: |
                ...
    extraConfig:
        MyService: |
            c.JupyterHub.services.append({
                "name": "my-service",
                "url": f"http://{get_name('hub')}:9090",
                "command": [sys.executable, "/usr/local/etc/jupyterhub/my_service.py"]
            })
    networkPolicy:
        ingress:
          - ports:
              - port: 9090
            from:
              - podSelector:
                    matchLabels:
                        app: jupyterhub

proxy:
    service:
        type: ClusterIP
    chp:
        networkPolicy:
        egress:
          - ports:
              - port: 9090
            to:
              - podSelector:
                    matchLabels:
                        component: hub
```
