### ISSUE TITLE
Make Pod-level security context configurable in Helm chart

### ISSUE THREAD

**Issue by wtripp180901** [jupyterhub/zero-to-jupyterhub-k8s#3632]
### Proposed change

Security contexts can generally be set at the container level but not at the pod level. It would be nice to have this be configurable in the Helm chart

### Alternative options

I've been using Helm post-renderers to work around this

### Who would use this feature?

I'm trying to run Jupyter in a restricted namespace and some of the controls require securityContexts to explicitly set values at the pod level. I don't believe there is anything in zero-to-jupyterhub which actually needs to violate any of the restricted controls, so having these be configurable would allow Jupyter to run in restricted namespaces and provide more security guarantees

**Comment by consideRatio** [comment]
There are many pods associated with a few different kinds of workloads - for what workload are you looking to configure the Pods' securityContext?

Example workloads:
- hub
- proxy
- jupyter-username (user server pods)

**Comment by radhupr** [comment]
Hi, I have similar issue.
I want to set security Context for singleuser instance pods (eg: Selinuxoptions) and currently there is no way to configure this in the helm chart. Would be helpful to have the securityContext configurable for all the pods created by the helm chart rather than adding it through new policies/ exceptions in our cluster.

**Comment by benz0li** [comment]
@radhupr Use the following [values](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/0eabc0a547dbba4dc671baa7553de071b2d048c9/jupyterhub/values.yaml) for [Pod Security Standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/) _Restricted_:

```yaml
jupyterhub:
  hub:
    ...
    extraConfig:
      containerSecurityContext: |
        c.KubeSpawner.container_security_context = {
          'capabilities': {
            'drop': ['ALL']
          },
            'allowPrivilegeEscalation': False
        }
 
...
 
  singleuser:
    ...
    extraPodConfig:
      securityContext:
        ...
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
```
