### ISSUE TITLE
AzureAD auth question

### ISSUE THREAD

**Issue by radhupr** [jupyterhub/zero-to-jupyterhub-k8s#3639]
I was using the below config for azure AD auth setup for the implementation
OAUTH_CLIENT_ID

```
hub:
  config:
    AzureAdOAuthenticator:
     client_id: XXXXX
      client_secret: YYYY
```

I wanted to avoid this and read the values from a secret , hence tried to setup using ENV vars as below:
```
hub:
  extraEnv:
    OAUTH_CLIENT_ID: XXXX
    OAUTH_CLIENT_SECRET: YYY
```

But this doesnt seem to work. Is there anything I'm missing here?

**Comment by benz0li** [comment]
@radhupr Cross references:

* https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1875
* https://kubernetes.io/docs/concepts/configuration/secret/
  * https://kubernetes.io/docs/tasks/configmap-secret/
  * https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data

**Comment by benz0li** [comment]
@radhupr Regarding https://github.com/rocker-org/rocker-versioned2/issues/888#issuecomment-2800104336:

If you got it working, please post the solution here.

This will help others who encounter the same problem.

On behalf of the *general public*: Thank you.

**Comment by radhupr** [comment]
It worked as in the initial question itself.
Full code for reference 
```
extraEnv:
    OAUTH_CLIENT_ID:
      valueFrom:
        secretKeyRef:
          key: client-id
          name: azure-oauth
    OAUTH_CLIENT_SECRET:
      valueFrom:
        secretKeyRef:
          key: client-secret
          name: azure-oauth
  config:
    AzureAdOAuthenticator:
      oauth_callback_url: https://jupyterhub.domain.com/hub/oauth_callback
      tenant_id: XX-XXX-XXX
      allow_all: false
      admin_groups:
        - XXX-XXXX  #group-id-1
        - YYY-YYYY   #group-id-2
      allowed_groups:
        - XXX-XXXX  #group-id-1
        - YYY-YYYY   #group-id-2
      manage_groups: true
      scope: ["openid", "profile", "email", "User.Read", "GroupMember.Read.All"]
    JupyterHub:
      authenticator_class: azuread
```
