### ISSUE TITLE
Align singleuser resource configuration keys with k8s defaults for 5.x release

### ISSUE THREAD

**Issue by samyuh** [jupyterhub/zero-to-jupyterhub-k8s#3679]
## Problem
Currently, resource limits and guarantees for single-user pods are configured using custom keys in the Helm chart:

```yaml
singleuser.cpu:
  limit: ...
  guarantee: ...

singleuser.memory:
  limit: ...
  guarantee: ...
```

While functional, this deviates from the standard Kubernetes resource configuration schema. To improve clarity and align with Kubernetes best practices, I propose we adopt the native resource format:

```yaml
resources:
  requests:
    cpu: ...
    memory: ..
  limits:
    cpu: ...
    memory: ...
```

## Rationale
- Follows Kubernetes conventions, making it more intuitive for users.
- Improves transparency and predictability of resource allocation.

It’s unclear if the current custom structure was introduced for a specific reason. If so, feel free to close this issue. If not, we should consider deprecating the current structure and transitioning to the standard format.

This would be a breaking change, so we should only introduce it in the `5.x` release.
