### ISSUE TITLE
Support pulling multiple singleuser images

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/zero-to-jupyterhub-k8s#376]
I'd like to be able to conditionally associate some users with alternative singleuser images. I can configure the hub's config to use them in extra config, but I can't configure the pre-puller to pull them.

**Comment by consideRatio** [comment]
## I'd also like that, so its investigation time!

__`pre-puller.yaml`__ - The kubernetes Job doing the work
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pull-all-nodes-{{ .Release.Time.Seconds }}-{{.Release.Name}}-{{.Release.Revision}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.rbac.enabled }}
      serviceAccountName: pre-puller-{{.Release.Name}}-{{.Release.Revision}}
      {{- end }}
      containers:
        - image: {{ .Values.prePuller.image.name }}:{{ .Values.prePuller.image.tag }}
          args: [{{ .Values.singleuser.image.name | quote }}, {{ .Values.singleuser.image.tag | quote }}]
          name: all-nodes-puller
```

__`values.yaml`__ - The docker image doing the work
```yaml
prePuller:
  enabled: true
  image:
    name: yuvipanda/image-allnodes-puller
    tag: v0.8
```

__`yuvipanda/image-allnodes-puller`__ - The docker image source
1. Docker hub - https://hub.docker.com/r/yuvipanda/image-allnodes-puller/tags/
2. GitHub repo - https://github.com/yuvipanda/kube-image-puller/tree/master/pull-allnodes
3. GitHub issue - https://github.com/yuvipanda/kube-image-puller/issues/5

---

## Conclusions

1. Update [the allnodes.sh file](https://github.com/yuvipanda/kube-image-puller/blob/master/pull-allnodes/allnodes.sh) to allow for multiple images
2. Allow for additional args to be provided in the `pre-puller.yaml` template through `values.yaml`.
```yaml
prePuller:
  enabled: true
  image:
    name: yuvipanda/image-allnodes-puller
    tag: v0.8
  # extraImagesToPull example: ["jupyter/r-notebook", "2c80cf3537ca", "jupyter/datascience-notebook", "2c80cf3537ca"]
  extraImagesToPull: []
```

---

I'm off to bed!
