### ISSUE TITLE
Github Organization as whitelist in config.yaml

### ISSUE THREAD

**Issue by twanito** [jupyterhub/zero-to-jupyterhub-k8s#382]
I am wanting to whitelist members of a github organization (be it a team within the organization or the whole organization). I have seen that this is possible using standard Jupyterhub but am not sure how to go about it using just the k8s version. I've read through docs and comments [here](https://github.com/jupyterhub/oauthenticator/pull/58) and am not sure how to do the same using the config.yaml file. Any help or direction appreciated!

## Contents of `config.yaml`
```
proxy:
  secretToken: "SOMESECRET"
  https:
    hosts:
      - SOMEDOMAINNAME
    letsencrypt:
      contactEmail: SOME@EMAIL.COM
singleuser:
  image:
    name: SOME/IMAGE
    tag: latest
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "test -f $HOME/.copied || cp -Rf /srv/app/src/. $HOME/; touch $HOME/.copied"]
  memory:
    limit: 3G
    guarantee: 3G
  cpu:
    limit: 1
    guarantee: 0.4
  storage:
    type: none
  initContainers:
    - name: block-metadata
      image: minrk/tc-init:0.0.4
      # Block access to GCE Metadata Service from user pods
      command: ["iptables", "-A", "OUTPUT", "-p", "tcp", "-d", "SOMEIP", "-j", "DROP"]
      securityContext:
        runAsUser: 0
        capabilities:
          add: [ "NET_ADMIN" ]
auth:
  admin:
    users:
      - twanito
  whitelist:
    users:
      - twanito
  type: github
  github:
    clientId: "SOMECLIENTIDE"
    clientSecret: "SOMECLIENTSECRET"
    callbackUrl: "https://SOMEDOMAINNAME/hub/oauth_callback"
```
