### ISSUE TITLE
If pre-puller fails with an non-existent singleuser image cleanup is difficult

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#425]
Testing on minikube with rbac enabled (`minikube start --extra-config=apiserver.Authorization.Mode=RBAC`)
Commit: 4124b39269328ff82037f706330d580a86e5007c (includes https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/399)

Set `singleuser.image` to an invalid value, e.g. `nonexistent/nonexistent-image` (in practice this could occur due to a typo)

If the prepuller fails the helm chart is not created:
```
$ helm install --name jupyter ./jupyterhub/ -f my-configs/minikube-local.yaml
Error: timed out waiting for the condition

$ helm list
$
```

However some Kubernetes resources are already created which aren't cleaned up, causing a second attempt to fail:
```
$ helm install --name jupyter ./jupyterhub/ -f my-configs/minikube-local.yaml
Error: clusterroles.rbac.authorization.k8s.io "pre-puller-jupyter-1" already exists

$ for k in ClusterRole Role ClusterRoleBinding RoleBinding ServiceAccount Job Pod; do echo $k && kubectl get $k | cut -d\  -f1 |grep pre-puller; done
ClusterRole
pre-puller-jupyter-1
Role
pre-puller-jupyter-1
ClusterRoleBinding
pre-puller-jupyter-1
RoleBinding
pre-puller-jupyter-1
ServiceAccount
pre-puller-jupyter-1
Job
pre-puller-1516285401-jupyter-1
Pod
pre-puller-1516285401-jupyter-1-l2fr4
```

It is necessary to manually `kubectl delete` each of the above resources before rerunning helm with a corrected config.
```
$ for k in ClusterRole Role ClusterRoleBinding RoleBinding ServiceAccount Job Pod; do kubectl delete $k $(kubectl get $k | cut -d\  -f1 |grep pre-puller); done
```

This isn't intuitive. I tried changing `helm.sh/hook-delete-policy` to `hook-succeeded,hook-failed` in https://github.com/manics/zero-to-jupyterhub-k8s/commit/f971c80df721967c1df26a5b14ce097c6849ba11 but only the Job and Pod were deleted:
```
$ for k in ClusterRole Role ClusterRoleBinding RoleBinding ServiceAccount Job Pod; do echo $k && kubectl get $k | cut -d\  -f1 |grep pre-puller; done
ClusterRole
pre-puller-jupyter-1
Role
pre-puller-jupyter-1
ClusterRoleBinding
pre-puller-jupyter-1
RoleBinding
pre-puller-jupyter-1
ServiceAccount
pre-puller-jupyter-1
Job
No resources found.
Pod
```

If there's no solution perhaps this should be made clear in the docs?

config:
```
proxy:
  secretToken: XXXXXXXXXX
  service:
    type: NodePort
    nodePorts:
      http: 31212

hub:
  cookieSecret: XXXXXXXXXX
  db:
    type: sqlite-memory
  extraConfig: |
    c.JupyterHub.log_level = 'DEBUG'
    c.Spawner.debug = True

singleuser:
  storage:
    type: none
  memory:
    guarantee: null
  image:
    name: nonexistent/nonexistent
```
