### ISSUE TITLE
prePuller doesn't understand noschedule taint

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/zero-to-jupyterhub-k8s#454]
In the pre-puller, we only check for the `unschedulable: true` spec to see if a daemonset will get scheduled there. This accounts for cordoned nodes, but not for tainted nodes.

We should check for:

```
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    timeAdded: null
    value: "true"
```

as well in the pre-puller.
