### ISSUE TITLE
Failed to apply default image tag "None:None": couldn't parse image reference "None:None": invalid reference format: repository name must be lowercase

### ISSUE THREAD

**Issue by summerswallow** [jupyterhub/zero-to-jupyterhub-k8s#472]
I'm trying to deploy a docker image I build verabtim from 
https://github.com/jupyterhub/zero-to-jupyterhub-k8s

I build the image:
`docker build k8s-hub`
I tag and push the image to AWS, ECS

I modify the config.yaml file to deploy it.
```
hub:
  image:
    name: xxxx.dkr.ecr.us-west-2.amazonaws.com/k8s-hub
    tag: latest-official
proxy:
  \# output of second execution of 'openssl rand -hex 32'                                                                                                          
  secretToken: "xxxx"

cull:
  enabled: false
```

When I run it, the hub fails to start,

I get the following log when I do a `kubectl describe pod hub-xxxx`
```Normal SuccessfulMountVolume 2m kubelet, ip-10-2-255-232.us-west-2.compute.internal MountVolume.SetUp succeeded for volume "pvc-032f7515-078e-11e8-ae10-024c438ab7fa"

Warning InspectFailed 4s (x11 over 2m) kubelet, ip-10-2-255-232.us-west-2.compute.internal Failed to apply default image tag "None:None": couldn't parse image reference "None:None": invalid reference format: repository name must be lowercase

Warning Failed 4s (x11 over 2m) kubelet, ip-10-2-255-232.us-west-2.compute.internal Error: InvalidImageName```

Any ideas? I did not modify anything out of the repo. Thanks

**Comment by summerswallow** [comment]
I forgot to mention. It only goes into this state when I try to start a server via the UI.

**Comment by choldgraf** [comment]
Latest dockerfile section for reference:

http://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html#use-an-existing-docker-image


3 quick things:
1. I think it's a typeo, but just to double check, you need `singleuser:` before the line with `image:`. That's in your config.yaml file right?
2. Can you show what's in the Dockerfile you used to create that image?
3. So everything works fine, but when you try to "start your server" that's when the problems start yes?

**Comment by summerswallow** [comment]
1) I did not add any singleuser: to my config.yaml line I was relying on the default values.yaml 
I didn't need it when I when I when through the reference example in the docs

2) https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/Dockerfile

No modifications. I understand this is latest not v0.5.0

3) Yes. It shows Crash backoff status

**Comment by choldgraf** [comment]
try adding the `singleuser:` line above `image:`, it should have the same structure as the example shown in the docs: http://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html#use-an-existing-docker-image

**Comment by summerswallow** [comment]
Same result. Still doesn't
```Warning  InspectFailed          1m (x11 over 2m)  kubelet, ip-10-2-255-232.us-west-2.compute.internal  Failed to apply default image tag "None:None": couldn't parse image reference "None:None": invalid reference format: repository name must be lowercase
  Warning  Failed                 1m (x11 over 2m)  kubelet, ip-10-2-255-232.us-west-2.compute.internal  Error: InvalidImageName
```
when I `kubectl describe pod jupyter-user`
Note that this is the error generate by the singleuser node not by the hub even though the only difference is the hub image I'm running.

**Comment by choldgraf** [comment]
can you again paste the contents of `config.yaml`? Any time you change your `config.yaml` file copy/paste all the contents in a code cell exactly as-is...otherwise it's quite difficult to debug

**Comment by choldgraf** [comment]
also is your docker image public? if so can you paste the link to that? (e.g. `xxxx.dkr.ecr.us-west-2.amazonaws.com/k8s-hub` but without the `xxxx` in there)

**Comment by summerswallow** [comment]
The config.yaml file is complete with the redactions.

Unfortunately the repo is not public.

**Comment by choldgraf** [comment]
> The config.yaml file is complete with the redactions.

Please just paste the actual content of the `config.yaml` file - oftentimes there are small errors in the written `yaml` and it's better to see the raw text to confirm that it's correct.

Regarding the image, can you try pushing to a public dockerhub image and using that in your `config.yaml` file?

**Comment by summerswallow** [comment]
How do I post the file. I get an error in github with We don't support that file type.

**Comment by yuvipanda** [comment]
Heya @summerswallow! It looks like your YAML is not valid/complete YAML, which makes it harder for us to help. http://www.yamllint.com/ is a useful tool to check if your YAML is valid or not. It might be a copy paste mistake? Am unsure!

What are you using to setup the cluster on AWS? The z2jh instructions with the heptio quickstart or something else?

Can you ssh into one of the nodes and try to docker pull from ECR? That might also be one of the problems.

**Comment by choldgraf** [comment]
`config.yaml` is the text file you use to configure kubernetes - in your original post you had these contents:

```
  image:
    name: xxxx.dkr.ecr.us-west-2.amazonaws.com/k8s-hub
    tag: latest-official
proxy:
  \# output of second execution of 'openssl rand -hex 32'                                                                                                          
  secretToken: "xxxx"

cull:
  enabled: false
```

and we identified an original problem that `singleuser:` wasn't in there. Can you now post the updated contents of `config.yaml`? Thanks!

**Comment by summerswallow** [comment]
Valid YAML.
Heptio quickstart for existing VPC

**Comment by summerswallow** [comment]
```hub:
  image:
    name: 801867477713.dkr.ecr.us-west-2.amazonaws.com/k8s-hub
    tag: latest-official
proxy:
  # output of second execution of 'openssl rand -hex 32'                                                                                                          
  secretToken: "690bbf90b774e158806bf17c6fabe3fde1ce52cc31c4921000adaa12028b5351"
singleuser:
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: v0.5.0

cull:
  enabled: false
```

**Comment by summerswallow** [comment]
I took the singleuser section out of the values.yaml for v0.5.0

**Comment by summerswallow** [comment]
I don't think it is a problem with pulling the image from ECR. My custom ks8-hub runs. I get an authentication screen. When it trys to spin up the server, the error I get is from the node.

**Comment by choldgraf** [comment]
the image specified in `singleuser:` is pulled onto the node the first time a person starts their server, so it sounds like what is happening is that the image isn't properly configured in `config.yaml` and the error only comes up when jupyterhub attempts to pull the image.

You should remove the first `image: name: tag:` section from your config.yaml...can you do that and re-paste the contents of `config.yaml`?

**Comment by summerswallow** [comment]
This yaml file runs fine:
```
proxy:
  secretToken: "690bbf90b774e158806bf17c6fabe3fde1ce52cc31c4921000adaa12028b5351"
```

**Comment by choldgraf** [comment]
try the same with this in your config.yaml file:

```
proxy:
  # output of second execution of 'openssl rand -hex 32'                                                                                                          
  secretToken: "690bbf90b774e158806bf17c6fabe3fde1ce52cc31c4921000adaa12028b5351"
singleuser:
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: v0.5.0
```

**Comment by summerswallow** [comment]
Sorry the hub: at the top of the pasted yaml files were missing. Bad cut and paste

**Comment by summerswallow** [comment]
Not cut and paste. I'm not use to this markdown. The hub: was hidden.

**Comment by choldgraf** [comment]
I don't think you want to be modifying the `hug: image:` - that's the image for jupyterhub itself and generally shouldn't be changed if you're just figuring out how to deploy your own jupyterhub on kubernetes

**Comment by summerswallow** [comment]
I'm customizing the authentication. The external customization currently available are not sufficient.

But before I start any heavy lifting I want to figure out how to deploy a hub image.

**Comment by summerswallow** [comment]
The modified yaml file works, but it doesn't include the desired hub image.

**Comment by choldgraf** [comment]
ah - I'm curious why you wish to modify the hub image? Your best bet for officially-supported authentication are the configurations listed here:

https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html

you shouldn't need to modify your hub image in order to get those to work...or are you attempting to write a new authenticator?

**Comment by summerswallow** [comment]
Couple. One is internally designed. A second to support SAML

**Comment by summerswallow** [comment]
And yes I looked at the link first.

**Comment by choldgraf** [comment]
cool - so to use a specific hub image, you need your config to be:

```
proxy:
  # output of second execution of 'openssl rand -hex 32'                                                                                                          
  secretToken: "690bbf90b774e158806bf17c6fabe3fde1ce52cc31c4921000adaa12028b5351"
singleuser:
  image:
    name: jupyterhub/k8s-singleuser-sample
    tag: v0.5.0
hub:
  image:
    name: jupyterhub/k8s-hub
    tag: v0.6
```
that will use the default jupyterhub hub image, so if you want to use a different image, the *only* thing you should replace are the `name:` and `tag:` sections.
