### ISSUE TITLE
Need way to set custom resource limits

### ISSUE THREAD

**Issue by dholt** [jupyterhub/zero-to-jupyterhub-k8s#510]
Is there a way, or could there be a way, to submit custom resource limits to the notebook pod via the Helm chart? This is needed to specify a number of GPUs to attach; for example:

```
singleuser:
  image:
    name: dholt/jupyterhub-k8s-gpu
    tag: v0.6
  extraEnv:
    - JUPYTER_ENABLE_LAB: 1
  resources:
    limits:
      nvidia.com/gpu: 1
  nodeSelector:
    gpu: "true"
```

**Comment by clkao** [comment]
This can be done with `c.KubeSpawner.extra_resource_limits`, but there's no z2jh configmap wrapper for that. You'd need to `extraConfig` for now.

**Comment by yuvipanda** [comment]
@willingc I'm going to keep this particular one open, since I think we should expose this through the chart.

**Comment by willingc** [comment]
Sure thing @yuvipanda. To make sure that I understand correctly, support KubeSpawner resource limits, such as GPU, directly in helm chart.

**Comment by naeemkhan12** [comment]
@clkao  would you like to elaborate how to achieve this with `c.KubeSpawner.extra_resource_limits`

**Comment by yuvipanda** [comment]
For example, you'd set:

```yaml
hub:
   extraConfig:
      10-gpu: |
          c.KubeSpawner.extra_resource_limits = { 'nvidia.com/gpu': 1 }
```

**Comment by choldgraf** [comment]
@yuvipanda do we have this behavior documented somewhere? Would be useful to show people this pattern until it's officially in the chart

**Comment by yuvipanda** [comment]
@choldgraf https://zero-to-jupyterhub.readthedocs.io/en/latest/advanced.html#arbitrary-extra-code-and-configuration-in-jupyterhub-config-py maybe?

**Comment by consideRatio** [comment]
I think I've initialized the resource limits to {} if it wasn't already in a kubespawner PR associated with #758 - we could encourage the use of `.update`
```yaml
hub:
  extraConfig:
    10-gpu: |
      c.KubeSpawner.extra_resource_limits.update({ 'nvidia.com/gpu': 1 })
```
