### ISSUE TITLE
If auth.whitelist.users is non-empty GitHub orgs are ignored

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#521]
Expected behaviour: If `auth.whitelist.users` is a non-empty list and `auth.github.org_whitelist` from https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/501 is set users should be able to login if they're in `auth.whitelist.users` or if they're a member of `auth.github.org_whitelist`

Observed behaviour: If `auth.whitelist.users` is a non-empty `auth.github.org_whitelist` is ignored

## Relevant config
```
auth:
  whitelist:
    users:
    - nonexistent-dummy-user
  type: github
  github:
    clientId: "CLIENT_ID"
    clientSecret: "CLIENT_SECRET"
    callbackUrl: "http://10.0.17.150.xip.io/hub/oauth_callback"
    org_whitelist:
    - idr-contrib
```
I'm a public member of [`idr-contrib`](https://github.com/idr-contrib)

`kubectl logs -f deploy/hub`:
```
[D 2018-02-21 12:04:36.986 JupyterHub proxy:552] Proxy: Fetching GET http://10.233.51.203:8001/api/routes
[I 2018-02-21 12:04:54.382 JupyterHub oauth2:82] OAuth redirect: 'http://10.0.17.150.xip.io/hub/oauth_callback'
[I 2018-02-21 12:04:54.383 JupyterHub log:122] 302 GET /hub/oauth_login?next= → https://github.com/login/oauth/authorize?redirect_uri=http%3A%2F%2F10.0.17.150.xip.io%2Fhub%2Foauth_callback&client_id=[CLIENT_ID]&response_type=code&state=[STATE]%3D%3D&scope=read%3Aorg (@134.36.162.197) 1.19ms
[W 2018-02-21 12:04:56.019 JupyterHub auth:249] User 'manics' not in whitelist.
[W 2018-02-21 12:04:56.019 JupyterHub base:351] Failed login for unknown user
[D 2018-02-21 12:04:56.020 JupyterHub base:633] No template for 403
[W 2018-02-21 12:04:56.024 JupyterHub log:122] 403 GET /hub/oauth_callback?code=5da9f5ee26ede539c294&state=[STATE]%3D%3D (@134.36.162.197) 1250.62ms
[D 2018-02-21 12:04:56.285 JupyterHub log:122] 304 GET /favicon.ico (@134.36.162.197) 0.65ms
```

Originally reported in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/501#issuecomment-367311371
