### ISSUE TITLE
Pressing "Access Server" as admin leads to ones personal account

### ISSUE THREAD

**Issue by mrocklin** [jupyterhub/zero-to-jupyterhub-k8s#525]
When diagnosing a user's issue I log into the hub/admin page and press the "Access Server" button next to their account name.  Instead of being taken to their account I am taken to my own.

## Contents of `config.yaml`

    --version=v0.6.0-9701a90

```
proxy:
  secretToken: SECRET

singleuser:
  image:
    name: daskdev/pangeo-notebook
    tag: 2018-02-14
  cmd: ['start-singleuser.sh']
  extraEnv:
    EXTRA_PIP_PACKAGES: >-
    GCSFUSE_BUCKET: pangeo-data
  storage:
    extraVolumes:
      - name: fuse
        hostPath:
          path: /dev/fuse
    extraVolumeMounts:
      - name: fuse
        mountPath: /dev/fuse
  cpu:
    limit: 2
    guarantee: 1
  memory:
    limit: 4G
    guarantee: 2G


# proxy:
#   https:
#     hosts:
#       - pangeo.pydata.org
#     letsencrypt:
#       contactEmail: mrocklin@gmail.com

auth:
  type: github
  github:
    clientId: "2cb5e09d5733ff2e6ae3"
    clientSecret: "SECRET"
    callbackUrl: "http://pangeo.pydata.org/hub/oauth_callback"
  admin:
    access: true
    users:
      - mrocklin
      - jhamman
      - rabernat
      - yuvipanda
      - choldgraf

rbac:
  enabled: false

hub:
  extraConfig: |
    c.KubeSpawner.singleuser_service_account = 'default'
    c.Spawner.default_url = '/lab'
    from kubernetes import client
    def modify_pod_hook(spawner, pod):
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
        )
        return pod
    c.KubeSpawner.modify_pod_hook = modify_pod_hook

cull:
  enabled: true
  users: false
  timeout: 3600
  every: 600
```
