### ISSUE TITLE
Support for NetworkPolicy ingress/egress

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#534]
I'm interested in using a singleuser pod [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) to limit egress. The use-case I have in mind is providing a public but very locked-down jupyterhub deployment to give people a taster with minimal barriers, and to provide full access behind a second authenticated deployment.

I found a related discussion on https://github.com/jupyterhub/mybinder.org-deploy/issues/146 and can see pros and cons to including it in this chart:
- Configuring everything in zero-to-jupyterhub-k8s is very convenient
- A NetworkPolicy is very specific to a deployment, and can be applied outside the chart since the pod labels are known

If you think it's worthwhile here's a proposal:
```
singleuser:
  networkPolicy:
    ingress:
      - List of ingress rules from https://kubernetes.io/docs/concepts/services-networking/network-policies/
    egress:
      - List of egress rules from https://kubernetes.io/docs/concepts/services-networking/network-policies/
```
applied to
```
  podSelector:
    matchLabels:
      app: jupyterhub
      component: singleuser-server
```
