### ISSUE TITLE
Labels and Selectors - a common practice within the templates

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#538]
#### Related issue: #615

---

I was about to make set labels and selectors for a StatefulSet I tried out, and wanted to mimic what had been done for other k8s object templates, but did not find a clear pattern.

So, I'd like to figure out a practice to follow within the guide.
- What labels do we declare?
- What are important labels within a selector?

```yaml
metadata:
  name: proxy
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: proxy
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: proxy
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
```

I'd like to discuss the following labels:
- chart, app, component, heritage, release

### My take
- I recommend we don't use the `chart` label, or is there a benefit to including that?
- I recommend we select on few labels in a minimalistic manner, perhaps only component or component and release is needed? What can go wrong by including / not including various labels?

Perhaps something like below?

#### The labels we declare on controllers
- [x] chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
- [x] app: jupyterhub
- [x] component: hub
- [x] release: {{ .Release.Name }}
- [x] heritage: {{ .Release.Service }}

#### The important labels within a selector and a controllers pod template
- [ ] chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
- [x] app: jupyterhub
- [x] component: hub
- [x] release: {{ .Release.Name }}
- [ ] heritage: {{ .Release.Service }}
