### ISSUE TITLE
How to configure jupyterhub-k8s pvc to use ceph

### ISSUE THREAD

**Issue by moskiGithub** [jupyterhub/zero-to-jupyterhub-k8s#577]
I configure ceph cluster as pvc of jupyterhub-k8s, the jupyter docker throws error:
Warning   FailedMount   kubelet, ip-10-0-58-63.ap-southeast-1.compute.internal   MountVolume.SetUp failed for volume "pvc-81d53fb4-2699-11e8-af36-06a45990210c" : CephFS: mount failed: mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/81d86df3-2699-11e8-af36-06a45990210c/volumes/kubernetes.io~cephfs/pvc-81d53fb4-2699-11e8-af36-06a45990210c --scope -- mount -t ceph -o name=kubernetes-dynamic-user-81ef691d-2699-11e8-bb7d-0a586013a,secret=AQBajaAA7eOnPlR7LI5gG3sEtt7y== 10.0.10.112:6789:/volumes/kubernetes/kubernetes-dynamic-pvc-81ef68d3-2699-11e8-bb7d-0a586460013a /var/lib/kubelet/pods/81d86df3-2699-11e8-af36-06a45990210c/volumes/kubernetes.io~cephfs/pvc-81d53fb4-2699-11e8-af36-06a45990210c
Output: Running scope as unit run-rf6411478a9b348c5a1716841365e5056.scope.
mount: 10.0.10.112:6789:/volumes/kubernetes/kubernetes-dynamic-pvc-81ef68d3-2699-11e8-bb7d-0a586460013a: can't read superblock

The configure file: 
```
proxy:
  secretToken: "3d5b83d0906b9737015d2bfbe81d012d509ff38a4d6f049bd547c9dc773sevbc"

singleuser:
  image:
    name: jupyter/tensorflow-notebook
    tag: latest
  storage:
    dynamic:
      storageClass: cephfs
    fsType: ext4
    capacity: 8Gi

```
