### ISSUE TITLE
Persist notebooks in local storage when using minikube

### ISSUE THREAD

**Issue by prcastro** [jupyterhub/zero-to-jupyterhub-k8s#661]
Hi,

I'm getting started with this tutorial and testing everything locally before deploying the kubernetes cluster in the cloud. For that, I'm using minikube (with RBAC) and I got JupyterHub (I can access the hub, create notebook servers with the specified docker image, etc).

However, every time I stop my notebook server all data is lost. I wanted to store the notebook files locally so that I can stop the server and recover the files the next time I start it.

## Contents of `config.yaml`
```
proxy:
  secretToken: ...
  service:
    type: NodePort
    nodePorts:
      http: 31212

hub:
  cookieSecret: ...
  db:
    type: sqlite-memory

singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: 9f9e5ca8fe5a
  storage:
    type: local-storage
  memory:
    guarantee: null

prePuller:
  hook:
    enabled: false
```
 
This was based on `minikube-config.yaml` on this repo, but changing the storage type in`singleuser` key, since the original value wasn't working. I also tried simply erasing the entire `storage` key from my config, without luck.
