### ISSUE TITLE
user $HOME environment not created

### ISSUE THREAD

**Issue by miramar-labs** [jupyterhub/zero-to-jupyterhub-k8s#662]
first, when I open a terminal I see this:

groups: cannot find name for group ID 2001

then I notice that files I create in the $HOME folder belong to the jovyan user....

Q: do I have this configured right? If I am logging in as user 'bob' I would expect to see bob's $HOME folder and files in there belonging to bob ..... instead I see:

jovyan@jupyter-bob:~$
-rw-r--r--. 1 jovyan 2001 0 Apr 23 23:07 welcome.txt

seems like a proper user $HOME env for bob isn't being created?

**Comment by choldgraf** [comment]
could you share your `config.yaml` file you've used to configure the jupyterhub? thanks!

**Comment by miramar-labs** [comment]
ansible template: ```proxy:
    secretToken: "{{_jhub_secret_token}}"
ingress:
    enabled: true
    hosts:
     - {{_jhub_ingress}}
singleuser:
  lifecycleHooks:
    postStart:
      exec:
        command: ["touch", "welcome.txt"]
  image:
    name: jupyter/all-spark-notebook
    tag: latest
  defaultUrl: "/lab"
  extraEnv:
    EDITOR: "vim"
  storage:
    dynamic:
      storageClass: gluster-sc
    capacity: 1Gi
  memory:
    limit: 1G
    guarantee: 1G
  cpu:
    limit: .5
    guarantee: .5
auth:
  type: google
  google:
    clientId: "324965136003-565usb3edmk5jn690b1r3h612fsqrlbm.apps.googleusercontent.com"
    clientSecret: "cpLJJrGK0YUQ6l9fcIdsbGNh"
    callbackUrl: "https://{{_domain}}/hub/oauth_callback"
    hostedDomain: "{{_domain}}"
    loginService: "Aaron's Data Science Lab"
hub:
  extraEnv:
    JUPYTER_ENABLE_LAB: 1
  extraConfig: |
    c.KubeSpawner.cmd = ['jupyter-labhub']```

**Comment by miramar-labs** [comment]
## Contents of `config.yaml`
```
proxy:
    secretToken: "{{_jhub_secret_token}}"
ingress:
    enabled: true
    hosts:
     - {{_jhub_ingress}}
singleuser:
  lifecycleHooks:
    postStart:
      exec:
        command: ["touch", "welcome.txt"]
  image:
#    name: registry.lan.aaroncody.com:5000/jupyter/ds-all
    name: jupyter/all-spark-notebook
    tag: latest
  defaultUrl: "/lab"
  extraEnv:
    EDITOR: "vim"
  storage:
    dynamic:
      storageClass: gluster-sc
    capacity: 1Gi
  memory:
    limit: 1G
    guarantee: 1G
  cpu:
    limit: .5
    guarantee: .5
auth:
  type: google
  google:
    clientId: "324965136003-565usb3edmk5jn690b1r3h612fsqrlbm.apps.googleusercontent.com"
    clientSecret: "cpLJJrGK0YUQ6l9fcIdsbGNh"
    callbackUrl: "https://{{_domain}}/hub/oauth_callback"
    hostedDomain: "{{_domain}}"
    loginService: "Aaron's Data Science Lab"
hub:
  extraEnv:
    JUPYTER_ENABLE_LAB: 1
  extraConfig: |
    c.KubeSpawner.cmd = ['jupyter-labhub']
```
