### ISSUE TITLE
How to add some files in user home?

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/zero-to-jupyterhub-k8s#664]
Hi

I'd like to add a welcome message to the user, and I would like it to be at his home (something like ~/.welcome-msg). It is printed when the use use the terminal and probably in a near welcome splashscreen plugin if I manage to find time to do it.

Today I have to burn the message inside the docker image, which is not very convenient. How I can send somes files from my config.yaml and have it added into the user's home directory (either as .dotfiles or even in a dot-folder with a mount volume somehow, that would be great!)

**Comment by consideRatio** [comment]
@gsemet I have a similar need and is quite happy about my solution. I want to provide updated content to all my users. My solution is to provide the following chart values under `singleuser.storage` in my `config.yaml`.
```yaml
      extraVolumes:
        - name: getting-started
          gitRepo:
            repository: https://github.com/consideRatio/jupyter-se-getting-started.git
      extraVolumeMounts:
        - name: getting-started
          mountPath: /home/jovyan/jupyter-se-getting-started
          subPath: jupyter-se-getting-started
```
