### ISSUE TITLE
Support SSL offloading to AWS ELB

### ISSUE THREAD

**Issue by pcfens** [jupyterhub/zero-to-jupyterhub-k8s#675]
Rather than terminating SSL in the application, we've traditionally terminated on the load balancer in AWS.

With one small change (and some perhaps creative use of the config file fed to helm), we're able to make this work. I'm happy to submit a PR, but I'm not sure how the maintainers would like to structure it, so I'm starting here.

Our sanitized config.yaml file looks like
```yaml
---
hub:
  image:
    name: wmit/jupyterhub-k8s-hub-casauth
    tag: v0.6
  extraConfig: |
    import jhub_cas_authenticator.cas_auth
proxy:
  secretToken: REDACTED
  https:
    enabled: true
    type: ACM
    hosts: jupyterhub.example.edu
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:1234567891011:certificate/uuid"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
auth:
  type: custom
  custom:
    className: jhub_cas_authenticator.cas_auth.CASAuthenticator
    config:
      cas_login_url: https://cas.example.edu/cas/login
      cas_service_url: https://jupyterhub.example.edu/login
      cas_service_validate_url: https://cas.example.edu/cas/p3/serviceValidate # Requires CAS 5
  admin:
    users:
      - user1
```

Helm creates a service with an exposed HTTPS port, while the additional annotations ensure that it's a TCP listener (so that websockets continue to work). The annotations also attach an SSL certificate that's managed outside of k8s.

To actually make things work, I change the HTTPS target port in the proxy-public service to match the HTTP target port (`kubectl --namespace=kube-system edit svc proxy-public`).

Thoughts on how we might add this to the existing chart?
