### ISSUE TITLE
Use of imagePullSecrets has no effect

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#676]
Based on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/447#issuecomment-386706464, various online resources as well as my understanding of z2jh, Kubernetes and Azure AKS documentation, I tried to introduce a value for the `imagePullSecret` key in my `config.yaml`. However, all attempts (`hub.extraConfig`, `imagePullSecrets.name`, `singleuser.image.imagePullSecrets.name` - I have removed the latter since) have resulted in no positive effect and relevant Azure Container Registry (ACR) authentication error. Below is my current Helm configuration. Any help will be much appreciated.

```
hub:
  cookieSecret: "***"
  extraConfig:
    c.KubeSpawner.singleuser_image_pull_secrets = "ACR_SECRET_NAME"

proxy:
  secretToken: "***"

prePuller:
  hook:
    enabled: true

imagePullSecrets:
  name: ACR_SECRET_NAME

rbac:
  enabled: false

auth:
  type: github
  github:
    clientId: "***"
    clientSecret: "***"
    callbackUrl: "http://***/hub/oauth_callback"
    org_whitelist:
      - "***"
    scopes:
      - "read:org"

singleuser:
  image:
    name: ***.azurecr.io/datascience-octave-notebook
    tag: v1
```
