### ISSUE TITLE
403 errors with github auth whitelist

### ISSUE THREAD

**Issue by rsignell-usgs** [jupyterhub/zero-to-jupyterhub-k8s#684]
I'm just capturing this github auth 403 whitelist problem in case other folks deploying find it useful, if I did something incorrect, or if this behavior is unexpected.  

On our JH instance at pangeo.esipfed.org, we initially were whitelisting users via the `auth: admin` section in `jupyter-config.yaml`, which makes them `admin` users, and that worked fine -- people on this list had no problem logging in.    

```
  auth:
    admin:
      access: true
      users:
        - jreadey
        - rsignell-usgs

    type: github
    github:
      clientId: "SECRET"
      clientSecret: "SECRET"
      callbackUrl: "http://pangeo.esipfed.org/hub/oauth_callback"
      org_whitelist:
        - "HDFGroup"
        - "pangeo-data"
        - "USGS-CMG"
    scopes:
      - "read:org"
```
I then decided to add `org_whitelist:` entries, and after this Helm upgrade, people who logged out to got 403 errors when they tried to log back in.  
Looking at the logs for the hub pod:
```
helm list
kubectl get pods -n esip-dev 
kubectl -n esip-dev logs hub-5647fc9dcd-m86gx
```
revealed that it said "User rsignell-usgs is not in org whitelist" even though I was listed as an admin, and also was a member of a whitelisted org.    

When I went to confirm my membership in the org on github, I saw that my membership in the org was "private", and when I switched it to "public":
![2018-05-15_9-31-54](https://user-images.githubusercontent.com/1872600/40059741-e7242a9c-5822-11e8-86f3-0213d37ebed2.png)
I was able to finally login.

Originally reported on pangeo as https://github.com/pangeo-data/pangeo/issues/256#issue-323220095
