### ISSUE TITLE
Expected behavior with org_whitelist ?

### ISSUE THREAD

**Issue by rsignell-usgs** [jupyterhub/zero-to-jupyterhub-k8s#687]
With ` jupyter-config.yaml` auth set up as:
```
  auth:
    admin:
      access: true
      users:
        - jreadey
        - rsignell-usgs

    type: github
    github:
      clientId: "SECRET"
      clientSecret: "SECRET"
      callbackUrl: "http://pangeo.esipfed.org/hub/oauth_callback"
      org_whitelist:
        - "HDFGroup"
        - "pangeo-data"
        - "ESIPFed"
        - "USGS-CMG"
    scopes:
      - "read:org"
```
I find that members of the above organizations, unless they are public, get challenged with:
![pangeo_err](https://user-images.githubusercontent.com/1872600/40131774-e83376c2-5908-11e8-96ef-5815d3718b90.jpg)
![pangeo_err2](https://user-images.githubusercontent.com/1872600/40131781-eac17ef2-5908-11e8-9081-c01de69e5b2a.jpg)

Is that expected, even though `auth.scopes` is `read:org`?

**Comment by choldgraf** [comment]
Specifically, are you concerned that the message is asking it to be able to modify organization data, as opposed to being read-only?

**Comment by rsignell-usgs** [comment]
I'm concerned that is involves getting a manager of the organization involved to approve, even though they've been whitelisted, but I guess there is no way around that if their group setting is set to private?

**Comment by rsignell-usgs** [comment]
@betatim, interesting!  I'll try that out and report back.

**Comment by manics** [comment]
It's related to the permissions set on the GitHub organisation. Under `Organization settings` `Third-party access` admins can optionally restrict access to third party applications in which case you'll see the `Request approval` button

**Comment by choldgraf** [comment]
So it sounds like this is something that needs configuring at the organization level _within github_ as opposed to within jupyterhub?

**Comment by betatim** [comment]
Is this something we can/should document in the ["User management" section](https://zero-to-jupyterhub.readthedocs.io/en/latest/user-management.html)?

**Comment by manics** [comment]
GitHub OAuth scopes are just very confusing! I thought I understood them but after changing my JupyterHub config a couple weeks ago and running into this problem (and also a problem with private org memberships, not sure if this is a bug that somehow crept in) I'm now pretty lost.

It would be good to test and document exactly what works. I think there are at least three factors which contribute to the confusion:
- public vs private membership of a GitHub organisation
- third party access policies on the GitHub organisation
- which auth scopes are useful out of: none, `read:user`, `read:org`
- owner of the Application (If the OAuth client belongs to an org it might be able to see org stuff).

**Comment by choldgraf** [comment]
@manics if you'd like to, just give a shot with each one and write down the general results of each test, and I am happy to put together a docs PR explaining it in more verbose detail etc. Would that work?

**Comment by manics** [comment]
@choldgraf It's the testing that's complicated, once the results are known updating the doc is easy :-). I'm wondering whether we could simplify things- instead of covering all combinations thoroughly test and document just two configs:
- public org membership, no scope (this definitely works)
- private org membership, scope `read:user` (sounds likes @rsignell-usgs has this working, I'll also test this when I get a chance)

And for everything else link to this issue or a community wiki?

**Comment by choldgraf** [comment]
I think that's fair: if `read:user` will work regardless of whether their membership is public, we can just recommend this. Then we can link to this issue or the github scopes page for more info.

**Comment by rsignell-usgs** [comment]
Actually, from my tests we need both both user and org scopes set for this to work, e.g:
```
    scopes:
      - "read:org"
      - "read:user
```
I just reconfirmed that setting `read:user` only is not sufficient.  Here's the relevant part of my working `jupyter-config.yaml`: 
```
   ...
  auth:
    admin:
      access: true
      users:
        - jreadey
        - rsignell-usgs

    type: github
    github:
      clientId: "SECRET"
      clientSecret: "SECRET"
      callbackUrl: "http://pangeo.esipfed.org/hub/oauth_callback"
      org_whitelist:
        - "HDFGroup"
        - "pangeo-data"
        - "ESIPFed"
        - "USGS-CMG"
    scopes:
      - "read:org"
      - "read:user"

  proxy:
    secretToken: "SECRET"
```
