### ISSUE TITLE
Bug (pre v0.7): Prepuller never finish

### ISSUE THREAD

**Issue by kalugny** [jupyterhub/zero-to-jupyterhub-k8s#735]
## Contents of `config.yaml`
```
proxy:
  secretToken: <REMOVED>
singleuser:
  image:
    name: <MY IMAGE ON gcr.io>
    tag: <TAG>
  defaultUrl: "/lab"
  https:
    hosts:
      - <MY HOST>
    letsencrypt:
      contactEmail: <MY EMAIL>
  extraEnv:
    HOME: "/home"
cull:
  enabled: false
hub:
  extraEnv:
    JUPYTER_ENABLE_LAB: 1
  extraConfig: |
    c.KubeSpawner.cmd = ['jupyter-labhub']
auth:
  type: google
  google:
    clientId: <ID>
    clientSecret: <SECRET>
    callbackUrl: <URL>
    hostedDomain: <DOMAIN>
    loginService: <NAME>
  admin:
    users:
      users:
        - <USERNAME>
```

I have two node pools in my cluster, one for "regular" and one for "high-mem" nodes.
When `install`ing or `update`ing, the DaemonSet pods finish pulling the images, but the prepuller job keeps logging:
```
E  2018/06/25 14:24:20 2 of 2 images pulled in node gke-cr-default-pool-4d2e4c64-n8k4
E  2018/06/25 14:24:20 1 of 2 images pulled in node gke-cr-default-pool-4d2e4c64-zwx7
```
Ad infinum.

**Comment by kalugny** [comment]
It seems that a work-around is to delete the prerunner Job and the the installation continues

**Comment by consideRatio** [comment]
This bug is fixed in 0.7 versions of the chart. I recall documenting a temporary workaround somewhere until an upgrade is made... Hmmm... #477, #502?

Ah well I suggest the quickest solution: disable the hook pre-puller and you will avoid it malfunctioning. The option is to clear a lot of docker images on the nodes. You could do this manually by sshing into the nodes i think, or delete the nodes and add them again.

```yaml
# in your config.yaml somewhere, you can disable the hook pre-puller
prePuller:
  hook:
    enabled: true
```

I'll spend a lot of time towards a 0.7 release from today onwards.
