### ISSUE TITLE
Organization-based GitHub authentication not working

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#741]
I might be missing something or doing something wrong, but it seems that relevant value in `config.yaml` configuration file for Helm has no expected effect on GitHub-based authentication. Here is how relevant section looks in my configuration file:

```
auth:
  type: github
  github:
    clientId: "<ID>"
    clientSecret: "<SECRET>"
    callbackUrl: "<URL>"
    org_whitelist:
      - "<MY_ORG>"
    scopes:
      - "read:org"
```

I have also tried documentation-recommended `read:user` scope, but it had the same effect of allowing any GitHub user to be able to authenticate and use our JupyterHub instance. I was expecting that access to the instance would be limited to users, belonging to defined set of white-listed organizations (in this case, only MY_ORG, for now). However, this is not happening. As always, your help / advice will be much appreciated.

**Comment by ablekh** [comment]
@consideRatio Thank you for the hint. I forgot to search existing issues in this repo (both open and closed). Just searched and only discovered #687. Which is interesting, but still is not helpful in terms of the solution.

**Comment by betatim** [comment]
I have a few hubs running with the following:
```yaml
  auth:
    type: github
    github:
      callbackUrl: "https://example.com/hub/oauth_callback"
      org_whitelist:
        - "wildtreetech"
    scopes:
      - "read:user"
```
and as far as I can tell that works :-/ Will double check.
