### ISSUE TITLE
Authentication via CILogon throws error when logging in with Github, Google

### ISSUE THREAD

**Issue by prkriz** [jupyterhub/zero-to-jupyterhub-k8s#767]
As per the instructions at https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#cilogon:

## Contents of `config.yaml`
```
auth:
  type: cilogon
  cilogon:
    clientId: "myproxy-----/client_id/----{masked}----"
    clientSecret: "z_WC----{masked}----apA"
    callbackUrl: "https://my.jupyterhub.site/hub/oauth_callback"
```
Signing in with University (UIUC Netid) works fine, but authentication via Google, Github, etc. throws *Internal Server Error: Failed to get username from CILogon*.

Current CILogon scopes: [email, edu.uiuc.ncsa.myproxy.getcert, openid, profile, org.cilogon.userinfo]

This might be related to caveats mentioned at https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/cilogon.py, not sure how to address this when setting up via K8S/helm chart.
