### ISSUE TITLE
urllib3.exceptions.MaxRetryError

### ISSUE THREAD

**Issue by Eagles2F** [jupyterhub/zero-to-jupyterhub-k8s#812]
## Contents of `config.yaml`
```
proxy:
  secretToken: xxxx
  service:
    type: NodePort
    nodePorts:
      http: 31212

hub:
  cookieSecret: xxxx
  db:
    type: sqlite-memory
  extraConfig: |
    c.JupyterHub.ssl_key='/root/214871478970384.key'
    c.JupyterHub.ssl_cert='/root/214871478970384.pem'

singleuser:
  storage:
    type: none
  memory:
    guarantee: null

prePuller:
  hook:
    enabled: false
```
Hi I've successfully installed Jupyterhub using Helm, but after I open the hub and login, I got error like this:
```
 urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='172.19.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/jupyterhub/pods?labelSelector=heritage%3Djupyterhub%2Ccomponent%3Dsingleuser-server (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))
```

Any idea how to resolve this issue?
