### ISSUE TITLE
Helm pre-puller v0.6 upgrade cleanup instructions

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#815]
I want to help the chart users cleanup the pre-puller pods by deleting the following resources created by the v0.6 prePuller logic.
- [x] [DaemonSet](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/64348a7d7d3c2372c354f1d7c74c4d9635ea874e/jupyterhub/templates/pre-puller/_helpers.yaml)
- [x] [RBAC resources](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/64348a7d7d3c2372c354f1d7c74c4d9635ea874e/jupyterhub/templates/pre-puller/rbac.yaml)
  - ServiceAccount
  - Role
  - RoleBinding
  - ClusterRole
  - ClusterRolebinding
- [x] [Job](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/64348a7d7d3c2372c354f1d7c74c4d9635ea874e/jupyterhub/templates/pre-puller/job.yaml)

## Deleting the DaemonSets
It can be quite easy to delete the DaemonSet resources as they have labels declared on them
```yaml
  # How we identify the DaemonSet!
  labels:
    app: jupyterhub
    component: image-puller
    release: {{ .top.Release.Name }}
    heritage: {{ .top.Release.Service }}
```
```bash
# Delete the orphaned DaemonSets - you can make a trial run by replacing `delete` with  `get` first
kubectl delete daemonsets --namespace <NAMESPACE> --selector app=jupyterhub,component=image-puller
```

## Deleting the RBAC and Job resources
The RBAC resources and the Job resources are a lot tougher though, they must be identified without labels available. I can imagine doing this in various ways...

1. Write a script that gathers all information, filters, then run a delete on the filtered resources
2. Delete all resources of the kind within the namespace, but we cannot do this for the ClusterRole and ClusterRoleBinding as they are not namespaced, they cover all namespaces, the full cluster.
3. We manage to target deletion of the resources based on the absence of labels
4. We ask the person upgrading to manually delete all these resources

```yaml
metadata:
  name: pre-puller-{{ .Release.Time.Seconds }}-{{.Release.Name}}-{{.Release.Revision}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
```
