### ISSUE TITLE
Minimal singleuser NetworkPolicy prevents access to server

### ISSUE THREAD

**Issue by manics** [jupyterhub/zero-to-jupyterhub-k8s#823]
Blocking all singleuser NetworkPolicy egress apart from the minimal requirements in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/bd39858411209dbdae852afe57a5f08eb1571d58/jupyterhub/templates/singleuser/netpol.yaml used to work:
```yaml
singleuser:
  networkPolicy:
    enabled: true
    egress:
```
With the latest version the singleuser server starts, but hangs at `Server ready at /jupyterhub-itr/user/a25cbb62-b7a2-4ea7-9e84-18bfd9e16a77/`

Enabling access to `10.0.0.0/8` allows it to work
```yaml
singleuser:
  networkPolicy:
    enabled: true
    egress:
      - to:
        - ipBlock:
            cidr: 10.0.0.0/8
```
I haven't tested network policies for a few months, I'll see if I can figure out what's changed.

**Comment by manics** [comment]
```shell
$ kubectl -n ome-sl-test get pods -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{range $k,$v:=.metadata.labels}}{{"\t"}}{{$k}}={{$v}}{{"\n"}}{{end}}{{"\n"}}{{end}}'
hub-854784d4d4-wqjhc
        app=jupyterhub
        component=hub
        hub.jupyter.org/network-access-proxy-api=true
        hub.jupyter.org/network-access-proxy-http=true
        hub.jupyter.org/network-access-singleuser=true
        pod-template-hash=4103408080
        release=ome-sl-test

jupyter-a25cbb62-2db7a2-2d4ea7-2d9e84-2d18bfd9e16a77
        app=jupyterhub
        chart=jupyterhub-v0.7-92ccb36
        component=singleuser-server
        heritage=jupyterhub
        hub.jupyter.org/network-access-hub=true
        release=ome-sl-test

proxy-67b4f867b8-pfwjm
        app=jupyterhub
        component=proxy
        hub.jupyter.org/network-access-hub=true
        hub.jupyter.org/network-access-singleuser=true
        pod-template-hash=2360942364
        release=ome-sl-test
```

```shell
$ kubectl -n ome-sl-test get netpol singleuser-network-policy -o yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  creationTimestamp: 2018-08-07T12:22:22Z
  generation: 1
  labels:
    app: jupyterhub
    chart: jupyterhub-v0.7-92ccb36
    component: singleuser
    heritage: Tiller
    release: ome-sl-test
  name: singleuser-network-policy
  namespace: ome-sl-test
  resourceVersion: "12267832"
  selfLink: /apis/extensions/v1beta1/namespaces/ome-sl-test/networkpolicies/singleuser-network-policy
  uid: 8969e1e3-9a3c-11e8-b6c3-0050569c3e37
spec:
  egress:
  - ports:
    - port: 8081
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: jupyterhub
          component: singleuser
          release: ome-sl-test
  ingress:
  - from:
    - podSelector:
        matchLabels:
          hub.jupyter.org/network-access-singleuser: "true"
    ports:
    - port: 8888
      protocol: TCP
  podSelector:
    matchLabels:
      app: jupyterhub
      component: singleuser-server
      release: ome-sl-test
  policyTypes:
  - Ingress
  - Egress
```
`spec.egress[].to[].podSelector.matchLabels.component: singleuser` is incorrect, the component should be `hub`

This can be fixed by patching the network policy:
```
cat << EOF > singleuser-network-policy-patch.yaml
spec:
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: jupyterhub
              component: hub
              release: ome-sl-test
      ports:
        - protocol: TCP
          port: 8081
EOF
kubectl -n ome-sl-test patch netpol singleuser-network-policy --patch "$(cat singleuser-network-policy-patch.yaml)"
```

@consideRatio This is the change that refactored the labels: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/5bfa3ac143623cc79337f69673ede0d5fadcf842#diff-eab17051a02f45b7f17c0217673a7b06R28
Do you have an idea of how best to fix it? I've looked at `templates/_helpers.tpl` but can't see a nice way to change it.

**Comment by consideRatio** [comment]
My investigation

## Values.yaml
- No recent changes to `singleuser.networkPolicy`
- No recent changes to `hub.networkPolicy`
- No recent changes to `proxy.networkPolicy`
- `.Values.singleuser.networkPolicy` only consumed by singleuser `netpol.yaml`

## hub/netpol.yaml 
- Did not notice anything

## proxy/netpol.yaml
I think I found two changes of potential impact here!
- See: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/6b6a9914a5bf7f7ad43da41af833e42c279f643b#diff-8b10c1f85bd2d20fb93ebe21f4cc7122

1. A logic fail on Line 3
2. The netpols spec.podSelector.matchLabels may have changed in a faulty manner because of the exception kube-lego introduce with the `app: kube-lego` label.

---

Oh you have also replied lets read :D

**Comment by consideRatio** [comment]
Aha sorry this is me @manics.

From singleuser/netpol.yaml

```yaml
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "jupyterhub.matchLabels" . | nindent 14 }}
```

This should be whats written in the helm template if it should be `hub` rendered there.
```
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- $_ := merge (dict "componentLabel" "hub") . }}
              {{- include "jupyterhub.matchLabels" $_ | nindent 14 }}
```
