### ISSUE TITLE
azurefile storageclass requires specific mountOptions for sqlite3 db locking

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/zero-to-jupyterhub-k8s#827]
Azure was having trouble attaching the hub-db-dir disk properly so I thought I'd try using azurefile.
```
hub:
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      storageClassName: azurefile
```

I found that if you don't edit edit the azurefile storageclass mountOptions, sqlite3 database locking will break and the hub won't start. This will also affect singleuser storage if users want to use sqlite3 or other things that use locking.

I ran `kubectl -n name edit storageclass azurefile` and added 
```
mountOptions:
- dir_mode=0755
- file_mode=0600
- uid=1000
- gid=1000
- mfsymlinks
- nobrl
```

Without uid/gid, /srv/jupyterhub gets owned by root. nobrl fixes the sqlite3 locking behavior. file_mode=0600 is required for the cookie secret.

Suggested text for the Azure instructions:
> If you use azurefile storageclass for either the hub db or singleuser storage, consider setting the following:

and then the mountOptions above.

Relevant: https://github.com/andyzhangx/demo/blob/master/pv/storageclass-azurefile-mountoptions.yaml
