### ISSUE TITLE
gitlab auth failed. 404 error.

### ISSUE THREAD

**Issue by chenyg0911** [jupyterhub/zero-to-jupyterhub-k8s#839]
I try to use gitlab as auth provider.
gitlab runs on 192.168.0.165:80, 
jupyterhub access URL(throuth nodePort) :http://192.168.0.185:30080
user created on gitlab. and enable oauth:
```
Application Id | 1bf0ccd8708f9ac10e16dc1e27630f72f7e0f8d00ee9def1e9ae2a17f1e23318
-- | --
Secret: | 3892aebd11523a72345a3024a0b93099132dff81f3ef745c9918192bc7649d2a
Callback url | http://192.168.0.185:30080/hub/oauth_callback
Scopes | api (Access the authenticated user's API)   read_user (Read the authenticated user's personal information)
```

config the jupyterhub through helm, config.yaml as below:
```
proxy:
  secretToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
  service:
    nodePorts:
      http: 30080
      https: 30443

auth:
  admin:
    users:
      - adminuser1
  type: gitlab
  gitlab:
    clientId: "1bf0ccd8708f9ac10e16dc1e27630f72f7e0f8d00ee9def1e9ae2a17f1e23318"
    clientSecret: "3892aebd11523a72345a3024a0b93099132dff81f3ef745c9918192bc7649d2a"
    callbackUrl: "http://192.168.0.185:30080/hub/oauth_callback"
...
hub:
  extraEnv:
    GITLAB_HOST: "192.168.0.165"
```

But, when click the hub page button "Sign in with Gitlab", got a 404 error.
check the hub pod log in k8s:
```
[I 2018-08-13 08:12:24.919 JupyterHub log:158] 200 GET /hub/login (@10.233.97.128) 63.63ms
[I 2018-08-13 08:12:28.883 JupyterHub oauth2:82] OAuth redirect: 'http://192.168.0.185:30080/hub/oauth_callback'
[I 2018-08-13 08:12:28.886 JupyterHub log:158] 302 GET /hub/oauth_login?next= -> 192.168.0.165/oauth/authorize?redirect_uri=http%3A%2F%2F192.168.0.185%3A30080%2Fhub%2Foauth_callback&client_id=1bf0ccd8708f9ac10e16dc1e27630f72f7e0f8d00ee9def1e9ae2a17f1e23318&response_type=code&state=[secret] (@10.233.97.128) 3.24ms
[W 2018-08-13 08:12:28.928 JupyterHub log:158] 404 GET /hub/192.168.0.165/oauth/authorize?redirect_uri=http%3A%2F%2F192.168.0.185%3A30080%2Fhub%2Foauth_callback&client_id=1bf0ccd8708f9ac10e16dc1e27630f72f7e0f8d00ee9def1e9ae2a17f1e23318&response_type=code&state=[secret] (@10.233.97.128) 15.83ms
```
hub images:
```
  image:
    name: jupyterhub/k8s-hub
    tag: a3fab36
```

what's the problem?Does I should change a newer images?
