### ISSUE TITLE
Accessing the JupyterHub api

### ISSUE THREAD

**Issue by odewahn** [jupyterhub/zero-to-jupyterhub-k8s#84]
Can you provide an example of how to access the JupyterHub API, especially which credential is required (i.e., of the two in the config.yaml file).  I've tried many vairiations (using httpie) and get something like this:

```
$ http http://jupyterhub.odewahn.com/hub/api/users 'Authorization: token 1dfa277014fac9f3d054e203325e8e44c80432c8c8f8bfafd8f2ac1603c3458d'

HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 39
Content-Security-Policy: frame-ancestors 'self'; report-uri /hub/security/csp-report
Content-Type: application/json
Date: Wed, 07 Jun 2017 19:53:46 GMT
Server: nginx/1.10.0 (Ubuntu)

{
    "message": "Forbidden", 
    "status": 403
}
```

**Comment by yan130** [comment]
Hi, I have the same issue with you, I fix it by adding the following to jupyterhub_config:

c.JupyterHub.proxy_api_ip = xxxx
c.JupyterHub.proxy_api_port = xxx
c.JupyterHub.proxy_auth_token = '1dfa277014fac9f3d054e203325e8e44c80432c8c8f8bfafd8f2ac1603c3458d'
c.JupyterHub.api_tokens = {'1dfa277014fac9f3d054e203325e8e44c80432c8c8f8bfafd8f2ac1603c3458d' : 'my-user-name'}

I know the token is kind of duplicate and you don't need to have your username when you call "api/users", so in theory you don't need the the last config (c.JupyterHub.api_tokens)

However,  without the last config it is not working.

**Comment by frouzbeh** [comment]
@odewahn Hi, have you been able to fix your issue? I'm seeing the same problem even though I set the api token in config.yaml. 
@consideRatio can you explain it more? I need to access to hub api from every jupyterlab instances I have on kubernetes cluster and I don't know how it's possible.

**Comment by consideRatio** [comment]
@frouzbeh I have not done it myself, I'd need to read up a bit to learn this.

This is a way to get credentials to access it as an admin at least. But, perhaps you already have non-admin credentials, coupled to the specific user of the JupyterLab instance available to you already, hmmm...

```
hub:
  services:
    myServiceName:
      admin: true
      apiToken: "aec7d32df938c0f55e54f09244a350cb29ea612907ed4f07be13d9553d18a8e4"
```

**Comment by bebosudo** [comment]
Hi @consideRatio,
using that snippet inside `hub` I was able to get a working curl line to interact with JupyterHub; is there any documentation about all these "secrets" in the yaml config file?
There's the `proxy.secretToken`, the `hub.cookieSecret` and also the `hub.services.*.apiToken`. What's the purpose of all these fields?

For anyone that may reach this point, this is my current (partial) configuration file `jupyterhub.yaml`:
```yaml
hub:
  # Image that manages the user login and jupyterlab creation.
  # Use the same tag used when installing with helm.
  image:
    name: jupyterhub/k8s-hub
    tag: 0.9.0-beta.4.n000.h72e54ee

  services:
    testService:
      admin: true
      apiToken: "aec7d32df938c0f55e54f09244a350cb29ea612907ed4f07be13d9553d18a8e4"

auth:
  type: "custom"
  custom:
   className: "nativeauthenticator.NativeAuthenticator"
  admin:
    users:
      - admin1
  whitelist:
    users:
      - test1
      - test2
```

which I apply with:
`helm upgrade --install jhub jupyterhub/jupyterhub --version=0.9.0-beta.4.n000.h72e54ee --values jupyterhub.yaml`.

Then I'm able to interact with the Jhub API server with:
`curl -L -H "accept: application/json" -H "Authorization: token aec7d32df938c0f55e54f09244a350cb29ea612907ed4f07be13d9553d18a8e4" http://host:port/hub/api/users |python -m json.tool`

It would be useful to have some notes like these in the documentation, I think; I've lost some hours wandering around the doc and the source code, before reaching this post.
