### ISSUE TITLE
Need help with configuring ingress (urgent!)

### ISSUE THREAD

**Issue by ablekh** [jupyterhub/zero-to-jupyterhub-k8s#855]
I created a new JH cluster on AKS. Need to correctly configure ingress, so that it works with relevant FQDN and Let's Encrypt certs (I'm using GitHub authentication, so having FQDN is important). I got confused by current instructions (https://zero-to-jupyterhub.readthedocs.io/en/latest/advanced.html#ingress-and-automatic-https-with-kube-lego-let-s-encrypt), so I also tried standard Azure/AKS approach (https://docs.microsoft.com/en-us/azure/aks/ingress) - I get the login page successfully, but going through GitHub auth generates an error page with content `default backend - 404`. Your help will be much appreciated.
cc: @yuvipanda @ryanlovett @minrk @consideRatio @betatim @ellisonbg @choldgraf

**Comment by minrk** [comment]
Can you include your config.yaml? Having an FQDN is indeed important.

My config with letsencrypt looks like this:

```yaml
proxy:
  https:
    enabled: true
    type: letsencrypt
    letsencrypt:
      contactEmail: me@example.com
    hosts:
      - my.domain.edu
```

**Comment by ablekh** [comment]
@minrk I appreciate you trying to help. The urgency has passed (this was an out-of-town workshop; typing this in the airport on my way back home), but I would definitely want to figure out a streamlined and reliable way to set up a JH cluster on Azure AKS. Everything was working well before a day before the workshop, when I would have needed to scale the cluster up to accommodate all registered participants. The scaling has failed and the cluster has been left in a corrupted state the evening before the event. Hence the urgency of my request at the time. All my attempts to recover the cluster have not been successful. Because I forgot the critical part of setting up FQDN on AKS and enabling TLS/LetsEncrypt.

For the event I have ended up using a JH server that I have configured earlier for a different purpose.

At the end of the workshop I've recalled how I have configured the FQDN and LetsEncrypt parts (details below) - by the way, Z2JH documentation should be improved in clarity in this regard - I might help after I get back home and streamline my notes. However, pods in the corrupted cluster and even some new ones that I have created in attempts to fix the situation all have been ending up in non-Running states (e.g., `CrashLoopBackOff` and `Error`) - the logs have not been conclusive ... Anyway, here the `config.yaml` I have used the most for the above.

```
hub:
  cookieSecret: "<SECRET>"
  extraConfig:
    c.KubeSpawner.singleuser_image_pull_secrets = "sbdh-acr-secret"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - <FQDN_of_the_JH_CLUSTER>
  tls:
    - hosts:
      - <FQDN_of_the_JH_CLUSTER>
      secretName: kubelego-tls-jupyterhub

proxy:
  secretToken: "<SECRET>"
  #  service:
  #    type: ClusterIP
  type: ClusterIP

prePuller:
  hook:
    enabled: false

imagePullSecrets:
  - name: sbdh-acr-secret-contrib

rbac:
  enabled: false

auth:
  type: github
  github:
    clientId: "<CLIENT_ID>"
    clientSecret: "<CLIENT_SECRET>"
    callbackUrl: "http://<FQDN_of_the_JH_CLUSTER>/hub/oauth_callback"
    #    org_whitelist:
    #      - "sbdh-dataup"
    #  scopes:
    #    - "read:org"

singleuser:
  image:
    name: jupyter/datascience-notebook
    tag: 177037d09156
    #name: sbdhcr.azurecr.io/datascience-octave-notebook
    #tag: v3
    #    name: jupyter/base-notebook
    #    tag: 1fbaef522f17
```

**Comment by ablekh** [comment]
FYI: For the above, I have tried both v0.6 and v0.7-b5ffce5 for the JH Helm chart.

**Comment by ablekh** [comment]
For the LetsEncrypt (after FQDN is set up - see below), I have used a Kube-Lego Helm chart like this:

```
helm repo update
helm install --name=letsencrypt --namespace=kube-system stable/kube-lego \
  --set config.LEGO_EMAIL=<MY_GMAIL_EMAIL> \
  --set config.LEGO_URL=https://acme-v01.api.letsencrypt.org/directory
```

To set up FQDN for the cluster on AKS, I have used the following script:

```
#!/bin/bash

# Public IP address
IP="<PUBLIC_IP_OF_THE_CLUSTER>"

# Name to associate with public IP address
DNSNAME="sbdh-jh"

# Get resource group and public ip name
RESOURCEGROUP=$(az network public-ip list --query "[?ipAddress!=null]|[?contains(ipAddress, '$IP')].[resourceGroup]" --output tsv)
PIPNAME=$(az network public-ip list --query "[?ipAddress!=null]|[?contains(ipAddress, '$IP')].[name]" --output tsv)

# Update public ip address with dns name
az network public-ip update --resource-group $RESOURCEGROUP --name  $PIPNAME --dns-name $DNSNAME
```

**Comment by minrk** [comment]
The jupyterhub chart itself deploys kube-lego if https is enabled and set to letsencrypt, so the above proxy config I posted should be *everything* you need to enable letsencrypt with jupyterhub, at least with the 0.7 chart. However, I've also done it via an ingress where it looks like this:

```yaml
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - fqdn
    tls:
      - secretName: kubelego-tls-jupyterhub
        hosts:
          - fqdn
```

The only difference I see is the `kubernetes.io/ingress.class: nginx`, which may or may not be relevant.

Here's [my deployment](https://github.com/minrk/simula-summer-school/blob/2018/config.yaml) where I deployed https via the ingress, if it helps.
