### ISSUE TITLE
singleUser.imagePullSecret is created only after the pre-pull

### ISSUE THREAD

**Issue by mhuttner** [jupyterhub/zero-to-jupyterhub-k8s#871]
## Setup
- Configure Jupyterhub to pull from a private registry
- Set the imagepullSecret in the config 

## Contents of `config.yaml`
```
singleuser:
  image:
    name: <registry-url>/containers/data-analysis-notebook
    tag: latest
  imagePullSecret:
    username: <name>
    password: <password>
    registry: <registry-url>
```

## Outcome
- The pre pull will fail with "Access denied". 
- Pulling images when the hub is running works (since the secret is in place then)

## Workaround
Disabling the pre pull with 
`prePuller.hook.enable: false`
fixes this, but it should probably be handled differently to still allow pre pulling images.
