### ISSUE TITLE
Offload HTTPS not working

### ISSUE THREAD

**Issue by n3f** [jupyterhub/zero-to-jupyterhub-k8s#874]
When I try to follow the directions here: <https://zero-to-jupyterhub.readthedocs.io/en/latest/security.html#off-loading-ssl-to-a-load-balancer>, the load balancer does not correctly configure the SSL listener, and the security group doesn't have the port 443 open either.  I don't know if this is a problem with kubernetes or the helm chart. (I'm using the v7.0-beta.2 helm chart)

## Contents of `config.yaml`
```yml
proxy:
  https:
    enabled: true
    type: offload
  service:
    annotations:
      # Certificate ARN
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "XXX"
      # The protocol to use on the backend, we use TCP since we're using websockets
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      # Which ports should use SSL - originally tried 'https', but changed to 443 based on information at
      # https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#aws
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
```

**Comment by cilquirm** [comment]
I came across this too, and it looks like the way the helm chart was written:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/proxy/service.yaml#L1

you have to specify a host for https configuration ( though I believe that shouldn't actually be necessary for offload ):

```yaml
proxy:
  https:
    enabled: true
    type: offload
    hosts:
      - myhost.mydomain
```
