### ISSUE TITLE
kubespawner.profile_list - demo example

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#906]
Since kubespawner has introduced this awesome feature, we could perhaps document how to use it in the guide somewhere.

Related: #903

**Comment by consideRatio** [comment]
@woop this is almost a duplicate issue of the one you commented on that i lost track of from my mobile.

It would not include who are permitted to which type of resource request though. To accomplish that one would need to configure things from a pre_spawn_hook in a custom authenticator.

**Comment by sampathkethineedi** [comment]
I'm trying to pull different branches of repo using gitpuller based on the profile selected. 

My **singleuser** snippet from config.yaml - 

```
singleuser:
  profileList:
    - display_name: <name>
      description: <description>
      kubespawner_override:
        cpu_limit: .5
        lifecycle_hooks:
          postStart:
            exec:
              command: ["gitpuller",<url>, <branch>,<folder>]
    - display_name: <name>
      description: <description>
      kubespawner_override:
        cpu_limit: 1
        cpu_guarantee: .2
        storage:
          capacity: 2Gi
        lifecycle_hooks:
          postStart:
            exec:
              command: ["gitpuller",<url>, <different branch>,<folder>]

  storage:
    capacity: 1Gi
  image:
    name: <docker>/<image>
    tag: <tag>

```

What is the proper way to add lifecyclehooks to kubespawner_override? Thanks!
