### ISSUE TITLE
Use rbac.create convention ?

### ISSUE THREAD

**Issue by kuahyeow** [jupyterhub/zero-to-jupyterhub-k8s#921]
Based on my understanding, the templates use `rbac.enabled` to determine if RBAC resources will be created - e.g. https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/templates/image-puller/rbac.yaml

According to https://docs.helm.sh/chart_best_practices/#rbac-resources-should-be-created-by-default, the best practice is to have `rbac.create` for the setting to create RBAC resources.

Other charts such as [nginx-ingress](https://github.com/helm/charts/blob/master/stable/nginx-ingress/templates/clusterrolebinding.yaml) do use `rbac.create`.

Would it be a good idea to use this convention ?

**Comment by consideRatio** [comment]
Ah, absolutely thanks for bringing this to our attention @kuahyeow! I'd like us to follow Helm's best practices. It would be a breaking change to rename it, but I think it will be fine as long as we write about it in the upgrade instructions, it is fine I think as this is a very easy thing to fix for those that disabled RBAC for some reason. I'm happy to review a PR if you want to fix it.

## PR Tasks, I think...
- [ ] Systematic change to reference `rbac.create` instead of `rbac.enabled` in helm templates ...
- [ ] ... and in the documentation as well.
- [ ] Make a note in the CHANGELOG.md about the breaking change and what needs to be done

**Comment by kuahyeow** [comment]
Thanks for the positive feedback @consideRatio .

Actually, now I read the chart best practices again, it seems that `rbac.create` should be reserved for the creation of Roles, RoleBindings, ClusterRoles and ClusterRoleBindings. ServiceAccounts, should be controlled under `serviceAccount.create` with the ability to pass in names. So for jupyterhub, it will look something like : 

```
rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccounts:
  hub:
    create: true
    name:
  image-puller:
    create: true
    name:
  proxy:
    autohttps:
      create: true
      name:
  scheduling:
    userScheduler:
      create: true
      name:
```

What do you think ?
