### ISSUE TITLE
hub certificate verify failed

### ISSUE THREAD

**Issue by wangxiaoxiao88** [jupyterhub/zero-to-jupyterhub-k8s#943]
hi,all
i met this problem 

> [D 2018-09-19 06:21:37.635 JupyterHub user:190] Creating <class 'kubespawner.spawner.KubeSpawner'> for 1:
> 2018-09-19 06:21:37,648 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),)': /api/v1/namespaces/jhub/pods?fieldSelector=&labelSelector=component%3Dsingleuser-server

and my config.yaml is

> hub:
>   cookieSecret: 8ed43048dcdfc14ee49295f5c450749c314fe0e2f92edc6e84a51ddc9c5d8149
>   db:
>     type: sqlite-memory
>   networkPolicy:
>     enabled: true
> proxy:
>   secretToken: 106342c8425f31dce6c4e2357b6721f98b251fd2e57c5322fff6fa2a295f87b3
> singleuser:
>   storage:
>     type: none

i google it ,but i found no solution。

**Comment by consideRatio** [comment]
Questions that can be helpful to us:
1. Does it work if you disable the network policy for the hub?
2. What version of k8s are you using (and it is the same version throughout your nodes right?)
3. How have you deployed your k8s cluster? Is it a managed google cloud k8s cluster (GKE), using kops on Amazon EC2, or kubeadm on your own servers etc?

**Comment by wangxiaoxiao88** [comment]
1.
```
hub:
  cookieSecret: xxxxx
  db:
    type: sqlite-memory
  networkPolicy:
    enabled: false
proxy:
  secretToken: xxxxx
singleuser:
  storage:
    type: none
```
still doesn't work

2.k8s version is  "1.10.4"

3.i am using "Alibaba Cloud" k8s
