### ISSUE TITLE
How to get a public IP for the jupyterhub proxy 

### ISSUE THREAD

**Issue by johnchase** [jupyterhub/zero-to-jupyterhub-k8s#953]
I would like to route traffic to jupyterhub through a subdomain. I am attempting to do this following the instructions on the [security section](https://zero-to-jupyterhub.readthedocs.io/en/stable/security.html?highlight=security#set-up-your-domain) of the tutorial. 

I am following the tutorial and setting this up on an AWS ec2 instance

Step 2 of the tutorial says:
> Create an A record from the domain you want to use, pointing to the EXTERNAL-IP of the proxy-public service.

I imagine I am missing something very simple, but where do I get the external IP? I tried:

```bash
$ kubectl get service --namespace $NAMESPACE
NAME           TYPE           CLUSTER-IP       EXTERNAL-IP                                                               PORT(S)        AGE
hub            ClusterIP      100.71.253.4     <none>                                                                    8081/TCP       1d
proxy-api      ClusterIP      100.71.188.49    <none>                                                                    8001/TCP       1d
proxy-public   LoadBalancer   100.68.242.159   aeade3ec4c04211e896930ef0b408b6c-1370331475.us-east-1.elb.amazonaws.com   80:30808/TCP   1d
```
However the external IP is not something I can point to. I also tried to use the public IP on the instance itself from the ec2 dashboard, however this does not connect to jupyterhub.

I have followed the zero-to-jupyterhub tutorial closely and am using `jhub.k8s.local` as the cluster name
  
## Contents of `config.yaml`
```
singleuser:
  defaultUrl: "/lab"
  image:
    name: chasejohnh/data-science-nb
    tag: v3.7
  storage:
    capacity: 100Gi

  lifecycleHooks:
    postStart:
      exec:
        command: ["cp", "-a", "/usr/local/bin/profile", "/home/jovyan/.condarc"]

extraEnv:
  EDITOR: "vim"

prePuller:
   hook:
     enabled: true

hub:
  extraConfig: |-
    c.Spawner.cmd = ['jupyter-labhub']
```
Thanks for you help!
