### ISSUE TITLE
kube-lego doesn't renew certificates

### ISSUE THREAD

**Issue by betatim** [jupyterhub/zero-to-jupyterhub-k8s#963]
There seems to be a bug in kube-lego 0.1.6 (the default in the chart) that prevents it from actually renewing the certificate (see [jetstack/kube-lego#338](https://github.com/jetstack/kube-lego/issues/338)).

As a temporary workaround you can set the version of kube-lego in your `values.yaml`:
```
lego:
    image:
      tag: 0.1.7
```

Deploying this now and will make a PR if that goes well.

Has anyone else experienced this?

cc @gedankenstuecke

**Comment by minrk** [comment]
Sounds like a good plan to me.

**Comment by ablekh** [comment]
Where in the attribute hierarchy should I put the `lego` branch? My current relevant setup is as follows.

```
hub:
  cookieSecret: <SECRET1>
  extraConfig:
    c.KubeSpawner.singleuser_image_pull_secrets = <SECRET2>

proxy:
  secretToken: <SECRET3>
  type: ClusterIP
  https:
    enabled: true
    type: letsencrypt
    letsencrypt:
      contactEmail: <E-MAIL>
    hosts:
      - <FQDN>

<... OTHER SETTINGS ...>
```
