### ISSUE TITLE
How to mount AzureFile into user pod

### ISSUE THREAD

**Issue by camer314** [jupyterhub/zero-to-jupyterhub-k8s#982]
I want to mount an AzureFile volume into my user pod and make that the location of the home directory, or at least make it available for selection.

In the JupyterHub announcement for 0.8 it mentions there is support for singleuser.storage.extraVolumes however this does not seem to exist in the documentation.

Is this possible and if so do you have an example yaml specification?

**Comment by manics** [comment]
This isn't quite what you want but it's what I'm using at the moment:
```
singleuser:
  storage:
    type: NONE
    extraVolumes:
    - name: jupyterhub-sharedscratch-rw
      persistentVolumeClaim:
        claimName: jupyterhub-internal-storage-nfs-volume
    extraVolumeMounts:
    - name: jupyterhub-sharedscratch-rw
      mountPath: /home/jovyan/shared
      subPath: shared
```
` jupyterhub-internal-storage-nfs-volume` is an existing PersistentVolumeClaim, mounted at `/home/jovyan/shared` inside the singleuser-server.
