### ISSUE TITLE
GPU nodes get no image-pulling

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/zero-to-jupyterhub-k8s#992]
The image-pulling pods are not going to the gpu nodes, a brute fix for this is to add a toleration specifically to the nvidia.com/gpu taint on these pods like this.

```
spec:
  tolerations:
    {{- include "jupyterhub.userTolerations" . | nindent 8 }}
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
```
