### ISSUE TITLE
Error: watch closed before Until timeout when deploying jupyterhub on kubernetes 

### ISSUE THREAD

**Issue by frouzbeh** [jupyterhub/zero-to-jupyterhub-k8s#997]
I need to deploy jupyterhub on kubernetes on our private cloud using local volume, and for now I'm trying to do it first on a kubernetes cluster on virtual machines to figure out all the configuration we need to set. 
I have been successful to deploy jupyterhub on two nodes cluster (one master and one worker), but I'm getting the following error with two workers cluster.

> Error: watch closed before Until timeout

I don't know what should be set in configuration file for this case. This was the content of config file with one worker cluster that was working:
 

## Contents of `config.yaml`
```
hub:
   cookieSecret: "..."
   extraConfig: |-
     c.Spawner.cmd = ['jupyter-labhub']
   db:
     pvc:
      storageClassName: local-ssd
      accessMode: ReadWriteOnce
      storage: 5Gi
proxy:
  secretToken: "..."
  service:
    type: NodePort
    nodePorts:
      http: 31600
      https: 31700
singleuser:
 memory:
    limit: 1G
    guarantee: 1G
 defaultUrl: "/lab"
 extraEnv:
    EDITOR: "vim"
 storage:
    dynamic:
      storageClass: local-ssd
    capacity: 2Gi
```
Eventually, I need to choose an authentication which I prefer PAM authentication, but I don't know what should I set the auth.type to for PAM. 
I also think I need to have node affinity for hub pod so it can have access to its database even after failure but I don't know how. After all, I think it should be deployed even without these information. Can anyone help me with this?
